Repository grafana/oncall, pull requests merged in 2023-06, with the labels that each got.

#2075 Fix a bug #1617 with permissions for telegram user settings
  CHANGELOG.md
  grafana-plugin/src/containers/UserSettings/parts/tabs/TelegramInfo/TelegramInfo.tsx
Labels: pr:no public docs

#2023 Fix orphaned messages in Slack
  CHANGELOG.md
  engine/apps/alerts/incident_appearance/renderers/slack_renderer.py
  engine/apps/slack/models/slack_message.py
  engine/apps/slack/scenarios/alertgroup_appearance.py
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/slack/scenarios/resolution_note.py
  engine/apps/slack/scenarios/step_mixins.py
  engine/apps/slack/tests/test_scenario_steps/test_alert_group_actions.py
  engine/apps/slack/tests/test_scenario_steps/test_resolution_note.py
  engine/apps/slack/tests/test_slack_renderer.py
Labels: pr:no public docs

#2069 Fix relative link to resolve 404 error
  docs/sources/get-started/_index.md
Labels: type/docs

#2039 Add initial setup for local dev prometheus exporter
  Makefile
  dev/.gitignore
  dev/README.md
  dev/prometheus.yml
  docker-compose-developer.yml
  engine/engine/urls.py
  engine/settings/base.py
  provisioning/datasources/automatic.yml
Labels: pr:no changelog, pr:no public docs

#1959 Better english
  engine/apps/api/tests/test_channel_filter.py
  engine/config_integrations/alertmanager.py
  engine/config_integrations/elastalert.py
  engine/config_integrations/formatted_webhook.py
  engine/config_integrations/grafana.py
  engine/config_integrations/grafana_alerting.py
  engine/config_integrations/kapacitor.py
  engine/config_integrations/webhook.py
  engine/config_integrations/zabbix.py
Labels: pr:no changelog, pr:no public docs

#2080 Trigger slack shift notifications on current shift change
  CHANGELOG.md
  engine/apps/alerts/tasks/notify_ical_schedule_shift.py
  engine/apps/alerts/tests/test_notify_ical_schedule_shift.py
Labels: pr:no public docs

#2081 Fix demo alert for inbound email
  CHANGELOG.md
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/tests/test_alert_receiver_channel.py
  engine/apps/alerts/tests/test_default_templates.py
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/views/alert_receive_channel.py
  engine/config_integrations/direct_paging.py
  engine/config_integrations/heartbeat.py
  engine/config_integrations/inbound_email.py
  engine/config_integrations/maintenance.py
  engine/config_integrations/manual.py
  engine/config_integrations/slack_channel.py
Labels: pr:no public docs

#2041 Social auth exception logging
  engine/apps/social_auth/middlewares.py
Labels: pr:no changelog, pr:no public docs

#2089 fix for MonacoEditor height
  grafana-plugin/src/containers/IntegrationSettings/IntegrationSettings.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
Labels: pr:no changelog, pr:no public docs

#2083 Use same account for status callback when using TwilioSender
  engine/apps/twilioapp/views.py
Labels: pr:no changelog, pr:no public docs

#2091 Use X-WR-TIMEZONE as calendar tz when available, fallback to UTC
  CHANGELOG.md
  engine/apps/alerts/tests/test_notify_ical_schedule_shift.py
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/tests/test_ical_utils.py
Labels: pr:no public docs

#2092 v1.2.36
  CHANGELOG.md
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/tests/test_alert_receiver_channel.py
  engine/apps/alerts/tests/test_default_templates.py
  engine/apps/alerts/tests/test_notify_ical_schedule_shift.py
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/views/alert_receive_channel.py
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/tests/test_ical_utils.py
  engine/apps/social_auth/middlewares.py
  engine/apps/twilioapp/views.py
  engine/config_integrations/direct_paging.py
  engine/config_integrations/heartbeat.py
  engine/config_integrations/inbound_email.py
  engine/config_integrations/maintenance.py
  engine/config_integrations/manual.py
  engine/config_integrations/slack_channel.py
  grafana-plugin/src/containers/IntegrationSettings/IntegrationSettings.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
Labels: pr:no public docs

#2094 Remove request reading middleware as we use post-buffering
  engine/engine/middlewares.py
  engine/settings/base.py
Labels: pr:no changelog, pr:no public docs

#2095 Add 413 for requests with content-length > 15Mb on uwsgi
  engine/Dockerfile
  engine/uwsgi.ini
Labels: pr:no changelog, pr:no public docs

#1964 Do not hide not secret settings in the web plugin UI
  CHANGELOG.md
  grafana-plugin/src/pages/settings/tabs/LiveSettings/LiveSettingsPage.tsx
Labels: pr:no public docs

#2102 Add support to update web schedule rotations in-place
  engine/apps/api/serializers/on_call_shifts.py
  engine/apps/api/tests/test_oncall_shift.py
  engine/apps/api/views/on_call_shifts.py
Labels: pr:no changelog, pr:no public docs

#2070 fixing another broken reference for jinja2 templating
  docs/sources/integrations/_index.md
Labels: type/docs, pr:no changelog

#2104 Webhooks 2 hide secrets
  engine/apps/api/serializers/webhook.py
  engine/apps/api/tests/test_webhooks.py
  engine/apps/webhooks/models/webhook.py
  engine/apps/webhooks/tasks/trigger_webhook.py
  grafana-plugin/src/containers/OutgoingWebhook2Form/OutgoingWebhook2Form.config.tsx
Labels: pr:no changelog, pr:no public docs

#2112 UID has been added to Integrations table, Integration page and routes
  grafana-plugin/src/components/HamburgerMenu/HamburgerMenu.module.css
  grafana-plugin/src/components/HamburgerMenu/HamburgerMenu.tsx
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.module.scss
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/pages/integration_2/Integration2.module.scss
  grafana-plugin/src/pages/integration_2/Integration2.tsx
  grafana-plugin/src/pages/integrations_2/Integrations2.module.scss
  grafana-plugin/src/pages/integrations_2/Integrations2.tsx
Labels: pr:no changelog, pr:no public docs

#2110 add github action to triage stale pull requests
  .github/workflows/triage-stale-pull-requests.yml
Labels: pr:no changelog

#2096 Revert "Revert slack org does not exist changes breaking escalate command (#2057)"
  CHANGELOG.md
  engine/apps/slack/tests/test_interactive_api_endpoint.py
  engine/apps/slack/views.py
Labels: pr:no public docs

#2100 Fix Telegram ratelimit on live setting change
  CHANGELOG.md
  engine/apps/api/tests/test_live_settings.py
  engine/apps/api/views/live_setting.py
  engine/apps/base/models/live_setting.py
  engine/apps/base/utils.py
  engine/apps/telegram/client.py
Labels: pr:no public docs

#2079 Fix warnings when running backend tests
  Makefile
  engine/apps/alerts/incident_appearance/renderers/telegram_renderer.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/signals.py
  engine/apps/alerts/tasks/check_escalation_finished.py
  engine/apps/alerts/tests/test_default_templates.py
  engine/apps/alerts/tests/test_escalation_policy_snapshot.py
  engine/apps/alerts/tests/test_terraform_renderer.py
  engine/apps/api/tests/test_features.py
  engine/apps/api/tests/test_user.py
  engine/apps/api/throttlers/test_call_throttler.py
  engine/apps/api/urls.py
  engine/apps/api/views/escalation_chain.py
  engine/apps/api/views/test_insight_logs.py
  engine/apps/base/tests/messaging_backend.py
  engine/apps/email/alert_rendering.py
  engine/apps/mobile_app/alert_rendering.py
  engine/apps/public_api/tests/test_on_call_shifts.py
  engine/apps/public_api/tests/test_schedules.py
  engine/apps/schedules/tests/test_custom_on_call_shift.py
  engine/apps/schedules/tests/test_ical_utils.py
  engine/apps/slack/slack_formatter.py
  engine/apps/slack/tests/test_scenario_steps/test_alert_group_actions.py
  engine/apps/twilioapp/tests/test_phone_calls.py
  engine/apps/webhooks/tests/factories.py
  engine/common/api_helpers/utils.py
  engine/common/tests/test_urlize.py
  engine/common/utils.py
  engine/requirements.txt
Labels: pr:no changelog, pr:no public docs

#2108 Main to dev
  docs/sources/get-started/_index.md
  docs/sources/integrations/_index.md
  engine/apps/api/views/alert_group.py
  helm/oncall/Chart.yaml
Labels: pr:no changelog

#1723 Using "sentence case" in the nav for consistency with the rest of grafana nav.
  README.md
  grafana-plugin/src/pages/index.tsx
  grafana-plugin/src/plugin.json
Labels: pr:no changelog, pr:no public docs, Stale

#2119 Fix phone code verification field
  grafana-plugin/src/containers/UserSettings/parts/tabs/PhoneVerification/PhoneVerification.tsx
Labels: pr:no changelog, pr:no public docs

#2120 Make viewset actions more consistent
  CHANGELOG.md
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/tests/test_channel_filter.py
  engine/apps/api/views/alert_receive_channel.py
  engine/apps/api/views/channel_filter.py
  engine/apps/api/views/escalation_chain.py
  engine/apps/api/views/escalation_policy.py
  engine/apps/api/views/user.py
  engine/apps/api/views/user_notification_policy.py
  engine/apps/public_api/views/maintaiable_object_mixin.py
  engine/apps/public_api/views/schedules.py
  engine/apps/public_api/views/users.py
  engine/common/api_helpers/mixins.py
  engine/common/api_helpers/serializers.py
  engine/common/tests/test_viewset_actions.py
Labels: pr:no public docs

#2116 Rares/templates tweaks 5
  grafana-plugin/src/components/Integrations/IntegrationBlock.module.scss
  grafana-plugin/src/components/Integrations/IntegrationBlockItem.module.scss
  grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/TeamName/TeamName.tsx
  grafana-plugin/src/pages/integration_2/Integration2.helper.ts
  grafana-plugin/src/pages/integration_2/Integration2.module.scss
  grafana-plugin/src/pages/integration_2/Integration2.tsx
  grafana-plugin/src/pages/integrations_2/Integrations2.tsx
Labels: pr:no changelog, pr:no public docs

#2034 TwilioPhoneProvider optimizations
  engine/apps/twilioapp/gather.py
  engine/apps/twilioapp/migrations/0006_auto_20230601_0807.py
  engine/apps/twilioapp/models/twilio_phone_call.py
  engine/apps/twilioapp/models/twilio_sms.py
  engine/apps/twilioapp/status_callback.py
  engine/apps/user_management/subscription_strategy/free_public_beta_subscription_strategy.py
Labels: pr:no changelog, pr:no public docs

#2074 Add BaseFailed exceptions for phone_notificator
  engine/apps/api/views/user.py
  engine/apps/phone_notifications/exceptions.py
  engine/apps/twilioapp/phone_provider.py
  engine/apps/twilioapp/tests/test_twilio_provider.py
Labels: pr:no changelog, pr:no public docs

#2053 Run containers as a non-root user
  CHANGELOG.md
  docker-compose-developer.yml
  engine/Dockerfile
  engine/uwsgi.ini
Labels: pr:no public docs

#2127 dev to main
  CHANGELOG.md
  docker-compose-developer.yml
  engine/Dockerfile
  engine/apps/api/views/user.py
  engine/apps/phone_notifications/exceptions.py
  engine/apps/twilioapp/gather.py
  engine/apps/twilioapp/migrations/0006_auto_20230601_0807.py
  engine/apps/twilioapp/models/twilio_phone_call.py
  engine/apps/twilioapp/models/twilio_sms.py
  engine/apps/twilioapp/phone_provider.py
  engine/apps/twilioapp/status_callback.py
  engine/apps/twilioapp/tests/test_twilio_provider.py
  engine/apps/user_management/subscription_strategy/free_public_beta_subscription_strategy.py
  engine/uwsgi.ini
Labels: pr:no changelog, pr:no public docs

#2129 Fixes for search, for last alert payload and some design changes
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.module.css
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
Labels: pr:no changelog, pr:no public docs

#2135 Fix docs, change team to organization in ratelimits, as previously te…
  docs/sources/oncall-api-reference/_index.md
Labels: pr:no changelog

#2136 fix for templates for routes
  grafana-plugin/src/containers/EditRegexpRouteTemplateModal/EditRegexpRouteTemplateModal.module.css
  grafana-plugin/src/containers/EditRegexpRouteTemplateModal/EditRegexpRouteTemplateModal.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
  grafana-plugin/src/pages/integration_2/Integration2.tsx
Labels: pr:no changelog, pr:no public docs

#2139 Fix demo-payload
  engine/apps/api/serializers/alert_receive_channel.py
Labels: pr:no changelog, pr:no public docs

#2114 Edit route hint
  grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.tsx
Labels: pr:no changelog, pr:no public docs

#2140 Update alert group view receive channel filter
  CHANGELOG.md
  engine/apps/api/tests/test_alert_group.py
  engine/apps/api/views/alert_group.py
Labels: pr:no public docs

#1085 Added nodeSelector for celery deployment and migrate job
  helm/oncall/templates/celery/_deployment.tpl
  helm/oncall/templates/engine/job-migrate.yaml
  helm/oncall/values.yaml
Labels: pr:no changelog, pr:no public docs

#2145 don't enforce line-length rule for markdownlint for code-blocks or tables
  .markdownlint.json
  dev/README.md
  docs/sources/oncall-api-reference/alertgroups.md
  docs/sources/oncall-api-reference/escalation_policies.md
  docs/sources/oncall-api-reference/on_call_shifts.md
  docs/sources/oncall-api-reference/personal_notification_rules.md
  docs/sources/oncall-api-reference/routes.md
  docs/sources/oncall-api-reference/schedules.md
  docs/sources/oncall-api-reference/user_groups.md
  helm/README.md
  helm/oncall/README.md
  tools/pagerduty-migrator/README.md
Labels: pr:no changelog

#2147 Templates&grouping tweaks&fixes
  grafana-plugin/src/components/HamburgerMenu/HamburgerMenu.module.css
  grafana-plugin/src/components/HamburgerMenu/HamburgerMenu.module.scss
  grafana-plugin/src/components/HamburgerMenu/HamburgerMenu.tsx
  grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.module.scss
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.module.scss
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.module.css
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
  grafana-plugin/src/pages/integration_2/Integration2.helper.ts
  grafana-plugin/src/pages/integration_2/Integration2.tsx
  grafana-plugin/src/pages/integrations_2/Integrations2.tsx
Labels: pr:no changelog, pr:no public docs

#2103 Add instructions for prometheus exporter setup
  README.md
  docker-compose.yml
  engine/apps/metrics_exporter/tests/test_views.py
  engine/apps/metrics_exporter/urls.py
  engine/apps/metrics_exporter/views.py
  engine/settings/base.py
  engine/settings/ci-test.py
  helm/oncall/templates/_env.tpl
  helm/oncall/templates/celery/_deployment.tpl
  helm/oncall/templates/engine/deployment.yaml
  helm/oncall/templates/engine/job-migrate.yaml
  helm/oncall/templates/secrets.yaml
  helm/oncall/values.yaml
Labels: pr:no changelog, pr:no public docs

#2159 Use secondary btn, updated copies on MobileApp Send Push
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.tsx
Labels: pr:no changelog, pr:no public docs

#2157 Adding a note about OSS env vars to enable tg/slack features
  docs/sources/open-source/_index.md
Labels: pr:no changelog

#2167 Draft AlertManager integration v2
  engine/apps/integrations/templates/html/integration_alertmanager_v2.html
  engine/apps/integrations/urls.py
  engine/apps/integrations/views.py
  engine/apps/public_api/serializers/integrations.py
  engine/config_integrations/alertmanager.py
  engine/config_integrations/alertmanager_v2.py
  engine/settings/base.py
Labels: pr:no changelog, pr:no public docs

#2201 remove SlackActionRecord model/table
  CHANGELOG.md
  docker-compose-developer.yml
  engine/apps/slack/admin.py
  engine/apps/slack/migrations/0003_delete_slackactionrecord.py
  engine/apps/slack/models/__init__.py
  engine/apps/slack/models/slack_action_record.py
  engine/apps/slack/tests/factories.py
  engine/apps/user_management/tests/test_organization.py
  engine/conftest.py
Labels: pr:no public docs

#2205 add comment to newly created issues which includes the current latest version
  .github/workflows/issues_add_to_project.yml
  .github/workflows/on-issue-creation.yml
Labels: pr:no changelog

#2190 Save only organizations with integrations in cache
  engine/apps/metrics_exporter/helpers.py
  engine/apps/metrics_exporter/tasks.py
Labels: pr:no changelog, pr:no public docs

#2124 Update shift week_start when translating to UTC
  engine/apps/api/serializers/on_call_shifts.py
  engine/apps/api/tests/test_oncall_shift.py
  grafana-plugin/src/containers/RotationForm/RotationForm.tsx
  grafana-plugin/src/models/schedule/schedule.types.ts
  grafana-plugin/src/pages/schedule/Schedule.helpers.ts
Labels: pr:no changelog, pr:no public docs

#2214 result showing improving
  grafana-plugin/src/containers/TemplatePreview/TemplatePreview.tsx
  grafana-plugin/src/pages/integrations_2/Integrations2.tsx
Labels: pr:no changelog, pr:no public docs

#2220 Require users when creating a schedule rotation
  CHANGELOG.md
  engine/apps/api/serializers/on_call_shifts.py
  engine/apps/api/tests/test_oncall_shift.py
Labels: pr:no public docs

#2150 Add autoresolve switch to templates section on Integrations page
  engine/apps/api/serializers/alert_receive_channel.py
  grafana-plugin/src/components/Integrations/IntegrationTemplateBlock.tsx
  grafana-plugin/src/containers/IntegrationContainers/IntegrationTemplatesList.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.types.ts
  grafana-plugin/src/pages/integration_2/Integration2.tsx
Labels: pr:no changelog, pr:no public docs

#2217 Add 'Edit templates' to dropdown, change wording
  grafana-plugin/src/pages/integration_2/Integration2.tsx
  grafana-plugin/src/pages/integrations_2/Integrations2.tsx
Labels: pr:no changelog, pr:no public docs

#2226 Refactor templatesToRender, add tooltips, fix wording
  grafana-plugin/src/components/Integrations/IntegrationTemplateBlock.tsx
  grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationContainers/Integration2HearbeatForm/Integration2HeartbeatForm.tsx
  grafana-plugin/src/containers/IntegrationContainers/IntegrationCommonTemplatesList.config.ts
  grafana-plugin/src/containers/IntegrationContainers/IntegrationTemplatesList.config.ts
  grafana-plugin/src/containers/IntegrationContainers/IntegrationTemplatesList.tsx
  grafana-plugin/src/containers/MaintenanceForm/MaintenanceForm.config.tsx
  grafana-plugin/src/containers/MaintenanceForm/MaintenanceForm.tsx
  grafana-plugin/src/pages/integration_2/CommonIntegration2.helper.ts
  grafana-plugin/src/pages/integration_2/Integration2.helper.ts
  grafana-plugin/src/pages/integration_2/Integration2.tsx
Labels: pr:no changelog, pr:no public docs

#2219 Rares/templates minor improvements
  grafana-plugin/src/components/IntegrationCollapsibleTreeView/IntegrationCollapsibleTreeView.tsx
  grafana-plugin/src/components/IntegrationInputField/IntegrationInputField.tsx
  grafana-plugin/src/components/Integrations/IntegrationTemplateBlock.tsx
  grafana-plugin/src/containers/IncidentsFilters/IncidentsFilters.tsx
  grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
  grafana-plugin/src/containers/MaintenanceForm/MaintenanceForm.tsx
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
  grafana-plugin/src/pages/escalation-chains/EscalationChains.tsx
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/integration_2/Integration2.tsx
  grafana-plugin/src/pages/integrations_2/Integrations2.tsx
Labels: pr:no changelog, pr:no public docs

#2212 Refactor metrics exporter to use `cache.get_many`
  engine/apps/metrics_exporter/metrics_collectors.py
  engine/apps/metrics_exporter/tests/conftest.py
Labels: pr:no changelog, pr:no public docs

#2239 Unify "name" and "title" field for oncall shift
  engine/apps/api/serializers/on_call_shifts.py
  engine/apps/api/tests/test_oncall_shift.py
  engine/apps/public_api/serializers/on_call_shifts.py
  engine/apps/schedules/migrations/0013_auto_20230517_0510.py
  engine/apps/schedules/models/custom_on_call_shift.py
Labels: pr:no changelog, pr:no public docs

#2224 Preserve schedule update_shift links on delete
  engine/apps/schedules/models/custom_on_call_shift.py
  engine/apps/schedules/tests/test_custom_on_call_shift.py
Labels: pr:no changelog, pr:no public docs

#2223 Update schedule preview to not create new shift by default
  engine/apps/api/tests/test_oncall_shift.py
  engine/apps/schedules/models/on_call_schedule.py
Labels: pr:no changelog, pr:no public docs

#2230 add new bug and feature-request GitHub Issue templates
  .github/ISSUE_TEMPLATE/0-bug-report-template.yml
  .github/ISSUE_TEMPLATE/1-feature-request-template.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/workflows/on-issue-creation.yml
  .github/workflows/triage-unlabeled-issues.yml
Labels: pr:no changelog

#2241 Handle non-UTC UNTIL datetime value when repeating ical events
  CHANGELOG.md
  engine/apps/schedules/ical_events/adapter/amixr_recurring_ical_events_adapter.py
  engine/apps/schedules/tests/test_on_call_schedule.py
Labels: pr:no public docs

#2255 Add telegram details field
  engine/apps/api/serializers/channel_filter.py
Labels: pr:no changelog, pr:no public docs

#2263 Update daily shifts by day to handle changed week start
  engine/apps/schedules/models/custom_on_call_shift.py
  engine/apps/schedules/tests/test_custom_on_call_shift.py
Labels: pr:no changelog, pr:no public docs

#864 fix existingSecret for RabbitMQ to default value (see #761)
  CHANGELOG.md
  helm/oncall/tests/rabbitmq_env_test.yaml
  helm/oncall/values.yaml
Labels: part:deployment/helm

#2269 remove legacy permission strings
  CHANGELOG.md
  engine/apps/api/permissions.py
  engine/apps/api/serializers/user.py
  engine/apps/api/tests/test_user.py
Labels: pr:no public docs

#2264 Refactor template for edit for DRY
  grafana-plugin/src/components/AlertTemplates/AlertTemplatesForm.config.ts
  grafana-plugin/src/components/AlertTemplates/CommonAlertTemplatesForm.config.ts
  grafana-plugin/src/components/CheatSheet/CheatSheet.config.ts
  grafana-plugin/src/containers/EditRegexpRouteTemplateModal/EditRegexpRouteTemplateModal.tsx
  grafana-plugin/src/containers/IntegrationContainers/IntegrationTemplatesList.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
  grafana-plugin/src/pages/integration_2/Integration2.tsx
Labels: pr:no changelog, pr:no public docs

#2273 Optmise autoresolve query
  CHANGELOG.md
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/tasks/resolve_alert_group_by_source_if_needed.py
  engine/apps/alerts/tests/test_alert_group.py
Labels: pr:no public docs

#2282 Dev to main
  .github/ISSUE_TEMPLATE/0-bug-report-template.yml
  .github/ISSUE_TEMPLATE/1-feature-request-template.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/workflows/linting-and-tests.yml
  .github/workflows/on-issue-creation.yml
  .github/workflows/on-issue-labeled.yml
  .github/workflows/triage-unlabeled-issues.yml
  CHANGELOG.md
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/tasks/resolve_alert_group_by_source_if_needed.py
  engine/apps/alerts/tests/test_alert_group.py
  engine/apps/api/permissions.py
  engine/apps/api/serializers/channel_filter.py
  engine/apps/api/serializers/on_call_shifts.py
  engine/apps/api/serializers/user.py
  engine/apps/api/tests/test_oncall_shift.py
  engine/apps/api/tests/test_user.py
  engine/apps/mobile_app/migrations/0008_mobileappusersettings_locale.py
  engine/apps/mobile_app/models.py
  engine/apps/mobile_app/serializers.py
  engine/apps/mobile_app/tasks.py
  engine/apps/mobile_app/tests/test_user_settings.py
  engine/apps/mobile_app/tests/test_your_going_oncall_notification.py
  engine/apps/public_api/serializers/on_call_shifts.py
  engine/apps/schedules/ical_events/adapter/amixr_recurring_ical_events_adapter.py
  engine/apps/schedules/migrations/0013_auto_20230517_0510.py
  engine/apps/schedules/models/custom_on_call_shift.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_custom_on_call_shift.py
  engine/apps/schedules/tests/test_on_call_schedule.py
  engine/apps/webhooks/tasks/trigger_webhook.py
  engine/common/l10n.py
  engine/common/tests/test_l10n.py
  engine/requirements.txt
  grafana-plugin/src/components/AlertTemplates/AlertTemplatesForm.config.ts
  grafana-plugin/src/components/AlertTemplates/CommonAlertTemplatesForm.config.ts
  grafana-plugin/src/components/CheatSheet/CheatSheet.config.ts
  grafana-plugin/src/components/IntegrationCollapsibleTreeView/IntegrationCollapsibleTreeView.tsx
  grafana-plugin/src/containers/EditRegexpRouteTemplateModal/EditRegexpRouteTemplateModal.tsx
  grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationContainers/IntegrationCommonTemplatesList.config.ts
  grafana-plugin/src/containers/IntegrationContainers/IntegrationTemplatesList.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
  grafana-plugin/src/containers/OutgoingWebhook2Form/OutgoingWebhook2Form.config.tsx
  grafana-plugin/src/pages/integration_2/Integration2.tsx
  helm/oncall/tests/rabbitmq_env_test.yaml
  helm/oncall/values.yaml
Labels: pr:no changelog, pr:no public docs

#2284 install requirements-dev.txt dependencies oncall docker image dev target
  engine/Dockerfile
Labels: pr:no changelog, pr:no public docs

#2289 add is_restricted column to alert_group table
  engine/apps/alerts/migrations/0017_alertgroup_is_restricted.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/user_management/models/organization.py
Labels: pr:no changelog, pr:no public docs

#2288 refactor title and subtitle of shift notifications
  CHANGELOG.md
  engine/apps/mobile_app/tasks.py
  engine/apps/mobile_app/tests/test_your_going_oncall_notification.py
Labels: pr:no public docs

#1720 Schedules 2nd iteration updates
  CHANGELOG.md
  engine/apps/api/serializers/on_call_shifts.py
  grafana-plugin/src/components/Collapse/Collapse.module.scss
  grafana-plugin/src/components/Collapse/Collapse.tsx
  grafana-plugin/src/components/GForm/GForm.module.scss
  grafana-plugin/src/components/GForm/GForm.tsx
  grafana-plugin/src/components/GForm/GForm.types.ts
  grafana-plugin/src/components/Modal/Modal.module.css
  grafana-plugin/src/components/Modal/Modal.tsx
  grafana-plugin/src/components/ScheduleFilters/ScheduleFilters.module.scss
  grafana-plugin/src/components/ScheduleFilters/ScheduleFilters.tsx
  grafana-plugin/src/components/ScheduleFilters/ScheduleFilters.types.ts
  grafana-plugin/src/components/ScheduleQuality/ScheduleQuality.tsx
  grafana-plugin/src/components/SchedulesFilters/SchedulesFilters.helpers.ts
  grafana-plugin/src/components/SchedulesFilters/SchedulesFilters.module.scss
  grafana-plugin/src/components/Text/Text.module.scss
  grafana-plugin/src/components/Text/Text.tsx
  grafana-plugin/src/components/TimelineMarks/TimelineMarks.module.scss
  grafana-plugin/src/components/TimelineMarks/TimelineMarks.tsx
  grafana-plugin/src/components/Unauthorized/__snapshots__/Unauthorized.test.tsx.snap
  grafana-plugin/src/components/UserGroups/UserGroups.helpers.ts
  grafana-plugin/src/components/UserGroups/UserGroups.module.css
  grafana-plugin/src/components/UserGroups/UserGroups.tsx
  grafana-plugin/src/components/UserTimezoneSelect/UserTimezoneSelect.tsx
  grafana-plugin/src/components/WorkingHours/WorkingHours.tsx
  grafana-plugin/src/containers/RemoteFilters/RemoteFilters.helpers.ts
  grafana-plugin/src/containers/Rotation/Rotation.helpers.ts
  grafana-plugin/src/containers/Rotation/Rotation.tsx
  grafana-plugin/src/containers/RotationForm/DateTimePicker.tsx
  grafana-plugin/src/containers/RotationForm/RotationForm.helpers.ts
  grafana-plugin/src/containers/RotationForm/RotationForm.module.css
  grafana-plugin/src/containers/RotationForm/RotationForm.tsx
  grafana-plugin/src/containers/RotationForm/RotationForm.types.ts
  grafana-plugin/src/containers/RotationForm/ScheduleOverrideForm.tsx
  grafana-plugin/src/containers/RotationForm/parts/DateTimePicker.tsx
  grafana-plugin/src/containers/RotationForm/parts/DaysSelector.tsx
  grafana-plugin/src/containers/RotationForm/parts/DeletionModal.tsx
  grafana-plugin/src/containers/RotationForm/parts/TimeUnitSelector.tsx
  grafana-plugin/src/containers/RotationForm/parts/UserItem.tsx
  grafana-plugin/src/containers/RotationForm/parts/WeekdayTimePicker.tsx
  grafana-plugin/src/containers/Rotations/Rotations.tsx
  grafana-plugin/src/containers/Rotations/ScheduleFinal.tsx
  grafana-plugin/src/containers/Rotations/ScheduleOverrides.tsx
  grafana-plugin/src/containers/ScheduleForm/ScheduleForm.config.ts
  grafana-plugin/src/containers/ScheduleSlot/ScheduleSlot.module.css
  grafana-plugin/src/containers/ScheduleSlot/ScheduleSlot.tsx
  grafana-plugin/src/containers/UsersTimezones/UsersTimezones.module.css
  grafana-plugin/src/containers/UsersTimezones/UsersTimezones.tsx
  grafana-plugin/src/models/schedule/schedule.helpers.ts
  grafana-plugin/src/models/schedule/schedule.ts
  grafana-plugin/src/models/schedule/schedule.types.ts
  grafana-plugin/src/models/timezone/timezone.types.ts
  grafana-plugin/src/models/user/user.ts
  grafana-plugin/src/pages/schedule/Schedule.helpers.ts
  grafana-plugin/src/pages/schedule/Schedule.tsx
  grafana-plugin/src/pages/schedules/Schedules.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/utils/consts.ts
  grafana-plugin/src/utils/datetime.ts
Labels: pr:no public docs

#2287 Add inbound email field to private api
  engine/apps/api/serializers/alert_receive_channel.py
Labels: pr:no changelog, pr:no public docs

#2294 Update test helper to match schedule UI change
  grafana-plugin/integration-tests/utils/schedule.ts
Labels: pr:no changelog, pr:no public docs

#2279 Changed web schedule updates to sync refresh ical
  CHANGELOG.md
  engine/apps/api/serializers/on_call_shifts.py
  engine/apps/api/tests/test_oncall_shift.py
  engine/apps/schedules/models/custom_on_call_shift.py
  engine/apps/schedules/tests/test_custom_on_call_shift.py
Labels: pr:no public docs

#2293 Grouping templating polishing11
  grafana-plugin/src/components/CheatSheet/CheatSheet.module.css
  grafana-plugin/src/components/CheatSheet/CheatSheet.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.module.scss
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.module.css
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
  grafana-plugin/src/pages/integration_2/Integration2.tsx
Labels: pr:no changelog, pr:no public docs

#2291 Templates&grouping changes
  grafana-plugin/src/components/AlertTemplates/AlertTemplatesForm.config.ts
  grafana-plugin/src/components/AlertTemplates/CommonAlertTemplatesForm.config.ts
  grafana-plugin/src/components/CheatSheet/CheatSheet.config.ts
  grafana-plugin/src/components/CheatSheet/CheatSheet.module.scss
  grafana-plugin/src/components/CheatSheet/CheatSheet.tsx
  grafana-plugin/src/components/Integrations/IntegrationBlock.module.scss
  grafana-plugin/src/components/Integrations/IntegrationBlockItem.module.scss
  grafana-plugin/src/components/Integrations/IntegrationTemplateBlock.tsx
  grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.module.scss
  grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationContainers/IntegrationCommonTemplatesList.config.ts
  grafana-plugin/src/containers/IntegrationContainers/IntegrationTemplatesList.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.module.scss
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
  grafana-plugin/src/models/channel_filter/channel_filter.types.ts
  grafana-plugin/src/models/telegram_channel/telegram_channel.types.ts
  grafana-plugin/src/pages/integration_2/Integration2.config.ts
  grafana-plugin/src/pages/integration_2/Integration2.helper.ts
  grafana-plugin/src/pages/integration_2/Integration2.module.scss
  grafana-plugin/src/pages/integration_2/Integration2.tsx
  grafana-plugin/src/pages/integration_2/Integration2Common.config.ts
  grafana-plugin/src/pages/integrations_2/Integrations2.module.scss
  grafana-plugin/src/pages/integrations_2/Integrations2.tsx
  grafana-plugin/src/style/utils.css
Labels: pr:no changelog, pr:no public docs

#2297 upgrade playwright
  grafana-plugin/package.json
  grafana-plugin/yarn.lock
Labels: pr:no changelog, pr:no public docs

#2296 Optimize getting response time for alert groups
  engine/apps/metrics_exporter/tasks.py
Labels: pr:no changelog, pr:no public docs

#2298 adjust stale PR bot to use pr:stale label instead
  .github/workflows/triage-stale-pull-requests.yml
Labels: pr:no changelog

#1973 Add dashboard for oncall metrics to provisioning plugin settings
  CHANGELOG.md
  grafana-plugin/src/dashboards/oncall_metrics_dashboard.json
  grafana-plugin/src/plugin.json
Labels: pr:no public docs

#2300 Fixes for templates&grouping
  grafana-plugin/src/components/UserTimezoneSelect/UserTimezoneSelect.tsx
  grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.module.css
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.types.ts
  grafana-plugin/src/pages/integration_2/Integration2.module.scss
  grafana-plugin/src/pages/integration_2/Integration2.tsx
  grafana-plugin/src/style/vars.css
Labels: pr:no changelog, pr:no public docs

#2278 Fix duplicate orders for user notification policies
  CHANGELOG.md
  docker-compose-developer.yml
  engine/apps/api/serializers/user_notification_policy.py
  engine/apps/api/tests/test_user_notification_policy.py
  engine/apps/api/views/user_notification_policy.py
  engine/apps/base/migrations/0004_auto_20230616_1510.py
  engine/apps/base/models/ordered_model.py
  engine/apps/base/models/user_notification_policy.py
  engine/apps/base/tests/test_ordered_model.py
  engine/apps/public_api/serializers/personal_notification_rules.py
  engine/tox.ini
Labels: pr:no public docs

#2302 light theme fixes
  grafana-plugin/src/components/HamburgerMenu/HamburgerMenu.module.scss
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.module.scss
  grafana-plugin/src/style/vars.css
Labels: pr:no changelog, pr:no public docs

#2295 Fix broken markup on alert group page, declutter, make time format consistent
  CHANGELOG.md
  grafana-plugin/src/containers/ApiTokenSettings/ApiTokenSettings.tsx
  grafana-plugin/src/containers/AttachIncidentForm/AttachIncidentForm.tsx
  grafana-plugin/src/pages/incident/Incident.module.scss
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/maintenance/Maintenance.tsx
  grafana-plugin/src/pages/outgoing_webhooks_2/OutgoingWebhooks2.tsx
Labels: pr:no public docs

#2304 Fix template preview markup
  grafana-plugin/src/components/AlertTemplates/CommonAlertTemplatesForm.config.ts
  grafana-plugin/src/containers/IntegrationContainers/IntegrationCommonTemplatesList.config.ts
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
  grafana-plugin/src/containers/TemplatePreview/TemplatePreview.module.css
  grafana-plugin/src/containers/TemplatePreview/TemplatePreview.tsx
Labels: pr:no changelog, pr:no public docs

#2305 Added missing chatOpsDisplayName to OSS + some ui tweaks
  grafana-plugin/src/components/AlertTemplates/CommonAlertTemplatesForm.config.ts
  grafana-plugin/src/components/Integrations/IntegrationBlock.module.scss
  grafana-plugin/src/components/Integrations/IntegrationBlock.tsx
  grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.module.scss
  grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.module.scss
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.module.css
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
  grafana-plugin/src/pages/integration_2/Integration2.module.scss
  grafana-plugin/src/pages/integration_2/Integration2.tsx
  grafana-plugin/src/pages/integration_2/Integration2Common.config.ts
  grafana-plugin/src/style/vars.css
Labels: pr:no changelog, pr:no public docs

#2307 Grouping templating chatops fix
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.module.scss
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
  grafana-plugin/src/containers/TemplatePreview/TemplatePreview.module.css
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
  grafana-plugin/src/pages/incident/Incident.module.scss
Labels: pr:no changelog, pr:no public docs

#2310 Switch old with new integrations page
  CHANGELOG.md
  grafana-plugin/integration-tests/utils/integrations.ts
  grafana-plugin/src/components/AlertTemplates/CommonAlertTemplatesForm.config.ts
  grafana-plugin/src/components/GForm/GForm.tsx
  grafana-plugin/src/containers/AlertRules/AlertRules.helpers.ts
  grafana-plugin/src/containers/AlertRules/AlertRules.module.css
  grafana-plugin/src/containers/AlertRules/AlertRules.tsx
  grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationContainers/IntegrationCommonTemplatesList.config.ts
  grafana-plugin/src/containers/IntegrationContainers/IntegrationHearbeatForm/IntegrationHeartbeatForm.tsx
  grafana-plugin/src/containers/IntegrationContainers/IntegrationTemplatesList.tsx
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.config.ts
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.helpers.ts
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.module.css
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/containers/IntegrationSettings/IntegrationSettings.module.css
  grafana-plugin/src/containers/IntegrationSettings/IntegrationSettings.tsx
  grafana-plugin/src/containers/IntegrationSettings/IntegrationSettings.types.ts
  grafana-plugin/src/containers/IntegrationSettings/parts/Autoresolve.module.css
  grafana-plugin/src/containers/IntegrationSettings/parts/Autoresolve.tsx
  grafana-plugin/src/containers/IntegrationSettings/parts/LiveLogs.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.module.scss
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/index.tsx
  grafana-plugin/src/pages/integration/CommonIntegration.helper.ts
  grafana-plugin/src/pages/integration/Integration.config.ts
  grafana-plugin/src/pages/integration/Integration.helper.ts
  grafana-plugin/src/pages/integration/Integration.module.scss
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/pages/integration/IntegrationCommon.config.ts
  grafana-plugin/src/pages/integrations/Integrations.module.css
  grafana-plugin/src/pages/integrations/Integrations.module.scss
  grafana-plugin/src/pages/integrations/Integrations.tsx
  grafana-plugin/src/pages/integrations_2/Integrations2.tsx
  grafana-plugin/src/pages/routes.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
Labels: pr:no public docs

#2337 Added chatops fetch (for MSTeams) and changed styling to be compatible with global grafana styles in templates
  grafana-plugin/src/components/HamburgerMenu/HamburgerMenu.module.scss
  grafana-plugin/src/components/HamburgerMenu/HamburgerMenu.tsx
  grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.tsx
  grafana-plugin/src/pages/integration/Integration.helper.ts
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/style/vars.css
Labels: pr:no changelog, pr:no public docs

#2340 v1.3.0
  CHANGELOG.md
  grafana-plugin/integration-tests/utils/integrations.ts
  grafana-plugin/src/components/AlertTemplates/CommonAlertTemplatesForm.config.ts
  grafana-plugin/src/components/GForm/GForm.tsx
  grafana-plugin/src/components/HamburgerMenu/HamburgerMenu.module.scss
  grafana-plugin/src/components/HamburgerMenu/HamburgerMenu.tsx
  grafana-plugin/src/containers/AlertRules/AlertRules.helpers.ts
  grafana-plugin/src/containers/AlertRules/AlertRules.module.css
  grafana-plugin/src/containers/AlertRules/AlertRules.tsx
  grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationContainers/IntegrationCommonTemplatesList.config.ts
  grafana-plugin/src/containers/IntegrationContainers/IntegrationHearbeatForm/IntegrationHeartbeatForm.tsx
  grafana-plugin/src/containers/IntegrationContainers/IntegrationTemplatesList.tsx
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.config.ts
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.helpers.ts
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.module.css
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/containers/IntegrationSettings/IntegrationSettings.module.css
  grafana-plugin/src/containers/IntegrationSettings/IntegrationSettings.tsx
  grafana-plugin/src/containers/IntegrationSettings/IntegrationSettings.types.ts
  grafana-plugin/src/containers/IntegrationSettings/parts/Autoresolve.module.css
  grafana-plugin/src/containers/IntegrationSettings/parts/Autoresolve.tsx
  grafana-plugin/src/containers/IntegrationSettings/parts/LiveLogs.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.module.scss
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
  grafana-plugin/src/containers/RotationForm/RotationForm.tsx
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
  grafana-plugin/src/models/schedule/schedule.ts
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/index.tsx
  grafana-plugin/src/pages/integration/CommonIntegration.helper.ts
  grafana-plugin/src/pages/integration/Integration.config.ts
  grafana-plugin/src/pages/integration/Integration.helper.ts
  grafana-plugin/src/pages/integration/Integration.module.scss
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/pages/integration/IntegrationCommon.config.ts
  grafana-plugin/src/pages/integrations/Integrations.module.css
  grafana-plugin/src/pages/integrations/Integrations.module.scss
  grafana-plugin/src/pages/integrations/Integrations.tsx
  grafana-plugin/src/pages/integrations_2/Integrations2.tsx
  grafana-plugin/src/pages/routes.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/style/vars.css
  helm/oncall/README.md
  helm/oncall/templates/_env.tpl
  helm/oncall/templates/celery/_deployment.tpl
  helm/oncall/templates/celery/deployment-celery.yaml
  helm/oncall/templates/secrets.yaml
  helm/oncall/tests/__snapshot__/wait_for_db_test.yaml.snap
  helm/oncall/tests/extra_env_test.yaml
  helm/oncall/tests/postgres_env_test.yaml
  helm/oncall/tests/postgres_password_env_test.yaml
  helm/oncall/tests/rabbitmq_env_test.yaml
  helm/oncall/tests/redis_env_test.yaml
  helm/oncall/tests/redis_password_env_test.yaml
  helm/oncall/tests/wait_for_db_test.yaml
  helm/oncall/values.yaml
Labels: pr:no public docs

#2327 [README]fix prometheus yml indentation error
  README.md
Labels: pr:no changelog, pr:no public docs

#2343 Remove unused prefetch_related in metrics task
  engine/apps/metrics_exporter/tasks.py
Labels: pr:no changelog, pr:no public docs

#2345 Fix phone call & SMS relay
  CHANGELOG.md
  engine/apps/phone_notifications/phone_backend.py
  engine/apps/phone_notifications/tests/test_phone_backend_oss_relay.py
Labels: pr:no public docs

#2346 v1.3.1
  CHANGELOG.md
  README.md
  engine/apps/metrics_exporter/tasks.py
  engine/apps/phone_notifications/phone_backend.py
  engine/apps/phone_notifications/tests/test_phone_backend_oss_relay.py
Labels: pr:no public docs

#2242 Change permissions used for finishing plugin setup
  CHANGELOG.md
  grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.test.tsx
  grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.tsx
  grafana-plugin/src/containers/PluginConfigPage/__snapshots__/PluginConfigPage.test.tsx.snap
  grafana-plugin/src/state/plugin/__snapshots__/plugin.test.ts.snap
  grafana-plugin/src/state/plugin/index.ts
  grafana-plugin/src/state/plugin/plugin.test.ts
  grafana-plugin/src/state/rootBaseStore/index.ts
  grafana-plugin/src/state/rootBaseStore/rootBaseStore.test.ts
  grafana-plugin/src/utils/authorization/index.ts
  grafana-plugin/src/utils/consts.ts
Labels: pr:no public docs

#2290 Refactor docs for the new integrations page
  docs/sources/escalation-chains-and-routes/_index.md
  docs/sources/get-started/_index.md
  docs/sources/integrations/_index.md
  docs/sources/integrations/alertmanager/index.md
  docs/sources/integrations/amazon-sns/index.md
  docs/sources/integrations/appdynamics/index.md
  docs/sources/integrations/datadog/index.md
  docs/sources/integrations/elastalert/index.md
  docs/sources/integrations/fabric/index.md
  docs/sources/integrations/grafana-alerting/index.md
  docs/sources/integrations/inbound-email/index.md
  docs/sources/integrations/jira/index.md
  docs/sources/integrations/kapacitor/index.md
  docs/sources/integrations/newrelic/index.md
  docs/sources/integrations/pingdom/index.md
  docs/sources/integrations/prtg/index.md
  docs/sources/integrations/sentry/index.md
  docs/sources/integrations/stackdriver/index.md
  docs/sources/integrations/uptimerobot/index.md
  docs/sources/integrations/zendesk/index.md
  docs/sources/jinja2-templating/_index.md
  grafana-plugin/src/containers/IntegrationContainers/IntegrationCommonTemplatesList.config.ts
Labels: pr:no changelog

#1901 Show 100000+ in stats when there are more than 100000 alert groups in the result
  CHANGELOG.md
  engine/apps/api/views/alert_group.py
Labels: pr:no public docs

#2351 For "You're Going OnCall" push notifications, show shift times in the user's configured timezone, otherwise UTC
  CHANGELOG.md
  engine/apps/mobile_app/tasks.py
  engine/apps/mobile_app/tests/test_your_going_oncall_notification.py
  engine/apps/user_management/models/user.py
Labels: pr:no public docs

#2352 Use correct slack key/display_name in templates
  grafana-plugin/src/components/AlertTemplates/CommonAlertTemplatesForm.config.ts
  grafana-plugin/src/containers/IntegrationContainers/IntegrationCommonTemplatesList.config.ts
Labels: pr:no changelog, pr:no public docs

#2170 continue addressing mypy violations
  engine/apps/alerts/escalation_snapshot/escalation_snapshot_mixin.py
  engine/apps/alerts/escalation_snapshot/snapshot_classes/escalation_policy_snapshot.py
  engine/apps/alerts/escalation_snapshot/snapshot_classes/escalation_snapshot.py
  engine/apps/alerts/grafana_alerting_sync_manager/grafana_alerting_sync.py
  engine/apps/alerts/incident_appearance/templaters/alert_templater.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/models/escalation_policy.py
  engine/apps/alerts/models/maintainable_object.py
  engine/apps/alerts/tasks/escalate_alert_group.py
  engine/apps/alerts/tasks/notify_user.py
  engine/apps/api/permissions.py
  engine/apps/api/serializers/escalation_policy.py
  engine/apps/api/serializers/on_call_shifts.py
  engine/apps/api/serializers/team.py
  engine/apps/api/serializers/user_notification_policy.py
  engine/apps/auth_token/models/schedule_export_auth_token.py
  engine/apps/base/models/user_notification_policy.py
  engine/apps/grafana_plugin/helpers/client.py
  engine/apps/grafana_plugin/views/self_hosted_install.py
  engine/apps/metrics_exporter/constants.py
  engine/apps/metrics_exporter/helpers.py
  engine/apps/oss_installation/models/cloud_connector.py
  engine/apps/public_api/serializers/escalation_policies.py
  engine/apps/public_api/serializers/routes.py
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/slack/constants.py
  engine/apps/slack/scenarios/step_mixins.py
  engine/apps/slack/slack_formatter.py
  engine/apps/telegram/client.py
  engine/apps/user_management/models/organization.py
  engine/apps/user_management/models/user.py
  engine/common/admin.py
  engine/common/api_helpers/mixins.py
  engine/common/insight_log/resource_insight_logs.py
  engine/engine/management/commands/setup_end_to_end_test.py
  engine/pyproject.toml
  engine/requirements-dev.txt
  engine/settings/base.py
  engine/settings/dev.py
  engine/type_stubs/icalendar/__init__.pyi
  engine/type_stubs/icalendar/cal.pyi
  engine/type_stubs/icalendar/caselessdict.pyi
  engine/type_stubs/icalendar/cli.pyi
  engine/type_stubs/icalendar/compat.pyi
  engine/type_stubs/icalendar/parser.pyi
  engine/type_stubs/icalendar/parser_tools.pyi
  engine/type_stubs/icalendar/prop.pyi
  engine/type_stubs/icalendar/timezone_cache.pyi
  engine/type_stubs/icalendar/tools.pyi
  engine/type_stubs/icalendar/windows_to_olson.pyi
Labels: pr:no changelog, pr:no public docs

#2358 Fix 404 link for schedule quality
  grafana-plugin/src/components/ScheduleQualityDetails/ScheduleQualityDetails.tsx
Labels: pr:no changelog, pr:no public docs

#2372 Fix for #2357
  grafana-plugin/src/components/ScheduleQualityDetails/ScheduleQualityDetails.tsx
Labels: pr:no changelog, pr:no public docs

#2370 mock package.json version for plugin configuration tests
  grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.test.tsx
Labels: pr:no changelog, pr:no public docs

#2373 Dev to main
  CHANGELOG.md
  docs/sources/insights-and-metrics/_index.md
  engine/apps/alerts/tasks/notify_user.py
  engine/apps/metrics_exporter/constants.py
  engine/apps/metrics_exporter/helpers.py
  engine/apps/metrics_exporter/metrics_collectors.py
  engine/apps/metrics_exporter/tasks.py
  engine/apps/metrics_exporter/tests/conftest.py
  engine/apps/metrics_exporter/tests/test_calculation_metrics.py
  engine/apps/metrics_exporter/tests/test_metrics_collectors.py
  engine/apps/metrics_exporter/tests/test_update_metics_cache.py
  engine/settings/prod_without_db.py
  grafana-plugin/src/components/ScheduleQualityDetails/ScheduleQualityDetails.tsx
  grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.test.tsx
Labels: pr:no changelog, pr:no public docs

#2382 Make `OrderedModel.save()` respect additional arguments
  engine/apps/base/models/ordered_model.py
Labels: pr:no changelog, pr:no public docs

#2383 Remove outdated Slack functionality to create alerts
  engine/apps/alerts/migrations/0018_remove_alertreceivechannel_integration_slack_channel_id.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/tests/test_alert_group.py
  engine/apps/slack/scenarios/scenario_step.py
  engine/apps/slack/scenarios/slack_channel_integration.py
  engine/apps/slack/views.py
Labels: pr:no changelog, pr:no public docs

#2366 in the e2e tests, await the grafana instance if it is currently down/unavailable
  grafana-plugin/.gitignore
  grafana-plugin/integration-tests/globalSetup.ts
  grafana-plugin/playwright.config.ts
Labels: pr:no changelog, pr:no public docs

#2359 update rabbitmq docker containers to v3.12.0
  .drone.yml
  .github/workflows/linting-and-tests.yml
  docker-compose-developer.yml
  docker-compose-mysql-rabbitmq.yml
Labels: pr:no changelog

#2375 use docker buildx native multiarch image support
  .drone.yml
Labels: pr:no changelog, pr:no public docs

#2395 v1.3.4
  .drone.yml
  .github/workflows/linting-and-tests.yml
  CHANGELOG.md
  docker-compose-developer.yml
  docker-compose-mysql-rabbitmq.yml
  engine/apps/alerts/migrations/0018_remove_alertreceivechannel_integration_slack_channel_id.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/tests/test_alert_group.py
  engine/apps/base/models/ordered_model.py
  engine/apps/slack/scenarios/scenario_step.py
  engine/apps/slack/scenarios/slack_channel_integration.py
  engine/apps/slack/views.py
  grafana-plugin/.gitignore
  grafana-plugin/integration-tests/globalSetup.ts
  grafana-plugin/playwright.config.ts
Labels: pr:no public docs

#2385 OnCall plugin use service accounts instead of api keys
  CHANGELOG.md
  grafana-plugin/src/state/plugin/index.ts
  grafana-plugin/src/state/plugin/plugin.test.ts
Labels: pr:no public docs

#2390 re-enable mypy GitHub Actions CI job
  .github/workflows/linting-and-tests.yml
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/models/custom_button.py
  engine/apps/alerts/models/escalation_chain.py
  engine/apps/alerts/models/escalation_policy.py
  engine/apps/auth_token/models/api_auth_token.py
  engine/apps/auth_token/models/plugin_auth_token.py
  engine/apps/auth_token/models/schedule_export_auth_token.py
  engine/apps/auth_token/models/user_schedule_export_auth_token.py
  engine/apps/mobile_app/models.py
  engine/apps/schedules/models/custom_on_call_shift.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/slack/models/slack_usergroup.py
  engine/apps/telegram/models/connectors/channel.py
  engine/apps/user_management/models/organization.py
  engine/apps/user_management/models/team.py
  engine/apps/user_management/models/user.py
  engine/apps/webhooks/models/webhook.py
  engine/pyproject.toml
  engine/requirements-dev.txt
Labels: pr:no changelog, pr:no public docs

#2384 Simplify `SlackEventApiEndpointView` methods
  engine/apps/slack/views.py
Labels: pr:no changelog, pr:no public docs

#2410 Remove attempt to check token when editor/viewers are accessing the plugin
  CHANGELOG.md
  grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.test.tsx
  grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.tsx
  grafana-plugin/src/containers/PluginConfigPage/__snapshots__/PluginConfigPage.test.tsx.snap
  grafana-plugin/src/state/plugin/index.ts
Labels: pr:no public docs

#2414 Add full avatar URL for on-call users in schedule internal API
  CHANGELOG.md
  engine/apps/api/tests/test_schedules.py
  engine/apps/user_management/models/user.py
Labels: pr:no public docs
