Repository grafana/oncall, pull requests merged in 2023-12, with the labels that each got.

#3480 Pass correct params when using retryFailingPromises
  grafana-plugin/src/state/rootBaseStore/index.ts
  grafana-plugin/src/utils/async.test.ts
  grafana-plugin/src/utils/async.ts
Labels: pr:no changelog, pr:no public docs, involved:Frontend

#3467 Fix monaco editor height
  grafana-plugin/src/assets/style/utils.css
  grafana-plugin/src/components/MonacoEditor/MonacoEditor.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.module.scss
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.module.css
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
  grafana-plugin/src/containers/WebhooksTemplateEditor/WebhooksTemplateEditor.tsx
Labels: pr:no changelog, pr:no public docs, involved:Frontend

#3472 Fix inherit label toggler
  grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.tsx
Labels: pr:no changelog, pr:no public docs, involved:Frontend

#3471 Make telegram on_alert_group_action_triggered asynchronous
  CHANGELOG.md
  engine/apps/telegram/alert_group_representative.py
  engine/apps/telegram/tasks.py
  engine/settings/celery_task_routes.py
Labels: pr:no public docs

#3483 Revert "upgrade to Python 3.12 (#3456)" and "bump uwsgi version to latest #3466"
  .drone.yml
  .github/workflows/linting-and-tests.yml
  .github/workflows/snyk.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  Makefile
  dev/README.md
  dev/scripts/generate-fake-data/README.md
  engine/Dockerfile
  engine/apps/alerts/grafana_alerting_sync_manager/grafana_alerting_sync.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/tests/test_paging.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/views/alert_receive_channel.py
  engine/apps/base/tests/test_live_settings.py
  engine/apps/grafana_plugin/tests/test_gcom_api_client.py
  engine/apps/grafana_plugin/tests/test_install.py
  engine/apps/grafana_plugin/tests/test_self_hosted_install.py
  engine/apps/integrations/tests/test_views.py
  engine/apps/oss_installation/cloud_heartbeat.py
  engine/apps/phone_notifications/tests/test_phone_backend_call.py
  engine/apps/phone_notifications/tests/test_phone_backend_sms.py
  engine/apps/public_api/tests/test_schedule_export.py
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_shift_swap_request.py
  engine/apps/slack/scenarios/slack_channel_integration.py
  engine/apps/slack/scenarios/slack_renderer.py
  engine/apps/slack/tests/test_scenario_steps/test_paging.py
  engine/apps/slack/types/scenario_routes.py
  engine/apps/user_management/tests/test_region.py
  engine/apps/user_management/tests/test_sync.py
  engine/common/utils.py
  engine/pyproject.toml
  engine/requirements-dev.txt
  engine/requirements.txt
  tools/pagerduty-migrator/Dockerfile
Labels: pr:no changelog, pr:no public docs

#3445 Add test ensuring integration endpoints work if redis cache is down
  engine/apps/integrations/tests/test_views.py
Labels: pr:no changelog, pr:no public docs

#3494 Pin markdown2 to 2.4.10
  engine/requirements.txt
Labels: pr:no changelog, pr:no public docs

#3493 Change labels feature flag to work per oncall org
  engine/apps/labels/tests/test_labels.py
  engine/apps/labels/utils.py
  engine/conftest.py
  engine/settings/base.py
Labels: pr:no changelog, pr:no public docs

#3475 Disallow creating and deleting direct paging integrations
  CHANGELOG.md
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/views/alert_receive_channel.py
  engine/apps/public_api/serializers/integrations.py
  engine/apps/public_api/tests/test_integrations.py
  engine/apps/public_api/views/integrations.py
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/pages/integration/Integration.tsx
Labels: pr:no public docs

#3496 patch redis cluster multi-key operations
  engine/apps/metrics_exporter/helpers.py
  engine/apps/mobile_app/tasks/going_oncall_notification.py
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/tests/test_ical_utils.py
  engine/common/cache.py
  engine/common/tests/test_cache.py
  engine/settings/base.py
Labels: pr:no changelog, pr:no public docs

#3498 Revert "Refactor gcom api calls when syncing org"
  engine/apps/grafana_plugin/helpers/client.py
  engine/apps/grafana_plugin/tests/test_gcom_api_client.py
  engine/apps/user_management/sync.py
  engine/apps/user_management/tests/test_sync.py
Labels: pr:no changelog, pr:no public docs

#3497 Update beat schedule to use crontab schedule types
  engine/settings/base.py
Labels: pr:no changelog, pr:no public docs

#3488 Minor update to schedules API docs
  docs/sources/oncall-api-reference/schedules.md
Labels: pr:no changelog

#3490 add borders to editors
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.module.scss
Labels: pr:no changelog, pr:no public docs, involved:Frontend

#3501 Rename integrations table tabs
  CHANGELOG.md
  grafana-plugin/e2e-tests/integrations/integrationsTable.test.ts
  grafana-plugin/src/pages/integrations/Integrations.tsx
  grafana-plugin/src/plugin.json
Labels: pr:no public docs

#3510 address issue with metrics calculations when redis cluster is used
  engine/apps/metrics_exporter/metrics_collectors.py
  engine/apps/metrics_exporter/tests/conftest.py
  engine/apps/metrics_exporter/tests/test_metrics_collectors.py
Labels: pr:no changelog, pr:no public docs

#3491 Polishing column selector and table view selector
  grafana-plugin/src/containers/ColumnsSelector/ColumnsSelector.styles.ts
  grafana-plugin/src/containers/ColumnsSelectorWrapper/ColumnsModal.tsx
  grafana-plugin/src/containers/ColumnsSelectorWrapper/ColumnsSelectorWrapper.styles.ts
  grafana-plugin/src/pages/incidents/Incidents.tsx
Labels: pr:no changelog, pr:no public docs, involved:Frontend

#3518 Return 404 from mobile app gateway viewset
  engine/apps/api/views/labels.py
  engine/apps/mobile_app/tests/test_mobile_app_gateway.py
  engine/apps/mobile_app/urls.py
  engine/apps/mobile_app/views.py
Labels: pr:no changelog, pr:no public docs

#3513 Track alert received timestamp on alert group creation
  CHANGELOG.md
  engine/apps/alerts/migrations/0042_alertgroup_received_at.py
  engine/apps/alerts/models/alert.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/tests/test_alert.py
  engine/apps/email/inbound.py
  engine/apps/heartbeat/tasks.py
  engine/apps/integrations/tasks.py
  engine/apps/integrations/tests/test_views.py
  engine/apps/integrations/views.py
Labels: pr:no changelog, pr:no public docs

#3514 Do not trigger alert group update log signal before setting alert
  engine/apps/alerts/models/alert_group_log_record.py
  engine/apps/alerts/tests/test_alert_group_log_record.py
Labels: pr:no changelog, pr:no public docs

#3522 Fix missing timestamp value, add test
  CHANGELOG.md
  engine/apps/integrations/tests/test_views.py
  engine/apps/integrations/views.py
Labels: pr:no changelog, pr:no public docs

#3527 Improve FCMDevice.send_message logging
  engine/apps/mobile_app/fcm_relay.py
  engine/apps/mobile_app/utils.py
Labels: pr:no changelog, pr:no public docs

#3530 Fix team changing on PUT request if team is not in request data
  CHANGELOG.md
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/serializers/escalation_chain.py
  engine/apps/api/serializers/schedule_base.py
  engine/apps/api/serializers/webhook.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/tests/test_escalation_chain.py
  engine/apps/api/tests/test_schedules.py
  engine/apps/api/tests/test_webhooks.py
Labels: pr:no public docs

#3526 Log average/max delta between alert ingestion and alert group creation
  engine/apps/alerts/tasks/check_escalation_finished.py
  engine/apps/alerts/tests/test_check_escalation_finished_task.py
Labels: pr:no changelog, pr:no public docs

#3528 Brojd/polishing labels
  grafana-plugin/src/assets/style/utils.css
  grafana-plugin/src/components/ManualAlertGroup/ManualAlertGroup.tsx
  grafana-plugin/src/components/NewScheduleSelector/NewScheduleSelector.module.css
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.module.scss
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.module.css
  grafana-plugin/src/containers/ScheduleForm/ScheduleForm.tsx
  grafana-plugin/src/models/base_store.ts
  grafana-plugin/src/pages/incidents/Incidents.module.scss
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/utils/types.ts
Labels: pr:no changelog, pr:no public docs

#3507 Limit the number of labels per alert group
  engine/apps/labels/alert_group_labels.py
  engine/apps/labels/tests/test_alert_group.py
Labels: pr:no changelog, pr:no public docs

#3532 Brojd/further labels polishing
  grafana-plugin/src/assets/style/utils.css
  grafana-plugin/src/components/GForm/GForm.tsx
  grafana-plugin/src/components/GForm/GForm.types.ts
  grafana-plugin/src/components/IntegrationContactPoint/IntegrationContactPoint.tsx
  grafana-plugin/src/components/PluginLink/PluginLink.tsx
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.config.tsx
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.helpers.test.ts
  grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.helpers.ts
  grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.tsx
  grafana-plugin/src/containers/Labels/Labels.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/models/base_store.ts
  grafana-plugin/src/models/label/label.types.ts
  grafana-plugin/src/models/outgoing_webhook/outgoing_webhook.ts
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/pages/integrations/Integrations.tsx
  grafana-plugin/src/utils/consts.ts
  grafana-plugin/src/utils/decorators.ts
Labels: pr:no changelog, pr:no public docs

#3536 Further improvements on labels
  grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.helpers.ts
  grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.tsx
  grafana-plugin/src/containers/Labels/Labels.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.tsx
Labels: pr:no changelog, pr:no public docs

#3537 Fix labels wording
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.tsx
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/pages/integrations/Integrations.tsx
Labels: pr:no changelog, pr:no public docs

#3538 Dev to main
  CHANGELOG.md
  grafana-plugin/src/assets/style/utils.css
  grafana-plugin/src/components/GForm/GForm.tsx
  grafana-plugin/src/components/GForm/GForm.types.ts
  grafana-plugin/src/components/IntegrationContactPoint/IntegrationContactPoint.tsx
  grafana-plugin/src/components/PluginLink/PluginLink.tsx
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.config.tsx
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.helpers.test.ts
  grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.helpers.ts
  grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.tsx
  grafana-plugin/src/containers/Labels/Labels.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/models/base_store.ts
  grafana-plugin/src/models/label/label.types.ts
  grafana-plugin/src/models/outgoing_webhook/outgoing_webhook.ts
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/pages/integrations/Integrations.tsx
  grafana-plugin/src/utils/consts.ts
  grafana-plugin/src/utils/decorators.ts
Labels: pr:no public docs

#3531 Unified logo with IRM, added few minor UI tweaks, bumped labels version
  grafana-plugin/e2e-tests/integrations/heartbeat.test.ts
  grafana-plugin/e2e-tests/utils/schedule.ts
  grafana-plugin/package.json
  grafana-plugin/src/PluginPage.tsx
  grafana-plugin/src/navbar/Header/Header.module.scss
  grafana-plugin/src/navbar/Header/Header.tsx
  grafana-plugin/src/pages/integrations/Integrations.module.scss
  grafana-plugin/yarn.lock
Labels: pr:no changelog, pr:no public docs

#3541 Fix schedules invalid dates issue
  CHANGELOG.md
  grafana-plugin/src/pages/schedule/Schedule.helpers.ts
Labels: pr:no public docs

#3540 Handle `Unauthorized` exception on posting alert group to telegram
  engine/apps/telegram/models/connectors/personal.py
  engine/apps/telegram/tests/test_personal_connector.py
Labels: pr:no changelog, pr:no public docs

#3509 Fix amazon_ses inbound email ESP provider
  CHANGELOG.md
  engine/apps/email/tests/test_inbound_email.py
  engine/requirements.txt
Labels: pr:no public docs

#3373 Add more docker image cache sources
  Tiltfile
Labels: pr:no changelog, pr:no public docs

#3545 fix typo and edit template btn position
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.tsx
Labels: pr:no changelog, pr:no public docs

#3552 Unifiy logo with IRM
  grafana-plugin/e2e-tests/integrations/heartbeat.test.ts
  grafana-plugin/e2e-tests/utils/schedule.ts
  grafana-plugin/package.json
  grafana-plugin/src/PluginPage.tsx
  grafana-plugin/src/containers/ColumnsSelectorWrapper/ColumnsModal.tsx
  grafana-plugin/src/navbar/Header/Header.module.scss
  grafana-plugin/src/navbar/Header/Header.tsx
  grafana-plugin/src/pages/integrations/Integrations.module.scss
  grafana-plugin/yarn.lock
Labels: pr:no changelog, pr:no public docs

#3553 Fix task retries for deleted alert groups
  engine/apps/alerts/tasks/send_update_log_report_signal.py
  engine/apps/telegram/tasks.py
Labels: pr:no changelog, pr:no public docs

#3554 Add error code for mobile notification logs
  CHANGELOG.md
  engine/apps/base/models/user_notification_policy_log_record.py
  engine/apps/mobile_app/tasks/new_alert_group.py
  engine/apps/mobile_app/tests/tasks/test_new_alert_group.py
Labels: pr:no public docs

#3556 Fix `message is too big` exception for mobile push notification
  CHANGELOG.md
  engine/apps/mobile_app/alert_rendering.py
  engine/apps/mobile_app/tests/tasks/test_new_alert_group.py
Labels: pr:no public docs

#3558 Dev to main
  CHANGELOG.md
  Tiltfile
  engine/apps/alerts/tasks/send_update_log_report_signal.py
  engine/apps/base/models/user_notification_policy_log_record.py
  engine/apps/mobile_app/alert_rendering.py
  engine/apps/mobile_app/tasks/new_alert_group.py
  engine/apps/mobile_app/tests/tasks/test_new_alert_group.py
  engine/apps/telegram/tasks.py
  grafana-plugin/e2e-tests/integrations/heartbeat.test.ts
  grafana-plugin/e2e-tests/utils/schedule.ts
  grafana-plugin/package.json
  grafana-plugin/src/PluginPage.tsx
  grafana-plugin/src/containers/ColumnsSelectorWrapper/ColumnsModal.tsx
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.tsx
  grafana-plugin/src/navbar/Header/Header.module.scss
  grafana-plugin/src/navbar/Header/Header.tsx
  grafana-plugin/src/pages/integrations/Integrations.module.scss
  grafana-plugin/yarn.lock
Labels: pr:no public docs

#3560 add missing borders
  grafana-plugin/src/pages/integration/Integration.module.scss
Labels: pr:no changelog, pr:no public docs

#3500 Add multi-stack support for mobile app
  CHANGELOG.md
  engine/apps/mobile_app/demo_push.py
  engine/apps/mobile_app/serializers.py
  engine/apps/mobile_app/tasks/going_oncall_notification.py
  engine/apps/mobile_app/tasks/new_alert_group.py
  engine/apps/mobile_app/tasks/new_shift_swap_request.py
  engine/apps/mobile_app/tests/tasks/test_going_oncall_notification.py
  engine/apps/mobile_app/tests/tasks/test_new_shift_swap_request.py
  engine/apps/mobile_app/tests/test_demo_push.py
  engine/apps/mobile_app/tests/test_fcm_endpoint.py
  engine/apps/mobile_app/tests/test_mobile_app_auth_token.py
  engine/apps/mobile_app/tests/test_utils.py
  engine/apps/mobile_app/utils.py
  engine/apps/mobile_app/views.py
  engine/apps/user_management/tests/factories.py
Labels: pr:no public docs

#3567 Dev to main
  CHANGELOG.md
  engine/apps/mobile_app/demo_push.py
  engine/apps/mobile_app/serializers.py
  engine/apps/mobile_app/tasks/going_oncall_notification.py
  engine/apps/mobile_app/tasks/new_alert_group.py
  engine/apps/mobile_app/tasks/new_shift_swap_request.py
  engine/apps/mobile_app/tests/tasks/test_going_oncall_notification.py
  engine/apps/mobile_app/tests/tasks/test_new_shift_swap_request.py
  engine/apps/mobile_app/tests/test_demo_push.py
  engine/apps/mobile_app/tests/test_fcm_endpoint.py
  engine/apps/mobile_app/tests/test_mobile_app_auth_token.py
  engine/apps/mobile_app/tests/test_utils.py
  engine/apps/mobile_app/utils.py
  engine/apps/mobile_app/views.py
  engine/apps/user_management/tests/factories.py
  grafana-plugin/src/pages/integration/Integration.module.scss
Labels: pr:no public docs

#3570 Remove unneeded filter making query slower
  engine/apps/alerts/tasks/check_escalation_finished.py
  engine/apps/alerts/tests/test_check_escalation_finished_task.py
Labels: pr:no changelog, pr:no public docs

#3557 Add missing success log entries for personal notifications
  CHANGELOG.md
  engine/apps/alerts/tasks/notify_user.py
  engine/apps/base/models/user_notification_policy_log_record.py
  engine/apps/email/tasks.py
  engine/apps/email/tests/test_notify_user.py
  engine/apps/mobile_app/tasks/new_alert_group.py
  engine/apps/mobile_app/tests/tasks/test_new_alert_group.py
  engine/apps/mobile_app/tests/test_utils.py
  engine/apps/mobile_app/utils.py
  engine/apps/slack/models/slack_message.py
  engine/apps/slack/tests/test_slack_message.py
  engine/apps/telegram/models/connectors/personal.py
  engine/apps/telegram/tests/factories.py
  engine/apps/telegram/tests/test_personal_connector.py
  engine/conftest.py
Labels: pr:no changelog, pr:no public docs

#3572 Added images to oncall migration guide for alert manager
  docs/sources/integrations/alertmanager/index.md
Labels: type/docs, pr:no changelog

#3573 Main to dev
  docs/sources/integrations/alertmanager/index.md
  helm/oncall/Chart.yaml
Labels: pr:no changelog, pr:no public docs

#3574 Dev to main
  CHANGELOG.md
  docs/sources/integrations/alertmanager/index.md
  engine/apps/alerts/tasks/check_escalation_finished.py
  engine/apps/alerts/tasks/notify_user.py
  engine/apps/alerts/tests/test_check_escalation_finished_task.py
  engine/apps/base/models/user_notification_policy_log_record.py
  engine/apps/email/tasks.py
  engine/apps/email/tests/test_notify_user.py
  engine/apps/mobile_app/tasks/new_alert_group.py
  engine/apps/mobile_app/tests/tasks/test_new_alert_group.py
  engine/apps/mobile_app/tests/test_utils.py
  engine/apps/mobile_app/utils.py
  engine/apps/slack/models/slack_message.py
  engine/apps/slack/tests/test_slack_message.py
  engine/apps/telegram/models/connectors/personal.py
  engine/apps/telegram/tests/factories.py
  engine/apps/telegram/tests/test_personal_connector.py
  engine/conftest.py
Labels: pr:no public docs

#3516 Brojd/improve e2e tests dx
  .gitignore
  .prettierrc.js
  CHANGELOG.md
  Makefile
  Tiltfile
  dev/README.md
  dev/helm-local.yml
  grafana-plugin/.dockerignore
  grafana-plugin/.gitignore
  grafana-plugin/e2e-tests/.env.example
  grafana-plugin/e2e-tests/alerts/onCallSchedule.test.ts
  grafana-plugin/e2e-tests/escalationChains/escalationPolicy.test.ts
  grafana-plugin/e2e-tests/globalSetup.ts
  grafana-plugin/e2e-tests/integrations/heartbeat.test.ts
  grafana-plugin/e2e-tests/integrations/integrationsTable.test.ts
  grafana-plugin/e2e-tests/integrations/maintenanceMode.test.ts
  grafana-plugin/e2e-tests/utils/constants.ts
  grafana-plugin/e2e-tests/utils/forms.ts
  grafana-plugin/e2e-tests/utils/integrations.ts
  grafana-plugin/e2e-tests/utils/navigation.ts
  grafana-plugin/playwright.config.ts
  grafana-plugin/src/components/TooltipBadge/TooltipBadge.tsx
  grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.tsx
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/pages/integrations/Integrations.tsx
  grafana-plugin/src/state/rootBaseStore/index.ts
  grafana-plugin/src/state/rootBaseStore/rootBaseStore.test.ts
  grafana-plugin/src/utils/consts.ts
Labels: pr:no public docs

#3562 Check if escalation was skipped in Slack before trying to notify user
  CHANGELOG.md
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/tasks/notify_user.py
  engine/apps/alerts/tests/test_notify_user.py
Labels: pr:no public docs

#3565 Fix: the examples in extraVolumeMounts and extraVolumes are swapped
  helm/oncall/values.yaml
Labels: pr:no changelog, pr:no public docs

#3571 Limit how long acknowledge reminders can run for
  CHANGELOG.md
  engine/apps/alerts/tasks/acknowledge_reminder.py
  engine/apps/alerts/tests/test_acknowledge_reminder.py
  engine/settings/base.py
Labels: pr:no public docs

#3577 Fix alert group columns validation
  CHANGELOG.md
  engine/apps/api/serializers/alert_group_table_settings.py
  engine/apps/api/tests/test_alert_group_table_settings.py
Labels: pr:no public docs

#3578 Speed up escalation auditor
  engine/apps/alerts/escalation_snapshot/escalation_snapshot_mixin.py
  engine/apps/alerts/escalation_snapshot/snapshot_classes/escalation_snapshot.py
  engine/apps/alerts/tasks/check_escalation_finished.py
  engine/apps/alerts/tests/test_check_escalation_finished_task.py
  engine/apps/alerts/tests/test_escalation_snapshot.py
Labels: pr:no changelog, pr:no public docs

#3563 Update auditor to check personal notifications
  engine/apps/alerts/tasks/check_escalation_finished.py
  engine/apps/alerts/tasks/notify_user.py
  engine/apps/alerts/tests/test_check_escalation_finished_task.py
  engine/apps/alerts/tests/test_notify_user.py
  engine/settings/celery_task_routes.py
Labels: pr:no changelog, pr:no public docs

#3582 Fix posting slack message about ratelimits
  CHANGELOG.md
  engine/apps/integrations/tasks.py
Labels: pr:no public docs

#3581 fix PUT /api/v1/escalation_policies/<id> issue related to updating from_time and to_time
  CHANGELOG.md
  engine/apps/public_api/serializers/escalation_policies.py
  engine/apps/public_api/tests/test_escalation_policies.py
  engine/common/api_helpers/custom_fields.py
  grafana-plugin/e2e-tests/escalationChains/escalationPolicy.test.ts
  grafana-plugin/e2e-tests/utils/escalationChain.ts
  grafana-plugin/src/components/TimeRange/TimeRange.tsx
Labels: pr:no public docs

#3586 Fix inbound email integration endpoint
  CHANGELOG.md
  engine/apps/email/inbound.py
  engine/apps/email/tests/test_inbound_email.py
Labels: pr:no public docs

#3580 fix(3564) Support PATCH Method In Outgoing webhook
  CHANGELOG.md
  engine/apps/api/tests/test_webhooks.py
  engine/apps/webhooks/models/webhook.py
  engine/apps/webhooks/tests/test_webhook.py
Labels: pr:no public docs

#3590 fix duplicate teams showing up in teams dropdown for `/escalate` slack command
  CHANGELOG.md
  engine/apps/slack/tests/test_scenario_steps/test_paging.py
  engine/apps/user_management/models/organization.py
  engine/apps/user_management/tests/test_organization.py
Labels: pr:no public docs

#3599 Hide "Limit each shift length" control for month-based rotations
  grafana-plugin/src/containers/RotationForm/RotationForm.tsx
Labels: pr:no changelog, pr:no public docs

#3600 use forked version of redis-py which adds extra debug logging
  engine/requirements.txt
Labels: pr:no changelog, pr:no public docs
