Repository grafana/oncall, pull requests merged in 2023-05, with the labels that each got.

#1856 Do not retry start_sync_organization
  engine/apps/grafana_plugin/tasks/sync.py
Labels: pr:no changelog, pr:no public docs

#1845 Add filter descriptions
  CHANGELOG.md
  engine/apps/api/views/alert_group.py
  grafana-plugin/src/containers/RemoteFilters/RemoteFilters.tsx
  grafana-plugin/src/containers/RemoteFilters/RemoteFilters.types.ts
Labels: pr:no public docs

#1847 Remove template editor from Slack
  CHANGELOG.md
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/slack/scenarios/alertgroup_appearance.py
Labels: pr:no public docs

#1747 Fix bugs in web title and message templates rendering and visual representation
  CHANGELOG.md
  engine/apps/alerts/tests/test_default_templates.py
  engine/common/utils.py
  engine/config_integrations/alertmanager.py
  engine/config_integrations/grafana.py
  engine/config_integrations/grafana_alerting.py
  engine/requirements.txt
  grafana-plugin/src/utils/sanitize.ts
Labels: pr:no public docs

#1842 Jira inbound integration docs
  docs/sources/integrations/available-integrations/configure-jira/index.md
  engine/apps/integrations/templates/html/integration_jira.html
  grafana-plugin/src/components/IntegrationLogo/IntegrationLogo.config.ts
Labels: pr:no changelog

#1853 Add "Notifications Receiver" RBAC role
  CHANGELOG.md
  dev/README.md
  docker-compose-developer.yml
  docker-compose-mysql-rabbitmq.yml
  docker-compose.yml
  engine/apps/api/permissions/__init__.py
  engine/apps/api/tests/test_user.py
  engine/apps/api/views/user.py
  engine/conftest.py
  grafana-plugin/src/components/UserGroups/UserGroups.tsx
  grafana-plugin/src/plugin.json
Labels: pr:no public docs

#1859 Remove schedule name uniqueness restriction
  CHANGELOG.md
  engine/apps/public_api/serializers/schedules_base.py
  engine/apps/public_api/tests/test_schedules.py
  engine/apps/schedules/migrations/0012_auto_20230502_1259.py
  engine/apps/schedules/models/on_call_schedule.py
Labels: pr:no public docs

#1863 Handle invitation button press
  engine/apps/slack/models/slack_user_identity.py
  engine/apps/slack/scenarios/notified_user_not_in_channel.py
  engine/apps/slack/views.py
Labels: pr:no changelog, pr:no public docs

#1860 Zendesk inbound integration docs
  docs/sources/integrations/available-integrations/configure-jira/index.md
  docs/sources/integrations/available-integrations/configure-zendesk/index.md
  engine/apps/integrations/templates/html/integration_jira.html
  engine/apps/integrations/templates/html/integration_zendesk.html
  grafana-plugin/src/components/IntegrationLogo/IntegrationLogo.config.ts
Labels: pr:no changelog

#1867 grafana -> Grafana
  engine/config_integrations/grafana.py
Labels: pr:no changelog, pr:no public docs

#1870 Update ical comparison to check only for event components
  CHANGELOG.md
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/tests/test_ical_utils.py
Labels: pr:no public docs

#1874 Add routes_count and connected_escalations_chains_count to alert_rece…
  engine/apps/api/serializers/alert_receive_channel.py
Labels: pr:no changelog, pr:no public docs

#1871 Rewrite texts for ~Connectivity~ Notification Warning
  grafana-plugin/src/containers/Alerts/Alerts.tsx
Labels: pr:no changelog, pr:no public docs

#1873 Add route_template to preview_template endpoint
  engine/common/api_helpers/mixins.py
Labels: pr:no changelog, pr:no public docs

#1872 Add pagination to integrations page
  engine/apps/api/views/alert_receive_channel.py
Labels: pr:no changelog, pr:no public docs

#1866 Minor tweaks to Tag component
  grafana-plugin/src/components/Tag/Tag.module.css
  grafana-plugin/src/pages/incident/Incident.module.scss
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/incidents/parts/IncidentDropdown.module.scss
Labels: pr:no changelog, pr:no public docs

#1881 Pin requests and urllib3
  engine/requirements.txt
Labels: pr:no changelog, pr:no public docs

#1880 properly parse grafana cloud feature toggles
  CHANGELOG.md
  engine/apps/grafana_plugin/helpers/client.py
  engine/apps/grafana_plugin/tests/test_gcom_api_client.py
Labels: pr:no public docs

#1852 Add make a copy action for advanced webhooks
  grafana-plugin/src/containers/OutgoingWebhook2Form/OutgoingWebhook2Form.tsx
  grafana-plugin/src/pages/outgoing_webhooks_2/OutgoingWebhooks2.tsx
Labels: pr:no changelog, pr:no public docs

#1814 "You're Going OnCall" mobile app push notification
  CHANGELOG.md
  engine/apps/mobile_app/migrations/0004_auto_20230425_1033.py
  engine/apps/mobile_app/models.py
  engine/apps/mobile_app/serializers.py
  engine/apps/mobile_app/tasks.py
  engine/apps/mobile_app/tests/test_fcm_relay.py
  engine/apps/mobile_app/tests/test_notify_user.py
  engine/apps/mobile_app/tests/test_user_settings.py
  engine/apps/mobile_app/tests/test_your_going_oncall_notification.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/settings/base.py
Labels: pr:no public docs

#1865 Fix and tidy alertmanager heartbeat template
  engine/apps/integrations/templates/heartbeat_instructions/alertmanager.html
  grafana-plugin/src/containers/HeartbeatModal/HeartbeatForm.tsx
Labels: pr:no public docs

#1883 Use the correct description
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.config.ts
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.types.ts
  grafana-plugin/src/pages/integration_2/Integration2.tsx
Labels: pr:no changelog, pr:no public docs

#1885 Fix teams filter related issue setting maintenance mode
  CHANGELOG.md
  engine/apps/api/tests/test_maintenance.py
  engine/apps/api/views/maintenance.py
Labels: pr:no public docs

#1879 Rares/templating tweaks
  grafana-plugin/src/components/CounterBadge/CounterBadge.tsx
  grafana-plugin/src/components/IntegrationCollapsibleTreeView/IntegrationCollapsibleTreeView.tsx
  grafana-plugin/src/components/ScheduleQuality/ScheduleQuality.tsx
  grafana-plugin/src/components/TooltipBadge/TooltipBadge.module.scss
  grafana-plugin/src/components/TooltipBadge/TooltipBadge.tsx
  grafana-plugin/src/models/alert_receive_channel.ts
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.types.ts
  grafana-plugin/src/pages/incident/Incident.module.scss
  grafana-plugin/src/pages/integration_2/Integration2.helper.ts
  grafana-plugin/src/pages/integration_2/Integration2.module.scss
  grafana-plugin/src/pages/integration_2/Integration2.tsx
  grafana-plugin/src/pages/integrations_2/Integrations2.tsx
  grafana-plugin/src/pages/schedules/Schedules.tsx
  grafana-plugin/src/pages/users/Users.tsx
  grafana-plugin/src/style/vars.css
Labels: pr:no changelog, pr:no public docs

#1894 add missing alertgroup db migration
  engine/apps/alerts/migrations/0015_auto_20230508_1641.py
Labels: pr:no changelog, pr:no public docs

#1891 Refactor upcoming shifts to use cached final schedule data
  engine/apps/api/tests/test_user.py
  engine/apps/api/views/user.py
  engine/apps/schedules/constants.py
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_ical_utils.py
  engine/apps/schedules/tests/test_on_call_schedule.py
Labels: pr:no changelog, pr:no public docs

#1897 Update .drone file signature
  .drone.yml
Labels: pr:no changelog, pr:no public docs

#1902 fix-new-schedule-creation
  grafana-plugin/src/components/NewScheduleSelector/NewScheduleSelector.tsx
Labels: pr:no changelog, pr:no public docs

#1900 Webhook response check content length instead of header for length limit
  engine/apps/webhooks/tasks/trigger_webhook.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
Labels: pr:no changelog, pr:no public docs

#1893 add important_notification_volume_override to mobile app user settings model
  CHANGELOG.md
  engine/apps/mobile_app/migrations/0005_mobileappusersettings_important_notification_volume_override.py
  engine/apps/mobile_app/models.py
  engine/apps/mobile_app/serializers.py
  engine/apps/mobile_app/tasks.py
  engine/apps/mobile_app/tests/test_notify_user.py
  engine/apps/mobile_app/tests/test_user_settings.py
Labels: pr:no public docs

#1911 Merge hotfix to dev
  CHANGELOG.md
  engine/apps/alerts/incident_appearance/templaters/alert_templater.py
  helm/oncall/Chart.yaml
Labels: pr:no changelog, pr:no public docs

#1896 allow the POST incoming alert endpoints to queue create_alert tasks independent of the database status
  engine/apps/grafana_plugin/apps.py
  engine/apps/integrations/mixins/alert_channel_defining_mixin.py
Labels: pr:no changelog, pr:no public docs

#1790 bump mysql from 5.7 to 8.0.32
  .drone.yml
  .github/workflows/linting-and-tests.yml
  docker-compose-developer.yml
  docker-compose-mysql-rabbitmq.yml
Labels: pr:no changelog

#1921 Delete SECURITY.md
  SECURITY.md
Labels: pr:no changelog

#1922 fix bug in the "you're going oncall" push notification copy
  CHANGELOG.md
  engine/apps/mobile_app/tasks.py
  engine/apps/mobile_app/tests/test_your_going_oncall_notification.py
Labels: pr:no public docs

#1916 Add docs & logo for AppDynamics integration
  docs/sources/integrations/available-integrations/configure-appdynamics/index.md
  engine/apps/integrations/templates/html/integration_appdynamics.html
  grafana-plugin/src/components/IntegrationLogo/IntegrationLogo.config.ts
Labels: pr:no changelog

#1878 Iskhakov/fix frontend tests
  grafana-plugin/jest.config.js
  grafana-plugin/src/components/CardButton/CardButton.test.tsx
  grafana-plugin/src/components/Collapse/Collapse.test.tsx
  grafana-plugin/src/components/ScheduleQualityDetails/ScheduleQualityProgressBar.test.tsx
  grafana-plugin/src/components/ScheduleQualityDetails/__snapshots__/ScheduleQualityProgressBar.test.tsx.snap
  grafana-plugin/src/components/SourceCode/SourceCode.test.tsx
  grafana-plugin/src/components/Unauthorized/Unauthorized.test.tsx
  grafana-plugin/src/components/Unauthorized/__snapshots__/Unauthorized.test.tsx.snap
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.test.tsx
  grafana-plugin/src/containers/MobileAppConnection/__snapshots__/MobileAppConnection.test.tsx.snap
  grafana-plugin/src/containers/MobileAppConnection/parts/DisconnectButton/DisconnectButton.test.tsx
  grafana-plugin/src/containers/MobileAppConnection/parts/DisconnectButton/__snapshots__/DisconnectButton.test.tsx.snap
  grafana-plugin/src/containers/MobileAppConnection/parts/DownloadIcons/DownloadIcons.test.tsx
  grafana-plugin/src/containers/MobileAppConnection/parts/DownloadIcons/__snapshots__/DownloadIcons.test.tsx.snap
  grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.test.tsx
  grafana-plugin/src/containers/PluginConfigPage/__snapshots__/PluginConfigPage.test.tsx.snap
  grafana-plugin/src/containers/PluginConfigPage/parts/ConfigurationForm/ConfigurationForm.test.tsx
  grafana-plugin/src/containers/PluginConfigPage/parts/ConfigurationForm/__snapshots__/ConfigurationForm.test.tsx.snap
  grafana-plugin/src/containers/PluginConfigPage/parts/RemoveCurrentConfigurationButton/RemoveCurrentConfigurationButton.test.tsx
  grafana-plugin/src/containers/PluginConfigPage/parts/RemoveCurrentConfigurationButton/__snapshots__/RemoveCurrentConfigurationButton.test.tsx.snap
  grafana-plugin/src/containers/PluginConfigPage/parts/StatusMessageBlock/StatusMessageBlock.test.tsx
  grafana-plugin/src/containers/PluginConfigPage/parts/StatusMessageBlock/__snapshots__/StatusMessageBlock.test.tsx.snap
  grafana-plugin/src/plugin/PluginSetup/PluginSetup.test.tsx
  grafana-plugin/src/plugin/PluginSetup/__snapshots__/PluginSetup.test.tsx.snap
Labels: pr:no changelog, pr:no public docs

#1925 Fix bug with newlines markdown converter
  CHANGELOG.md
  engine/common/utils.py
  engine/config_integrations/alertmanager.py
  engine/config_integrations/grafana.py
Labels: pr:no public docs

#1926 add user settings for info notifications
  CHANGELOG.md
  engine/apps/mobile_app/migrations/0006_auto_20230512_0902.py
  engine/apps/mobile_app/models.py
  engine/apps/mobile_app/serializers.py
  engine/apps/mobile_app/tasks.py
  engine/apps/mobile_app/tests/test_user_settings.py
Labels: pr:no public docs

#1917 add the ability to set/display "currently undergoing maintenance message" in the UI
  CHANGELOG.md
  engine/conftest.py
  engine/engine/celery.py
  engine/engine/tests/test_maintenance_mode.py
  engine/engine/urls.py
  engine/engine/views.py
  engine/settings/base.py
  grafana-plugin/src/plugin/PluginSetup/PluginSetup.test.tsx
  grafana-plugin/src/plugin/PluginSetup/__snapshots__/PluginSetup.test.tsx.snap
  grafana-plugin/src/plugin/PluginSetup/index.tsx
  grafana-plugin/src/state/plugin/index.ts
  grafana-plugin/src/state/plugin/plugin.test.ts
  grafana-plugin/src/state/rootBaseStore/index.ts
  grafana-plugin/src/state/rootBaseStore/rootBaseStore.test.ts
Labels: pr:no public docs

#1924 Remove prints
  engine/apps/alerts/tests/test_default_templates.py
Labels: pr:no changelog, pr:no public docs

#1907 Grouping templating polishing 1st part
  grafana-plugin/integration-tests/alerts/sms.test.ts
  grafana-plugin/src/components/AlertTemplates/AlertTemplatesForm.config.ts
  grafana-plugin/src/components/CheatSheet/CheatSheet.module.css
  grafana-plugin/src/components/CheatSheet/CheatSheet.tsx
  grafana-plugin/src/containers/EditRegexpRouteTemplateModal/EditRegexpRouteTemplateModal.module.css
  grafana-plugin/src/containers/EditRegexpRouteTemplateModal/EditRegexpRouteTemplateModal.tsx
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm2.config.ts
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm2.helpers.ts
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm2.module.css
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm2.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.module.css
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
  grafana-plugin/src/containers/TemplatePreview/TemplatePreview.tsx
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.module.css
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
  grafana-plugin/src/models/alert_receive_channel.ts
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.types.ts
  grafana-plugin/src/models/channel_filter/channel_filter.types.ts
  grafana-plugin/src/pages/index.tsx
  grafana-plugin/src/pages/integration_2/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/pages/integration_2/Integration2.helper.ts
  grafana-plugin/src/pages/integration_2/Integration2.tsx
  grafana-plugin/src/pages/integrations_2/Integrations2.module.scss
  grafana-plugin/src/pages/integrations_2/Integrations2.tsx
Labels: pr:no changelog, pr:no public docs

#1941 dont enable silk if maintenance mode is enabled
  engine/settings/base.py
Labels: pr:no changelog, pr:no public docs

#1937 Rares/templating settings
  grafana-plugin/src/components/AlertTemplates/AlertTemplatesForm.tsx
  grafana-plugin/src/components/IntegrationCollapsibleTreeView/IntegrationCollapsibleTreeView.tsx
  grafana-plugin/src/components/IntegrationInputField/IntegrationInputField.module.scss
  grafana-plugin/src/components/IntegrationInputField/IntegrationInputField.tsx
  grafana-plugin/src/components/IntegrationMaskedInputField/IntegrationMaskedInputField.tsx
  grafana-plugin/src/components/MonacoEditor/MonacoEditor.tsx
  grafana-plugin/src/components/MonacoEditor/jinja2.ts
  grafana-plugin/src/components/Tag/Tag.tsx
  grafana-plugin/src/components/Text/Text.tsx
  grafana-plugin/src/containers/AlertTemplatesFormContainer/AlertTemplatesFormContainer.tsx
  grafana-plugin/src/containers/ChannelFilterForm/ChannelFilterForm.tsx
  grafana-plugin/src/containers/EditRegexpRouteTemplateModal/EditRegexpRouteTemplateModal.tsx
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm2.helpers.ts
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm2.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
  grafana-plugin/src/containers/MaintenanceForm/MaintenanceForm.tsx
  grafana-plugin/src/containers/MobileAppConnection/__snapshots__/MobileAppConnection.test.tsx.snap
  grafana-plugin/src/containers/MobileAppConnection/parts/DownloadIcons/__snapshots__/DownloadIcons.test.tsx.snap
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.module.css
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
  grafana-plugin/src/containers/UserDisplay/UserDisplayWithAvatar.tsx
  grafana-plugin/src/models/action.ts
  grafana-plugin/src/models/alert_receive_channel.ts
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.types.ts
  grafana-plugin/src/models/alertgroup/alertgroup.ts
  grafana-plugin/src/models/channel_filter.ts
  grafana-plugin/src/pages/integration_2/CollapsedIntegrationRouteDisplay.tsx
  grafana-plugin/src/pages/integration_2/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/pages/integration_2/Integration2.config.ts
  grafana-plugin/src/pages/integration_2/Integration2.helper.ts
  grafana-plugin/src/pages/integration_2/Integration2.module.scss
  grafana-plugin/src/pages/integration_2/Integration2.tsx
  grafana-plugin/src/pages/integration_2/Integration2HeartbeatForm.module.scss
  grafana-plugin/src/pages/integration_2/Integration2HeartbeatForm.tsx
  grafana-plugin/src/pages/integration_2/IntegrationBlock.module.scss
  grafana-plugin/src/pages/integration_2/IntegrationBlock.tsx
  grafana-plugin/src/pages/integration_2/IntegrationTemplateBlock.tsx
  grafana-plugin/src/pages/integration_2/IntegrationTemplatesList.tsx
  grafana-plugin/src/pages/integrations_2/Integrations2.tsx
  grafana-plugin/src/pages/maintenance/Maintenance.tsx
  grafana-plugin/src/style/vars.css
Labels: pr:no changelog, pr:no public docs

#1947 Grouping templating polishing 2
  grafana-plugin/src/containers/EditRegexpRouteTemplateModal/EditRegexpRouteTemplateModal.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
  grafana-plugin/src/icons/index.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/pages/integration_2/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/pages/integration_2/Integration2.tsx
  grafana-plugin/src/pages/integrations_2/Integrations2.tsx
Labels: pr:no changelog, pr:no public docs

#1951 Fix for creating Integration
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm2.tsx
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.module.css
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
  grafana-plugin/src/pages/integration_2/Integration2.tsx
Labels: pr:no changelog, pr:no public docs

#1952 Allow null for short description in integrations api
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/public_api/serializers/integrations.py
  engine/config_integrations/alertmanager.py
  engine/config_integrations/formatted_webhook.py
Labels: pr:no changelog, pr:no public docs

#1957 Fix escalation reordering
  CHANGELOG.md
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/containers/EscalationChainSteps/EscalationChainSteps.tsx
Labels: pr:no public docs

#1950 Fix organizations not being deleted by start_cleanup_deleted_organizations
  engine/apps/grafana_plugin/helpers/client.py
  engine/apps/user_management/sync.py
  engine/apps/user_management/tests/test_sync.py
Labels: pr:no changelog, pr:no public docs

#1962 Merge dev to main
  CHANGELOG.md
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/grafana_plugin/helpers/client.py
  engine/apps/public_api/serializers/integrations.py
  engine/apps/user_management/sync.py
  engine/apps/user_management/tests/test_sync.py
  engine/config_integrations/alertmanager.py
  engine/config_integrations/formatted_webhook.py
  engine/requirements.txt
  engine/settings/base.py
  grafana-plugin/src/components/AlertTemplates/AlertTemplatesForm.tsx
  grafana-plugin/src/components/IntegrationCollapsibleTreeView/IntegrationCollapsibleTreeView.tsx
  grafana-plugin/src/components/IntegrationInputField/IntegrationInputField.module.scss
  grafana-plugin/src/components/IntegrationInputField/IntegrationInputField.tsx
  grafana-plugin/src/components/IntegrationMaskedInputField/IntegrationMaskedInputField.tsx
  grafana-plugin/src/components/MonacoEditor/MonacoEditor.tsx
  grafana-plugin/src/components/MonacoEditor/jinja2.ts
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/components/Tag/Tag.tsx
  grafana-plugin/src/components/Text/Text.tsx
  grafana-plugin/src/containers/AlertTemplatesFormContainer/AlertTemplatesFormContainer.tsx
  grafana-plugin/src/containers/ChannelFilterForm/ChannelFilterForm.tsx
  grafana-plugin/src/containers/EditRegexpRouteTemplateModal/EditRegexpRouteTemplateModal.tsx
  grafana-plugin/src/containers/EscalationChainSteps/EscalationChainSteps.tsx
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm2.helpers.ts
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm2.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
  grafana-plugin/src/containers/MaintenanceForm/MaintenanceForm.tsx
  grafana-plugin/src/containers/MobileAppConnection/__snapshots__/MobileAppConnection.test.tsx.snap
  grafana-plugin/src/containers/MobileAppConnection/parts/DownloadIcons/__snapshots__/DownloadIcons.test.tsx.snap
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.module.css
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
  grafana-plugin/src/containers/UserDisplay/UserDisplayWithAvatar.tsx
  grafana-plugin/src/icons/index.tsx
  grafana-plugin/src/models/action.ts
  grafana-plugin/src/models/alert_receive_channel.ts
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.types.ts
  grafana-plugin/src/models/alertgroup/alertgroup.ts
  grafana-plugin/src/models/channel_filter.ts
  grafana-plugin/src/pages/integration_2/CollapsedIntegrationRouteDisplay.tsx
  grafana-plugin/src/pages/integration_2/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/pages/integration_2/Integration2.config.ts
  grafana-plugin/src/pages/integration_2/Integration2.helper.ts
  grafana-plugin/src/pages/integration_2/Integration2.module.scss
  grafana-plugin/src/pages/integration_2/Integration2.tsx
  grafana-plugin/src/pages/integration_2/Integration2HeartbeatForm.module.scss
  grafana-plugin/src/pages/integration_2/Integration2HeartbeatForm.tsx
  grafana-plugin/src/pages/integration_2/IntegrationBlock.module.scss
  grafana-plugin/src/pages/integration_2/IntegrationBlock.tsx
  grafana-plugin/src/pages/integration_2/IntegrationTemplateBlock.tsx
  grafana-plugin/src/pages/integration_2/IntegrationTemplatesList.tsx
  grafana-plugin/src/pages/integrations_2/Integrations2.tsx
  grafana-plugin/src/pages/maintenance/Maintenance.tsx
  grafana-plugin/src/style/vars.css
Labels: pr:no public docs

#1890 Feat(Dev): Improve Building of Grafana Plugin in Development Env + update node version
  .drone.yml
  .github/workflows/linting-and-tests.yml
  .github/workflows/snyk.yml
  .nvmrc
  Makefile
  dev/README.md
  docker-compose-developer.yml
  grafana-plugin/Dockerfile.dev
  grafana-plugin/package.json
  grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.test.tsx
  grafana-plugin/yarn.lock
Labels: pr:no changelog, pr:no public docs

#1933 Test mobile push
  CHANGELOG.md
  engine/apps/api/throttlers/test_call_throttler.py
  engine/apps/api/views/features.py
  engine/apps/api/views/user.py
  engine/apps/mobile_app/demo_push.py
  engine/apps/mobile_app/exceptions.py
  engine/apps/mobile_app/tests/test_demo_push.py
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.module.scss
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.tsx
  grafana-plugin/src/containers/MobileAppConnection/__snapshots__/MobileAppConnection.test.tsx.snap
  grafana-plugin/src/models/user/user.ts
Labels: pr:no public docs

#1965 v1.2.25
  .drone.yml
  .github/workflows/linting-and-tests.yml
  .github/workflows/snyk.yml
  .nvmrc
  CHANGELOG.md
  Makefile
  dev/README.md
  docker-compose-developer.yml
  engine/apps/api/throttlers/test_call_throttler.py
  engine/apps/api/views/features.py
  engine/apps/api/views/user.py
  engine/apps/mobile_app/demo_push.py
  engine/apps/mobile_app/exceptions.py
  engine/apps/mobile_app/tests/test_demo_push.py
  grafana-plugin/Dockerfile.dev
  grafana-plugin/package.json
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.module.scss
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.tsx
  grafana-plugin/src/containers/MobileAppConnection/__snapshots__/MobileAppConnection.test.tsx.snap
  grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.test.tsx
  grafana-plugin/src/models/user/user.ts
  grafana-plugin/yarn.lock
Labels: pr:no public docs

#1967 Mobile push dynamic setting
  engine/apps/api/views/features.py
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.tsx
  grafana-plugin/src/state/features.ts
Labels: pr:no changelog, pr:no public docs

#1970 Fix inbound email bug when attaching files
  CHANGELOG.md
  engine/apps/email/inbound.py
Labels: pr:no public docs

#1979 Templates tweaks
  grafana-plugin/src/components/IntegrationCollapsibleTreeView/IntegrationCollapsibleTreeView.module.scss
  grafana-plugin/src/components/Tag/Tag.module.css
  grafana-plugin/src/pages/integration_2/CollapsedIntegrationRouteDisplay.module.scss
  grafana-plugin/src/pages/integration_2/CollapsedIntegrationRouteDisplay.tsx
  grafana-plugin/src/pages/integration_2/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/pages/integration_2/Integration2.helper.ts
  grafana-plugin/src/pages/integration_2/Integration2.module.scss
  grafana-plugin/src/pages/integration_2/Integration2.tsx
  grafana-plugin/src/pages/integration_2/IntegrationBlockItem.module.scss
  grafana-plugin/src/pages/integration_2/IntegrationTemplateBlock.module.scss
  grafana-plugin/src/pages/integration_2/IntegrationTemplateBlock.tsx
  grafana-plugin/src/pages/integration_2/IntegrationTemplatesList.tsx
Labels: pr:no changelog, pr:no public docs

#1969 Allow passing Firebase credentials via environment variable
  CHANGELOG.md
  docker-compose-developer.yml
  engine/settings/base.py
Labels: pr:no public docs

#1980 Bring back FCM_PROJECT_ID env variable
  docker-compose-developer.yml
  engine/settings/base.py
Labels: pr:no changelog, pr:no public docs

#1984 Fix SQLite permission issue
  CHANGELOG.md
  engine/Dockerfile
  engine/apps/telegram/views.py
  engine/engine/celery.py
  engine/engine/management/commands/create_sqlite_db.py
Labels: pr:no public docs

#1944 Refactor alertmanager templates
  engine/config_integrations/alertmanager.py
Labels: pr:no changelog, pr:no public docs

#1981 Refactored templates within templates&grouping
  grafana-plugin/src/components/Integrations/IntegrationBlock.module.scss
  grafana-plugin/src/components/Integrations/IntegrationBlock.tsx
  grafana-plugin/src/components/Integrations/IntegrationBlockItem.module.scss
  grafana-plugin/src/components/Integrations/IntegrationBlockItem.tsx
  grafana-plugin/src/components/Integrations/IntegrationTemplateBlock.module.scss
  grafana-plugin/src/components/Integrations/IntegrationTemplateBlock.tsx
  grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.module.scss
  grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.module.scss
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationContainers/Integration2HearbeatForm/Integration2HeartbeatForm.tsx
  grafana-plugin/src/containers/IntegrationContainers/IntegrationTemplatesList.config.ts
  grafana-plugin/src/containers/IntegrationContainers/IntegrationTemplatesList.tsx
  grafana-plugin/src/pages/integration_2/Integration2.tsx
  grafana-plugin/src/pages/integration_2/Integration2HeartbeatForm.module.scss
  grafana-plugin/src/pages/integration_2/IntegrationTemplatesList.tsx
Labels: pr:no changelog, pr:no public docs

#1988 Fixed delete integration copy
  grafana-plugin/src/pages/integration_2/Integration2.tsx
Labels: pr:no changelog, pr:no public docs

#1993 Templates tweaks
  grafana-plugin/src/components/Timeline/Timeline.module.css
  grafana-plugin/src/components/Timeline/TimelineItem.tsx
  grafana-plugin/src/containers/AlertRules/parts/index.tsx
  grafana-plugin/src/containers/GSelect/GSelect.tsx
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
Labels: pr:no changelog, pr:no public docs

#1953 Fix autosuggestions in monaco editor
  grafana-plugin/src/components/MonacoEditor/MonacoEditor.tsx
Labels: pr:no changelog, pr:no public docs

#1995 Improve plugin authentication
  CHANGELOG.md
  engine/apps/auth_token/auth.py
  engine/apps/auth_token/models/plugin_auth_token.py
  engine/apps/auth_token/tests/test_plugin_auth.py
  engine/apps/grafana_plugin/helpers/gcom.py
Labels: pr:no public docs

#1961 re-enable e2e UI tests on CI
  .github/workflows/linting-and-tests.yml
  grafana-plugin/integration-tests/globalSetup.ts
  grafana-plugin/integration-tests/schedules/quality.test.ts
  grafana-plugin/playwright.config.ts
  grafana-plugin/src/components/EscalationsFilters/EscalationsFilters.module.css
  grafana-plugin/src/components/EscalationsFilters/EscalationsFilters.tsx
  grafana-plugin/src/components/ScheduleQuality/ScheduleQuality.tsx
  grafana-plugin/src/components/ScheduleQualityDetails/ScheduleQualityDetails.tsx
  grafana-plugin/src/plugin.json
Labels: pr:no changelog, pr:no public docs

#1997 e2e tests on CI - actually await k8s resources to be ready before starting tests
  .github/workflows/linting-and-tests.yml
  grafana-plugin/integration-tests/globalSetup.ts
  grafana-plugin/playwright.config.ts
Labels: pr:no changelog, pr:no public docs

#1998 Improve twilio callback logging
  engine/apps/twilioapp/gather.py
  engine/apps/twilioapp/status_callback.py
  engine/apps/twilioapp/views.py
Labels: pr:no changelog, pr:no public docs

#2001 Remove user defined time period from "you're going oncall" mobile push
  CHANGELOG.md
  engine/apps/mobile_app/tasks.py
  engine/apps/mobile_app/tests/test_your_going_oncall_notification.py
Labels: pr:no public docs

#1837 Docs: update slack setup
  docs/sources/notify/slack/index.md
Labels: type/docs, pr:no changelog

#1836 Docs: Update teams setup
  docs/sources/notify/ms-teams/index.md
Labels: type/docs, pr:no changelog

#1835 Docs: Oncall getting started
  docs/sources/get-started/_index.md
Labels: type/docs, pr:no changelog

#1716 Insight logs docs
  docs/sources/insights-and-metrics/_index.md
Labels: pr:no changelog

#2006 Remove spammy log message for device not setup
  engine/apps/mobile_app/tasks.py
Labels: pr:no changelog, pr:no public docs

#2009 fix import issue which affected going oncall push notification
  engine/apps/mobile_app/tasks.py
Labels: pr:no changelog, pr:no public docs

#2014 Fix status callbacks
  engine/apps/phone_notifications/phone_backend.py
  engine/apps/twilioapp/status_callback.py
Labels: pr:no changelog, pr:no public docs

#2015 dev to main
  CHANGELOG.md
  engine/apps/phone_notifications/phone_backend.py
  engine/apps/twilioapp/status_callback.py
Labels: pr:no changelog, pr:no public docs

#2019 Handle error when updating closed modal window in Slack
  CHANGELOG.md
  engine/apps/slack/scenarios/resolution_note.py
  engine/apps/slack/tests/test_scenario_steps/test_resolution_note.py
Labels: pr:no public docs

#2021 update engine log format + log out device type when sending push notifications
  engine/apps/mobile_app/tasks.py
  engine/engine/middlewares.py
Labels: pr:no changelog, pr:no public docs

#2004 Refresh final schedule after cached icals are dropped
  CHANGELOG.md
  engine/apps/schedules/models/custom_on_call_shift.py
  engine/apps/schedules/tasks/drop_cached_ical.py
  engine/apps/schedules/tests/test_tasks_drop_cached_ical.py
Labels: pr:no public docs

#2007 Handle slack payload metadata limit in paging command
  CHANGELOG.md
  engine/apps/slack/constants.py
  engine/apps/slack/scenarios/paging.py
  engine/apps/slack/tests/test_scenario_steps/test_paging.py
Labels: pr:no public docs

#2028 Remove spammy log message for device not setup 2
  engine/apps/mobile_app/tasks.py
Labels: pr:no changelog, pr:no public docs

#2025 Handle date values coming from ical in final schedule caching
  CHANGELOG.md
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_on_call_schedule.py
Labels: pr:no public docs

#1605 OnCall prometheus metrics exporter
  CHANGELOG.md
  engine/apps/alerts/constants.py
  engine/apps/alerts/migrations/0016_auto_20230523_1355.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/tasks/unsilence.py
  engine/apps/alerts/tests/test_silence.py
  engine/apps/metrics_exporter/__init__.py
  engine/apps/metrics_exporter/constants.py
  engine/apps/metrics_exporter/helpers.py
  engine/apps/metrics_exporter/metrics_cache_manager.py
  engine/apps/metrics_exporter/metrics_collectors.py
  engine/apps/metrics_exporter/tasks.py
  engine/apps/metrics_exporter/tests/__init__.py
  engine/apps/metrics_exporter/tests/conftest.py
  engine/apps/metrics_exporter/tests/test_calculation_metrics.py
  engine/apps/metrics_exporter/tests/test_metrics_collectors.py
  engine/apps/metrics_exporter/tests/test_update_metics_cache.py
  engine/apps/metrics_exporter/urls.py
  engine/apps/metrics_exporter/views.py
  engine/apps/user_management/models/team.py
  engine/conftest.py
  engine/requirements.txt
  engine/settings/base.py
  engine/settings/prod_without_db.py
Labels: pr:no public docs

#2022 update logging for slack interactive_api_endpoint
  engine/apps/slack/views.py
Labels: pr:no changelog, pr:no public docs

#1976 Map country code to different Twilio resources
  CHANGELOG.md
  engine/apps/base/tests/test_live_settings.py
  engine/apps/twilioapp/migrations/0005_twilioaccount_twiliophonecallsender_twiliosmssender_twilioverificationsender.py
  engine/apps/twilioapp/models/__init__.py
  engine/apps/twilioapp/models/twilio_sender.py
  engine/apps/twilioapp/phone_provider.py
  engine/apps/twilioapp/tests/conftest.py
  engine/apps/twilioapp/tests/factories.py
  engine/apps/twilioapp/tests/test_senders.py
Labels: pr:no public docs

#2020 bug fixes
  grafana-plugin/src/components/CheatSheet/CheatSheet.module.css
  grafana-plugin/src/components/CheatSheet/CheatSheet.tsx
  grafana-plugin/src/components/GForm/GForm.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.module.css
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
  grafana-plugin/src/containers/TemplatePreview/TemplatePreview.tsx
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.module.css
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
  grafana-plugin/src/pages/integration_2/Integration2.tsx
Labels: pr:no changelog, pr:no public docs

#2027 changed notification title and subtitle; removed body
  CHANGELOG.md
  engine/apps/mobile_app/alert_rendering.py
  engine/apps/mobile_app/tasks.py
Labels: pr:no public docs

#2036 Fix bugs in helm chart with external postgresql configuration
  .github/workflows/linting-and-tests.yml
  helm/oncall/.helmignore
  helm/oncall/templates/_env.tpl
  helm/oncall/tests/postgres_env_test.yaml
  helm/oncall/tests/postgres_password_env_test.yaml
  helm/oncall/values.yaml
Labels: pr:no changelog

#2037 Enable selecting active days for every shift freq
  CHANGELOG.md
  engine/apps/api/serializers/on_call_shifts.py
  engine/apps/api/tests/test_oncall_shift.py
  grafana-plugin/src/containers/RotationForm/RotationForm.tsx
Labels: pr:no public docs

#2042 Answering customer's questions by updating docs.
  docs/sources/jinja2-templating/_index.md
  docs/sources/notify/phone-calls-sms/index.md
Labels: pr:no changelog, pr:no public docs

#2040 Properly address Organization.DoesNotExist resulting in HTTP 500 on Slack interactive_api_endpoint
  CHANGELOG.md
  engine/apps/slack/tests/test_interactive_api_endpoint.py
  engine/apps/slack/views.py
Labels: pr:no public docs

#2046 Update find contact point name, receiver could be missing key
  CHANGELOG.md
  engine/apps/alerts/grafana_alerting_sync_manager/grafana_alerting_sync.py
  engine/apps/alerts/tests/test_grafana_alerting_sync.py
Labels: pr:no public docs

#2044 Templating&grouping bugfixing
  grafana-plugin/src/components/IntegrationCollapsibleTreeView/IntegrationCollapsibleTreeView.tsx
  grafana-plugin/src/components/Integrations/IntegrationBlockItem.module.scss
  grafana-plugin/src/containers/AlertRules/parts/connectors/SlackConnector.tsx
  grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/models/maintenance/helpers.ts
  grafana-plugin/src/pages/integration_2/Integration2.helper.ts
  grafana-plugin/src/pages/integration_2/Integration2.module.scss
  grafana-plugin/src/pages/integration_2/Integration2.tsx
Labels: pr:no changelog, pr:no public docs

#2057 Revert slack org does not exist changes breaking escalate command
  CHANGELOG.md
  engine/apps/slack/tests/test_interactive_api_endpoint.py
  engine/apps/slack/views.py
Labels: pr:no public docs

#2058 v1.2.33
  CHANGELOG.md
  engine/apps/slack/tests/test_interactive_api_endpoint.py
  engine/apps/slack/views.py
Labels: pr:no public docs

#2051 add description to "Default channel for Slack notifications" UI dropdown
  CHANGELOG.md
  grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/SlackSettings/SlackSettings.tsx
Labels: pr:no public docs

#2063 Edit critical to be Important to align with the rest of app convention
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.tsx
Labels: pr:no changelog, pr:no public docs

#2052 Rares/templates tweaks 3
  grafana-plugin/src/components/IntegrationCollapsibleTreeView/IntegrationCollapsibleTreeView.tsx
  grafana-plugin/src/components/Integrations/IntegrationBlock.tsx
  grafana-plugin/src/containers/AlertRules/AlertRules.tsx
  grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/pages/integration_2/Integration2.module.scss
  grafana-plugin/src/pages/integration_2/Integration2.tsx
  grafana-plugin/src/utils/consts.ts
Labels: pr:no changelog, pr:no public docs

#2064 Fix 500 on templates when slack or tg integration is disabled
  CHANGELOG.md
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/tests/test_alert_receive_channel_template.py
Labels: pr:no public docs

#2066 Templates&grouping changes
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/pages/integration_2/Integration2.config.ts
Labels: pr:no changelog, pr:no public docs

#2055 Dieter/mobile app docs tweaks
  docs/sources/mobile-app/on-call-status-and-shifts/index.md
  docs/sources/mobile-app/push-notifications/index.md
Labels: type/docs, feature request, pr:no changelog, part:mobile, involved:Frontend

#2067 bug fixes
  grafana-plugin/src/components/CheatSheet/CheatSheet.module.css
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm2.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.module.css
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
  grafana-plugin/src/containers/TemplatePreview/TemplatePreview.module.css
  grafana-plugin/src/containers/TemplatePreview/TemplatePreview.tsx
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.module.css
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
  grafana-plugin/src/pages/integration_2/Integration2.tsx
Labels: pr:no changelog, pr:no public docs

#1986 Change integrations page wording and add more guidance
  engine/apps/alerts/integration_options_mixin.py
  engine/apps/api/views/alert_receive_channel.py
  engine/config_integrations/grafana_alerting.py
  engine/config_integrations/webhook.py
  grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm2.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.types.ts
  grafana-plugin/src/pages/integration_2/Integration2.helper.ts
  grafana-plugin/src/pages/integration_2/Integration2.tsx
  grafana-plugin/src/pages/integrations_2/Integrations2.tsx
Labels: pr:no changelog, pr:no public docs

#2060 Change email message on_delete to not block organization delete
  engine/apps/email/migrations/0002_alter_emailmessage_receiver.py
  engine/apps/email/models.py
Labels: pr:no changelog, pr:no public docs

#2049 Limit on Attach To action in Slack
  CHANGELOG.md
  engine/apps/slack/scenarios/distribute_alerts.py
Labels: pr:no public docs

#2071 Add extra shift changed logging
  engine/apps/alerts/tasks/notify_ical_schedule_shift.py
Labels: pr:no changelog, pr:no public docs
