Repository grafana/oncall, pull requests merged in 2023-01, with the labels that each got.

#1163 add github action to verify that changelog has been updated
  .github/workflows/verify-changelog-updated.yml
Labels: no changelog

#1177 add small script + github action to check that public docs updated
  .github/verify-public-docs-updated.sh
  .github/workflows/verify-public-docs-updated.yml
Labels: no changelog, no public docs

#1179 remove duplicate call in UI to GET /alert_receive_channels
  CHANGELOG.md
  grafana-plugin/src/state/rootBaseStore/index.ts
Labels: no public docs

#1186 Optimize alertgroups endpoint
  engine/Dockerfile
  engine/apps/api/views/alert_group.py
Labels: no changelog, no public docs

#1188 Optimize alertgroups endpoint
  engine/apps/api/views/alert_group.py
Labels: no changelog, no public docs

#1189 Optimize alertgroups endpoint
  engine/apps/api/views/alert_group.py
Labels: no changelog, no public docs

#1190 Update message when user needs to connect their profile
  engine/apps/slack/views.py
Labels: no changelog, no public docs

#1191 Optimize alert group filtering queries
  engine/apps/alerts/models/alert_group.py
Labels: no changelog, no public docs

#1181 Allow viewers fetch cloud connection status
  CHANGELOG.md
  engine/apps/oss_installation/tests/__init__.py
  engine/apps/oss_installation/tests/test_views.py
  engine/apps/oss_installation/urls.py
  engine/apps/oss_installation/views/cloud_connection.py
  engine/engine/urls.py
Labels: no public docs

#1180 Sync users and teams on tf requests
  CHANGELOG.md
  engine/apps/grafana_plugin/helpers/client.py
  engine/apps/grafana_plugin/tasks/__init__.py
  engine/apps/grafana_plugin/tasks/sync.py
  engine/apps/public_api/tf_sync.py
  engine/apps/public_api/views/teams.py
  engine/apps/public_api/views/users.py
  engine/apps/user_management/sync.py
  engine/apps/user_management/tests/test_sync.py
  engine/common/oncall_gateway/oncall_gateway_client.py
Labels: no public docs

#1198 Add check for MANIFEST.txt after signing
  .drone.yml
Labels: no changelog, no public docs

#1202 Fix markdown formatting in docs
  .pre-commit-config.yaml
  docs/sources/calendar-schedules/_index.md
  docs/sources/calendar-schedules/ical-schedules/index.md
  docs/sources/calendar-schedules/web-schedule/_index.md
  docs/sources/calendar-schedules/web-schedule/calendar-export/index.md
  docs/sources/calendar-schedules/web-schedule/create-schedule/index.md
Labels: no changelog

#1201 Remove resolved and acknowledged filters as we switched to status
  CHANGELOG.md
  engine/apps/api/views/alert_group.py
  grafana-plugin/src/models/alertgroup/alertgroup.ts
Labels: no public docs

#1192 When removing Slack ChatOps integration, warn the user of the implications
  CHANGELOG.md
  grafana-plugin/src/components/WithConfirm/WithConfirm.tsx
  grafana-plugin/src/containers/SlackIntegrationButton/SlackIntegrationButton.tsx
  grafana-plugin/src/img/slack_workspace_choose_attention.png
  grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/SlackSettings/SlackSettings.tsx
Labels: no public docs

#1204 Remove DynamicSetting usage for mobile app backend on OSS
  engine/apps/mobile_app/backend.py
Labels: no changelog, no public docs

#1200 Refactor plugin sync
  CHANGELOG.md
  engine/apps/auth_token/auth.py
  engine/apps/grafana_plugin/views/sync.py
Labels: no public docs

#872 Refactor create/update contact points for Alerting integration
  CHANGELOG.md
  engine/apps/alerts/grafana_alerting_sync_manager/grafana_alerting_sync.py
  engine/apps/alerts/tasks/create_contact_points_for_datasource.py
Labels: no public docs

#1169 optimize GET /schedules internal API endpoint
  CHANGELOG.md
  engine/apps/api/permissions/__init__.py
  engine/apps/api/serializers/schedule_base.py
  engine/apps/api/views/schedule.py
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_custom_on_call_shift.py
  engine/apps/slack/models/slack_usergroup.py
  engine/apps/slack/tests/test_user_group.py
Labels: no public docs

#1183 Add schedules support for slack direct paging
  engine/apps/alerts/paging.py
  engine/apps/alerts/tests/test_paging.py
  engine/apps/slack/scenarios/paging.py
  engine/apps/slack/tests/test_scenario_steps/test_paging.py
Labels: no changelog, no public docs

#1218 Set SILKY_PYTHON_PROFILER_BINARY setting to False by default
  engine/settings/base.py
Labels: no changelog, no public docs

#1225 Fix typo in snyk workflow file name
  .github/workflows/snyk.yml
Labels: no changelog

#1228 Add silk setting to store .prof files in the specific folder and share it between uwsgi workers
  engine/Dockerfile
  engine/settings/base.py
Labels: no changelog, no public docs

#1223 Fix format issues introduced by markdown linter
  docs/.markdownlint.json
  docs/sources/calendar-schedules/ical-schedules/index.md
  docs/sources/calendar-schedules/web-schedule/_index.md
  docs/sources/calendar-schedules/web-schedule/calendar-export/index.md
  docs/sources/calendar-schedules/web-schedule/create-schedule/index.md
Labels: type/docs, no changelog

#1230 fix NPE in schedule user details
  CHANGELOG.md
  grafana-plugin/src/components/ScheduleUserDetails/ScheduleUserDetails.tsx
Labels: no public docs

#1232 Add paging for direct paging users in slack dialog
  engine/apps/slack/scenarios/paging.py
Labels: no changelog, no public docs

#1236 Cache render_for_web field for alertgroups list serializer
  engine/apps/alerts/migrations/0009_alertreceivechannel_web_templates_modified_at.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/api/serializers/alert_group.py
  engine/apps/api/serializers/alert_receive_channel.py
Labels: no changelog, no public docs

#1185 [RBAC] - minor UI bug fixes
  CHANGELOG.md
  grafana-plugin/src/components/UserGroups/UserGroups.tsx
  grafana-plugin/src/containers/ApiTokenSettings/ApiTokenSettings.tsx
  grafana-plugin/src/containers/RemoteSelect/RemoteSelect.tsx
  grafana-plugin/src/containers/UserSettings/parts/index.tsx
  grafana-plugin/src/network/index.ts
  grafana-plugin/src/pages/index.tsx
  grafana-plugin/src/pages/settings/tabs/Cloud/CloudPage.tsx
  grafana-plugin/src/pages/users/Users.tsx
  grafana-plugin/src/plugin.json
  grafana-plugin/src/state/plugin/__snapshots__/plugin.test.ts.snap
  grafana-plugin/src/state/plugin/index.ts
  grafana-plugin/src/state/plugin/plugin.test.ts
  grafana-plugin/src/utils/authorization/authorization.test.ts
  grafana-plugin/src/utils/authorization/index.ts
Labels: no public docs

#1209 Add Server URL below QR code for OSS for debugging purposes
  CHANGELOG.md
  grafana-plugin/package.json
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.tsx
Labels: no public docs

#1249 fix failing lint github actions job due to issue w/ isort version
  .pre-commit-config.yaml
Labels: no changelog, no public docs

#1250 don't tag oncall-backend when CHANGELOG is updated
  .github/CODEOWNERS
Labels: no changelog, no public docs

#1241 Return alert group ID in direct paging API
  engine/apps/alerts/paging.py
  engine/apps/alerts/tests/test_paging.py
  engine/apps/api/tests/test_paging.py
  engine/apps/api/views/paging.py
Labels: no changelog, no public docs

#994 Add oncall slack commands to docs
  docs/.markdownlint.json
  docs/sources/integrations/chatops-integrations/configure-slack/index.md
Labels: type/docs, no changelog

#1240 Add a filter by involved users to alert groups page
  CHANGELOG.md
  engine/apps/api/views/alert_group.py
  grafana-plugin/src/containers/IncidentsFilters/IncidentsFilters.tsx
Labels: no public docs

#1208 Add event stop propagation for react router links
  grafana-plugin/src/components/PluginLink/PluginLink.tsx
  grafana-plugin/src/components/WorkingHours/WorkingHours.helpers.ts
Labels: no changelog, no public docs

#1251 tag @grafana/docs-oncall instead of oncall-backend for docs related changes
  .github/CODEOWNERS
Labels: no changelog, no public docs

#1048 Add cache for working moments
  grafana-plugin/package.json
  grafana-plugin/src/components/WorkingHours/WorkingHours.helpers.ts
  grafana-plugin/yarn.lock
Labels: no changelog, no public docs

#1262 add django-dbconn-retry library
  CHANGELOG.md
  engine/requirements.txt
  engine/settings/base.py
Labels: no public docs
