Repository grafana/oncall, pull requests merged in 2023-11, with the labels that each got.

#3227 Rares/bump labels 1.2.X
  grafana-plugin/package.json
  grafana-plugin/src/containers/Labels/Labels.tsx
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/pages/integrations/Integrations.tsx
  grafana-plugin/yarn.lock
Labels: pr:no changelog, pr:no public docs

#3239 automerge Helm release PRs after Docker images have been released to Docker Hub
  .drone.yml
Labels: pr:no changelog

#3240 Order alert groups by -started_at in internal API
  CHANGELOG.md
  engine/apps/api/views/alert_group.py
Labels: pr:no public docs

#3232 Updates to POST /direct_paging internal API endpoint to support Grafana Incident use-cases
  engine/apps/alerts/migrations/0036_alertgroup_grafana_incident_id.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/paging.py
  engine/apps/api/serializers/alert_group.py
  engine/apps/api/serializers/paging.py
  engine/apps/api/tests/test_paging.py
  engine/apps/api/views/paging.py
  grafana-plugin/src/models/alertgroup/alertgroup.types.ts
  grafana-plugin/src/pages/incident/Incident.tsx
Labels: pr:no changelog, pr:no public docs

#3245 Add BUILDKIT_INLINE_CACHE build arg to docker builder step
  .drone.yml
  Tiltfile
Labels: pr:no changelog, pr:no public docs

#3223 Return alert groups for deleted integrations on private api
  engine/apps/api/tests/test_alert_group.py
  engine/apps/api/views/alert_group.py
Labels: pr:no changelog, pr:no public docs

#3246 Add labels feature flag for list of organizations
  engine/apps/api/tests/test_labels.py
  engine/apps/labels/tests/test_labels.py
  engine/apps/labels/utils.py
  engine/common/utils.py
  engine/conftest.py
  engine/settings/base.py
Labels: pr:no changelog, pr:no public docs

#3250 Change expected migration date for alertmanager
  docs/sources/integrations/alertmanager/index.md
  docs/sources/integrations/grafana-alerting/index.md
  grafana-plugin/src/pages/integration/Integration.tsx
Labels: pr:no changelog

#3251 Use docker build remote cache
  .drone.yml
Labels: pr:no changelog, pr:no public docs

#3253 Update wording for mobile push notifications timing choices
  CHANGELOG.md
  engine/apps/mobile_app/models.py
Labels: pr:no public docs

#3260 Fix db migration for mobile app
  CHANGELOG.md
  engine/apps/mobile_app/migrations/0011_alter_mobileappusersettings_going_oncall_notification_timing.py
Labels: pr:no public docs

#3244 Limit number of times webhooks retry
  engine/apps/webhooks/tasks/trigger_webhook.py
Labels: pr:no changelog, pr:no public docs

#3262 Fix getting alert group from telegram action
  engine/apps/telegram/tests/test_button_update_handler.py
  engine/apps/telegram/updates/update_handlers/button_press.py
Labels: pr:no changelog, pr:no public docs

#3268 Add missing referenced local_image.yml for local helm setup
  helm/local_image.yml
Labels: pr:no changelog, pr:no public docs

#3270 Check if organization was deleted for heartbeat integration
  engine/apps/heartbeat/tasks.py
  engine/apps/heartbeat/tests/test_integration_heartbeat.py
Labels: pr:no changelog, pr:no public docs

#3271 Use started_at for alert group order in paginator
  engine/common/api_helpers/paginators.py
Labels: pr:no changelog, pr:no public docs

#3275 Update grafana-labels-url
  engine/apps/labels/client.py
Labels: pr:no changelog, pr:no public docs

#3238 Alert group labels filter
  engine/apps/api/tests/test_alert_group.py
  engine/apps/api/tests/test_labels.py
  engine/apps/api/urls.py
  engine/apps/api/views/alert_group.py
  engine/apps/api/views/labels.py
  engine/apps/labels/migrations/0002_alertgroupassociatedlabel_and_more.py
  engine/apps/labels/models.py
  engine/apps/labels/tests/factories.py
  engine/conftest.py
  grafana-plugin/src/containers/Labels/LabelsFilter.tsx
  grafana-plugin/src/containers/RemoteFilters/RemoteFilters.helpers.ts
  grafana-plugin/src/containers/RemoteFilters/RemoteFilters.tsx
  grafana-plugin/src/containers/RemoteFilters/RemoteFilters.types.ts
  grafana-plugin/src/models/alertgroup/alertgroup.ts
Labels: pr:no changelog, pr:no public docs

#3256 remove AlertGroup.is_restricted column
  engine/apps/alerts/migrations/0037_remove_alertgroup_is_restricted_state.py
  engine/apps/alerts/models/alert_group.py
Labels: pr:no changelog, pr:no public docs

#3269 Move cache clear to fixtures, fix some deprecation notices
  engine/apps/alerts/tasks/notify_ical_schedule_shift.py
  engine/apps/alerts/tests/test_notify_ical_schedule_shift.py
  engine/apps/api/tests/test_schedules.py
  engine/apps/public_api/serializers/schedules_base.py
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/tests/test_custom_on_call_shift.py
  engine/apps/schedules/tests/test_notify_about_empty_shifts_in_schedule.py
  engine/apps/schedules/tests/test_notify_about_gaps_in_schedule.py
  engine/apps/schedules/tests/test_on_call_schedule.py
  engine/apps/schedules/tests/test_quality_score.py
  engine/apps/user_management/tests/test_user.py
  engine/conftest.py
Labels: pr:no changelog, pr:no public docs

#3280 add get_cached_oncall_users_for_multiple_schedules method + add DELETE /alertgroups/<id> internal API endpoint
  engine/apps/alerts/paging.py
  engine/apps/api/tests/test_alert_group.py
  engine/apps/api/tests/test_user.py
  engine/apps/api/views/alert_group.py
  engine/apps/api/views/team.py
  engine/apps/api/views/user.py
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/tests/test_ical_utils.py
  engine/apps/slack/scenarios/paging.py
  grafana-plugin/src/containers/AddResponders/parts/AddRespondersPopup/AddRespondersPopup.tsx
  grafana-plugin/src/models/user/user.ts
Labels: pr:no changelog, pr:no public docs

#3284 Fix assert_called_once usage in tests
  engine/engine/tests/test_views.py
Labels: pr:no changelog, pr:no public docs

#3282 Fix escalation policy importance going back to default
  CHANGELOG.md
  grafana-plugin/e2e-tests/escalationChains/escalationPolicy.test.ts
  grafana-plugin/e2e-tests/utils/escalationChain.ts
  grafana-plugin/src/models/escalation_policy/escalation_policy.helpers.ts
Labels: pr:no public docs

#3289 Update test to avoid failure depending on when it is run
  engine/apps/schedules/tests/test_on_call_schedule.py
Labels: pr:no changelog, pr:no public docs

#3283 Add a command to continue escalations for alert groups
  engine/apps/alerts/escalation_snapshot/escalation_snapshot_mixin.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/tasks/check_escalation_finished.py
  engine/apps/alerts/tests/test_alert_group.py
  engine/engine/management/commands/continue_escalation.py
Labels: pr:no changelog, pr:no public docs

#3293 Add a flag to rebuild escalation snapshot when use `continue_escalation` command
  engine/engine/management/commands/continue_escalation.py
Labels: pr:no changelog, pr:no public docs

#3287 remove AlertGroup.is_restricted column
  engine/apps/alerts/migrations/0038_remove_alertgroup_is_restricted_db.py
Labels: pr:no changelog, pr:no public docs

#3209 Add GitHub action cron job to triage stale GH issues
  .github/workflows/triage-stale-pull-requests.yml
Labels: pr:no changelog, pr:no public docs

#3299 Pass all integration labels down to alert groups
  engine/apps/alerts/models/alert.py
  engine/apps/labels/tests/test_alert_group.py
  engine/apps/labels/utils.py
  engine/common/utils.py
Labels: pr:no changelog, pr:no public docs

#3301 Revert "Pass all integration labels down to alert groups"
  engine/apps/alerts/models/alert.py
  engine/apps/labels/tests/test_alert_group.py
  engine/apps/labels/utils.py
  engine/common/utils.py
Labels: pr:no changelog, pr:no public docs

#3302 Pass all integration labels down to alert groups
  engine/apps/alerts/models/alert.py
  engine/apps/alerts/tests/factories.py
  engine/apps/labels/tests/factories.py
  engine/apps/labels/tests/test_alert_group.py
  engine/apps/labels/utils.py
  engine/apps/slack/tests/factories.py
  engine/apps/webhooks/tests/factories.py
Labels: pr:no changelog, pr:no public docs

#3288 Specify new AM migration date
  docs/sources/integrations/alertmanager/index.md
  docs/sources/integrations/grafana-alerting/index.md
  grafana-plugin/src/pages/integration/Integration.tsx
Labels: pr:no changelog, pr:no public docs

#3304 A few clarifications and updates for "Notify whole Slack channel" and…
  docs/sources/escalation-chains-and-routes/_index.md
Labels: pr:no changelog

#3310 Make usernames unique in tests
  engine/apps/user_management/tests/factories.py
Labels: pr:no changelog, pr:no public docs

#3312 Add notifications success ratio log to auditor
  engine/apps/alerts/tasks/check_escalation_finished.py
  engine/apps/alerts/tests/test_check_escalation_finished_task.py
Labels: pr:no changelog, pr:no public docs

#3314 Add command for restarting acknowledge reminder tasks for organization
  engine/engine/management/commands/restart_acknowledge_reminder.py
Labels: pr:no changelog, pr:no public docs

#3315 AmazonSNS integration exception handling
  CHANGELOG.md
  engine/apps/integrations/views.py
  engine/apps/user_management/tests/test_region.py
Labels: pr:no public docs

#3323 Dev to main
  CHANGELOG.md
  engine/apps/integrations/views.py
  engine/apps/user_management/tests/test_region.py
  engine/engine/management/commands/restart_acknowledge_reminder.py
Labels: pr:no public docs

#3290 Direct paging integrations table
  CHANGELOG.md
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/views/alert_receive_channel.py
  grafana-plugin/.eslintrc.js
  grafana-plugin/e2e-tests/integrations/heartbeat.test.ts
  grafana-plugin/e2e-tests/integrations/integrationsTable.test.ts
  grafana-plugin/e2e-tests/integrations/maintenanceMode.test.ts
  grafana-plugin/e2e-tests/utils/escalationChain.ts
  grafana-plugin/e2e-tests/utils/integrations.ts
  grafana-plugin/package.json
  grafana-plugin/src/containers/Labels/LabelsFilter.tsx
  grafana-plugin/src/containers/RemoteFilters/RemoteFilters.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.types.ts
  grafana-plugin/src/pages/integrations/Integrations.module.scss
  grafana-plugin/src/pages/integrations/Integrations.tsx
Labels: pr:no public docs

#3322 Add test ensuring ingestion works without db access
  engine/apps/integrations/tests/test_views.py
  engine/apps/labels/tests/factories.py
Labels: pr:no changelog, pr:no public docs

#3088 Update _index.md
  docs/sources/integrations/_index.md
Labels: pr:no changelog, pr:no public docs, pr:stale

#3135 docs: remove stray bullet point & organize subtopic "Possible transit…
  docs/sources/get-started/_index.md
Labels: pr:no changelog

#3210 Docs: Typo fix
  docs/sources/escalation-chains-and-routes/_index.md
Labels: type/docs, pr:no changelog

#3326 Forward headers for Amazon SNS
  CHANGELOG.md
  engine/apps/user_management/middlewares.py
  engine/apps/user_management/tests/test_region.py
Labels: pr:no public docs

#3327 Fix few minor Slack connection issues
  CHANGELOG.md
  engine/apps/social_auth/pipeline.py
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.tsx
  grafana-plugin/src/containers/MobileAppConnection/__snapshots__/MobileAppConnection.test.tsx.snap
  grafana-plugin/src/containers/UserSettings/parts/connectors/SlackConnector.tsx
  grafana-plugin/src/containers/UserSettings/parts/tabs/SlackTab/SlackTab.tsx
  grafana-plugin/src/models/user/user.types.ts
  grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/SlackSettings/SlackSettings.tsx
Labels: pr:no public docs

#3336 Exclude dark css vars when light theme is turned on
  CHANGELOG.md
  grafana-plugin/src/assets/style/vars.css
Labels: pr:no public docs

#3343 Grafana IRM -> Grafana OnCall
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.tsx
Labels: pr:no changelog, pr:no public docs

#3346 fix jest snapshot
  grafana-plugin/src/containers/MobileAppConnection/__snapshots__/MobileAppConnection.test.tsx.snap
Labels: pr:no changelog, pr:no public docs

#3339 Enable filtering users by public primary key
  CHANGELOG.md
  engine/apps/api/tests/test_user.py
  engine/apps/api/views/user.py
Labels: pr:no public docs

#3345 Fix acknowledge reminder
  CHANGELOG.md
  engine/apps/alerts/tasks/acknowledge_reminder.py
  engine/apps/alerts/tests/test_acknowledge_reminder.py
Labels: pr:no public docs

#3347 use qrcode.react instead of react-qr-code lib
  CHANGELOG.md
  grafana-plugin/package.json
  grafana-plugin/src/containers/MobileAppConnection/__snapshots__/MobileAppConnection.test.tsx.snap
  grafana-plugin/src/containers/MobileAppConnection/parts/QRCode/QRCode.tsx
  grafana-plugin/src/containers/MobileAppConnection/parts/QRCode/__snapshots__/QRCode.test.tsx.snap
  grafana-plugin/yarn.lock
Labels: pr:no public docs, involved:Frontend

#3337 Mention shift swaps in schedule quality docs
  docs/sources/on-call-schedules/web-schedule/_index.md
Labels: pr:no changelog, pr:no public docs

#3307 Inheritable integration labels
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/labels/migrations/0003_alertreceivechannelassociatedlabel_inherit.py
  engine/apps/labels/models.py
  engine/apps/labels/tests/test_alert_group.py
  engine/apps/labels/utils.py
  grafana-plugin/src/components/TooltipBadge/TooltipBadge.tsx
  grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.module.css
  grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.tsx
  grafana-plugin/src/containers/RemoteFilters/RemoteFilters.tsx
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.types.ts
  grafana-plugin/src/models/alertgroup/alertgroup.ts
  grafana-plugin/src/models/alertgroup/alertgroup.types.ts
  grafana-plugin/src/models/filters/filters.ts
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/pages/integrations/Integrations.tsx
Labels: pr:no changelog, pr:no public docs

#3358 Schedule recurrence limit fix
  CHANGELOG.md
  grafana-plugin/src/containers/RotationForm/RotationForm.tsx
Labels: pr:no public docs

#3365 Schedules rotation form tweaks
  CHANGELOG.md
  grafana-plugin/src/components/UserGroups/UserGroups.module.css
  grafana-plugin/src/containers/RotationForm/RotationForm.module.css
  grafana-plugin/src/containers/RotationForm/RotationForm.tsx
Labels: pr:no public docs

#3364 Fix broken openapi schema + add integration test
  engine/apps/alerts/models/alert_group.py
  engine/apps/api/serializers/alert_group.py
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/serializers/alerts_field_cache_buster_mixin.py
  engine/apps/api/tests/test_openapi_schema.py
  engine/apps/api/views/alert_group.py
  engine/requirements.txt
Labels: pr:no changelog, pr:no public docs

#3303 fix(2989) Return users field data for web overriden shifts via public…
  CHANGELOG.md
  engine/apps/public_api/serializers/on_call_shifts.py
  engine/apps/public_api/tests/test_on_call_shifts.py
Labels: pr:no public docs

#3351 Truncate resolution note text in slack message to satisfy block limits
  engine/apps/alerts/incident_appearance/renderers/slack_renderer.py
  engine/apps/slack/constants.py
  engine/apps/slack/scenarios/resolution_note.py
  engine/apps/slack/tests/test_scenario_steps/test_resolution_note.py
Labels: pr:no changelog, pr:no public docs

#3362 Update helm readme to mention ingestion split config
  helm/oncall/README.md
Labels: pr:no changelog, pr:no public docs

#3363 Update slack user group update not to retry on some errors
  CHANGELOG.md
  engine/apps/slack/errors.py
  engine/apps/slack/models/slack_usergroup.py
  engine/apps/slack/tests/test_user_group.py
Labels: pr:no public docs

#3367 Delete direct paging integration on team delete
  CHANGELOG.md
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/user_management/models/team.py
  engine/apps/user_management/tests/test_sync.py
Labels: pr:no public docs

#3368 allow specifying more than one redis server URI in the REDIS_URI env var
  CHANGELOG.md
  engine/apps/api/tests/test_openapi_schema.py
  engine/settings/base.py
Labels: pr:no public docs

#3371 Handle Amazon SNS headers for moved
  CHANGELOG.md
  engine/apps/user_management/middlewares.py
  engine/apps/user_management/tests/test_region.py
Labels: pr:no public docs

#3374 Use chromium only in PRs e2e tests
  .github/workflows/daily-e2e-tests.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/linting-and-tests.yml
  grafana-plugin/playwright.config.ts
Labels: pr:no changelog, pr:no public docs

#3377 show delete integration btn only if allow_delete is truthy
  grafana-plugin/src/components/RenderConditionally/RenderConditionally.tsx
  grafana-plugin/src/containers/CreateAlertReceiveChannelContainer/CreateAlertReceiveChannelContainer.module.css
  grafana-plugin/src/containers/CreateAlertReceiveChannelContainer/CreateAlertReceiveChannelContainer.tsx
  grafana-plugin/src/pages/integrations/Integrations.tsx
Labels: pr:no changelog, pr:no public docs

#3380 fix missing users in rotations when RBAC is enabled
  CHANGELOG.md
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/tests/test_ical_utils.py
Labels: pr:no public docs

#3372 Avoid msg_too_long errors when posting/updating slack resolution note
  engine/apps/slack/scenarios/resolution_note.py
  engine/apps/slack/tests/test_scenario_steps/test_resolution_note.py
Labels: pr:no changelog, pr:no public docs

#3381 fix issue in /escalate Slack command when selecting a team
  CHANGELOG.md
  engine/apps/slack/scenarios/paging.py
  engine/apps/slack/tests/test_scenario_steps/test_paging.py
Labels: pr:no public docs

#3387 Switch to django-redis, update redis deps
  engine/requirements.txt
  engine/settings/base.py
Labels: pr:no changelog, pr:no public docs

#3397 Fix deleting integrations with duplicate names
  CHANGELOG.md
  engine/apps/alerts/migrations/0039_remove_alertreceivechannel_unique_integration_name.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/tests/test_alert_receiver_channel.py
Labels: pr:no public docs

#3392 Add more logging info on alert creation
  CHANGELOG.md
  engine/apps/integrations/tasks.py
Labels: pr:no public docs

#3136 Fixing helm hooks for install stage
  helm/oncall/templates/engine/job-migrate.yaml
  helm/oncall/templates/secrets.yaml
  helm/oncall/templates/serviceaccount.yaml
  helm/oncall/tests/migrate_annotations_test.yaml
  helm/oncall/tests/mysql_password_env_test.yaml
  helm/oncall/tests/postgres_password_env_test.yaml
  helm/oncall/tests/rabbitmq_env_test.yaml
  helm/oncall/tests/redis_env_test.yaml
  helm/oncall/tests/service_account_test.yaml
  helm/oncall/values.yaml
Labels: pr:no changelog, pr:no public docs

#3394 helm: fix conditions create svc for detached integrations
  helm/oncall/templates/integrations/service-internal.yaml
  helm/oncall/tests/integrations_deployment_test.yaml
Labels: pr:no changelog, pr:no public docs

#3401 Add builtin slack retry on ratelimited error
  CHANGELOG.md
  engine/apps/slack/client.py
  engine/apps/slack/tests/test_slack_client.py
Labels: pr:no public docs

#3403 add more logging in apps.alerts.tasks.notify_user.perform_notification task
  engine/apps/alerts/tasks/notify_user.py
Labels: pr:no changelog, pr:no public docs

#3198 [Docs] add details inbound email integration setup
  docs/sources/integrations/inbound-email/index.md
  docs/sources/open-source/_index.md
Labels: pr:no changelog

#3383 Webhook labels
  Tiltfile
  engine/apps/api/label_filtering.py
  engine/apps/api/serializers/webhook.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/tests/test_labels.py
  engine/apps/api/tests/test_webhook_presets.py
  engine/apps/api/tests/test_webhooks.py
  engine/apps/api/views/alert_group.py
  engine/apps/api/views/alert_receive_channel.py
  engine/apps/api/views/labels.py
  engine/apps/api/views/webhooks.py
  engine/apps/labels/migrations/0004_webhookassociatedlabel.py
  engine/apps/labels/models.py
  engine/apps/labels/tasks.py
  engine/apps/labels/tests/factories.py
  engine/apps/labels/tests/test_labels.py
  engine/apps/labels/utils.py
  engine/apps/webhooks/tasks/trigger_webhook.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
  engine/apps/webhooks/utils.py
  engine/conftest.py
  grafana-plugin/.eslintrc.js
  grafana-plugin/package.json
  grafana-plugin/src/components/GForm/GForm.tsx
  grafana-plugin/src/components/LabelsTooltipBadge/LabelsTooltipBadge.tsx
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/containers/Labels/Labels.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.config.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.types.ts
  grafana-plugin/src/containers/RemoteFilters/RemoteFilters.helpers.ts
  grafana-plugin/src/containers/RemoteFilters/RemoteFilters.tsx
  grafana-plugin/src/models/filters/filters.ts
  grafana-plugin/src/models/outgoing_webhook/outgoing_webhook.types.ts
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/integrations/Integrations.tsx
  grafana-plugin/src/pages/outgoing_webhooks/OutgoingWebhooks.tsx
  grafana-plugin/src/state/rootBaseStore/index.ts
Labels: pr:no changelog, pr:no public docs

#3410 Remove unused prefetch; prefer indexed query
  engine/apps/api/serializers/webhook.py
  engine/apps/api/views/webhooks.py
Labels: pr:no changelog, pr:no public docs

#3414 Make alert ingestion cache independent
  engine/apps/integrations/mixins/alert_channel_defining_mixin.py
  engine/apps/integrations/mixins/ratelimit_mixin.py
  engine/engine/views.py
  engine/settings/base.py
Labels: pr:no changelog, pr:no public docs

#3259 Filters polishing, remove displaying rotation modal for Terraform/API based schedules
  CHANGELOG.md
  grafana-plugin/src/components/LabelsFilter/LabelsFilter.tsx
  grafana-plugin/src/containers/RemoteFilters/RemoteFilters.tsx
  grafana-plugin/src/containers/RemoteSelect/RemoteSelect.tsx
  grafana-plugin/src/pages/schedule/Schedule.tsx
Labels: pr:no public docs

#3189 Allow OnCall API to use Grafana Service Accounts
  CHANGELOG.md
  engine/apps/api/serializers/webhook.py
  engine/apps/auth_token/auth.py
  engine/apps/auth_token/exceptions.py
  engine/apps/auth_token/grafana/__init__.py
  engine/apps/auth_token/grafana/grafana_auth_token.py
  engine/apps/auth_token/tests/test_grafana_auth.py
  engine/apps/grafana_plugin/helpers/client.py
  engine/apps/public_api/serializers/resolution_notes.py
  engine/apps/public_api/tests/test_resolution_notes.py
  engine/apps/public_api/views/resolution_notes.py
  engine/apps/webhooks/presets/advanced.py
  engine/apps/webhooks/presets/preset.py
  engine/apps/webhooks/presets/simple.py
  engine/apps/webhooks/tasks/trigger_webhook.py
  engine/apps/webhooks/tests/test_webhook_presets.py
Labels: pr:no public docs

#3413 Rework alert group internal API team filter
  engine/apps/api/serializers/alert_group.py
  engine/apps/api/tests/test_alert_group.py
  engine/apps/api/tests/test_escalation_chain.py
  engine/apps/api/tests/test_team.py
  engine/apps/api/views/alert_group.py
  engine/apps/api/views/alert_receive_channel.py
  engine/apps/api/views/escalation_chain.py
  engine/apps/api/views/team.py
  engine/apps/public_api/views/incidents.py
  engine/common/api_helpers/filters.py
Labels: pr:no changelog, pr:no public docs

#3419 Allow users with user settings read to list users
  CHANGELOG.md
  engine/apps/api/tests/test_user.py
  engine/apps/api/views/user.py
Labels: pr:no public docs

#3420 Trigger distribute task after alert is committed
  engine/apps/alerts/models/alert.py
  engine/apps/alerts/tests/test_alert.py
Labels: pr:no changelog, pr:no public docs

#3418 Add test to ensure integrations work when cache is down
  engine/apps/integrations/tests/test_views.py
Labels: pr:no changelog, pr:no public docs

#3424 Fix alert group rendering
  CHANGELOG.md
  engine/apps/slack/slack_formatter.py
  engine/apps/slack/tests/test_slack_formatter.py
Labels: pr:no public docs

#3431 Revert "Add test to ensure integrations work when cache is down"
  engine/apps/integrations/tests/test_views.py
Labels: pr:no changelog, pr:no public docs

#3430 Revert "Make alert ingestion cache independent (#3414)"
  engine/apps/integrations/mixins/alert_channel_defining_mixin.py
  engine/apps/integrations/mixins/ratelimit_mixin.py
  engine/engine/views.py
  engine/settings/base.py
Labels: pr:no changelog, pr:no public docs

#3385 Alert group payload labels
  engine/apps/alerts/migrations/0040_alertreceivechannel_alert_group_labels_custom_and_more.py
  engine/apps/alerts/models/alert.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/serializers/channel_filter.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/tests/test_alert_receive_channel_template.py
  engine/apps/labels/alert_group_labels.py
  engine/apps/labels/models.py
  engine/apps/labels/tests/test_alert_group.py
  engine/apps/labels/utils.py
  engine/apps/public_api/serializers/routes.py
  engine/common/api_helpers/mixins.py
  engine/common/api_helpers/utils.py
  engine/conftest.py
  grafana-plugin/package.json
  grafana-plugin/playwright.config.ts
  grafana-plugin/src/components/LabelsTooltipBadge/LabelsTooltipBadge.tsx
  grafana-plugin/src/components/MonacoEditor/MonacoEditor.tsx
  grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
  grafana-plugin/src/containers/Labels/Labels.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.types.ts
  grafana-plugin/yarn.lock
Labels: pr:no changelog, pr:no public docs

#3434 Alert group payload labels
  engine/apps/alerts/migrations/0040_alertreceivechannel_alert_group_labels_custom_and_more.py
  engine/apps/alerts/models/alert.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/serializers/channel_filter.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/tests/test_alert_receive_channel_template.py
  engine/apps/labels/alert_group_labels.py
  engine/apps/labels/models.py
  engine/apps/labels/tests/test_alert_group.py
  engine/apps/labels/utils.py
  engine/apps/public_api/serializers/routes.py
  engine/common/api_helpers/mixins.py
  engine/common/api_helpers/utils.py
  engine/conftest.py
  grafana-plugin/package.json
  grafana-plugin/playwright.config.ts
  grafana-plugin/src/components/LabelsTooltipBadge/LabelsTooltipBadge.tsx
  grafana-plugin/src/components/MonacoEditor/MonacoEditor.tsx
  grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
  grafana-plugin/src/containers/Labels/Labels.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.types.ts
  grafana-plugin/yarn.lock
Labels: pr:no changelog, pr:no public docs

#3440 Fix slack ratelimit
  CHANGELOG.md
  engine/apps/slack/views.py
Labels: pr:no changelog, pr:no public docs

#3443 Users profile tweaks
  CHANGELOG.md
  grafana-plugin/src/containers/Labels/Labels.module.css
  grafana-plugin/src/containers/Labels/Labels.tsx
  grafana-plugin/src/containers/Labels/LabelsFilter.tsx
  grafana-plugin/src/containers/UserSettings/parts/connectors/PhoneConnector.tsx
  grafana-plugin/src/containers/UserSettings/parts/index.module.css
  grafana-plugin/src/containers/UserSettings/parts/tabs/PhoneVerification/PhoneVerification.tsx
Labels: pr:no public docs

#3416 Add alert group actions extension point to plugin
  grafana-plugin/src/components/ExtensionLinkMenu/ExtensionLinkDropdown.tsx
  grafana-plugin/src/components/ExtensionLinkMenu/ExtensionLinkMenu.tsx
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/types.ts
  grafana-plugin/src/utils/string.ts
Labels: feature request, pr:no changelog, pr:no public docs

#3384 generate types, create http client and add exemplary usage
  .pre-commit-config.yaml
  dev/.env.dev.example
  dev/README.md
  engine/engine/urls.py
  engine/settings/base.py
  grafana-plugin/.eslintignore
  grafana-plugin/README.md
  grafana-plugin/jest.config.js
  grafana-plugin/package.json
  grafana-plugin/src/README.md
  grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.tsx
  grafana-plugin/src/jest/openapiFetchMock.ts
  grafana-plugin/src/models/alertgroup/alertgroup.ts
  grafana-plugin/src/models/label/label.ts
  grafana-plugin/src/models/label/label.types.ts
  grafana-plugin/src/network/index.ts
  grafana-plugin/src/network/oncall-api/api.types.d.ts
  grafana-plugin/src/network/oncall-api/autogenerated-api.types.d.ts
  grafana-plugin/src/network/oncall-api/http-client.test.ts
  grafana-plugin/src/network/oncall-api/http-client.ts
  grafana-plugin/src/network/oncall-api/types-generator/custom-schemas.ts
  grafana-plugin/src/network/oncall-api/types-generator/generate-types.ts
  grafana-plugin/src/network/oncall-api/types-generator/package.json
  grafana-plugin/src/network/oncall-api/types-generator/types-generator.tsconfig.json
  grafana-plugin/tsconfig.json
  grafana-plugin/yarn.lock
Labels: pr:no changelog, pr:no public docs

#3446 improve error handling and notifications for labels
  grafana-plugin/package.json
  grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.tsx
  grafana-plugin/src/containers/Labels/Labels.tsx
  grafana-plugin/src/containers/Labels/LabelsFilter.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/models/label/label.ts
  grafana-plugin/src/utils/decorators.ts
Labels: pr:no changelog, pr:no public docs

#3448 Update transaction.on_commit to use partial instead of lambda
  engine/apps/alerts/tasks/custom_button_result.py
  engine/apps/alerts/tasks/escalate_alert_group.py
  engine/apps/alerts/tasks/maintenance.py
  engine/apps/alerts/tasks/notify_user.py
  engine/apps/alerts/tasks/unsilence.py
  engine/apps/heartbeat/tasks.py
Labels: pr:no changelog, pr:no public docs

#3451 Move new alert group metric creation into async task
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/tasks/notify_user.py
  engine/apps/metrics_exporter/apps.py
  engine/apps/metrics_exporter/metrics_cache_manager.py
  engine/apps/metrics_exporter/signals.py
  engine/apps/metrics_exporter/tasks.py
  engine/apps/metrics_exporter/tests/test_calculation_metrics.py
  engine/apps/metrics_exporter/tests/test_update_metics_cache.py
  engine/settings/celery_task_routes.py
Labels: pr:no changelog, pr:no public docs

#3454 Enable flake8-bugbear, fix issues
  .pre-commit-config.yaml
  engine/apps/alerts/models/alert_manager_models.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/tests/test_maintenance.py
  engine/apps/alerts/utils.py
  engine/apps/api/serializers/escalation_chain.py
  engine/apps/api/tests/test_labels.py
  engine/apps/api/tests/test_schedules.py
  engine/apps/api/tests/test_team.py
  engine/apps/api/views/auth.py
  engine/apps/grafana_plugin/tests/test_gcom_api_client.py
  engine/apps/metrics_exporter/metrics_collectors.py
  engine/apps/public_api/serializers/integrations.py
  engine/apps/public_api/serializers/routes.py
  engine/apps/public_api/tests/test_schedules.py
  engine/apps/public_api/tests/test_webhooks.py
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/tests/test_on_call_schedule.py
  engine/apps/slack/alert_group_slack_service.py
  engine/apps/social_auth/backends.py
  engine/apps/user_management/tests/test_region.py
  engine/apps/webhooks/models/webhook.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
  engine/apps/webhooks/tests/test_webhook.py
  engine/common/api_helpers/mixins.py
  engine/common/insight_log/resource_insight_logs.py
  engine/common/tests/test_ordered_model.py
  engine/common/utils.py
  engine/conftest.py
Labels: pr:no changelog, pr:no public docs

#3458 Ensure stack_id and org_id are ints
  CHANGELOG.md
  grafana-plugin/src/plugin.json
Labels: pr:no public docs

#3412 Delete duplicate direct paging integrations
  CHANGELOG.md
  engine/apps/alerts/migrations/0041_alertreceivechannel_unique_direct_paging_integration_per_team.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/tests/test_alert_receiver_channel.py
  engine/apps/api/tests/test_alert_receive_channel.py
Labels: pr:no public docs

#3464 v1.3.66
  CHANGELOG.md
  docs/make-docs
  engine/apps/alerts/migrations/0041_alertreceivechannel_unique_direct_paging_integration_per_team.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/tests/test_alert_receiver_channel.py
  engine/apps/api/tests/test_alert_receive_channel.py
  grafana-plugin/package.json
  grafana-plugin/src/components/RenderConditionally/RenderConditionally.tsx
  grafana-plugin/src/containers/EscalationChainSteps/EscalationChainSteps.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.config.tsx
  grafana-plugin/src/containers/PersonalNotificationSettings/PersonalNotificationSettings.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/models/cloud/cloud.ts
  grafana-plugin/src/models/escalation_policy/escalation_policy.ts
  grafana-plugin/src/models/grafana_team/grafana_team.ts
  grafana-plugin/src/models/label/label.ts
  grafana-plugin/src/models/organization/organization.ts
  grafana-plugin/src/models/outgoing_webhook/outgoing_webhook.ts
  grafana-plugin/src/models/user/user.ts
  grafana-plugin/src/pages/outgoing_webhooks/OutgoingWebhooks.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/state/rootBaseStore/index.ts
  grafana-plugin/src/utils/async.test.ts
  grafana-plugin/src/utils/async.ts
  grafana-plugin/yarn.lock
Labels: pr:no changelog, pr:no public docs

#3447 Update when slack client ratelimit retry handler is enabled
  engine/apps/alerts/tasks/notify_ical_schedule_shift.py
  engine/apps/integrations/tasks.py
  engine/apps/slack/client.py
  engine/apps/slack/models/slack_usergroup.py
  engine/apps/slack/tasks.py
  engine/apps/slack/tests/test_slack_client.py
Labels: pr:no changelog, pr:no public docs

#3456 upgrade to Python 3.12
  .drone.yml
  .github/workflows/linting-and-tests.yml
  .github/workflows/snyk.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  Makefile
  dev/README.md
  dev/scripts/generate-fake-data/README.md
  engine/Dockerfile
  engine/apps/alerts/grafana_alerting_sync_manager/grafana_alerting_sync.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/tests/test_paging.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/views/alert_receive_channel.py
  engine/apps/base/tests/test_live_settings.py
  engine/apps/grafana_plugin/tests/test_gcom_api_client.py
  engine/apps/grafana_plugin/tests/test_install.py
  engine/apps/grafana_plugin/tests/test_self_hosted_install.py
  engine/apps/integrations/tests/test_views.py
  engine/apps/oss_installation/cloud_heartbeat.py
  engine/apps/phone_notifications/tests/test_phone_backend_call.py
  engine/apps/phone_notifications/tests/test_phone_backend_sms.py
  engine/apps/public_api/tests/test_schedule_export.py
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_shift_swap_request.py
  engine/apps/slack/scenarios/slack_channel_integration.py
  engine/apps/slack/scenarios/slack_renderer.py
  engine/apps/slack/tests/test_scenario_steps/test_paging.py
  engine/apps/slack/types/scenario_routes.py
  engine/apps/user_management/tests/test_region.py
  engine/apps/user_management/tests/test_sync.py
  engine/common/utils.py
  engine/pyproject.toml
  engine/requirements-dev.txt
  engine/requirements.txt
  tools/pagerduty-migrator/Dockerfile
Labels: pr:no public docs

#3468 Create missing direct paging integrations
  CHANGELOG.md
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/tests/test_alert_receiver_channel.py
  engine/apps/metrics_exporter/helpers.py
  engine/apps/metrics_exporter/tests/test_update_metrics_cache.py
  engine/apps/user_management/models/team.py
  engine/apps/user_management/tests/test_sync.py
Labels: pr:no public docs
