Repository grafana/oncall, pull requests merged in 2023-07, with the labels that each got.

#2416 Remove test push dynamic setting
  engine/apps/api/views/features.py
  engine/apps/mobile_app/demo_push.py
  engine/apps/mobile_app/tests/test_demo_push.py
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.tsx
  grafana-plugin/src/state/features.ts
Labels: pr:no changelog, pr:no public docs

#2417 add first multi-role e2e tests
  .github/workflows/linting-and-tests.yml
  dev/README.md
  grafana-plugin/.env.example
  grafana-plugin/integration-tests/.auth/.gitignore
  grafana-plugin/integration-tests/.env.example
  grafana-plugin/integration-tests/alerts/onCallSchedule.test.ts
  grafana-plugin/integration-tests/alerts/sms.test.ts
  grafana-plugin/integration-tests/escalationChains/searching.test.ts
  grafana-plugin/integration-tests/fixtures.ts
  grafana-plugin/integration-tests/globalSetup.ts
  grafana-plugin/integration-tests/integrations/uniqueIntegrationNames.test.ts
  grafana-plugin/integration-tests/schedules/addOverride.test.ts
  grafana-plugin/integration-tests/schedules/quality.test.ts
  grafana-plugin/integration-tests/users/viewUsers.test.ts
  grafana-plugin/integration-tests/utils/clients/grafana.ts
  grafana-plugin/integration-tests/utils/constants.ts
  grafana-plugin/integration-tests/utils/schedule.ts
  grafana-plugin/playwright.config.ts
  grafana-plugin/src/pages/users/Users.tsx
Labels: pr:no changelog, pr:no public docs

#2422 Add organization moved exception to mobile app auth
  engine/apps/mobile_app/auth.py
  engine/apps/user_management/middlewares.py
Labels: pr:no changelog, pr:no public docs

#2317 Remove url from sms notification, change format
  CHANGELOG.md
  engine/apps/alerts/incident_appearance/renderers/sms_renderer.py
  grafana-plugin/src/components/AlertTemplates/CommonAlertTemplatesForm.config.ts
Labels: pr:no public docs

#2419 Rares/webhook UI changes
  CHANGELOG.md
  grafana-plugin/src/components/HamburgerMenu/HamburgerMenu.module.scss
  grafana-plugin/src/components/ScheduleQualityDetails/ScheduleQualityDetails.tsx
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/OutgoingWebhook2Form/OutgoingWebhook2Form.module.css
  grafana-plugin/src/containers/OutgoingWebhook2Form/OutgoingWebhook2Form.tsx
  grafana-plugin/src/containers/OutgoingWebhook2Status/OutgoingWebhook2Status.tsx
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/pages/integrations/Integrations.tsx
  grafana-plugin/src/pages/outgoing_webhooks_2/OutgoingWebhooks2.module.css
  grafana-plugin/src/pages/outgoing_webhooks_2/OutgoingWebhooks2.module.scss
  grafana-plugin/src/pages/outgoing_webhooks_2/OutgoingWebhooks2.tsx
  grafana-plugin/src/pages/outgoing_webhooks_2/OutgoingWebhooks2.types.ts
  grafana-plugin/src/style/utils.css
Labels: pr:no public docs

#2349 Add terraform readme
  terraform/README.md
Labels: pr:no changelog, pr:no public docs

#2408 fix mypy return errors
  engine/apps/mobile_app/tasks.py
  engine/apps/slack/scenarios/step_mixins.py
  engine/apps/telegram/updates/update_handlers/button_press.py
  engine/apps/telegram/updates/update_manager.py
  engine/apps/twilioapp/phone_provider.py
  engine/pyproject.toml
Labels: pr:no changelog, pr:no public docs

#2400 Update oncall metrics dashboard
  CHANGELOG.md
  grafana-plugin/src/dashboards/oncall_metrics_dashboard.json
  grafana-plugin/src/plugin.json
Labels: pr:no public docs

#2457 Dev to main
  CHANGELOG.md
  engine/requirements.txt
  engine/settings/base.py
  grafana-plugin/src/dashboards/oncall_metrics_dashboard.json
  grafana-plugin/src/plugin.json
Labels: pr:no public docs

#2459 add user (full) avatar to schedule filter events internal API endpoint
  CHANGELOG.md
  engine/apps/api/tests/test_oncall_shift.py
  engine/apps/api/tests/test_schedules.py
  engine/apps/api/views/schedule.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_on_call_schedule.py
  engine/common/api_helpers/utils.py
Labels: pr:no public docs

#2467 fix pagination next and previous links for schedules and integrations GET endpoints
  CHANGELOG.md
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/tests/test_schedules.py
  engine/apps/api/views/alert_receive_channel.py
  engine/apps/api/views/schedule.py
  engine/common/api_helpers/paginators.py
Labels: pr:no public docs

#2477 fix parsing of grafana feature flags that're enabled via the feature_toggles.enabled syntax
  CHANGELOG.md
  engine/apps/grafana_plugin/helpers/client.py
  engine/apps/grafana_plugin/tests/test_gcom_api_client.py
Labels: pr:no public docs

#2484 adjust frontmatter weight and add menu title
  docs/sources/_index.md
Labels: type/docs, pr:no changelog

#2353 fix(oncall): fix celery tolerations and affinity
  CHANGELOG.md
  helm/oncall/templates/celery/_deployment.tpl
  helm/oncall/templates/engine/job-migrate.yaml
  helm/oncall/tests/__snapshot__/affinity_deployments_test.yaml.snap
  helm/oncall/tests/__snapshot__/nodeselector_deployments_test.yaml.snap
  helm/oncall/tests/__snapshot__/tolerations_deployments_test.yaml.snap
  helm/oncall/tests/affinity_deployments_test.yaml
  helm/oncall/tests/nodeselector_deployments_test.yaml
  helm/oncall/tests/tolerations_deployments_test.yaml
  helm/oncall/values.yaml
Labels: pr:no public docs

#2488 Fix cuddled list Markdown issue
  CHANGELOG.md
  engine/common/tests/test_markup.py
  engine/common/utils.py
Labels: pr:no public docs

#2493 Exclude schedules from deleted organizations from notification list
  CHANGELOG.md
  engine/apps/alerts/tasks/notify_ical_schedule_shift.py
  engine/apps/schedules/tasks/refresh_ical_files.py
  engine/apps/schedules/tests/test_tasks_refresh_ical_files.py
Labels: pr:no public docs

#2500 Bring back `/oncall` Slack command
  engine/apps/slack/scenarios/manual_incident.py
  engine/apps/slack/views.py
Labels: pr:no changelog, pr:no public docs

#2466 add debounce for GSelect and RemoteSelect
  CHANGELOG.md
  grafana-plugin/integration-tests/utils/forms.ts
  grafana-plugin/playwright.config.ts
  grafana-plugin/src/containers/GSelect/GSelect.tsx
  grafana-plugin/src/containers/RemoteSelect/RemoteSelect.tsx
  grafana-plugin/src/models/grafana_team/grafana_team.ts
Labels: pr:no public docs

#2455 Rares/add template editor to webhooks
  CHANGELOG.md
  engine/apps/api/serializers/webhook.py
  engine/apps/api/tests/test_webhooks.py
  engine/apps/api/views/webhooks.py
  engine/apps/webhooks/migrations/0007_webhookresponse_event_data.py
  engine/apps/webhooks/models/webhook.py
  engine/apps/webhooks/tasks/trigger_webhook.py
  grafana-plugin/src/components/AlertTemplates/AlertTemplatesForm.tsx
  grafana-plugin/src/components/GForm/GForm.tsx
  grafana-plugin/src/components/GForm/GForm.types.ts
  grafana-plugin/src/components/MonacoEditor/MonacoEditor.config.ts
  grafana-plugin/src/components/MonacoEditor/MonacoEditor.tsx
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationContainers/IntegrationTemplatesList.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
  grafana-plugin/src/containers/OutgoingWebhook2Form/OutgoingWebhook2Form.config.tsx
  grafana-plugin/src/containers/OutgoingWebhook2Form/OutgoingWebhook2Form.module.css
  grafana-plugin/src/containers/OutgoingWebhook2Form/OutgoingWebhook2Form.tsx
  grafana-plugin/src/containers/TemplatePreview/TemplatePreview.tsx
  grafana-plugin/src/containers/TemplateResult/TemplateResult.tsx
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
  grafana-plugin/src/containers/TemplatesAlertGroupsList/WebhooksDefaultAlertGroup.ts
  grafana-plugin/src/containers/WebhooksTemplateEditor/WebhooksTemplateEditor.tsx
  grafana-plugin/src/models/outgoing_webhook_2/outgoing_webhook_2.ts
  grafana-plugin/src/models/outgoing_webhook_2/outgoing_webhook_2.types.ts
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/pages/integration/IntegrationCommon.config.ts
Labels: pr:no public docs

#2504 Webhooks 2 template editor fixes
  engine/apps/api/views/webhooks.py
  grafana-plugin/src/containers/OutgoingWebhook2Form/OutgoingWebhook2Form.tsx
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
Labels: pr:no changelog, pr:no public docs

#2502 remove deprecated backend code
  engine/apps/alerts/migrations/0020_auto_20230711_1532.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/tasks/__init__.py
  engine/apps/alerts/tasks/resolve_alert_group_by_source_if_needed.py
  engine/apps/alerts/tasks/send_update_postmortem_signal.py
  engine/apps/api/serializers/organization.py
  engine/apps/api/tests/test_subscription.py
  engine/apps/api/urls.py
  engine/apps/api/views/alert_group.py
  engine/apps/api/views/subscription.py
  engine/apps/slack/scenarios/alertgroup_appearance.py
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/slack/scenarios/resolution_note.py
  engine/apps/slack/scenarios/step_mixins.py
  engine/apps/slack/tasks.py
  engine/apps/slack/tests/test_scenario_steps/test_alert_group_actions.py
  engine/apps/slack/tests/test_scenario_steps/test_resolution_note.py
  engine/apps/twilioapp/migrations/0007_delete_twiliologrecord.py
  engine/apps/twilioapp/models/__init__.py
  engine/apps/twilioapp/models/twilio_log_record.py
  engine/apps/user_management/migrations/0012_auto_20230711_1554.py
  engine/apps/user_management/models/organization.py
  engine/apps/user_management/subscription_strategy/base_subsription_strategy.py
  engine/apps/user_management/subscription_strategy/free_public_beta_subscription_strategy.py
  engine/engine/logging/formatters.py
  engine/engine/management/commands/restart_escalation.py
  engine/engine/urls.py
  engine/engine/views.py
  engine/requirements.txt
  engine/settings/prod_without_db.py
  grafana-plugin/src/models/team.ts
  grafana-plugin/src/models/team/team.ts
  grafana-plugin/src/models/team/team.types.ts
  grafana-plugin/src/utils/url.ts
Labels: pr:no changelog, pr:no public docs

#2497 Maintenance page is deprecated, info message was added
  CHANGELOG.md
  grafana-plugin/src/pages/maintenance/Maintenance.module.css
  grafana-plugin/src/pages/maintenance/Maintenance.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
Labels: pr:no changelog, pr:no public docs

#2511 remove organization maintenance mode + fix integration maintenance mode
  CHANGELOG.md
  engine/apps/alerts/escalation_snapshot/escalation_snapshot_mixin.py
  engine/apps/alerts/models/alert.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/tasks/distribute_alert.py
  engine/apps/alerts/tasks/maintenance.py
  engine/apps/alerts/tasks/send_update_log_report_signal.py
  engine/apps/alerts/tests/test_maintenance.py
  engine/apps/api/serializers/organization.py
  engine/apps/api/tests/test_escalation_policy.py
  engine/apps/api/tests/test_maintenance.py
  engine/apps/api/urls.py
  engine/apps/api/views/maintenance.py
  engine/apps/public_api/serializers/organizations.py
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/user_management/models/organization.py
  grafana-plugin/integration-tests/integrations/maintenanceMode.test.ts
  grafana-plugin/integration-tests/utils/alertGroup.ts
  grafana-plugin/integration-tests/utils/forms.ts
  grafana-plugin/integration-tests/utils/integrations.ts
  grafana-plugin/playwright.config.ts
  grafana-plugin/src/components/Integrations/IntegrationBlockItem.tsx
  grafana-plugin/src/components/TooltipBadge/TooltipBadge.tsx
  grafana-plugin/src/components/WithContextMenu/WithContextMenu.tsx
  grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/MaintenanceForm/MaintenanceForm.config.tsx
  grafana-plugin/src/containers/MaintenanceForm/MaintenanceForm.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/models/maintenance/maintenance.ts
  grafana-plugin/src/models/maintenance/maintenance.types.ts
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/pages/integrations/Integrations.tsx
  grafana-plugin/src/state/rootBaseStore/index.ts
  grafana-plugin/src/utils/index.ts
Labels: pr:no public docs

#2483 Unhide direct paging integration
  CHANGELOG.md
  engine/apps/alerts/paging.py
  engine/apps/alerts/tests/test_paging.py
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/serializers/paging.py
  engine/apps/api/tests/test_alert_group.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/views/alert_receive_channel.py
  engine/apps/public_api/tests/test_integrations.py
  engine/apps/public_api/views/integrations.py
  engine/config_integrations/direct_paging.py
  grafana-plugin/src/components/ManualAlertGroup/ManualAlertGroup.config.ts
  grafana-plugin/src/components/ManualAlertGroup/ManualAlertGroup.module.css
  grafana-plugin/src/components/ManualAlertGroup/ManualAlertGroup.tsx
  grafana-plugin/src/containers/CreateAlertReceiveChannelContainer/CreateAlertReceiveChannelContainer.tsx
  grafana-plugin/src/containers/EscalationVariants/EscalationVariants.tsx
  grafana-plugin/src/containers/GrafanaTeamSelect/GrafanaTeamSelect.tsx
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/integration/Integration.tsx
Labels: pr:no public docs

#2482 remove unused frontend code
  grafana-plugin/.eslintrc.js
  grafana-plugin/src/components/UserTimezoneSelect/UserTimezoneSelect.tsx
  grafana-plugin/src/containers/OrganizationLogFilters/OrganizationLogFilters.module.css
  grafana-plugin/src/containers/OrganizationLogFilters/OrganizationLogFilters.tsx
  grafana-plugin/src/declare/index.d.ts
  grafana-plugin/src/icons/cross-circled.svg
  grafana-plugin/src/icons/grafana-icon.svg
  grafana-plugin/src/icons/heart-green.svg
  grafana-plugin/src/icons/heart-line.svg
  grafana-plugin/src/icons/heart-red.svg
  grafana-plugin/src/icons/index.tsx
  grafana-plugin/src/img/telegram_discussion.png
  grafana-plugin/src/interceptors/index.ts
  grafana-plugin/src/models/card.ts
  grafana-plugin/src/models/curler/curler.ts
  grafana-plugin/src/models/curler/curler.types.ts
  grafana-plugin/src/models/current_subscription.ts
  grafana-plugin/src/models/current_subscription/current_subscription.ts
  grafana-plugin/src/models/current_subscription/current_subscription.types.ts
  grafana-plugin/src/models/integrations_list.ts
  grafana-plugin/src/models/leader.ts
  grafana-plugin/src/models/organization_log/organization_log.ts
  grafana-plugin/src/models/organization_log/organization_log.types.ts
  grafana-plugin/src/models/timezone/timezone.helpers.ts
  grafana-plugin/src/models/timezone/timezone.types.ts
  grafana-plugin/src/models/webinar/webinar.ts
  grafana-plugin/src/models/webinar/webinar.types.ts
  grafana-plugin/src/pages/index.tsx
  grafana-plugin/src/pages/organization-logs/OrganizationLog.module.css
  grafana-plugin/src/pages/organization-logs/OrganizationLog.tsx
  grafana-plugin/src/pages/routes.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/services/experimentManager.ts
  grafana-plugin/src/services/googleTagManager.ts
  grafana-plugin/src/services/urlManager.ts
  grafana-plugin/src/state/rootBaseStore/index.ts
Labels: pr:no changelog, pr:no public docs

#2519 bump celery version to a version which supports Python 3.11
  engine/requirements.txt
Labels: pr:no changelog, pr:no public docs

#2456 Update all links to use `docs/reference` style
  .github/CODEOWNERS
  .github/workflows/linting-and-tests.yml
  .github/workflows/update-make-docs.yml
  .pre-commit-config.yaml
  docs/.markdownlint.json
  docs/docs.mk
  docs/make-docs
  docs/sources/escalation-chains-and-routes/_index.md
  docs/sources/get-started/_index.md
  docs/sources/insights-and-metrics/_index.md
  docs/sources/integrations/_index.md
  docs/sources/integrations/alertmanager/index.md
  docs/sources/integrations/amazon-sns/index.md
  docs/sources/integrations/appdynamics/index.md
  docs/sources/integrations/datadog/index.md
  docs/sources/integrations/elastalert/index.md
  docs/sources/integrations/fabric/index.md
  docs/sources/integrations/inbound-email/index.md
  docs/sources/integrations/jira/index.md
  docs/sources/integrations/kapacitor/index.md
  docs/sources/integrations/newrelic/index.md
  docs/sources/integrations/pingdom/index.md
  docs/sources/integrations/prtg/index.md
  docs/sources/integrations/sentry/index.md
  docs/sources/integrations/stackdriver/index.md
  docs/sources/integrations/uptimerobot/index.md
  docs/sources/integrations/webhook/index.md
  docs/sources/integrations/zendesk/index.md
  docs/sources/notify/_index.md
  docs/sources/notify/phone-calls-sms/index.md
  docs/sources/notify/slack/index.md
  docs/sources/on-call-schedules/_index.md
  docs/sources/on-call-schedules/api-terraform-schedule/_index.md
  docs/sources/on-call-schedules/ical-schedules/index.md
  docs/sources/oncall-api-reference/integrations.md
  docs/variables.mk
Labels: pr:no changelog

#1830 Webhooks 2 Release
  CHANGELOG.md
  engine/apps/api/tests/test_escalation_policy.py
  engine/apps/api/views/escalation_policy.py
  engine/apps/api/views/features.py
  engine/apps/api/views/webhooks.py
  engine/apps/webhooks/migrations/0008_auto_20230712_1613.py
  engine/apps/webhooks/utils.py
  engine/settings/base.py
  grafana-plugin/src/components/GForm/GForm.tsx
  grafana-plugin/src/components/GForm/GForm.types.ts
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/containers/OutgoingWebhook2Form/OutgoingWebhook2Form.config.tsx
  grafana-plugin/src/containers/OutgoingWebhook2Form/OutgoingWebhook2Form.tsx
  grafana-plugin/src/containers/WebhooksTemplateEditor/WebhooksTemplateEditor.tsx
  grafana-plugin/src/models/filters/filters.helpers.ts
  grafana-plugin/src/pages/index.tsx
  grafana-plugin/src/pages/outgoing_webhooks_2/OutgoingWebhooks2.module.scss
  grafana-plugin/src/pages/outgoing_webhooks_2/OutgoingWebhooks2.tsx
  grafana-plugin/src/pages/routes.tsx
  grafana-plugin/src/plugin.json
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
Labels: pr:no public docs

#1844 Outgoing webhooks 2 documentation
  docs/sources/integrations/jira/index.md
  docs/sources/integrations/servicenow/index.md
  docs/sources/integrations/zendesk/index.md
  docs/sources/outgoing-webhooks/_index.md
Labels: pr:no changelog

#2528 Fix migration for long names and do not include deleted
  engine/apps/webhooks/migrations/0008_auto_20230712_1613.py
Labels: pr:no changelog, pr:no public docs

#2529 Merge dev to main
  engine/apps/webhooks/migrations/0008_auto_20230712_1613.py
Labels: pr:no changelog, pr:no public docs

#2515 Fix markup bug and change text
  grafana-plugin/src/components/ManualAlertGroup/ManualAlertGroup.module.css
  grafana-plugin/src/components/ManualAlertGroup/ManualAlertGroup.tsx
Labels: pr:no changelog, pr:no public docs

#2530 remove deprecated gitops views
  engine/apps/alerts/terraform_renderer/__init__.py
  engine/apps/alerts/terraform_renderer/terraform_file_renderer.py
  engine/apps/alerts/terraform_renderer/terraform_state_renderer.py
  engine/apps/alerts/tests/test_terraform_renderer.py
  engine/apps/api/response_renderers.py
  engine/apps/api/tests/test_gitops.py
  engine/apps/api/tests/test_terraform_renderer.py
  engine/apps/api/urls.py
  engine/apps/api/views/gitops.py
Labels: pr:no changelog, pr:no public docs

#2407 fix import mypy errors
  engine/pyproject.toml
Labels: pr:no changelog, pr:no public docs

#2541 Fix authorization header masked
  CHANGELOG.md
  engine/apps/webhooks/tasks/trigger_webhook.py
Labels: pr:no public docs

#2489 improve RBAC documentation
  docs/sources/user-and-team-management/_index.md
  docs/sources/user-and-team-management/convert_plugin_json_rbac_roles_into_markdown_table.py
Labels: pr:no changelog

#2533 Remove INTEGRATIONS_TO_REVERSE_URL_MAP
  engine/apps/alerts/integration_options_mixin.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/tests/test_alert_receiver_channel.py
  engine/apps/public_api/serializers/integrations.py
Labels: pr:no changelog, pr:no public docs

#2534 remove deprecated heartbeat_heartbeat table/model
  CHANGELOG.md
  docs/sources/open-source/_index.md
  engine/apps/heartbeat/admin.py
  engine/apps/heartbeat/migrations/0002_delete_heartbeat.py
  engine/apps/heartbeat/models.py
  engine/apps/heartbeat/tasks.py
  engine/apps/integrations/metadata/heartbeat/_heartbeat_text_creator.py
  engine/apps/integrations/urls.py
  engine/apps/integrations/views.py
  engine/settings/base.py
  engine/settings/prod_without_db.py
  grafana-plugin/src/containers/IntegrationContainers/IntegrationHeartbeatForm/IntegrationHeartbeatForm.tsx
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/pages/integrations/Integrations.tsx
Labels: pr:no public docs

#2548 Revert "bring heartbeats back to UI"
  grafana-plugin/src/containers/IntegrationContainers/IntegrationHeartbeatForm/IntegrationHeartbeatForm.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/pages/integration/Integration.tsx
Labels: pr:no changelog, pr:no public docs

#2425 Polish user settings and warnings
  CHANGELOG.md
  engine/apps/api/views/user.py
  engine/apps/user_management/models/organization.py
  grafana-plugin/src/components/Policy/NotificationPolicy.module.css
  grafana-plugin/src/containers/Alerts/Alerts.tsx
  grafana-plugin/src/containers/UserSettings/UserSettings.tsx
  grafana-plugin/src/containers/UserSettings/parts/connectors/ICalConnector.tsx
  grafana-plugin/src/containers/UserSettings/parts/connectors/MobileAppConnector.tsx
  grafana-plugin/src/containers/UserSettings/parts/connectors/PhoneConnector.tsx
  grafana-plugin/src/containers/UserSettings/parts/connectors/SlackConnector.tsx
  grafana-plugin/src/containers/UserSettings/parts/connectors/TelegramConnector.tsx
  grafana-plugin/src/containers/UserSettings/parts/connectors/index.tsx
  grafana-plugin/src/containers/UserSettings/parts/index.tsx
  grafana-plugin/src/containers/UserSettings/parts/tabs/CloudPhoneSettings/CloudPhoneSettings.tsx
  grafana-plugin/src/containers/UserSettings/parts/tabs/UserInfoTab/UserInfoTab.tsx
  grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/SlackSettings/SlackSettings.tsx
  grafana-plugin/src/pages/users/Users.tsx
Labels: pr:no public docs

#2494 Docs: Update oncall rbac detail
  docs/sources/mobile-app/alert-groups-feed/index.md
  docs/sources/user-and-team-management/_index.md
Labels: type/docs, pr:no changelog

#2539 Update Users.tsx
  grafana-plugin/src/pages/users/Users.tsx
Labels: pr:no changelog, pr:no public docs

#2538 Update all make docs CI to match
  .github/workflows/linting-and-tests.yml
  .github/workflows/publish-technical-documentation-next.yml
  .github/workflows/publish-technical-documentation-release.yml
Labels: pr:no changelog, pr:no public docs

#2537 Direct paging improvements
  CHANGELOG.md
  engine/apps/alerts/paging.py
  engine/apps/alerts/tests/test_paging.py
  engine/apps/api/serializers/paging.py
  engine/apps/api/views/user.py
  engine/apps/slack/scenarios/manual_incident.py
  engine/apps/slack/scenarios/paging.py
  engine/apps/slack/scenarios/scenario_step.py
  engine/apps/slack/tests/test_interactive_api_endpoint.py
  engine/apps/slack/tests/test_scenario_steps/test_paging.py
  engine/apps/slack/views.py
  grafana-plugin/integration-tests/alerts/directPaging.test.ts
  grafana-plugin/integration-tests/utils/alertGroup.ts
  grafana-plugin/integration-tests/utils/navigation.ts
  grafana-plugin/src/components/ManualAlertGroup/ManualAlertGroup.config.ts
  grafana-plugin/src/components/ManualAlertGroup/ManualAlertGroup.tsx
  grafana-plugin/src/containers/EscalationVariants/EscalationVariants.tsx
  grafana-plugin/src/containers/GrafanaTeamSelect/GrafanaTeamSelect.tsx
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/incidents/Incidents.tsx
Labels: pr:no public docs

#2540 Remove v prefix from plugin version on build
  .drone.yml
  CHANGELOG.md
Labels: pr:no public docs

#2554 minor improvements for check_escalation_finished celery task
  engine/apps/alerts/tasks/check_escalation_finished.py
  engine/apps/alerts/tests/test_check_escalation_finished_task.py
Labels: pr:no changelog, pr:no public docs

#2559 Jira & Zendesk docs minor formatting fixes
  docs/sources/integrations/jira/index.md
  docs/sources/integrations/zendesk/index.md
Labels: pr:no changelog

#2562 Update Slack "invite" feature to use direct paging
  CHANGELOG.md
  engine/apps/alerts/incident_appearance/renderers/slack_renderer.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/paging.py
  engine/apps/api/serializers/alert_group.py
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/slack/scenarios/manage_responders.py
  engine/apps/slack/scenarios/paging.py
  engine/apps/slack/tests/test_interactive_api_endpoint.py
  engine/apps/slack/tests/test_scenario_steps/test_manage_responders.py
  engine/apps/slack/tests/test_slack_renderer.py
  engine/apps/slack/views.py
Labels: pr:no public docs

#2567 Current responders -> Additional Responders
  CHANGELOG.md
  grafana-plugin/src/pages/incident/parts/PagedUsers.tsx
Labels: pr:no public docs

#2524 remove references to AlertGroup.is_archived and AlertGroup.unarchived_objects
  CHANGELOG.md
  engine/apps/alerts/admin.py
  engine/apps/alerts/escalation_snapshot/escalation_snapshot_mixin.py
  engine/apps/alerts/migrations/0023_auto_20230718_0952.py
  engine/apps/alerts/models/alert.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/models/maintainable_object.py
  engine/apps/alerts/tasks/acknowledge_reminder.py
  engine/apps/alerts/tasks/alert_group_web_title_cache.py
  engine/apps/alerts/tasks/call_ack_url.py
  engine/apps/alerts/tasks/check_escalation_finished.py
  engine/apps/alerts/tasks/custom_button_result.py
  engine/apps/alerts/tasks/delete_alert_group.py
  engine/apps/alerts/tasks/distribute_alert.py
  engine/apps/alerts/tasks/escalate_alert_group.py
  engine/apps/alerts/tasks/invite_user_to_join_incident.py
  engine/apps/alerts/tasks/maintenance.py
  engine/apps/alerts/tasks/notify_all.py
  engine/apps/alerts/tasks/notify_group.py
  engine/apps/alerts/tasks/notify_user.py
  engine/apps/alerts/tasks/resolve_alert_group_by_source_if_needed.py
  engine/apps/alerts/tasks/resolve_by_last_step.py
  engine/apps/alerts/tasks/send_update_log_report_signal.py
  engine/apps/alerts/tasks/send_update_resolution_note_signal.py
  engine/apps/alerts/tasks/unsilence.py
  engine/apps/alerts/tasks/wipe.py
  engine/apps/alerts/tests/test_alert_group_renderer.py
  engine/apps/alerts/tests/test_maintenance.py
  engine/apps/alerts/tests/test_paging.py
  engine/apps/api/serializers/paging.py
  engine/apps/api/serializers/resolution_note.py
  engine/apps/api/views/alert_group.py
  engine/apps/api/views/route_regex_debugger.py
  engine/apps/api_for_grafana_incident/views.py
  engine/apps/email/tasks.py
  engine/apps/mobile_app/tasks.py
  engine/apps/public_api/serializers/resolution_notes.py
  engine/apps/public_api/tests/test_incidents.py
  engine/apps/public_api/views/incidents.py
  engine/apps/slack/representatives/alert_group_representative.py
  engine/apps/slack/scenarios/alertgroup_appearance.py
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/slack/scenarios/manage_responders.py
  engine/apps/slack/scenarios/resolution_note.py
  engine/apps/slack/scenarios/slack_renderer.py
  engine/apps/slack/scenarios/step_mixins.py
  engine/apps/slack/tasks.py
  engine/apps/telegram/alert_group_representative.py
  engine/apps/telegram/tasks.py
  engine/apps/telegram/updates/update_handlers/button_press.py
  engine/apps/webhooks/tasks/alert_group_status.py
  engine/apps/webhooks/tasks/trigger_webhook.py
  engine/apps/webhooks/tests/test_alert_group_status_change.py
Labels: pr:no public docs

#2569 fix UI typo
  grafana-plugin/src/pages/integration/Integration.tsx
Labels: pr:no changelog, pr:no public docs

#2526 Reworked slack login pipeline errors
  CHANGELOG.md
  engine/apps/api/tests/test_auth.py
  engine/apps/api/views/auth.py
  engine/apps/social_auth/pipeline.py
  engine/conftest.py
  grafana-plugin/src/containers/Alerts/Alerts.tsx
Labels: pr:no public docs

#2568 Fix duplicate orders on routes and escalation policies
  CHANGELOG.md
  engine/apps/alerts/escalation_snapshot/snapshot_classes/escalation_snapshot.py
  engine/apps/alerts/migrations/0024_auto_20230718_0953.py
  engine/apps/alerts/migrations/0025_auto_20230718_1042.py
  engine/apps/alerts/models/channel_filter.py
  engine/apps/alerts/models/escalation_policy.py
  engine/apps/alerts/tests/test_escalation_snapshot.py
  engine/apps/api/serializers/channel_filter.py
  engine/apps/api/serializers/escalation_policy.py
  engine/apps/api/serializers/user_notification_policy.py
  engine/apps/api/tests/test_channel_filter.py
  engine/apps/api/tests/test_escalation_policy.py
  engine/apps/api/views/channel_filter.py
  engine/apps/api/views/escalation_policy.py
  engine/apps/api/views/user_notification_policy.py
  engine/apps/base/models/user_notification_policy.py
  engine/apps/public_api/serializers/escalation_policies.py
  engine/apps/public_api/serializers/personal_notification_rules.py
  engine/apps/public_api/serializers/routes.py
  engine/apps/public_api/tests/test_escalation_policies.py
  engine/apps/public_api/tests/test_routes.py
  engine/common/api_helpers/mixins.py
  engine/common/ordered_model/__init__.py
  engine/common/ordered_model/ordered_model.py
  engine/common/ordered_model/serializer.py
  engine/common/ordered_model/viewset.py
  engine/common/tests/test_ordered_model.py
  engine/requirements.txt
  grafana-plugin/src/containers/ChannelFilterForm/ChannelFilterForm.tsx
  grafana-plugin/src/models/channel_filter.ts
  grafana-plugin/src/models/channel_filter/channel_filter.types.ts
  grafana-plugin/src/models/escalation_policy.ts
  grafana-plugin/src/models/escalation_policy/escalation_policy.types.ts
  grafana-plugin/src/models/notification_policy.ts
  grafana-plugin/src/pages/integration/Integration.tsx
Labels: pr:no public docs

#2572 Outgoing webhooks docs minor updates
  docs/sources/integrations/jira/index.md
  docs/sources/integrations/servicenow/index.md
  docs/sources/integrations/zendesk/index.md
  docs/sources/outgoing-webhooks/_index.md
Labels: pr:no changelog

#2573 Fix public API integration default route
  engine/apps/public_api/tests/test_integrations.py
  engine/common/ordered_model/serializer.py
Labels: pr:no changelog, pr:no public docs

#2571 Fix slack channels sync
  CHANGELOG.md
  engine/apps/slack/slack_client/slack_client.py
  engine/apps/slack/tasks.py
  engine/apps/slack/tests/test_populate_slack_channels.py
  engine/apps/slack/utils.py
Labels: pr:no public docs

#2581 fix migrations that were causing issues
  engine/apps/alerts/migrations/0022_alter_alertgroup_manual_severity.py
  engine/apps/alerts/migrations/0023_auto_20230718_0952.py
  engine/apps/alerts/migrations/0026_auto_20230719_1010.py
  engine/apps/alerts/models/alert_group.py
Labels: pr:no changelog, pr:no public docs

#2574 Remove docker-compose warnings
  docker-compose.yml
Labels: pr:no changelog, pr:no public docs

#2601 allowing storing/updating time_zone in mobile app user settings table
  CHANGELOG.md
  engine/apps/mobile_app/migrations/0010_mobileappusersettings_time_zone.py
  engine/apps/mobile_app/models.py
  engine/apps/mobile_app/serializers.py
  engine/apps/mobile_app/tasks.py
  engine/apps/mobile_app/tests/test_user_settings.py
  engine/apps/mobile_app/tests/test_your_going_oncall_notification.py
Labels: pr:no public docs

#2607 Minor direct paging docs update
  docs/sources/integrations/manual/index.md
Labels: pr:no changelog

#2608 Check original webhook for sensitive fields when copying
  CHANGELOG.md
  engine/apps/api/serializers/webhook.py
  engine/apps/api/tests/test_webhooks.py
Labels: pr:no public docs

#2609 Add filter integrations by type
  CHANGELOG.md
  engine/apps/api/views/alert_receive_channel.py
Labels: pr:no public docs

#2603 Improve APIs for creating/updating direct paging integrations
  CHANGELOG.md
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/views/alert_receive_channel.py
  engine/apps/public_api/serializers/integrations.py
  engine/apps/public_api/tests/test_integrations.py
Labels: pr:no public docs

#2379 Update download app text
  grafana-plugin/src/containers/MobileAppConnection/__snapshots__/MobileAppConnection.test.tsx.snap
  grafana-plugin/src/containers/MobileAppConnection/parts/DownloadIcons/__snapshots__/DownloadIcons.test.tsx.snap
  grafana-plugin/src/containers/MobileAppConnection/parts/DownloadIcons/index.tsx
Labels: pr:no changelog, pr:no public docs

#2606 Remove unnecessary team checks
  CHANGELOG.md
  engine/apps/public_api/serializers/escalation_policies.py
  engine/apps/public_api/serializers/routes.py
  engine/apps/public_api/serializers/schedules_calendar.py
  engine/apps/public_api/serializers/schedules_web.py
  terraform/README.md
Labels: pr:no public docs

#2611 add rbac_permissions to current-user response + rbac_enabled to current-org response
  CHANGELOG.md
  engine/apps/api/serializers/organization.py
  engine/apps/api/serializers/user.py
  engine/apps/api/tests/test_organization.py
  engine/apps/api/tests/test_user.py
  engine/apps/api/urls.py
  engine/apps/api/views/organization.py
  engine/apps/api/views/user.py
  grafana-plugin/src/components/ScheduleUserDetails/ScheduleUserDetails.tsx
  grafana-plugin/src/containers/AlertRules/parts/connectors/SlackConnector.tsx
  grafana-plugin/src/containers/AlertRules/parts/index.tsx
  grafana-plugin/src/containers/Alerts/Alerts.tsx
  grafana-plugin/src/containers/DefaultPageLayout/DefaultPageLayout.helpers.tsx
  grafana-plugin/src/containers/EscalationChainSteps/EscalationChainSteps.tsx
  grafana-plugin/src/containers/PersonalNotificationSettings/PersonalNotificationSettings.tsx
  grafana-plugin/src/containers/UserSettings/UserSettings.tsx
  grafana-plugin/src/containers/UserSettings/parts/connectors/SlackConnector.tsx
  grafana-plugin/src/containers/UserSettings/parts/tabs/PhoneVerification/PhoneVerification.tsx
  grafana-plugin/src/containers/UserSettings/parts/tabs/TelegramInfo/TelegramInfo.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/models/base_store.ts
  grafana-plugin/src/models/organization/organization.ts
  grafana-plugin/src/models/organization/organization.types.ts
  grafana-plugin/src/models/team/team.ts
  grafana-plugin/src/models/user/user.types.ts
  grafana-plugin/src/pages/integration/Integration.helper.ts
  grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/SlackSettings/SlackSettings.tsx
  grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/TelegramSettings/TelegramSettings.tsx
  grafana-plugin/src/pages/settings/tabs/MainSettings/MainSettings.tsx
  grafana-plugin/src/pages/users/Users.tsx
  grafana-plugin/src/state/rootBaseStore/index.ts
Labels: pr:no public docs

#2597 shift swap requests model + CRUD endpoints
  Makefile
  engine/apps/api/permissions.py
  engine/apps/api/serializers/schedule_calendar.py
  engine/apps/api/serializers/schedule_web.py
  engine/apps/api/serializers/shift_swap.py
  engine/apps/api/serializers/user.py
  engine/apps/api/tests/test_permissions.py
  engine/apps/api/tests/test_shift_swaps.py
  engine/apps/api/urls.py
  engine/apps/api/views/shift_swap.py
  engine/apps/mobile_app/serializers.py
  engine/apps/public_api/serializers/on_call_shifts.py
  engine/apps/public_api/serializers/schedules_calendar.py
  engine/apps/public_api/serializers/schedules_web.py
  engine/apps/schedules/exceptions.py
  engine/apps/schedules/migrations/0014_shiftswaprequest.py
  engine/apps/schedules/models/__init__.py
  engine/apps/schedules/models/shift_swap_request.py
  engine/apps/schedules/tests/factories.py
  engine/apps/schedules/tests/test_shift_swap_request.py
  engine/apps/webhooks/__init__.py
  engine/common/api_helpers/custom_fields.py
  engine/common/tests/test_custom_fields.py
  engine/common/tests/test_ordered_model.py
  engine/common/tests/test_timezones.py
  engine/common/timezones.py
  engine/conftest.py
  engine/settings/base.py
  engine/settings/ci-test.py
Labels: pr:no changelog, pr:no public docs

#2566 Alert with information has been added to chatOPs tab
  CHANGELOG.md
  grafana-plugin/src/jest/utils.ts
  grafana-plugin/src/pages/settings/tabs/ChatOps/ChatOps.tsx
Labels: pr:no public docs

#2627 Remove integration html instructions
  engine/apps/alerts/integration_options_mixin.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/serializers/integration_heartbeat.py
  engine/apps/integrations/metadata/heartbeat/_heartbeat_text_creator.py
  engine/apps/integrations/metadata/heartbeat/alertmanager.py
  engine/apps/integrations/metadata/heartbeat/elastalert.py
  engine/apps/integrations/metadata/heartbeat/formatted_webhook.py
  engine/apps/integrations/metadata/heartbeat/grafana.py
  engine/apps/integrations/metadata/heartbeat/prtg.py
  engine/apps/integrations/metadata/heartbeat/webhook.py
  engine/apps/integrations/metadata/heartbeat/zabbix.py
  engine/apps/integrations/templates/heartbeat_instructions/alertmanager.html
  engine/apps/integrations/templates/heartbeat_instructions/elastalert.html
  engine/apps/integrations/templates/heartbeat_instructions/formatted_webhook.html
  engine/apps/integrations/templates/heartbeat_instructions/grafana.html
  engine/apps/integrations/templates/heartbeat_instructions/prtg.html
  engine/apps/integrations/templates/heartbeat_instructions/webhook.html
  engine/apps/integrations/templates/heartbeat_instructions/zabbix.html
  engine/apps/integrations/templates/html/integration_alertmanager.html
  engine/apps/integrations/templates/html/integration_alertmanager_v2.html
  engine/apps/integrations/templates/html/integration_amazon_sns.html
  engine/apps/integrations/templates/html/integration_appdynamics.html
  engine/apps/integrations/templates/html/integration_curler.html
  engine/apps/integrations/templates/html/integration_datadog.html
  engine/apps/integrations/templates/html/integration_demo.html
  engine/apps/integrations/templates/html/integration_direct_paging.html
  engine/apps/integrations/templates/html/integration_elastalert.html
  engine/apps/integrations/templates/html/integration_fabric.html
  engine/apps/integrations/templates/html/integration_formatted_webhook.html
  engine/apps/integrations/templates/html/integration_grafana.html
  engine/apps/integrations/templates/html/integration_grafana_alerting.html
  engine/apps/integrations/templates/html/integration_heartbeat.html
  engine/apps/integrations/templates/html/integration_inbound_email.html
  engine/apps/integrations/templates/html/integration_jira.html
  engine/apps/integrations/templates/html/integration_kapacitor.html
  engine/apps/integrations/templates/html/integration_manual.html
  engine/apps/integrations/templates/html/integration_newrelic.html
  engine/apps/integrations/templates/html/integration_pagerduty.html
  engine/apps/integrations/templates/html/integration_pingdom.html
  engine/apps/integrations/templates/html/integration_prtg.html
  engine/apps/integrations/templates/html/integration_sentry.html
  engine/apps/integrations/templates/html/integration_sentry_platform.html
  engine/apps/integrations/templates/html/integration_slack_channel.html
  engine/apps/integrations/templates/html/integration_stackdriver.html
  engine/apps/integrations/templates/html/integration_uptimerobot.html
  engine/apps/integrations/templates/html/integration_webhook.html
  engine/apps/integrations/templates/html/integration_zabbix.html
  engine/apps/integrations/templates/html/integration_zendesk.html
  engine/apps/integrations/tests/test_heartbeat_metadata.py
Labels: pr:no changelog, pr:no public docs

#2605 added all queries to incident page
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/incidents/Incidents.tsx
Labels: pr:no changelog, pr:no public docs

#2623 support comma and space delimited grafana feature_toggles
  CHANGELOG.md
  engine/apps/grafana_plugin/helpers/client.py
  engine/apps/grafana_plugin/tests/test_gcom_api_client.py
Labels: pr:no public docs

#2545 remove deprecated call_ack_url celery task
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/tasks/__init__.py
  engine/apps/alerts/tasks/call_ack_url.py
  engine/apps/alerts/utils.py
  engine/apps/webhooks/models/webhook.py
  engine/apps/webhooks/tests/test_webhook.py
  engine/apps/webhooks/utils.py
  engine/settings/prod_without_db.py
Labels: pr:no changelog, pr:no public docs

#2030 Remove unnecessary signal
  engine/apps/alerts/models/__init__.py
  engine/apps/alerts/models/alert.py
  engine/conftest.py
Labels: pr:no changelog, pr:no public docs, pr:stale

#2550 Maxim/bring heartbeats back to UI
  CHANGELOG.md
  grafana-plugin/integration-tests/integrations/heartbeat.test.ts
  grafana-plugin/src/containers/IntegrationContainers/IntegrationHeartbeatForm/IntegrationHeartbeatForm.module.scss
  grafana-plugin/src/containers/IntegrationContainers/IntegrationHeartbeatForm/IntegrationHeartbeatForm.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/pages/integrations/Integrations.tsx
Labels: pr:no public docs

#2632 remove alert_receive_channel.restricted_at unused column
  engine/apps/alerts/migrations/0027_remove_alertreceivechannel_restricted_at.py
  engine/apps/alerts/models/alert_receive_channel.py
Labels: pr:no changelog, pr:no public docs

#2634 modify alert_receive_channel migration
  engine/apps/alerts/models/alert_receive_channel.py
Labels: pr:no changelog, pr:no public docs

#2625 Refactoring schedule final events for reusability
  CHANGELOG.md
  engine/apps/alerts/escalation_snapshot/snapshot_classes/escalation_policy_snapshot.py
  engine/apps/alerts/tests/test_escalation_policy_snapshot.py
  engine/apps/api/tests/test_schedules.py
  engine/apps/api/views/on_call_shifts.py
  engine/apps/api/views/schedule.py
  engine/apps/mobile_app/tasks.py
  engine/apps/public_api/views/schedules.py
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_ical_utils.py
  engine/apps/schedules/tests/test_on_call_schedule.py
  engine/apps/schedules/tests/test_quality_score.py
Labels: pr:no public docs

#2642 Revert "Refactoring schedule final events for reusability"
  CHANGELOG.md
  engine/apps/alerts/escalation_snapshot/snapshot_classes/escalation_policy_snapshot.py
  engine/apps/alerts/tests/test_escalation_policy_snapshot.py
  engine/apps/api/tests/test_schedules.py
  engine/apps/api/views/on_call_shifts.py
  engine/apps/api/views/schedule.py
  engine/apps/mobile_app/tasks.py
  engine/apps/public_api/views/schedules.py
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_ical_utils.py
  engine/apps/schedules/tests/test_on_call_schedule.py
  engine/apps/schedules/tests/test_quality_score.py
Labels: pr:no public docs

#2624 Remove checks that slow down plugin load and cause "Initializing plugin..."
  CHANGELOG.md
  engine/apps/grafana_plugin/tasks/sync.py
  engine/apps/grafana_plugin/views/status.py
  engine/apps/grafana_plugin/views/sync.py
  grafana-plugin/integration-tests/integrations/heartbeat.test.ts
  grafana-plugin/package.json
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.test.tsx
  grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.tsx
  grafana-plugin/src/containers/PluginConfigPage/__snapshots__/PluginConfigPage.test.tsx.snap
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/plugin/PluginSetup/PluginSetup.test.tsx
  grafana-plugin/src/plugin/PluginSetup/__snapshots__/PluginSetup.test.tsx.snap
  grafana-plugin/src/plugin/PluginSetup/index.tsx
  grafana-plugin/src/state/plugin/__snapshots__/plugin.test.ts.snap
  grafana-plugin/src/state/plugin/index.ts
  grafana-plugin/src/state/plugin/plugin.test.ts
  grafana-plugin/src/state/rootBaseStore/index.ts
  grafana-plugin/src/state/rootBaseStore/rootBaseStore.test.ts
Labels: pr:no public docs

#2648 Fix e2e tests
  .github/workflows/linting-and-tests.yml
  grafana-plugin/integration-tests/integrations/heartbeat.test.ts
Labels: pr:no changelog, pr:no public docs

#2636 Fix "Continue escalation if >X alerts per Y minutes" escalation step
  CHANGELOG.md
  engine/apps/alerts/escalation_snapshot/escalation_snapshot_mixin.py
  engine/apps/alerts/tasks/distribute_alert.py
  engine/apps/alerts/tests/test_alert.py
  engine/apps/alerts/tests/test_escalation_snapshot_mixin.py
Labels: pr:no public docs

#2646 drop alert_receive_channel.restricted_at column
  engine/apps/alerts/migrations/0028_drop_alertreceivechannel_restricted_at.py
  engine/apps/alerts/models/alert_receive_channel.py
Labels: pr:no changelog, pr:no public docs

#2641 Minor formatting changes
  .pre-commit-config.yaml
  engine/apps/alerts/escalation_snapshot/escalation_snapshot_mixin.py
  engine/apps/alerts/models/alert_group_log_record.py
  engine/apps/alerts/tasks/check_escalation_finished.py
  engine/apps/alerts/tasks/notify_user.py
  engine/apps/alerts/tasks/resolve_alert_group_by_source_if_needed.py
  engine/apps/api/serializers/channel_filter.py
  engine/apps/api/tests/test_alert_group.py
  engine/apps/api/tests/test_channel_filter.py
  engine/apps/api/tests/test_team.py
  engine/apps/api/views/user.py
  engine/apps/email/inbound.py
  engine/apps/email/tasks.py
  engine/apps/grafana_plugin/apps.py
  engine/apps/grafana_plugin/tests/test_gcom_api_client.py
  engine/apps/grafana_plugin/views/self_hosted_install.py
  engine/apps/integrations/tasks.py
  engine/apps/metrics_exporter/tasks.py
  engine/apps/mobile_app/tasks.py
  engine/apps/mobile_app/tests/test_your_going_oncall_notification.py
  engine/apps/oss_installation/models/cloud_connector.py
  engine/apps/phone_notifications/phone_backend.py
  engine/apps/public_api/serializers/routes.py
  engine/apps/public_api/tests/test_incidents.py
  engine/apps/schedules/models/shift_swap_request.py
  engine/apps/slack/scenarios/manual_incident.py
  engine/apps/slack/scenarios/paging.py
  engine/apps/slack/views.py
  engine/apps/twilioapp/phone_provider.py
  engine/apps/zvonok/models/phone_call.py
  engine/apps/zvonok/phone_provider.py
  engine/common/insight_log/maintenance_insight_log.py
  engine/engine/celery.py
  engine/pyproject.toml
  engine/settings/prod_without_db.py
  engine/tox.ini
Labels: pr:no changelog, pr:no public docs

#2090 Incident -> Alert Group
  engine/apps/alerts/incident_appearance/renderers/phone_call_renderer.py
  engine/apps/alerts/tests/test_alert_group.py
Labels: pr:no changelog, pr:no public docs

#2652 Fix race condition in plugin auth
  engine/apps/grafana_plugin/helpers/gcom.py
Labels: pr:no changelog, pr:no public docs

#2664 Add notifications:read permission to OnCaller role
  grafana-plugin/src/plugin.json
Labels: pr:no changelog, pr:no public docs

#2498 fix: post to Telegram ChatOps channel option is not showing in the integration page
  CHANGELOG.md
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
Labels: pr:no public docs

#2667 Use locationService.push after plugin install
  grafana-plugin/src/state/rootBaseStore/index.ts
  grafana-plugin/src/state/rootBaseStore/rootBaseStore.test.ts
Labels: pr:no changelog, pr:no public docs

#2671 Require basic data loaded for schedule page
  grafana-plugin/src/pages/schedule/Schedule.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
Labels: pr:no changelog, pr:no public docs

#2663 Do not publish frontend plugin to github releases
  .drone.yml
Labels: pr:no changelog, pr:no public docs

#2651 Refactoring schedule final events
  CHANGELOG.md
  engine/apps/alerts/escalation_snapshot/snapshot_classes/escalation_policy_snapshot.py
  engine/apps/alerts/tests/test_escalation_policy_snapshot.py
  engine/apps/api/tests/test_schedules.py
  engine/apps/api/views/on_call_shifts.py
  engine/apps/api/views/schedule.py
  engine/apps/mobile_app/tasks.py
  engine/apps/public_api/views/schedules.py
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_ical_utils.py
  engine/apps/schedules/tests/test_on_call_schedule.py
  engine/apps/schedules/tests/test_quality_score.py
Labels: pr:no public docs

#2680 Fix `alerts.0028` migration for SQLite
  CHANGELOG.md
  engine/Dockerfile
Labels: pr:no public docs

#2677 Apply shift swap requests to schedule events
  CHANGELOG.md
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/models/shift_swap_request.py
  engine/apps/schedules/tests/test_custom_on_call_shift.py
  engine/apps/schedules/tests/test_on_call_schedule.py
  engine/apps/schedules/tests/test_shift_swap_request.py
Labels: pr:no public docs

#2669 Paginate calls to get instances from gcom
  CHANGELOG.md
  engine/apps/grafana_plugin/helpers/client.py
  engine/apps/grafana_plugin/helpers/gcom.py
  engine/apps/grafana_plugin/tests/test_gcom_api_client.py
Labels: pr:no public docs

#2668 Commented permissions required by our Slack bot.
  docs/sources/notify/slack/index.md
Labels: pr:no changelog

#1659 Updated opening paragraph
  docs/sources/get-started/_index.md
Labels: pr:stale

#2686 Update _index.md to correct spelling error of uers to users.
  docs/sources/integrations/_index.md
Labels: type/docs

#2685 Update index.md to correct the ordered list numbers.
  docs/sources/integrations/zabbix/index.md
Labels: type/docs

#2675 Helm - Support topologySpreadConstraints and priorityClassName
  helm/oncall/templates/celery/_deployment.tpl
  helm/oncall/templates/engine/deployment.yaml
  helm/oncall/tests/priority_class_deployments_test.yaml
  helm/oncall/tests/topology_deployments_test.yaml
  helm/oncall/values.yaml
Labels: pr:no changelog, pr:no public docs

#2674 Helm - Twilio validation make auth fields optional
  CHANGELOG.md
  helm/oncall/templates/_env.tpl
  helm/oncall/tests/twilio_auth_env_test.yaml
Labels: pr:no public docs

#2684 Add filter_shift_swaps endpoint to schedules API
  CHANGELOG.md
  engine/apps/api/tests/test_schedules.py
  engine/apps/api/tests/test_shift_swaps.py
  engine/apps/api/views/schedule.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/common/api_helpers/utils.py
Labels: pr:no public docs

#2692 Fix for mobile verification
  CHANGELOG.md
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/plugin/PluginSetup/index.tsx
  grafana-plugin/src/state/rootBaseStore/index.ts
  grafana-plugin/src/utils/loadJs.ts
Labels: pr:no public docs

#2650 add option for sidecar containers in helm chart
  CHANGELOG.md
  helm/oncall/templates/celery/_deployment.tpl
  helm/oncall/templates/engine/deployment.yaml
  helm/oncall/templates/engine/job-migrate.yaml
  helm/oncall/tests/extra_containers_celery_test.yaml
  helm/oncall/tests/extra_containers_engine_test.yaml
  helm/oncall/tests/migrate_extra_containers_test.yaml
  helm/oncall/values.yaml
Labels: pr:no public docs

#2536 remove old webhook UI
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/containers/AlertReceiveChannelCard/AlertReceiveChannelCard.tsx
  grafana-plugin/src/containers/EscalationChainSteps/EscalationChainSteps.tsx
  grafana-plugin/src/containers/OutgoingWebhook2Form/OutgoingWebhook2Form.module.css
  grafana-plugin/src/containers/OutgoingWebhook2Form/OutgoingWebhook2Form.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.config.ts
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.config.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.module.css
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.tsx
  grafana-plugin/src/containers/OutgoingWebhookStatus/OutgoingWebhookStatus.tsx
  grafana-plugin/src/containers/TemplatePreview/TemplatePreview.tsx
  grafana-plugin/src/containers/TemplateResult/TemplateResult.tsx
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
  grafana-plugin/src/containers/WebhooksTemplateEditor/WebhooksTemplateEditor.tsx
  grafana-plugin/src/models/action.ts
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/models/escalation_policy.ts
  grafana-plugin/src/models/escalation_policy/escalation_policy.types.ts
  grafana-plugin/src/models/outgoing_webhook/outgoing_webhook.ts
  grafana-plugin/src/models/outgoing_webhook/outgoing_webhook.types.ts
  grafana-plugin/src/models/outgoing_webhook_2/outgoing_webhook_2.ts
  grafana-plugin/src/models/outgoing_webhook_2/outgoing_webhook_2.types.ts
  grafana-plugin/src/pages/outgoing_webhooks/OutgoingWebhooks.module.css
  grafana-plugin/src/pages/outgoing_webhooks/OutgoingWebhooks.module.scss
  grafana-plugin/src/pages/outgoing_webhooks/OutgoingWebhooks.tsx
  grafana-plugin/src/pages/outgoing_webhooks/OutgoingWebhooks.types.ts
  grafana-plugin/src/pages/outgoing_webhooks_2/OutgoingWebhooks2.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/state/features.ts
  grafana-plugin/src/state/rootBaseStore/index.ts
Labels: pr:no changelog, pr:no public docs

#2513 Update index.md
  docs/sources/get-started/_index.md
  docs/sources/integrations/_index.md
  docs/sources/integrations/alertmanager/index.md
  docs/sources/integrations/zabbix/index.md
  helm/oncall/Chart.yaml
Labels: type/docs, pr:no changelog

#2697 Add list shifts for swap request endpoint
  CHANGELOG.md
  engine/apps/api/tests/test_shift_swaps.py
  engine/apps/api/views/shift_swap.py
  engine/apps/schedules/models/shift_swap_request.py
  engine/apps/schedules/tests/test_shift_swap_request.py
Labels: pr:no public docs

#2699 Fix docs lint issues
  docs/sources/get-started/_index.md
  docs/sources/integrations/zabbix/index.md
Labels: pr:no changelog, pr:no public docs
