Repository grafana/oncall, pull requests merged in 2023-04, with the labels that each got.

#1681 Display warnings on users page in a clean and consistent way
  CHANGELOG.md
  grafana-plugin/src/components/ScheduleQuality/ScheduleQuality.tsx
  grafana-plugin/src/components/StatusCounterBadgeWithTooltip/StatusCounterBadgeWithTooltip.module.scss
  grafana-plugin/src/components/StatusCounterBadgeWithTooltip/StatusCounterBadgeWithTooltip.tsx
  grafana-plugin/src/pages/schedules/Schedules.tsx
  grafana-plugin/src/pages/users/Users.tsx
Labels: pr:no public docs

#1696 Disable mentions when resolution note is created
  CHANGELOG.md
  engine/apps/slack/scenarios/resolution_note.py
Labels: pr:no public docs

#1693 temporarily disable e2e CI job
  .github/workflows/linting-and-tests.yml
Labels: pr:no changelog

#1619 Allow editing assigned team via public api
  CHANGELOG.md
  engine/apps/public_api/serializers/action.py
  engine/apps/public_api/serializers/escalation_chains.py
  engine/apps/public_api/serializers/integrations.py
  engine/apps/public_api/serializers/on_call_shifts.py
  engine/apps/public_api/serializers/schedules_calendar.py
  engine/apps/public_api/serializers/schedules_ical.py
  engine/apps/public_api/serializers/schedules_web.py
  engine/apps/public_api/views/escalation_chains.py
Labels: pr:no public docs

#1702 Restore escalation policy importance explanations
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
Labels: pr:no changelog, pr:no public docs

#1654 Add escalation chain support for new webhooks
  engine/apps/alerts/escalation_snapshot/serializers/escalation_policy_snapshot.py
  engine/apps/alerts/escalation_snapshot/snapshot_classes/escalation_policy_snapshot.py
  engine/apps/alerts/migrations/0011_auto_20230329_1617.py
  engine/apps/alerts/models/alert_group_log_record.py
  engine/apps/alerts/models/escalation_policy.py
  engine/apps/alerts/tasks/__init__.py
  engine/apps/alerts/tasks/custom_webhook_result.py
  engine/apps/alerts/tests/test_custom_webhook_result.py
  engine/apps/alerts/tests/test_escalation_policy_snapshot.py
  engine/apps/alerts/tests/test_escalation_snapshot.py
  engine/apps/api/serializers/escalation_policy.py
  engine/apps/api/serializers/webhook.py
  engine/apps/api/tests/test_escalation_policy.py
  engine/apps/api/tests/test_webhooks.py
  engine/apps/api/views/escalation_policy.py
  engine/apps/api/views/webhooks.py
  engine/apps/webhooks/tasks/trigger_webhook.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
  engine/apps/webhooks/utils.py
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/containers/EscalationChainSteps/EscalationChainSteps.tsx
  grafana-plugin/src/models/escalation_policy/escalation_policy.types.ts
  grafana-plugin/src/models/filters/filters.helpers.ts
  grafana-plugin/src/models/outgoing_webhook_2/outgoing_webhook_2.ts
  grafana-plugin/src/models/outgoing_webhook_2/outgoing_webhook_2.types.ts
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
Labels: pr:no changelog, pr:no public docs

#1699 Docs: change 'Alerts & incidents' to 'Alerts & IRM' in the docs
  docs/sources/configure-user-settings/_index.md
Labels: type/docs, pr:no changelog

#1705 Add user endpoint to get upcoming shifts details
  engine/apps/api/tests/test_user.py
  engine/apps/api/views/user.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_on_call_schedule.py
Labels: pr:no changelog, pr:no public docs

#1706 Add more context data to webhook templating
  engine/apps/webhooks/tasks/trigger_webhook.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
  engine/apps/webhooks/utils.py
Labels: pr:no changelog, pr:no public docs

#1712 Fix a bug in GForm
  CHANGELOG.md
  grafana-plugin/src/components/GForm/GForm.tsx
Labels: pr:no public docs

#1721 Add Slack Api error "message_limit_exceeded" to SlackAPIRateLimitException
  CHANGELOG.md
  engine/apps/slack/slack_client/slack_client.py
Labels: pr:no public docs

#1725 Add mobile app auth for `notification_policies` endpoint
  README.md
  dev/README.md
  engine/apps/api/views/user_notification_policy.py
Labels: pr:no changelog, pr:no public docs

#1730 1620 table view for integrations
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.config.ts
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.helpers.ts
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.module.css
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/pages/index.tsx
  grafana-plugin/src/pages/integrations_2/Integrations2.module.scss
  grafana-plugin/src/pages/integrations_2/Integrations2.tsx
  grafana-plugin/src/pages/routes.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
Labels: pr:no changelog, pr:no public docs

#1733 creating escalation chain from integration fix
  grafana-plugin/src/containers/AlertRules/AlertRules.tsx
Labels: pr:no changelog, pr:no public docs

#1729 run e2e tests against grafana 8.5.22 on CI job
  .github/workflows/linting-and-tests.yml
Labels: pr:no changelog, pr:no public docs

#1726 Fix GForm Select dropdowns
  grafana-plugin/src/components/GForm/GForm.tsx
Labels: pr:no changelog, pr:no public docs

#1737 Migrate unsupported integrations to webhook
  tools/pagerduty-migrator/migrator/config.py
  tools/pagerduty-migrator/migrator/report.py
  tools/pagerduty-migrator/migrator/resources/integrations.py
Labels: pr:no changelog, pr:no public docs

#1738 Fix `web_link` property of AlertGroup
  CHANGELOG.md
  engine/apps/alerts/models/alert_group.py
Labels: pr:no public docs

#1744 Merge dev to main
  .github/workflows/linting-and-tests.yml
  CHANGELOG.md
  README.md
  dev/README.md
  engine/apps/alerts/models/alert_group.py
  engine/apps/api/serializers/webhook.py
  engine/apps/api/tests/test_webhooks.py
  engine/apps/api/views/user_notification_policy.py
  engine/apps/webhooks/migrations/0003_auto_20230412_0006.py
  engine/apps/webhooks/models/webhook.py
  engine/apps/webhooks/tasks/alert_group_status.py
  engine/apps/webhooks/tasks/trigger_webhook.py
  engine/apps/webhooks/tests/test_alert_group_status_change.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
  engine/apps/webhooks/utils.py
  grafana-plugin/src/components/GForm/GForm.tsx
  grafana-plugin/src/components/GForm/GForm.types.ts
  grafana-plugin/src/containers/AlertRules/AlertRules.tsx
  grafana-plugin/src/containers/OutgoingWebhook2Form/OutgoingWebhook2Form.config.tsx
  grafana-plugin/src/containers/OutgoingWebhook2Form/OutgoingWebhook2Form.tsx
  grafana-plugin/src/containers/OutgoingWebhook2Status/OutgoingWebhook2Status.tsx
  grafana-plugin/src/models/outgoing_webhook_2/outgoing_webhook_2.types.ts
  grafana-plugin/src/pages/outgoing_webhooks_2/OutgoingWebhooks2.tsx
  screenshot_mobile.png
  tools/pagerduty-migrator/migrator/config.py
  tools/pagerduty-migrator/migrator/report.py
  tools/pagerduty-migrator/migrator/resources/integrations.py
Labels: pr:no public docs

#1748 Support PD integrations without vendor
  tools/pagerduty-migrator/README.md
  tools/pagerduty-migrator/migrator/report.py
  tools/pagerduty-migrator/migrator/resources/integrations.py
Labels: pr:no changelog, pr:no public docs

#1522 add several new database columns + emit two new Django signals
  CHANGELOG.md
  engine/apps/alerts/escalation_snapshot/escalation_snapshot_mixin.py
  engine/apps/alerts/incident_appearance/renderers/classic_markdown_renderer.py
  engine/apps/alerts/incident_appearance/renderers/web_renderer.py
  engine/apps/alerts/migrations/0012_auto_20230406_1010.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/models/alert_group_log_record.py
  engine/apps/alerts/signals.py
  engine/apps/api/serializers/alert.py
  engine/apps/api/serializers/alert_group.py
  engine/apps/api/serializers/alerts_field_cache_buster_mixin.py
  engine/apps/public_api/serializers/alerts.py
  engine/apps/public_api/serializers/incidents.py
  engine/apps/user_management/migrations/0011_auto_20230411_1358.py
  engine/apps/user_management/models/organization.py
  engine/apps/user_management/signals.py
  engine/apps/user_management/sync.py
  engine/apps/user_management/tests/test_sync.py
  engine/common/constants/alert_group_restrictions.py
  grafana-plugin/src/PluginPage.tsx
  grafana-plugin/src/containers/AlertReceiveChannelCard/AlertReceiveChannelCard.module.css
  grafana-plugin/src/containers/AlertReceiveChannelCard/AlertReceiveChannelCard.module.scss
  grafana-plugin/src/containers/AlertReceiveChannelCard/AlertReceiveChannelCard.tsx
  grafana-plugin/src/containers/Alerts/Alerts.module.scss
  grafana-plugin/src/containers/Alerts/Alerts.tsx
  grafana-plugin/src/containers/EscalationVariants/EscalationVariants.tsx
  grafana-plugin/src/containers/IRMBanner/IRMBanner.tsx
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.test.tsx
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.types.ts
  grafana-plugin/src/models/alertgroup/alertgroup.ts
  grafana-plugin/src/models/alertgroup/alertgroup.types.ts
  grafana-plugin/src/navbar/Header/Header.module.scss
  grafana-plugin/src/navbar/Header/Header.tsx
  grafana-plugin/src/pages/incident/Incident.helpers.tsx
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/incident/parts/PagedUsers.tsx
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/state/rootBaseStore/index.ts
Labels: pr:no public docs

#1749 fix small bug in IRMBanner rendering logic
  grafana-plugin/src/containers/IRMBanner/IRMBanner.tsx
  grafana-plugin/src/models/alertgroup/alertgroup.ts
  grafana-plugin/src/pages/incidents/Incidents.tsx
Labels: pr:no changelog, pr:no public docs

#1754 Fix responses context when no response
  engine/apps/webhooks/models/webhook.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
Labels: pr:no changelog, pr:no public docs

#1757 Fix insight_logs exceptions
  engine/apps/api/views/telegram_channels.py
  engine/apps/api/views/user.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/slack/models/slack_team_identity.py
  engine/apps/slack/views.py
  engine/apps/social_auth/pipeline.py
  engine/apps/telegram/models/connectors/channel.py
  engine/apps/telegram/models/verification/channel.py
  engine/apps/telegram/models/verification/personal.py
  engine/apps/user_management/models/organization.py
  engine/common/insight_log/__init__.py
  engine/common/insight_log/chatops_insight_logs.py
Labels: pr:no changelog, pr:no public docs

#1386 Add option to use helm hook for migration job
  CHANGELOG.md
  helm/oncall/Chart.yaml
  helm/oncall/templates/engine/job-migrate.yaml
  helm/oncall/values.yaml
Labels: pr:no public docs

#1764 PD migrator: ignore 404s on delete + delete ONCALL_DEFAULT_CONTACT_METHOD
  tools/pagerduty-migrator/README.md
  tools/pagerduty-migrator/migrator/__main__.py
  tools/pagerduty-migrator/migrator/config.py
  tools/pagerduty-migrator/migrator/oncall_api_client.py
  tools/pagerduty-migrator/migrator/report.py
  tools/pagerduty-migrator/migrator/resources/notification_rules.py
Labels: pr:no changelog, pr:no public docs

#1715 Added preview and migration API endpoints for route migration from regex into jinja2
  CHANGELOG.md
  engine/apps/api/serializers/channel_filter.py
  engine/apps/api/tests/test_channel_filter.py
  engine/apps/api/views/channel_filter.py
  engine/common/jinja_templater/filters.py
  engine/common/jinja_templater/jinja_template_env.py
  engine/common/tests/test_apply_jinja_template.py
Labels: pr:no public docs

#1755 Add endpoints to start and stop maintenance in alert receive channel …
  CHANGELOG.md
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/views/alert_receive_channel.py
  engine/apps/api/views/maintenance.py
Labels: pr:no public docs

#1756 Allow use of dynamic payloads in alert receive channels preview templ…
  CHANGELOG.md
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/views/alert_group.py
  engine/apps/api/views/alert_receive_channel.py
  engine/common/api_helpers/mixins.py
Labels: pr:no public docs

#1759 Add is_default fields to templates, remove WritableSerialiserMethodFi…
  CHANGELOG.md
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/tests/test_alert_receive_channel_template.py
  engine/common/api_helpers/custom_fields.py
Labels: pr:no public docs

#1698 Add new field description_short to private and public api
  CHANGELOG.md
  engine/apps/alerts/migrations/0012_alertreceivechannel_description_short.py
  engine/apps/alerts/migrations/0013_merge_20230418_0336.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/public_api/serializers/integrations.py
  engine/apps/public_api/tests/test_integrations.py
Labels: pr:no public docs

#1770 move alert_group.is_restricted to alert_receive_channel.restricted_at
  CHANGELOG.md
  engine/apps/alerts/migrations/0012_auto_20230406_1010.py
  engine/apps/alerts/migrations/0014_alertreceivechannel_restricted_at.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/models/alert_receive_channel.py
Labels: pr:no public docs

#1776 Fix templates bug
  engine/apps/api/serializers/alert_receive_channel.py
Labels: pr:no changelog, pr:no public docs

#1773 v1.2.12
  .gitignore
  CHANGELOG.md
  engine/apps/alerts/migrations/0012_alertreceivechannel_description_short.py
  engine/apps/alerts/migrations/0012_auto_20230406_1010.py
  engine/apps/alerts/migrations/0013_merge_20230418_0336.py
  engine/apps/alerts/migrations/0014_alertreceivechannel_restricted_at.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/models/channel_filter.py
  engine/apps/alerts/tests/test_alert_receiver_channel.py
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/serializers/channel_filter.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/tests/test_alert_receive_channel_template.py
  engine/apps/api/tests/test_channel_filter.py
  engine/apps/api/views/alert_group.py
  engine/apps/api/views/alert_receive_channel.py
  engine/apps/api/views/channel_filter.py
  engine/apps/api/views/maintenance.py
  engine/apps/api/views/telegram_channels.py
  engine/apps/api/views/user.py
  engine/apps/public_api/serializers/integrations.py
  engine/apps/public_api/tests/test_integrations.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/slack/models/slack_team_identity.py
  engine/apps/slack/views.py
  engine/apps/social_auth/pipeline.py
  engine/apps/telegram/models/connectors/channel.py
  engine/apps/telegram/models/verification/channel.py
  engine/apps/telegram/models/verification/personal.py
  engine/apps/user_management/models/organization.py
  engine/apps/webhooks/models/webhook.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
  engine/common/api_helpers/custom_fields.py
  engine/common/api_helpers/mixins.py
  engine/common/exceptions/exceptions.py
  engine/common/insight_log/__init__.py
  engine/common/insight_log/chatops_insight_logs.py
  engine/common/insight_log/insight_logs_enabled_check.py
  engine/common/insight_log/maintenance_insight_log.py
  engine/common/insight_log/resource_insight_logs.py
  engine/common/jinja_templater/filters.py
  engine/common/jinja_templater/jinja_template_env.py
  engine/common/tests/test_apply_jinja_template.py
  helm/oncall/templates/engine/job-migrate.yaml
  helm/oncall/values.yaml
  tools/pagerduty-migrator/README.md
  tools/pagerduty-migrator/migrator/__main__.py
  tools/pagerduty-migrator/migrator/config.py
  tools/pagerduty-migrator/migrator/oncall_api_client.py
  tools/pagerduty-migrator/migrator/report.py
  tools/pagerduty-migrator/migrator/resources/notification_rules.py
Labels: pr:no public docs

#1777 Update PD migrator docs
  tools/pagerduty-migrator/README.md
Labels: pr:no changelog, pr:no public docs

#1743 Add mine filter to schedules listing
  CHANGELOG.md
  engine/apps/api/tests/test_schedules.py
  engine/apps/api/views/schedule.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_on_call_schedule.py
  grafana-plugin/src/components/SchedulesFilters/SchedulesFilters.tsx
  grafana-plugin/src/components/SchedulesFilters/SchedulesFilters.types.ts
  grafana-plugin/src/models/schedule/schedule.ts
  grafana-plugin/src/pages/schedules/Schedules.tsx
Labels: pr:no public docs

#1784 Update upcoming shift endpoint to return a list
  engine/apps/api/tests/test_user.py
  engine/apps/api/views/user.py
  engine/apps/schedules/tests/test_on_call_schedule.py
Labels: pr:no changelog, pr:no public docs

#1783 Rework schedule ical export
  CHANGELOG.md
  engine/apps/api/views/schedule.py
  engine/apps/public_api/tests/test_schedule_export.py
  engine/apps/public_api/views/schedules.py
  engine/apps/schedules/constants.py
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/migrations/0011_oncallschedule_cached_ical_final_schedule.py
  engine/apps/schedules/models/custom_on_call_shift.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tasks/__init__.py
  engine/apps/schedules/tasks/refresh_ical_files.py
  engine/apps/schedules/tests/test_on_call_schedule.py
  engine/settings/base.py
Labels: pr:no public docs

#1753 Webhooks 2 - Add copy ID to clipboard buttons
  engine/apps/api/views/features.py
  grafana-plugin/src/containers/AlertReceiveChannelCard/AlertReceiveChannelCard.tsx
  grafana-plugin/src/containers/AlertRules/AlertRules.tsx
  grafana-plugin/src/pages/outgoing_webhooks_2/OutgoingWebhooks2.tsx
  grafana-plugin/src/state/features.ts
Labels: pr:no changelog, pr:no public docs

#1768 Add unacknowledge trigger for new webhooks
  engine/apps/webhooks/migrations/0004_auto_20230418_0109.py
  engine/apps/webhooks/models/webhook.py
  engine/apps/webhooks/tasks/alert_group_status.py
  engine/apps/webhooks/tasks/trigger_webhook.py
  engine/apps/webhooks/tests/test_alert_group_status_change.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
  grafana-plugin/src/containers/OutgoingWebhook2Form/OutgoingWebhook2Form.config.tsx
Labels: pr:no changelog, pr:no public docs

#1785 Use shift tz for web-created events
  CHANGELOG.md
  engine/apps/api/tests/test_user.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_on_call_schedule.py
Labels: pr:no public docs

#1787 Merge dev to main
  CHANGELOG.md
  engine/apps/api/tests/test_schedules.py
  engine/apps/api/tests/test_user.py
  engine/apps/api/views/features.py
  engine/apps/api/views/schedule.py
  engine/apps/api/views/user.py
  engine/apps/public_api/tests/test_schedule_export.py
  engine/apps/public_api/views/schedules.py
  engine/apps/schedules/constants.py
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/migrations/0011_oncallschedule_cached_ical_final_schedule.py
  engine/apps/schedules/models/custom_on_call_shift.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tasks/__init__.py
  engine/apps/schedules/tasks/refresh_ical_files.py
  engine/apps/schedules/tests/test_on_call_schedule.py
  engine/apps/webhooks/migrations/0004_auto_20230418_0109.py
  engine/apps/webhooks/models/webhook.py
  engine/apps/webhooks/tasks/alert_group_status.py
  engine/apps/webhooks/tasks/trigger_webhook.py
  engine/apps/webhooks/tests/test_alert_group_status_change.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
  engine/settings/base.py
  grafana-plugin/src/components/SchedulesFilters/SchedulesFilters.tsx
  grafana-plugin/src/components/SchedulesFilters/SchedulesFilters.types.ts
  grafana-plugin/src/containers/AlertReceiveChannelCard/AlertReceiveChannelCard.tsx
  grafana-plugin/src/containers/AlertRules/AlertRules.tsx
  grafana-plugin/src/containers/OutgoingWebhook2Form/OutgoingWebhook2Form.config.tsx
  grafana-plugin/src/models/schedule/schedule.ts
  grafana-plugin/src/pages/outgoing_webhooks_2/OutgoingWebhooks2.tsx
  grafana-plugin/src/pages/schedules/Schedules.tsx
  grafana-plugin/src/state/features.ts
  tools/pagerduty-migrator/README.md
Labels: pr:no public docs

#1766 Fix documentation links
  README.md
  dev/README.md
  engine/apps/base/models/live_setting.py
  engine/settings/base.py
  grafana-plugin/src/README.md
  grafana-plugin/src/utils/consts.ts
Labels: pr:no changelog, pr:no public docs

#1794 Fix team update
  CHANGELOG.md
  engine/apps/api/tests/test_team.py
  engine/apps/api/views/team.py
Labels: pr:no public docs

#1795 v1.2.14 changelog
  CHANGELOG.md
Labels: pr:no changelog, pr:no public docs

#1799 Make screenshots bigger in README.md
  README.md
Labels: pr:no changelog, pr:no public docs

#1789 Fix helm hook for migration job
  CHANGELOG.md
  helm/oncall/templates/engine/job-migrate.yaml
Labels: pr:no public docs

#1782 Return is_based_on_alertmanager for alert_receive_channel in private api
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/tests/test_alert_receive_channel_template.py
Labels: pr:no changelog, pr:no public docs

#1802 Optimise alert groups private api endpoint
  engine/apps/api/views/alert_group.py
Labels: pr:no changelog, pr:no public docs

#1798 Add users_to_be_notified to new webhooks payload
  engine/apps/alerts/signals.py
  engine/apps/alerts/tasks/distribute_alert.py
  engine/apps/webhooks/listeners.py
  engine/apps/webhooks/signals.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
  engine/apps/webhooks/utils.py
Labels: pr:no changelog, pr:no public docs

#1435 Extend twilio secrets
  CHANGELOG.md
  helm/oncall/templates/_env.tpl
  helm/oncall/values.yaml
Labels: pr:no public docs

#1786 Reuse web templates in other templates
  CHANGELOG.md
  engine/apps/alerts/incident_appearance/templaters/alert_templater.py
Labels: pr:no public docs

#1742 Use centralized make-docs script from Writers' Toolkit
  docs/Makefile
  docs/docs.mk
  docs/make-docs
  docs/variables.mk
Labels: pr:no changelog

#1807 Add final schedule export refresh note
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/models/on_call_schedule.py
  grafana-plugin/src/containers/ScheduleIcalLink/ScheduleIcalLink.tsx
  grafana-plugin/src/containers/UserSettings/parts/connectors/ICalConnector.tsx
Labels: pr:no changelog, pr:no public docs

#1812 Update ci jobs to node:14.17.0-buster from node:14.17.0-stretch
  .drone.yml
Labels: pr:no changelog, pr:no public docs

#1813 Add is_legacy column to handle webhook migration
  engine/apps/api/serializers/webhook.py
  engine/apps/api/tests/test_webhooks.py
  engine/apps/webhooks/migrations/0005_webhook_is_legacy.py
  engine/apps/webhooks/models/webhook.py
  engine/apps/webhooks/tests/test_webhook.py
  grafana-plugin/src/containers/OutgoingWebhook2Form/OutgoingWebhook2Form.tsx
  grafana-plugin/src/models/outgoing_webhook_2/outgoing_webhook_2.types.ts
Labels: pr:no changelog, pr:no public docs

#1808 Enable final schedule exports
  CHANGELOG.md
  engine/apps/schedules/ical_utils.py
Labels: pr:no public docs

#1822 Add 2, 3 and 6 hours silence options
  CHANGELOG.md
  engine/apps/alerts/models/alert_group.py
Labels: pr:no public docs

#1809 Optimize duplicate queries occurring in AlertGroupFilter
  CHANGELOG.md
  engine/apps/api/views/alert_group.py
Labels: pr:no public docs

#1828 Rework schedule related users, add endpoint
  CHANGELOG.md
  engine/apps/api/serializers/user.py
  engine/apps/api/tests/test_schedules.py
  engine/apps/api/views/schedule.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_on_call_schedule.py
Labels: pr:no public docs

#1829 Webhook 2 improvements and fixes
  engine/apps/api/tests/test_webhooks.py
  engine/apps/webhooks/migrations/0006_auto_20230426_1631.py
  engine/apps/webhooks/models/webhook.py
  engine/apps/webhooks/tasks/alert_group_status.py
  engine/apps/webhooks/tasks/trigger_webhook.py
  engine/apps/webhooks/tests/test_alert_group_status_change.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
  engine/apps/webhooks/utils.py
  engine/settings/base.py
  grafana-plugin/src/containers/OutgoingWebhook2Form/OutgoingWebhook2Form.config.tsx
  grafana-plugin/src/containers/OutgoingWebhook2Status/OutgoingWebhook2Status.tsx
Labels: pr:no changelog, pr:no public docs

#1832 Restore removed parameter
  engine/apps/webhooks/tasks/trigger_webhook.py
Labels: pr:no changelog, pr:no public docs

#1803 Use subquery for mine alert groups
  engine/apps/api/views/alert_group.py
Labels: pr:no changelog, pr:no public docs

#1841 Fix flaky Slack test
  engine/apps/slack/tests/factories.py
Labels: pr:no changelog, pr:no public docs

#1850 Update dev directory .gitignore
  dev/.gitignore
Labels: pr:no changelog, pr:no public docs
