Repository grafana/oncall, pull requests merged in 2023-03, with the labels that each got.

#1427 Release v1.1.30
  CHANGELOG.md
  engine/apps/alerts/tasks/notify_ical_schedule_shift.py
  engine/apps/api/serializers/alert_group.py
  engine/apps/api/tests/test_alert_group.py
  engine/apps/api/tests/test_schedules.py
  engine/apps/api/views/schedule.py
  engine/apps/auth_token/auth.py
  engine/apps/grafana_plugin/views/sync.py
  engine/apps/integrations/mixins/alert_channel_defining_mixin.py
  engine/apps/public_api/tests/test_schedule_export.py
  engine/apps/public_api/tests/test_schedules.py
  engine/apps/schedules/models/custom_on_call_shift.py
  engine/apps/schedules/tasks/refresh_ical_files.py
  engine/apps/schedules/tests/test_custom_on_call_shift.py
  engine/apps/schedules/tests/test_tasks_refresh_ical_files.py
  engine/settings/base.py
  grafana-plugin/package.json
  grafana-plugin/src/components/Modal/Modal.module.css
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/components/UserGroups/UserGroups.module.css
  grafana-plugin/src/containers/EscalationVariants/parts/EscalationVariantsPopup.tsx
  grafana-plugin/src/containers/RotationForm/RotationForm.module.css
  grafana-plugin/src/containers/RotationForm/RotationForm.tsx
  grafana-plugin/src/containers/ScheduleSlot/ScheduleSlot.module.css
  grafana-plugin/src/containers/ScheduleSlot/ScheduleSlot.tsx
  grafana-plugin/src/containers/UserSettings/parts/connectors/ICalConnector.tsx
  grafana-plugin/src/containers/UserSettings/parts/tabs/PhoneVerification/PhoneVerification.tsx
  grafana-plugin/src/img/grafanaGlobalStyles.css
  grafana-plugin/src/models/schedule/schedule.ts
  grafana-plugin/src/models/user/user.ts
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/integrations/Integrations.tsx
  grafana-plugin/src/pages/schedule/Schedule.module.css
  grafana-plugin/src/pages/schedule/Schedule.tsx
  grafana-plugin/src/pages/schedules/Schedules.module.css
  grafana-plugin/src/pages/schedules/Schedules.tsx
  grafana-plugin/src/pages/settings/tabs/ChatOps/ChatOps.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/state/plugin/index.ts
  grafana-plugin/src/state/plugin/plugin.test.ts
  grafana-plugin/src/state/rootBaseStore/index.ts
  grafana-plugin/src/utils/consts.ts
  grafana-plugin/src/utils/index.ts
  grafana-plugin/yarn.lock
  tools/pagerduty-migrator/migrator/__main__.py
  tools/pagerduty-migrator/migrator/resources/schedules.py
  tools/pagerduty-migrator/migrator/tests/test_schedules.py
Labels: pr:no changelog, pr:no public docs

#1429 Release v1.1.31
  CHANGELOG.md
  docs/sources/oncall-api-reference/integrations.md
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/tests/test_alert_receive_channel_template.py
  engine/apps/api/views/preview_template_options.py
  engine/apps/base/messaging.py
  engine/apps/base/models/user_notification_policy.py
  engine/apps/mobile_app/backend.py
  engine/apps/public_api/serializers/integrations.py
  engine/apps/public_api/serializers/routes.py
  engine/apps/public_api/tests/test_integrations.py
  engine/common/api_helpers/mixins.py
  engine/settings/dev.py
Labels: pr:no changelog, pr:no public docs

#1419 1387 source link redesign
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/incidents/Incidents.tsx
Labels: pr:no changelog, pr:no public docs

#1406 Schedule Filters tweaks
  CHANGELOG.md
  grafana-plugin/src/components/SchedulesFilters/SchedulesFilters.tsx
  grafana-plugin/src/components/SchedulesFilters/SchedulesFilters.types.ts
  grafana-plugin/src/models/schedule/schedule.ts
  grafana-plugin/src/models/user/user.ts
  grafana-plugin/src/pages/schedules/Schedules.tsx
Labels: pr:no public docs

#1437 Fix pagination issue when searching schedules
  CHANGELOG.md
  engine/apps/api/tests/test_schedules.py
  engine/apps/api/views/schedule.py
Labels: pr:no public docs

#1438 Dev to main
  CHANGELOG.md
  engine/apps/api/tests/test_schedules.py
  engine/apps/api/views/schedule.py
  grafana-plugin/src/components/SchedulesFilters/SchedulesFilters.tsx
  grafana-plugin/src/components/SchedulesFilters/SchedulesFilters.types.ts
  grafana-plugin/src/models/schedule/schedule.ts
  grafana-plugin/src/models/user/user.ts
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/schedules/Schedules.tsx
Labels: pr:no public docs

#1450 Incident -> Alert Group wording
  engine/apps/slack/scenarios/distribute_alerts.py
Labels: pr:no changelog, pr:no public docs

#1422 fix for #1273, added component for showing permission restricted acce…
  CHANGELOG.md
  grafana-plugin/src/components/AlertTemplates/AlertTemplatesForm.tsx
  grafana-plugin/src/components/NewScheduleSelector/NewScheduleSelector.tsx
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/components/Policy/NotificationPolicy.tsx
  grafana-plugin/src/containers/AlertRules/AlertRules.tsx
  grafana-plugin/src/containers/AlertRules/parts/connectors/SlackConnector.tsx
  grafana-plugin/src/containers/AlertRules/parts/connectors/TelegramConnector.tsx
  grafana-plugin/src/containers/ApiTokenSettings/ApiTokenSettings.tsx
  grafana-plugin/src/containers/AttachIncidentForm/AttachIncidentForm.tsx
  grafana-plugin/src/containers/EscalationChainSteps/EscalationChainSteps.tsx
  grafana-plugin/src/containers/EscalationVariants/EscalationVariants.tsx
  grafana-plugin/src/containers/GrafanaTeamSelect/GrafanaTeamSelect.tsx
  grafana-plugin/src/containers/HeartbeatModal/HeartbeatForm.tsx
  grafana-plugin/src/containers/IntegrationSettings/parts/Autoresolve.tsx
  grafana-plugin/src/containers/MaintenanceForm/MaintenanceForm.tsx
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.tsx
  grafana-plugin/src/containers/PersonalNotificationSettings/PersonalNotificationSettings.tsx
  grafana-plugin/src/containers/Rotations/Rotations.tsx
  grafana-plugin/src/containers/Rotations/ScheduleOverrides.tsx
  grafana-plugin/src/containers/ScheduleForm/ScheduleForm.tsx
  grafana-plugin/src/containers/TelegramIntegrationButton/TelegramIntegrationButton.tsx
  grafana-plugin/src/containers/UserSettings/parts/connectors/ICalConnector.tsx
  grafana-plugin/src/containers/UserSettings/parts/tabs/CloudPhoneSettings/CloudPhoneSettings.tsx
  grafana-plugin/src/containers/UserSettings/parts/tabs/PhoneVerification/PhoneVerification.tsx
  grafana-plugin/src/containers/UserSettings/parts/tabs/TelegramInfo/TelegramInfo.tsx
  grafana-plugin/src/containers/WithPermissionControl/WithPermissionControlDisplay.tsx
  grafana-plugin/src/containers/WithPermissionControl/WithPermissionControlTooltip.module.css
  grafana-plugin/src/containers/WithPermissionControl/WithPermissionControlTooltip.tsx
  grafana-plugin/src/containers/WithPermissionControl2/WithPermissionControl.tsx
  grafana-plugin/src/pages/escalation-chains/EscalationChains.tsx
  grafana-plugin/src/pages/incident/Incident.helpers.tsx
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/incident/parts/PagedUsers.tsx
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/incidents/parts/IncidentDropdown.tsx
  grafana-plugin/src/pages/incidents/parts/SilenceButtonCascader.tsx
  grafana-plugin/src/pages/incidents/parts/SilenceSelect.tsx
  grafana-plugin/src/pages/integrations/Integrations.tsx
  grafana-plugin/src/pages/maintenance/Maintenance.tsx
  grafana-plugin/src/pages/outgoing_webhooks/OutgoingWebhooks.tsx
  grafana-plugin/src/pages/routes.tsx
  grafana-plugin/src/pages/schedules/Schedules.tsx
  grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/SlackSettings/SlackSettings.tsx
  grafana-plugin/src/pages/settings/tabs/LiveSettings/LiveSettingsPage.tsx
  grafana-plugin/src/pages/settings/tabs/MainSettings/MainSettings.tsx
  grafana-plugin/src/pages/test/Test.module.css
  grafana-plugin/src/pages/test/Test.tsx
  grafana-plugin/src/pages/users/Users.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
Labels: pr:no public docs

#1445 Add validation of hostname for recapctha
  engine/apps/api/serializers/user.py
  engine/apps/api/tests/test_user.py
  engine/apps/api/views/user.py
  engine/apps/grafana_plugin/views/sync.py
  engine/common/recaptcha/__init__.py
  engine/common/recaptcha/recaptcha_v3.py
  engine/common/tests/test_recaptcha.py
  engine/requirements.txt
  engine/settings/base.py
Labels: pr:no changelog, pr:no public docs

#1458 Fix wording for cloud notifications
  grafana-plugin/src/containers/UserSettings/parts/tabs/CloudPhoneSettings/CloudPhoneSettings.tsx
  grafana-plugin/src/pages/settings/tabs/Cloud/CloudPage.tsx
Labels: pr:no changelog, pr:no public docs

#1454 PD migrator: migrate overrides
  engine/apps/public_api/serializers/on_call_shifts.py
  engine/apps/public_api/tests/test_on_call_shifts.py
  tools/pagerduty-migrator/migrator/__main__.py
  tools/pagerduty-migrator/migrator/resources/schedules.py
  tools/pagerduty-migrator/migrator/tests/test_schedules.py
Labels: pr:no changelog, pr:no public docs

#1455 PD migrator: fix layer levels
  tools/pagerduty-migrator/migrator/resources/schedules.py
  tools/pagerduty-migrator/migrator/tests/test_schedules.py
Labels: pr:no changelog, pr:no public docs

#1461 Schedule quality backend improvements
  engine/apps/schedules/quality_score.py
  engine/apps/schedules/tests/test_quality_score.py
Labels: pr:no changelog, pr:no public docs

#809 Refactor get_user_verbal_for_team_for_slack.
  engine/apps/alerts/incident_appearance/renderers/slack_renderer.py
  engine/apps/alerts/incident_log_builder/incident_log_builder.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/models/alert_group_log_record.py
  engine/apps/alerts/models/maintainable_object.py
  engine/apps/alerts/models/resolution_note.py
  engine/apps/alerts/tasks/invite_user_to_join_incident.py
  engine/apps/alerts/tests/test_alert_group_renderer.py
  engine/apps/base/models/user_notification_policy_log_record.py
  engine/apps/slack/models/slack_message.py
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/slack/scenarios/escalation_delivery.py
  engine/apps/slack/scenarios/manual_incident.py
  engine/apps/slack/scenarios/notification_delivery.py
  engine/apps/slack/scenarios/resolution_note.py
  engine/apps/slack/scenarios/schedules.py
  engine/apps/slack/scenarios/step_mixins.py
  engine/apps/slack/tests/test_scenario_steps/test_resolution_note.py
  engine/apps/telegram/tests/test_message_renderer.py
  engine/apps/user_management/models/user.py
Labels: pr:no changelog, pr:no public docs

#881 Remove OSS_INSTALATION env var
  dev/.env.dev.example
  engine/apps/api/serializers/user.py
  engine/apps/api/tests/test_features.py
  engine/apps/api/views/features.py
  engine/apps/api/views/user.py
  engine/apps/grafana_plugin/apps.py
  engine/apps/grafana_plugin/tests/test_app_config.py
  engine/apps/mobile_app/tasks.py
  engine/apps/mobile_app/tests/test_notify_user.py
  engine/engine/urls.py
  engine/settings/base.py
Labels: pr:no changelog, pr:no public docs

#1473 Chore: add integrity hash to templates
  engine/apps/integrations/templates/heartbeat_link.html
  engine/apps/integrations/templates/integration_link.html
Labels: pr:no changelog, pr:no public docs

#1466 Rework alert group mine filter query
  engine/apps/api/views/alert_group.py
Labels: pr:no changelog, pr:no public docs

#1472 Chat-ops fix
  grafana-plugin/src/pages/settings/tabs/ChatOps/ChatOps.tsx
Labels: pr:no changelog, pr:no public docs

#1474 Prohibit creating & updating past overrides
  CHANGELOG.md
  engine/apps/api/serializers/on_call_shifts.py
  engine/apps/api/tests/test_oncall_shift.py
Labels: pr:no public docs

#1484 remove mobile app feature flag
  CHANGELOG.md
  engine/apps/api/tests/test_features.py
  engine/apps/api/views/features.py
  engine/apps/mobile_app/tests/test_fcm_relay.py
  engine/conftest.py
  engine/engine/urls.py
  engine/settings/base.py
  grafana-plugin/src/containers/UserSettings/UserSettings.tsx
  grafana-plugin/src/containers/UserSettings/parts/connectors/MobileAppConnector.tsx
  grafana-plugin/src/pages/settings/tabs/Cloud/CloudPage.tsx
  grafana-plugin/src/state/features.ts
Labels: pr:no public docs

#1485 Hide edit button for default route
  grafana-plugin/src/containers/AlertRules/AlertRules.tsx
Labels: pr:no changelog, pr:no public docs

#1482 add unique idx on user column in mobileapp authtoken table
  CHANGELOG.md
  engine/apps/mobile_app/migrations/0002_alter_mobileappauthtoken_user.py
  engine/apps/mobile_app/models.py
  engine/apps/mobile_app/tests/test_mobile_app_auth_token.py
  engine/conftest.py
Labels: pr:no public docs

#1498 FIx insight_logs for mobile app backend
  engine/apps/alerts/models/channel_filter.py
  engine/common/insight_log/chatops_insight_logs.py
Labels: pr:no changelog, pr:no public docs

#1500 Fix involved users filter, add missing test
  CHANGELOG.md
  engine/apps/api/tests/test_alert_group.py
  engine/apps/api/views/alert_group.py
Labels: pr:no public docs

#1499 grafana ticketing 81244 : Emails fails if the alert title has a newline char
  CHANGELOG.md
  engine/apps/email/alert_rendering.py
Labels: pr:no public docs

#1510 Add test for newlines in email subject
  engine/apps/email/tests/test_notify_user.py
Labels: pr:no changelog, pr:no public docs

#1481 Fix ratelimit message: incident -> alert groups
  engine/apps/slack/tasks.py
Labels: pr:no changelog, pr:no public docs

#1469 Check stack cluster for insight_logs
  engine/apps/grafana_plugin/helpers/client.py
  engine/common/insight_log/insight_logs_enabled_check.py
Labels: pr:no changelog, pr:no public docs

#1516 Update dev/README.md
  dev/README.md
Labels: pr:no changelog, pr:no public docs

#1101 Add webhooks app and initial models
  engine/apps/webhooks/admin.py
  engine/apps/webhooks/apps.py
  engine/apps/webhooks/migrations/0001_initial.py
  engine/apps/webhooks/migrations/__init__.py
  engine/apps/webhooks/models/__init__.py
  engine/apps/webhooks/models/webhook.py
  engine/apps/webhooks/tests/__init__.py
  engine/apps/webhooks/tests/factories.py
  engine/apps/webhooks/tests/test_webhook.py
  engine/apps/webhooks/utils.py
  engine/conftest.py
  engine/settings/base.py
Labels: pr:no changelog, pr:no public docs

#1470 improve e2e tests authentication flow
  grafana-plugin/.gitignore
  grafana-plugin/integration-tests/alerts/onCallSchedule.test.ts
  grafana-plugin/integration-tests/alerts/sms.test.ts
  grafana-plugin/integration-tests/globalSetup.ts
  grafana-plugin/integration-tests/schedules/addOverride.test.ts
  grafana-plugin/integration-tests/utils/alertGroup.ts
  grafana-plugin/integration-tests/utils/configurePlugin.ts
  grafana-plugin/integration-tests/utils/constants.ts
  grafana-plugin/integration-tests/utils/escalationChain.ts
  grafana-plugin/integration-tests/utils/index.ts
  grafana-plugin/integration-tests/utils/integrations.ts
  grafana-plugin/integration-tests/utils/login.ts
  grafana-plugin/integration-tests/utils/navigation.ts
  grafana-plugin/integration-tests/utils/schedule.ts
  grafana-plugin/integration-tests/utils/userSettings.ts
  grafana-plugin/playwright.config.ts
Labels: pr:no changelog, pr:no public docs

#1524 Add initial webhooks internal plugin API
  engine/apps/api/serializers/webhook.py
  engine/apps/api/tests/test_webhooks.py
  engine/apps/api/urls.py
  engine/apps/api/views/webhooks.py
  engine/common/api_helpers/utils.py
Labels: pr:no changelog, pr:no public docs

#1449 Prevent redirecting to Integrations if you navigated away to a different screen
  CHANGELOG.md
  grafana-plugin/src/pages/integrations/Integrations.tsx
Labels: pr:no public docs

#1324 Rares/score quality
  CHANGELOG.md
  grafana-plugin/src/components/ScheduleCounter/ScheduleCounter.module.css
  grafana-plugin/src/components/ScheduleCounter/ScheduleCounter.tsx
  grafana-plugin/src/components/ScheduleQuality/ScheduleQuality.module.css
  grafana-plugin/src/components/ScheduleQuality/ScheduleQuality.module.scss
  grafana-plugin/src/components/ScheduleQuality/ScheduleQuality.tsx
  grafana-plugin/src/components/ScheduleQualityDetails/ScheduleQualityDetails.module.scss
  grafana-plugin/src/components/ScheduleQualityDetails/ScheduleQualityDetails.tsx
  grafana-plugin/src/components/ScheduleQualityDetails/ScheduleQualityProgressBar.module.scss
  grafana-plugin/src/components/ScheduleQualityDetails/ScheduleQualityProgressBar.test.tsx
  grafana-plugin/src/components/ScheduleQualityDetails/ScheduleQualityProgressBar.tsx
  grafana-plugin/src/components/ScheduleQualityDetails/__snapshots__/ScheduleQualityProgressBar.test.tsx.snap
  grafana-plugin/src/components/Tag/Tag.module.css
  grafana-plugin/src/components/Tag/Tag.tsx
  grafana-plugin/src/components/Text/Text.module.scss
  grafana-plugin/src/components/Text/Text.tsx
  grafana-plugin/src/containers/AlertRules/parts/index.tsx
  grafana-plugin/src/containers/EscalationChainSteps/EscalationChainSteps.tsx
  grafana-plugin/src/containers/RotationForm/ScheduleOverrideForm.tsx
  grafana-plugin/src/models/schedule/schedule.ts
  grafana-plugin/src/models/schedule/schedule.types.ts
  grafana-plugin/src/pages/incident/Incident.helpers.tsx
  grafana-plugin/src/pages/incidents/parts/IncidentDropdown.tsx
  grafana-plugin/src/pages/schedule/Schedule.module.css
  grafana-plugin/src/pages/schedule/Schedule.tsx
  grafana-plugin/src/pages/schedules/Schedules.tsx
  grafana-plugin/src/style/utils.css
  grafana-plugin/src/style/vars.css
  grafana-plugin/src/utils/DOM.ts
Labels: pr:no public docs

#1471 Improve direct user paging
  CHANGELOG.md
  grafana-plugin/src/components/ManualAlertGroup/ManualAlertGroup.config.ts
  grafana-plugin/src/components/ManualAlertGroup/ManualAlertGroup.tsx
  grafana-plugin/src/components/PluginLink/PluginLink.tsx
  grafana-plugin/src/containers/EscalationVariants/EscalationVariants.module.scss
  grafana-plugin/src/containers/EscalationVariants/EscalationVariants.tsx
  grafana-plugin/src/containers/EscalationVariants/parts/EscalationVariantsPopup.tsx
  grafana-plugin/src/containers/UserWarningModal/UserWarning.module.scss
  grafana-plugin/src/containers/UserWarningModal/UserWarning.tsx
  grafana-plugin/src/pages/incident/Incident.module.scss
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/incident/parts/PagedUsers.tsx
Labels: pr:no public docs

#1526 Add inital UI for new webhooks
  grafana-plugin/src/containers/OutgoingWebhook2Form/OutgoingWebhook2Form.config.ts
  grafana-plugin/src/containers/OutgoingWebhook2Form/OutgoingWebhook2Form.module.css
  grafana-plugin/src/containers/OutgoingWebhook2Form/OutgoingWebhook2Form.tsx
  grafana-plugin/src/containers/OutgoingWebhook2Status/OutgoingWebhook2Status.tsx
  grafana-plugin/src/models/outgoing_webhook_2/outgoing_webhook_2.ts
  grafana-plugin/src/models/outgoing_webhook_2/outgoing_webhook_2.types.ts
  grafana-plugin/src/pages/index.tsx
  grafana-plugin/src/pages/outgoing_webhooks_2/OutgoingWebhooks2.module.css
  grafana-plugin/src/pages/outgoing_webhooks_2/OutgoingWebhooks2.tsx
  grafana-plugin/src/pages/routes.tsx
  grafana-plugin/src/plugin.json
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/state/rootBaseStore/index.ts
Labels: pr:no changelog, pr:no public docs

#1532 Quickfix for integrations
  grafana-plugin/src/pages/integrations/Integrations.tsx
Labels: pr:no changelog, pr:no public docs

#1533 Webhooks trigger tasks on alert group events
  engine/apps/webhooks/apps.py
  engine/apps/webhooks/listeners.py
  engine/apps/webhooks/signals.py
  engine/apps/webhooks/tasks/__init__.py
  engine/apps/webhooks/tasks/alert_group_status.py
  engine/apps/webhooks/tasks/trigger_webhook.py
  engine/apps/webhooks/tests/test_alert_group_status_change.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
  engine/apps/webhooks/utils.py
Labels: pr:no changelog, pr:no public docs

#1413 Add RBAC guidance to users and teams documentation
  docs/sources/configure-user-settings/_index.md
Labels: type/docs, pr:no changelog

#1541 Minor fix for schedule quality calculation methodology text
  grafana-plugin/src/components/ScheduleQualityDetails/ScheduleQualityDetails.tsx
Labels: pr:no changelog, pr:no public docs

#1534 Enable new webhooks preview per org
  engine/apps/api/tests/test_webhooks.py
  engine/apps/api/views/webhooks.py
Labels: pr:no changelog, pr:no public docs

#1535 Add alert group filter by escalation chain
  CHANGELOG.md
  engine/apps/api/serializers/escalation_chain.py
  engine/apps/api/tests/test_alert_group.py
  engine/apps/api/tests/test_escalation_chain.py
  engine/apps/api/views/alert_group.py
  engine/apps/api/views/escalation_chain.py
  grafana-plugin/integration-tests/utils/escalationChain.ts
Labels: pr:no public docs

#1544 Rework webhook trigger tasks checks and payload build
  CHANGELOG.md
  engine/apps/webhooks/tasks/alert_group_status.py
  engine/apps/webhooks/tasks/trigger_webhook.py
  engine/apps/webhooks/tests/test_alert_group_status_change.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
Labels: pr:no public docs

#1547 Merge dev to main
  CHANGELOG.md
  engine/apps/api/serializers/escalation_chain.py
  engine/apps/api/tests/test_alert_group.py
  engine/apps/api/tests/test_escalation_chain.py
  engine/apps/api/tests/test_webhooks.py
  engine/apps/api/views/alert_group.py
  engine/apps/api/views/escalation_chain.py
  engine/apps/api/views/webhooks.py
  engine/apps/webhooks/tasks/alert_group_status.py
  engine/apps/webhooks/tasks/trigger_webhook.py
  engine/apps/webhooks/tests/test_alert_group_status_change.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
  grafana-plugin/integration-tests/utils/escalationChain.ts
  grafana-plugin/src/components/ScheduleQualityDetails/ScheduleQualityDetails.tsx
Labels: pr:no public docs

#1546 add IS_OPEN_SOURCE env var to UI integration tests
  grafana-plugin/.env.example
  grafana-plugin/integration-tests/utils/configurePlugin.ts
  grafana-plugin/integration-tests/utils/constants.ts
Labels: pr:no changelog, pr:no public docs

#1554 Check for duplicated positions in TF escalation policies
  CHANGELOG.md
  engine/apps/public_api/serializers/escalation_policies.py
  engine/apps/public_api/tests/test_escalation_policies.py
Labels: pr:no public docs

#1555 PD migrator: add ability to migrate event rules
  tools/pagerduty-migrator/migrator/__main__.py
  tools/pagerduty-migrator/migrator/config.py
  tools/pagerduty-migrator/migrator/report.py
  tools/pagerduty-migrator/migrator/resources/rulesets.py
Labels: pr:no changelog, pr:no public docs

#1561 fix resolution note Slack rendering bug
  CHANGELOG.md
  engine/apps/slack/scenarios/resolution_note.py
Labels: pr:no public docs

#1565 update wording in some Slack messages which mention 'incident' instead of 'alert group'
  CHANGELOG.md
  engine/apps/slack/models/slack_message.py
  engine/apps/slack/scenarios/escalation_delivery.py
Labels: pr:no public docs

#1566 PD migrator: allow migrating inbound email integrations
  tools/pagerduty-migrator/README.md
  tools/pagerduty-migrator/migrator/resources/integrations.py
Labels: pr:no changelog, pr:no public docs

#1569 PD migrator: ignore deleted services in event rules
  tools/pagerduty-migrator/migrator/resources/rulesets.py
Labels: pr:no changelog, pr:no public docs

#1537 Prevent viewer from opening link to mobile app
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.tsx
  grafana-plugin/src/containers/UserSettings/parts/connectors/MobileAppConnector.tsx
Labels: pr:no changelog, pr:no public docs

#1529 Rares/1448 permissions
  CHANGELOG.md
  grafana-plugin/src/components/AlertTemplates/AlertTemplatesForm.module.css
  grafana-plugin/src/components/AlertTemplates/AlertTemplatesForm.tsx
  grafana-plugin/src/containers/IntegrationSettings/parts/Autoresolve.tsx
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/schedule/Schedule.tsx
Labels: pr:no public docs

#1576 update integration heartbeat description to use 'alert group' instead of 'incident'
  CHANGELOG.md
  grafana-plugin/src/containers/HeartbeatModal/HeartbeatForm.tsx
Labels: pr:no public docs

#1538 UI Tweaks on schedules
  grafana-plugin/src/components/ScheduleCounter/ScheduleCounter.module.css
  grafana-plugin/src/components/ScheduleCounter/ScheduleCounter.module.scss
  grafana-plugin/src/components/ScheduleCounter/ScheduleCounter.tsx
  grafana-plugin/src/components/ScheduleQuality/ScheduleQuality.module.scss
  grafana-plugin/src/components/ScheduleQuality/ScheduleQuality.tsx
  grafana-plugin/src/pages/schedule/Schedule.module.css
  grafana-plugin/src/pages/schedules/Schedules.tsx
  grafana-plugin/src/style/utils.css
Labels: pr:no changelog, pr:no public docs

#1577 1124 viewers are not allowed in rotations
  CHANGELOG.md
  grafana-plugin/src/components/UserGroups/UserGroups.tsx
Labels: pr:no changelog, pr:no public docs

#1424 319 telegram warning bug
  CHANGELOG.md
  grafana-plugin/src/components/Policy/NotificationPolicy.tsx
  grafana-plugin/src/containers/AlertRules/parts/index.tsx
  grafana-plugin/src/containers/PersonalNotificationSettings/PersonalNotificationSettings.tsx
  grafana-plugin/src/containers/TelegramIntegrationButton/TelegramIntegrationButton.tsx
  grafana-plugin/src/containers/UserSettings/UserSettings.tsx
  grafana-plugin/src/containers/UserSettings/parts/connectors/index.tsx
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/settings/tabs/ChatOps/ChatOps.tsx
  grafana-plugin/src/pages/users/Users.tsx
Labels: pr:no changelog, pr:no public docs

#1579 add e2e test that we have unique integrations
  grafana-plugin/integration-tests/integrations/uniqueIntegrationNames.test.ts
  grafana-plugin/integration-tests/utils/integrations.ts
  grafana-plugin/src/components/Text/Text.tsx
  grafana-plugin/src/containers/CreateAlertReceiveChannelContainer/CreateAlertReceiveChannelContainer.tsx
Labels: pr:no changelog, pr:no public docs

#1583 Add "make help" command
  Makefile
  dev/README.md
Labels: pr:no changelog, pr:no public docs

#1582 Add SLACK_INTEGRATION_MAINTENANCE env var
  engine/apps/api/views/auth.py
  engine/apps/slack/views.py
  engine/settings/base.py
  grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/SlackSettings/SlackSettings.tsx
Labels: pr:no changelog, pr:no public docs

#1580 Keep webhook responses data
  engine/apps/api/serializers/webhook.py
  engine/apps/api/tests/test_webhooks.py
  engine/apps/api/views/webhooks.py
  engine/apps/webhooks/listeners.py
  engine/apps/webhooks/migrations/0002_auto_20230320_1604.py
  engine/apps/webhooks/models/__init__.py
  engine/apps/webhooks/models/webhook.py
  engine/apps/webhooks/tasks/trigger_webhook.py
  engine/apps/webhooks/tests/factories.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
  engine/apps/webhooks/utils.py
  engine/conftest.py
  grafana-plugin/src/containers/OutgoingWebhook2Form/OutgoingWebhook2Form.config.ts
  grafana-plugin/src/containers/OutgoingWebhook2Status/OutgoingWebhook2Status.tsx
  grafana-plugin/src/models/outgoing_webhook_2/outgoing_webhook_2.types.ts
Labels: pr:no changelog, pr:no public docs

#1591 Fix teams duplication and user list permission control
  engine/apps/user_management/models/user.py
  grafana-plugin/src/containers/TeamsList/TeamsList.tsx
Labels: pr:no changelog, pr:no public docs

#1571 Mobile app settings backend
  engine/apps/mobile_app/migrations/0003_mobileappusersettings.py
  engine/apps/mobile_app/models.py
  engine/apps/mobile_app/serializers.py
  engine/apps/mobile_app/tasks.py
  engine/apps/mobile_app/tests/test_notify_user.py
  engine/apps/mobile_app/tests/test_user_settings.py
  engine/apps/mobile_app/urls.py
  engine/apps/mobile_app/views.py
  engine/conftest.py
Labels: pr:no changelog, pr:no public docs

#1567 Inbound email OSS docs minor improvements
  docs/sources/open-source/_index.md
Labels: pr:no changelog

#1610 update pr template
  .github/pull_request_template.md
Labels: pr:no changelog, pr:no public docs

#1572 Update wording when creating an integration
  CHANGELOG.md
  grafana-plugin/src/containers/AlertRules/AlertRules.tsx
Labels: pr:no public docs

#1398 use CustomURLValidator in custom_button
  CHANGELOG.md
  engine/apps/api/serializers/custom_button.py
  engine/apps/api/tests/test_custom_button.py
  engine/common/api_helpers/utils.py
  engine/common/tests/test_urlvalidator_without_tld.py
Labels: pr:no public docs

#1606 Update team management docs
  docs/sources/configure-user-settings/_index.md
Labels: pr:no changelog

#1614 minor bugfix for ios push notifications config
  engine/apps/mobile_app/tasks.py
Labels: pr:no changelog, pr:no public docs

#1585 Rares/2 webhooks
  grafana-plugin/src/components/GForm/GForm.tsx
  grafana-plugin/src/components/GForm/GForm.types.ts
  grafana-plugin/src/components/SourceCode/SourceCode.module.scss
  grafana-plugin/src/components/SourceCode/SourceCode.tsx
  grafana-plugin/src/containers/GSelect/GSelect.tsx
  grafana-plugin/src/containers/OutgoingWebhook2Form/OutgoingWebhook2Form.config.tsx
  grafana-plugin/src/containers/OutgoingWebhook2Status/OutgoingWebhook2Status.tsx
  grafana-plugin/src/pages/index.tsx
  grafana-plugin/src/pages/outgoing_webhooks_2/OutgoingWebhooks2.module.css
  grafana-plugin/src/pages/outgoing_webhooks_2/OutgoingWebhooks2.tsx
  grafana-plugin/src/utils/index.ts
Labels: pr:no changelog, pr:no public docs

#1465 Add label and formatted JSON example
  docs/sources/alert-behavior/outgoing-webhooks/index.md
Labels: type/docs, pr:no changelog, Q1CX

#1608 Closing drawers by clicking outside was changed
  CHANGELOG.md
  grafana-plugin/src/components/ManualAlertGroup/ManualAlertGroup.tsx
  grafana-plugin/src/containers/MaintenanceForm/MaintenanceForm.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.tsx
  grafana-plugin/src/containers/ScheduleForm/ScheduleForm.tsx
Labels: pr:no public docs

#1602 Improve schedule quality feature
  CHANGELOG.md
  engine/apps/api/views/schedule.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/quality_score.py
  engine/apps/schedules/tests/test_quality_score.py
  grafana-plugin/integration-tests/schedules/quality.test.ts
  grafana-plugin/src/components/ScheduleQualityDetails/ScheduleQualityDetails.module.scss
  grafana-plugin/src/components/ScheduleQualityDetails/ScheduleQualityDetails.tsx
  grafana-plugin/src/models/schedule/schedule.ts
  grafana-plugin/src/models/schedule/schedule.types.ts
Labels: pr:no public docs

#1615 speed up ci builds from 15 to <7 minutes
  .github/workflows/ci.yml
  .github/workflows/helm_release.yml
  .github/workflows/integration_tests.yml
  .github/workflows/issue_commands.yml
  .github/workflows/linting-and-tests.yml
  .github/workflows/publish-technical-documentation-next.yml
  .github/workflows/publish-technical-documentation-release.yml
  .github/workflows/snyk.yml
  engine/settings/ci-test.py
  engine/wait_for_test_mysql_start.sh
  grafana-plugin/integration-tests/alerts/onCallSchedule.test.ts
  grafana-plugin/integration-tests/alerts/sms.test.ts
  grafana-plugin/integration-tests/escalationChains/searching.test.ts
  grafana-plugin/integration-tests/globalSetup.ts
  grafana-plugin/integration-tests/integrations/uniqueIntegrationNames.test.ts
  grafana-plugin/integration-tests/schedules/addOverride.test.ts
  grafana-plugin/integration-tests/schedules/quality.test.ts
  grafana-plugin/integration-tests/utils/configurePlugin.ts
  grafana-plugin/integration-tests/utils/escalationChain.ts
  grafana-plugin/integration-tests/utils/forms.ts
  grafana-plugin/package.json
  grafana-plugin/playwright.config.ts
  grafana-plugin/src/PluginPage.tsx
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/containers/GSelect/GSelect.tsx
  grafana-plugin/src/pages/escalation-chains/EscalationChains.tsx
  grafana-plugin/yarn.lock
Labels: pr:no changelog, pr:no public docs

#1638 Configure pyroscope
  engine/engine/celery.py
  engine/engine/wsgi.py
  engine/settings/base.py
  engine/uwsgi.ini
Labels: pr:no changelog, pr:no public docs

#1581 Slack team connector v2
  engine/apps/slack/views.py
  engine/apps/social_auth/exceptions.py
  engine/apps/social_auth/middlewares.py
  engine/apps/social_auth/pipeline.py
  engine/apps/user_management/models/organization.py
  engine/common/oncall_gateway/__init__.py
  engine/common/oncall_gateway/oncall_gateway_client.py
  engine/common/oncall_gateway/tasks.py
  engine/common/oncall_gateway/utils.py
  grafana-plugin/src/containers/DefaultPageLayout/DefaultPageLayout.helpers.tsx
  grafana-plugin/src/containers/DefaultPageLayout/DefaultPageLayout.types.ts
Labels: pr:no changelog, pr:no public docs

#1640 Fix failing ci task
  engine/wait_for_test_mysql_start.sh
Labels: pr:no changelog, pr:no public docs

#1639 Revert "speed up ci builds from 15 to <7 minutes"
  .github/workflows/ci.yml
  .github/workflows/helm_release.yml
  .github/workflows/integration_tests.yml
  .github/workflows/issue_commands.yml
  .github/workflows/linting-and-tests.yml
  .github/workflows/publish-technical-documentation-next.yml
  .github/workflows/publish-technical-documentation-release.yml
  .github/workflows/snyk.yml
  engine/settings/ci-test.py
  engine/wait_for_test_mysql_start.sh
  grafana-plugin/integration-tests/alerts/onCallSchedule.test.ts
  grafana-plugin/integration-tests/alerts/sms.test.ts
  grafana-plugin/integration-tests/escalationChains/searching.test.ts
  grafana-plugin/integration-tests/globalSetup.ts
  grafana-plugin/integration-tests/integrations/uniqueIntegrationNames.test.ts
  grafana-plugin/integration-tests/schedules/addOverride.test.ts
  grafana-plugin/integration-tests/schedules/quality.test.ts
  grafana-plugin/integration-tests/utils/configurePlugin.ts
  grafana-plugin/integration-tests/utils/escalationChain.ts
  grafana-plugin/integration-tests/utils/forms.ts
  grafana-plugin/package.json
  grafana-plugin/playwright.config.ts
  grafana-plugin/src/PluginPage.tsx
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/containers/GSelect/GSelect.tsx
  grafana-plugin/src/pages/escalation-chains/EscalationChains.tsx
  grafana-plugin/yarn.lock
Labels: pr:no changelog, pr:no public docs

#1641 Dev to Main
  engine/apps/slack/views.py
  engine/apps/social_auth/exceptions.py
  engine/apps/social_auth/middlewares.py
  engine/apps/social_auth/pipeline.py
  engine/apps/user_management/models/organization.py
  engine/common/oncall_gateway/__init__.py
  engine/common/oncall_gateway/oncall_gateway_client.py
  engine/common/oncall_gateway/tasks.py
  engine/common/oncall_gateway/utils.py
  engine/engine/celery.py
  engine/engine/wsgi.py
  engine/settings/base.py
  engine/uwsgi.ini
  grafana-plugin/src/containers/DefaultPageLayout/DefaultPageLayout.helpers.tsx
  grafana-plugin/src/containers/DefaultPageLayout/DefaultPageLayout.types.ts
Labels: pr:no changelog, pr:no public docs

#1642 fix failing drone ci builds
  .drone.yml
Labels: pr:no changelog, pr:no public docs

#1643 Revert "Revert "speed up ci builds from 15 to <7 minutes""
  .github/workflows/ci.yml
  .github/workflows/helm_release.yml
  .github/workflows/integration_tests.yml
  .github/workflows/issue_commands.yml
  .github/workflows/linting-and-tests.yml
  .github/workflows/publish-technical-documentation-next.yml
  .github/workflows/publish-technical-documentation-release.yml
  .github/workflows/snyk.yml
  engine/settings/ci-test.py
  engine/wait_for_test_mysql_start.sh
  grafana-plugin/integration-tests/alerts/onCallSchedule.test.ts
  grafana-plugin/integration-tests/alerts/sms.test.ts
  grafana-plugin/integration-tests/escalationChains/searching.test.ts
  grafana-plugin/integration-tests/globalSetup.ts
  grafana-plugin/integration-tests/integrations/uniqueIntegrationNames.test.ts
  grafana-plugin/integration-tests/schedules/addOverride.test.ts
  grafana-plugin/integration-tests/schedules/quality.test.ts
  grafana-plugin/integration-tests/utils/configurePlugin.ts
  grafana-plugin/integration-tests/utils/escalationChain.ts
  grafana-plugin/integration-tests/utils/forms.ts
  grafana-plugin/package.json
  grafana-plugin/playwright.config.ts
  grafana-plugin/src/PluginPage.tsx
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/containers/GSelect/GSelect.tsx
  grafana-plugin/src/pages/escalation-chains/EscalationChains.tsx
  grafana-plugin/yarn.lock
Labels: pr:no changelog, pr:no public docs

#1646 Update apns payload with corrected `interruption-level` field
  CHANGELOG.md
  engine/apps/mobile_app/tasks.py
  engine/apps/mobile_app/tests/test_notify_user.py
Labels: pr:no public docs

#1574 Refactoring of isInWorkingHours method
  grafana-plugin/src/components/WorkingHours/WorkingHours.helpers.test.ts
  grafana-plugin/src/components/WorkingHours/WorkingHours.helpers.ts
Labels: pr:no changelog, pr:no public docs

#1652 Fix Grafana teams sync
  CHANGELOG.md
  engine/apps/schedules/migrations/0010_fix_polymorphic_delete_related.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_on_call_schedule.py
  engine/apps/user_management/tests/test_organization.py
  engine/common/database.py
Labels: pr:no public docs

#1600 Collection of bugs
  grafana-plugin/src/components/Tutorial/Tutorial.tsx
  grafana-plugin/src/containers/AlertReceiveChannelCard/AlertReceiveChannelCard.tsx
  grafana-plugin/src/containers/AlertRules/AlertRules.tsx
  grafana-plugin/src/containers/AttachIncidentForm/AttachIncidentForm.tsx
  grafana-plugin/src/containers/IncidentMatcher/IncidentMatcher.tsx
  grafana-plugin/src/containers/IntegrationSettings/IntegrationSettings.tsx
  grafana-plugin/src/containers/IntegrationSettings/parts/Autoresolve.module.css
  grafana-plugin/src/containers/IntegrationSettings/parts/Autoresolve.tsx
  grafana-plugin/src/containers/MaintenanceForm/MaintenanceForm.config.tsx
  grafana-plugin/src/containers/RotationForm/RotationForm.module.css
  grafana-plugin/src/pages/escalation-chains/EscalationChains.tsx
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/index.tsx
  grafana-plugin/src/plugin.json
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/utils/consts.ts
  grafana-plugin/src/utils/url.ts
Labels: pr:no changelog, pr:no public docs

#1671 Revert "Collection of bugs"
  CHANGELOG.md
  grafana-plugin/src/components/Tutorial/Tutorial.tsx
  grafana-plugin/src/containers/AlertReceiveChannelCard/AlertReceiveChannelCard.tsx
  grafana-plugin/src/containers/AlertRules/AlertRules.tsx
  grafana-plugin/src/containers/AttachIncidentForm/AttachIncidentForm.tsx
  grafana-plugin/src/containers/IncidentMatcher/IncidentMatcher.tsx
  grafana-plugin/src/containers/IntegrationSettings/IntegrationSettings.tsx
  grafana-plugin/src/containers/IntegrationSettings/parts/Autoresolve.module.css
  grafana-plugin/src/containers/IntegrationSettings/parts/Autoresolve.tsx
  grafana-plugin/src/containers/MaintenanceForm/MaintenanceForm.config.tsx
  grafana-plugin/src/containers/RotationForm/RotationForm.module.css
  grafana-plugin/src/pages/escalation-chains/EscalationChains.tsx
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/index.tsx
  grafana-plugin/src/plugin.json
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/utils/consts.ts
  grafana-plugin/src/utils/url.ts
Labels: pr:no public docs

#1672 v1.2.5
  CHANGELOG.md
  grafana-plugin/src/components/Tutorial/Tutorial.tsx
  grafana-plugin/src/containers/AlertReceiveChannelCard/AlertReceiveChannelCard.tsx
  grafana-plugin/src/containers/AlertRules/AlertRules.tsx
  grafana-plugin/src/containers/AttachIncidentForm/AttachIncidentForm.tsx
  grafana-plugin/src/containers/IncidentMatcher/IncidentMatcher.tsx
  grafana-plugin/src/containers/IntegrationSettings/IntegrationSettings.tsx
  grafana-plugin/src/containers/IntegrationSettings/parts/Autoresolve.module.css
  grafana-plugin/src/containers/IntegrationSettings/parts/Autoresolve.tsx
  grafana-plugin/src/containers/MaintenanceForm/MaintenanceForm.config.tsx
  grafana-plugin/src/containers/RotationForm/RotationForm.module.css
  grafana-plugin/src/pages/escalation-chains/EscalationChains.tsx
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/index.tsx
  grafana-plugin/src/plugin.json
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/utils/consts.ts
  grafana-plugin/src/utils/url.ts
Labels: pr:no changelog, pr:no public docs

#1674 GH Action to add OSS issues to team's kanban board
  .github/workflows/issues_add_to_project.yml
Labels: pr:no changelog, pr:no public docs

#1661 RRULE until values must be specified in UTC tz
  CHANGELOG.md
  engine/apps/schedules/models/custom_on_call_shift.py
  engine/apps/schedules/tests/test_custom_on_call_shift.py
Labels: pr:no public docs

#1679 Include a note on user working hours
  docs/sources/calendar-schedules/web-schedule/create-schedule/index.md
Labels: Q1CX

#1680 Fix team search
  CHANGELOG.md
  engine/apps/api/tests/test_team.py
  engine/apps/api/views/team.py
Labels: pr:no public docs

#1663 fix safari scroll
  .github/workflows/linting-and-tests.yml
  CHANGELOG.md
  grafana-plugin/integration-tests/alerts/onCallSchedule.test.ts
  grafana-plugin/integration-tests/utils/forms.ts
  grafana-plugin/playwright.config.ts
  grafana-plugin/src/img/grafanaGlobalStyles.css
  grafana-plugin/src/pages/escalation-chains/EscalationChains.tsx
Labels: pr:no public docs

#1613 Save selected teams filter in local storage
  CHANGELOG.md
  grafana-plugin/src/models/filters/filters.ts
Labels: pr:no public docs

#1678 Incidents mapped to /alert-groups
  CHANGELOG.md
  grafana-plugin/src/components/Tutorial/Tutorial.tsx
  grafana-plugin/src/containers/AlertReceiveChannelCard/AlertReceiveChannelCard.tsx
  grafana-plugin/src/containers/AlertRules/AlertRules.tsx
  grafana-plugin/src/containers/AttachIncidentForm/AttachIncidentForm.tsx
  grafana-plugin/src/containers/IncidentMatcher/IncidentMatcher.tsx
  grafana-plugin/src/containers/IntegrationSettings/IntegrationSettings.tsx
  grafana-plugin/src/containers/IntegrationSettings/parts/Autoresolve.module.css
  grafana-plugin/src/containers/IntegrationSettings/parts/Autoresolve.tsx
  grafana-plugin/src/containers/MaintenanceForm/MaintenanceForm.config.tsx
  grafana-plugin/src/containers/RotationForm/RotationForm.module.css
  grafana-plugin/src/pages/escalation-chains/EscalationChains.tsx
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/index.tsx
  grafana-plugin/src/plugin.json
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/utils/consts.ts
Labels: pr:no public docs

#1685 PD migrator: migrate push notification user rules
  tools/pagerduty-migrator/README.md
  tools/pagerduty-migrator/migrator/config.py
Labels: pr:no changelog, pr:no public docs

#1687 PD migrator: include service & integration names to ruleset
  tools/pagerduty-migrator/migrator/__main__.py
  tools/pagerduty-migrator/migrator/config.py
  tools/pagerduty-migrator/migrator/report.py
  tools/pagerduty-migrator/migrator/resources/rulesets.py
Labels: pr:no changelog, pr:no public docs
