Repository grafana/oncall, pull requests merged in 2023-08, with the labels that each got.

#2701 Polish amv2
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/integrations/templates/heartbeat_instructions/legacy_alertmanager.html
  engine/apps/integrations/templates/html/integration_legacy_grafana_alerting.html
  engine/apps/integrations/tests/test_legacy_alertmanager.py
  engine/apps/public_api/serializers/integrations.py
  engine/config_integrations/alertmanager.py
  engine/settings/base.py
Labels: pr:no changelog, pr:no public docs

#2707 Bump Python version in CI to 3.11.4
  .drone.yml
  .github/workflows/linting-and-tests.yml
  .github/workflows/snyk.yml
  tools/pagerduty-migrator/Dockerfile
Labels: pr:no changelog, pr:no public docs

#2711 fix bug introduced by #2655
  helm/oncall/templates/engine/deployment.yaml
Labels: pr:no changelog, pr:no public docs

#2716 Fix swap requests event filter limits
  CHANGELOG.md
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_on_call_schedule.py
Labels: pr:no public docs

#2712 add shifts property to shift swap request response schema + finalize slack message layout
  engine/apps/api/serializers/shift_swap.py
  engine/apps/api/tests/test_shift_swaps.py
  engine/apps/api/views/shift_swap.py
  engine/apps/schedules/models/custom_on_call_shift.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/models/shift_swap_request.py
  engine/apps/schedules/tasks/notify_about_empty_shifts_in_schedule.py
  engine/apps/schedules/tasks/notify_about_gaps_in_schedule.py
  engine/apps/schedules/tests/test_shift_swap_request.py
  engine/apps/slack/scenarios/schedules.py
  engine/apps/slack/scenarios/shift_swap_requests.py
  engine/apps/slack/tests/test_scenario_steps/test_shift_swap_requests.py
  engine/apps/slack/utils.py
  engine/apps/user_management/models/organization.py
  engine/apps/user_management/models/team.py
  engine/common/api_helpers/mixins.py
Labels: pr:no changelog, pr:no public docs

#2698 remove some references to amixr
  docs/sources/integrations/prtg/index.md
  docs/sources/integrations/uptimerobot/index.md
  docs/sources/outgoing-webhooks/_index.md
  engine/apps/alerts/incident_appearance/templaters/alert_templater.py
  engine/apps/alerts/incident_appearance/templaters/web_templater.py
  engine/apps/alerts/tests/test_alert_group.py
  engine/apps/heartbeat/tests/test_integration_heartbeat.py
  engine/conftest.py
  grafana-plugin/src/containers/TemplatesAlertGroupsList/WebhooksDefaultAlertGroup.ts
Labels: pr:no changelog, pr:no public docs

#2718 Skip past due swap requests when calculating events
  CHANGELOG.md
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_on_call_schedule.py
Labels: pr:no public docs

#2717 Add mobile app push notifications for shift swap requests
  CHANGELOG.md
  engine/apps/mobile_app/models.py
  engine/apps/mobile_app/tasks.py
  engine/apps/mobile_app/tests/test_shift_swap_request.py
  engine/apps/schedules/migrations/0016_alter_shiftswaprequest_created_at.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/models/shift_swap_request.py
  engine/apps/schedules/tests/test_on_call_schedule.py
  engine/apps/schedules/tests/test_shift_swap_request.py
  engine/apps/user_management/models/user.py
  engine/apps/user_management/tests/test_user.py
  engine/settings/base.py
  engine/settings/prod_without_db.py
Labels: pr:no public docs

#2721 Fix contact point auto-creation
  CHANGELOG.md
  engine/apps/alerts/models/alert_receive_channel.py
Labels: pr:no public docs

#2645 Api for grafana alerting
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/views/alert_receive_channel.py
  engine/apps/api/views/features.py
  engine/settings/base.py
Labels: pr:no changelog, pr:no public docs

#2612 add a couple of tests for users screen
  .github/workflows/linting-and-tests.yml
  dev/README.md
  grafana-plugin/.gitignore
  grafana-plugin/e2e-tests/.auth/.gitignore
  grafana-plugin/e2e-tests/.env.example
  grafana-plugin/e2e-tests/alerts/directPaging.test.ts
  grafana-plugin/e2e-tests/alerts/onCallSchedule.test.ts
  grafana-plugin/e2e-tests/alerts/sms.test.ts
  grafana-plugin/e2e-tests/escalationChains/searching.test.ts
  grafana-plugin/e2e-tests/fixtures.ts
  grafana-plugin/e2e-tests/globalSetup.ts
  grafana-plugin/e2e-tests/integrations/heartbeat.test.ts
  grafana-plugin/e2e-tests/integrations/maintenanceMode.test.ts
  grafana-plugin/e2e-tests/integrations/uniqueIntegrationNames.test.ts
  grafana-plugin/e2e-tests/schedules/addOverride.test.ts
  grafana-plugin/e2e-tests/schedules/quality.test.ts
  grafana-plugin/e2e-tests/users/usersActions.test.ts
  grafana-plugin/e2e-tests/utils/alertGroup.ts
  grafana-plugin/e2e-tests/utils/clients/grafana.ts
  grafana-plugin/e2e-tests/utils/constants.ts
  grafana-plugin/e2e-tests/utils/escalationChain.ts
  grafana-plugin/e2e-tests/utils/forms.ts
  grafana-plugin/e2e-tests/utils/integrations.ts
  grafana-plugin/e2e-tests/utils/modals.ts
  grafana-plugin/e2e-tests/utils/navigation.ts
  grafana-plugin/e2e-tests/utils/phone.ts
  grafana-plugin/e2e-tests/utils/schedule.ts
  grafana-plugin/e2e-tests/utils/userSettings.ts
  grafana-plugin/integration-tests/users/viewUsers.test.ts
  grafana-plugin/jest.config.js
  grafana-plugin/package.json
  grafana-plugin/playwright.config.ts
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.tsx
  grafana-plugin/src/containers/UserSettings/parts/index.tsx
  grafana-plugin/src/containers/UserSettings/parts/tabs/CloudPhoneSettings/CloudPhoneSettings.tsx
  grafana-plugin/src/containers/UserSettings/parts/tabs/PhoneVerification/PhoneVerification.tsx
  grafana-plugin/src/containers/UserSettings/parts/tabs/SlackTab/SlackTab.tsx
  grafana-plugin/src/containers/UserSettings/parts/tabs/TelegramInfo/TelegramInfo.tsx
  grafana-plugin/src/containers/WithPermissionControl/WithPermissionControlDisplay.tsx
  grafana-plugin/src/pages/users/Users.tsx
  grafana-plugin/tsconfig.json
Labels: pr:no changelog, pr:no public docs

#2720 Increase max size of authorization_header in DB
  engine/apps/webhooks/migrations/0009_alter_webhook_authorization_header.py
  engine/apps/webhooks/models/webhook.py
Labels: pr:no changelog, pr:no public docs

#2732 Update shift swap test to make it stable
  engine/apps/api/tests/test_shift_swaps.py
Labels: pr:no changelog, pr:no public docs

#2734 remove two unused feature flags
  dev/.env.dev.example
  engine/apps/api/tests/test_escalation_policy.py
  engine/apps/api/tests/test_features.py
  engine/apps/api/tests/test_webhooks.py
  engine/apps/api/views/escalation_policy.py
  engine/apps/api/views/features.py
  engine/apps/api/views/webhooks.py
  engine/settings/base.py
  grafana-plugin/src/state/features.ts
Labels: pr:no changelog, pr:no public docs

#2731 remove django admin panel
  engine/apps/alerts/admin.py
  engine/apps/base/admin.py
  engine/apps/schedules/admin.py
  engine/apps/slack/admin.py
  engine/apps/user_management/admin.py
  engine/apps/webhooks/admin.py
  engine/common/admin.py
  engine/engine/urls.py
  engine/settings/base.py
  engine/static/images/heartbeat_instructions/heartbeat_grafana_1.png
  engine/static/images/heartbeat_instructions/heartbeat_grafana_2.png
  engine/static/images/heartbeat_instructions/heartbeat_grafana_3.png
  engine/static/images/heartbeat_instructions/heartbeat_grafana_4.png
  engine/static/images/heartbeat_instructions/heartbeat_grafana_5.png
  engine/static/images/heartbeat_instructions/heartbeat_zabbix_1.png
  engine/static/images/heartbeat_instructions/heartbeat_zabbix_2.png
  engine/static/images/heartbeat_instructions/heartbeat_zabbix_3.png
  engine/static/images/heartbeat_instructions/heartbeat_zabbix_4.png
  engine/static/images/heartbeat_instructions/heartbeat_zabbix_5.png
Labels: pr:no changelog, pr:no public docs

#2728 configure yamllint pre-commit step
  .drone.yml
  .github/ISSUE_TEMPLATE/0-bug-report-template.yml
  .github/ISSUE_TEMPLATE/1-feature-request-template.yml
  .github/workflows/helm_release.yml
  .github/workflows/helm_release_pr.yml
  .github/workflows/issue_commands.yml
  .github/workflows/linting-and-tests.yml
  .github/workflows/on-issue-creation.yml
  .github/workflows/publish-technical-documentation-next.yml
  .github/workflows/publish-technical-documentation-release.yml
  .github/workflows/snyk.yml
  .github/workflows/triage-stale-pull-requests.yml
  .github/workflows/update-make-docs.yml
  .github/workflows/verify-changelog-updated.yml
  .github/workflows/verify-public-docs-updated.yml
  .pre-commit-config.yaml
  .yamllint.yml
  dev/prometheus.yml
  docker-compose-developer.yml
  docker-compose-mysql-rabbitmq.yml
  helm/cr.yaml
  helm/ct.yaml
  helm/oncall/tests/migrate_annotations_test.yaml
  helm/oncall/tests/postgres_password_env_test.yaml
  helm/oncall/tests/rabbitmq_env_test.yaml
  helm/oncall/values.yaml
Labels: pr:no changelog, pr:no public docs

#2735 remove unused dynamic settings
  engine/apps/base/migrations/0005_drop_unused_dynamic_settings.py
  engine/apps/slack/slack_client/slack_client.py
Labels: pr:no changelog, pr:no public docs

#2737 API for grafana alerting (including test fix)
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/views/alert_receive_channel.py
  engine/apps/api/views/features.py
  engine/settings/base.py
Labels: pr:no changelog, pr:no public docs

#2725 Re-enable a few mypy rules + fix existing errors
  engine/apps/alerts/models/alert.py
  engine/apps/alerts/models/alert_group_log_record.py
  engine/apps/alerts/models/invitation.py
  engine/apps/alerts/paging.py
  engine/apps/api/serializers/channel_filter.py
  engine/apps/grafana_plugin/helpers/client.py
  engine/apps/metrics_exporter/helpers.py
  engine/apps/metrics_exporter/metrics_cache_manager.py
  engine/apps/metrics_exporter/tests/test_update_metics_cache.py
  engine/apps/mobile_app/tasks.py
  engine/apps/phone_notifications/phone_provider.py
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/slack/scenarios/alertgroup_appearance.py
  engine/apps/slack/scenarios/declare_incident.py
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/slack/scenarios/invited_to_channel.py
  engine/apps/slack/scenarios/manage_responders.py
  engine/apps/slack/scenarios/manual_incident.py
  engine/apps/slack/scenarios/notified_user_not_in_channel.py
  engine/apps/slack/scenarios/onboarding.py
  engine/apps/slack/scenarios/paging.py
  engine/apps/slack/scenarios/profile_update.py
  engine/apps/slack/scenarios/resolution_note.py
  engine/apps/slack/scenarios/scenario_step.py
  engine/apps/slack/scenarios/schedules.py
  engine/apps/slack/scenarios/shift_swap_requests.py
  engine/apps/slack/scenarios/slack_channel.py
  engine/apps/slack/scenarios/slack_channel_integration.py
  engine/apps/slack/scenarios/slack_usergroup.py
  engine/apps/slack/scenarios/step_mixins.py
  engine/apps/slack/types/__init__.py
  engine/apps/slack/types/block_elements.py
  engine/apps/slack/types/blocks.py
  engine/apps/slack/types/composition_objects.py
  engine/apps/slack/types/interaction_payloads/__init__.py
  engine/apps/slack/types/views.py
  engine/apps/slack/views.py
  engine/apps/user_management/models/team.py
  engine/apps/user_management/models/user.py
  engine/apps/user_management/sync.py
  engine/common/ordered_model/ordered_model.py
  engine/common/public_primary_keys.py
  engine/pyproject.toml
Labels: pr:no changelog, pr:no public docs

#2710 Update schedule slack notifications
  CHANGELOG.md
  engine/apps/alerts/tasks/notify_ical_schedule_shift.py
  engine/apps/alerts/tests/test_notify_ical_schedule_shift.py
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tasks/notify_about_empty_shifts_in_schedule.py
  engine/apps/schedules/tasks/notify_about_gaps_in_schedule.py
  engine/apps/schedules/tests/test_notify_about_empty_shifts_in_schedule.py
  engine/apps/schedules/tests/test_notify_about_gaps_in_schedule.py
  engine/apps/schedules/tests/test_on_call_schedule.py
  engine/apps/slack/scenarios/schedules.py
Labels: pr:no public docs

#2743 Add stack slug to organization options for direct paging
  CHANGELOG.md
  engine/apps/slack/scenarios/paging.py
  engine/apps/slack/tests/test_scenario_steps/test_paging.py
Labels: pr:no public docs

#2741 Add more logging for `SlackUserGroup.update_oncall_members`
  engine/apps/slack/models/slack_usergroup.py
Labels: pr:no changelog, pr:no public docs

#2744 fix make start command when using mysql/postgres as db
  dev/README.md
  docker-compose-developer.yml
  docker-compose-mysql-rabbitmq.yml
  docker-compose.yml
Labels: pr:no changelog, pr:no public docs

#2752 Enable push notifications for SSR beneficiary for testing purposes
  engine/apps/schedules/models/shift_swap_request.py
  engine/apps/schedules/tests/test_shift_swap_request.py
Labels: pr:no changelog, pr:no public docs

#2694 Shift Swap Requests - build out web UI changes
  CHANGELOG.md
  grafana-plugin/src/containers/Rotation/Rotation.tsx
  grafana-plugin/src/containers/RotationForm/RotationForm.module.css
  grafana-plugin/src/containers/RotationForm/ShiftSwapForm.module.css
  grafana-plugin/src/containers/RotationForm/ShiftSwapForm.tsx
  grafana-plugin/src/containers/RotationForm/parts/UserItem.tsx
  grafana-plugin/src/containers/Rotations/Rotations.helpers.ts
  grafana-plugin/src/containers/Rotations/Rotations.tsx
  grafana-plugin/src/containers/Rotations/ScheduleFinal.tsx
  grafana-plugin/src/containers/ScheduleSlot/ScheduleSlot.tsx
  grafana-plugin/src/containers/UsersTimezones/UsersTimezones.tsx
  grafana-plugin/src/models/schedule/schedule.helpers.ts
  grafana-plugin/src/models/schedule/schedule.ts
  grafana-plugin/src/models/schedule/schedule.types.ts
  grafana-plugin/src/pages/schedule/Schedule.tsx
Labels: pr:no public docs

#2755 remove shift swap feature flag
  engine/apps/api/urls.py
  engine/apps/mobile_app/tasks.py
  engine/apps/mobile_app/tests/test_shift_swap_request.py
  engine/settings/base.py
  engine/settings/ci-test.py
Labels: pr:no changelog, pr:no public docs

#2649 merge final schedule in as less lines as possible
  CHANGELOG.md
  grafana-plugin/src/containers/Rotation/Rotation.tsx
  grafana-plugin/src/containers/Rotations/ScheduleFinal.tsx
  grafana-plugin/src/models/schedule/schedule.helpers.ts
  grafana-plugin/src/models/schedule/schedule.types.ts
  grafana-plugin/src/pages/schedule/Schedule.tsx
Labels: pr:no public docs

#2748 Filter out untaken swaps from final schedule and shift notifications
  CHANGELOG.md
  engine/apps/alerts/tasks/notify_ical_schedule_shift.py
  engine/apps/alerts/tests/test_notify_ical_schedule_shift.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/models/shift_swap_request.py
  engine/apps/schedules/tests/test_on_call_schedule.py
  engine/apps/schedules/tests/test_shift_swap_request.py
Labels: pr:no public docs

#2760 Handle ical schedule import with duplicated event UIDs
  CHANGELOG.md
  engine/apps/schedules/constants.py
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/tests/calendars/modified_recurring_event.ics
  engine/apps/schedules/tests/test_ical_utils.py
  engine/apps/schedules/tests/test_on_call_schedule.py
Labels: pr:no public docs

#2659 Add instruction on removing nullable fields from Django models
  dev/README.md
  engine/common/migrations/__init__.py
  engine/common/migrations/remove_field.py
  engine/engine/management/commands/remove_field.py
Labels: pr:no changelog, pr:no public docs

#2723 Use periodic task for heartbeats
  CHANGELOG.md
  engine/apps/heartbeat/models.py
  engine/apps/heartbeat/tasks.py
  engine/apps/heartbeat/tests/test_integration_heartbeat.py
  engine/apps/integrations/metadata/heartbeat/elastalert.py
  engine/apps/integrations/metadata/heartbeat/formatted_webhook.py
  engine/apps/integrations/metadata/heartbeat/grafana.py
  engine/apps/integrations/metadata/heartbeat/prtg.py
  engine/apps/integrations/metadata/heartbeat/webhook.py
  engine/apps/integrations/metadata/heartbeat/zabbix.py
  engine/apps/integrations/tests/test_ratelimit.py
  engine/apps/integrations/views.py
  engine/config_integrations/elastalert.py
  engine/config_integrations/webhook.py
  engine/settings/base.py
Labels: pr:no public docs

#2772 Use UserSettingsWrite instead of OtherSettingsWrite for phone tab
  CHANGELOG.md
  grafana-plugin/src/containers/UserSettings/parts/tabs/CloudPhoneSettings/CloudPhoneSettings.tsx
  grafana-plugin/src/containers/UserSettings/parts/tabs/PhoneVerification/PhoneVerification.tsx
Labels: pr:no public docs

#2769 Fix Slack acknowledgment reminders
  CHANGELOG.md
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/tasks/acknowledge_reminder.py
  engine/apps/alerts/tests/test_acknowledge_reminder.py
Labels: pr:no public docs

#2779 Remove `django-ordered-model` from requirements
  engine/requirements.txt
  engine/settings/base.py
Labels: pr:no changelog, pr:no public docs

#2782 Make field rbac_enabled readonly for organization endpoint
  CHANGELOG.md
  engine/apps/api/serializers/organization.py
  engine/apps/api/tests/test_organization.py
Labels: pr:no public docs

#2776 Ignore ical cancelled events when calculating shifts
  CHANGELOG.md
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/tests/test_ical_utils.py
Labels: pr:no public docs

#2783 Don't send notifications about past SSRs when turning on info notifications
  CHANGELOG.md
  engine/apps/mobile_app/tasks.py
  engine/apps/mobile_app/tests/test_shift_swap_request.py
Labels: pr:no public docs

#2789 Add schedule shift type validation on create/preview
  CHANGELOG.md
  engine/apps/api/serializers/on_call_shifts.py
  engine/apps/api/tests/test_oncall_shift.py
Labels: pr:no public docs

#2771 Add openapi schema generation for internal api
  docker-compose-developer.yml
  engine/apps/api/serializers/alert_group.py
  engine/apps/api/serializers/user.py
  engine/apps/api/views/alert_group.py
  engine/apps/api/views/features.py
  engine/engine/included_path.py
  engine/engine/urls.py
  engine/requirements.txt
  engine/settings/base.py
Labels: pr:no changelog, pr:no public docs

#2798 Shift swap request Slack follow-ups
  CHANGELOG.md
  engine/apps/mobile_app/tasks.py
  engine/apps/schedules/models/shift_swap_request.py
  engine/apps/schedules/tasks/shift_swaps/__init__.py
  engine/apps/schedules/tasks/shift_swaps/slack_followups.py
  engine/apps/schedules/tests/tasks/shift_swaps/test_slack_followups.py
  engine/apps/slack/scenarios/shift_swap_requests.py
  engine/settings/base.py
  engine/settings/prod_without_db.py
Labels: pr:no public docs

#2794 Improve template to handle empty group labels
  CHANGELOG.md
  engine/config_integrations/alertmanager.py
  engine/config_integrations/grafana_alerting.py
Labels: pr:no public docs

#2807 Add alertmanager integration for heartbeat support
  CHANGELOG.md
  engine/apps/alerts/tests/test_alert_receiver_channel.py
  engine/apps/integrations/metadata/heartbeat/__init__.py
  engine/apps/integrations/metadata/heartbeat/alertmanager.py
Labels: pr:no public docs

#2719 Add documentation about shift swap requests
  docs/sources/insights-and-metrics/_index.md
  docs/sources/mobile-app/push-notifications/index.md
  docs/sources/on-call-schedules/_index.md
  docs/sources/on-call-schedules/shift-swaps/_index.md
  engine/apps/api/views/shift_swap.py
  engine/apps/schedules/models/shift_swap_request.py
Labels: pr:no changelog

#2823 Set schema url for Swagger via env variable
  docker-compose-developer.yml
  engine/settings/base.py
  engine/settings/prod_without_db.py
Labels: pr:no changelog, pr:no public docs

#2824 Remove UTC from step as it is using local time
  engine/apps/alerts/models/escalation_policy.py
Labels: pr:no changelog, pr:no public docs

#2742 Improve getting/updating contact points for Grafana Alerting integration
  CHANGELOG.md
  engine/apps/alerts/grafana_alerting_sync_manager/__init__.py
  engine/apps/alerts/grafana_alerting_sync_manager/grafana_alerting_sync.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/models/grafana_alerting_contact_point.py
  engine/apps/alerts/tasks/__init__.py
  engine/apps/alerts/tasks/sync_grafana_alerting_contact_points.py
  engine/apps/alerts/tests/test_grafana_alerting_sync.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/views/alert_receive_channel.py
  engine/apps/grafana_plugin/helpers/client.py
  engine/settings/prod_without_db.py
  grafana-plugin/src/assets/style/utils.css
  grafana-plugin/src/components/GForm/GForm.tsx
  grafana-plugin/src/components/GForm/GForm.types.ts
  grafana-plugin/src/components/IntegrationCollapsibleTreeView/IntegrationCollapsibleTreeView.module.scss
  grafana-plugin/src/components/IntegrationContactPoint/IntegrationContactPoint.tsx
  grafana-plugin/src/components/IntegrationHowToConnect/IntegrationHowToConnect.tsx
  grafana-plugin/src/components/IntegrationSendDemoAlertModal/IntegrationSendDemoAlertModal.tsx
  grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.module.scss
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.config.ts
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.module.scss
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.types.ts
  grafana-plugin/src/pages/integration/Integration.helper.ts
  grafana-plugin/src/pages/integration/Integration.module.scss
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/pages/integrations/Integrations.tsx
  grafana-plugin/src/types.ts
Labels: pr:no public docs

#2826 Prevent conversion of escalation start/end times to UTC
  CHANGELOG.md
  engine/apps/alerts/models/escalation_policy.py
  grafana-plugin/src/components/TimeRange/TimeRange.tsx
Labels: pr:no public docs

#2827 Set is_escalation_finished to True if alert group won't be escalated
  engine/apps/alerts/escalation_snapshot/escalation_snapshot_mixin.py
Labels: pr:no changelog, pr:no public docs

#2829 Added validation for existent contact point for grafana alerting
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/pages/integration/Integration.tsx
Labels: pr:no changelog, pr:no public docs

#2828 Check possible split events in range when resolving schedule
  CHANGELOG.md
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_on_call_schedule.py
  engine/apps/schedules/tests/test_quality_score.py
Labels: pr:no public docs

#2840 Changed HTTP Endpoint to Email for inbound email integrations
  CHANGELOG.md
  grafana-plugin/src/components/IntegrationHowToConnect/IntegrationHowToConnect.tsx
Labels: pr:no public docs

#2846 Enable `FEATURE_INBOUND_EMAIL_ENABLED` by default
  CHANGELOG.md
  engine/settings/base.py
Labels: pr:no public docs

#2849 Skip amazon_sns integration view test
  engine/apps/integrations/tests/test_views.py
Labels: pr:no changelog, pr:no public docs

#2858 add shift swap request demo video to public docs
  docs/sources/on-call-schedules/_index.md
  docs/sources/user-and-team-management/_index.md
Labels: pr:no changelog

#2847 Users search fix
  CHANGELOG.md
  grafana-plugin/e2e-tests/users/usersActions.test.ts
  grafana-plugin/src/components/UsersFilters/UsersFilters.tsx
  grafana-plugin/src/pages/schedule/Schedule.tsx
  grafana-plugin/src/pages/users/Users.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
Labels: pr:no public docs

#2859 increase mobile app verification token TTL from 1 minute to 5 minutes
  CHANGELOG.md
  docker-compose-developer.yml
  engine/apps/mobile_app/models.py
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.tsx
  grafana-plugin/webpack.config.js
Labels: pr:no changelog, pr:no public docs

#2867 Add 'pr: no changelog' label because these PRs dont need to update the changelog
  .github/workflows/update-make-docs.yml
Labels: pr:no changelog

#2862 Minor metrics dashboard updates
  grafana-plugin/src/dashboards/oncall_metrics_dashboard.json
Labels: pr:no changelog, pr:no public docs

#2870 Status to not access grafana headers from mobile request
  engine/apps/grafana_plugin/tests/test_status.py
  engine/apps/grafana_plugin/views/status.py
  engine/common/api_helpers/mixins.py
Labels: pr:no changelog, pr:no public docs

#2871 Update ical export to track primary/overrides calendar using priority
  CHANGELOG.md
  engine/apps/schedules/constants.py
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_on_call_schedule.py
Labels: pr:no public docs

#2856 add comments to uwsgi config + tweak a few settings
  engine/uwsgi.ini
Labels: pr:no changelog, pr:no public docs

#2882 Revert "Bump uwsgi from 2.0.21 to 2.0.22 in /engine"
  engine/requirements.txt
Labels: pr:no changelog, pr:no public docs

#2884 Prevent uWSGI from consuming too much memory
  engine/uwsgi.ini
Labels: pr:no changelog, pr:no public docs

#2887 Fix next step eta for silenced alert groups
  engine/apps/alerts/escalation_snapshot/escalation_snapshot_mixin.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/tasks/check_escalation_finished.py
  engine/apps/alerts/tests/test_alert_group.py
  engine/apps/alerts/tests/test_check_escalation_finished_task.py
  engine/apps/alerts/tests/test_escalation_snapshot_mixin.py
Labels: pr:no changelog, pr:no public docs

#2894 Alerting integration use get for receiver key
  CHANGELOG.md
  engine/apps/alerts/grafana_alerting_sync_manager/grafana_alerting_sync.py
Labels: pr:no public docs

#2892 Always update last_heartbeat_time async
  engine/apps/integrations/views.py
Labels: pr:no changelog, pr:no public docs

#2872 Switch to alpine base image
  CHANGELOG.md
  engine/Dockerfile
  engine/requirements.txt
Labels: pr:no public docs

#2888 refactor apps.mobile_app.tasks into individual task files
  engine/apps/mobile_app/backend.py
  engine/apps/mobile_app/demo_push.py
  engine/apps/mobile_app/tasks.py
  engine/apps/mobile_app/tasks/__init__.py
  engine/apps/mobile_app/tasks/going_oncall_notification.py
  engine/apps/mobile_app/tasks/new_alert_group.py
  engine/apps/mobile_app/tasks/new_shift_swap_request.py
  engine/apps/mobile_app/tests/tasks/__init__.py
  engine/apps/mobile_app/tests/tasks/test_going_oncall_notification.py
  engine/apps/mobile_app/tests/tasks/test_new_alert_group.py
  engine/apps/mobile_app/tests/tasks/test_new_shift_swap_request.py
  engine/apps/mobile_app/tests/test_fcm_relay.py
  engine/apps/mobile_app/tests/test_utils.py
  engine/apps/mobile_app/utils.py
Labels: pr:no changelog, pr:no public docs

#2901 Set next step eta to None if escalation was paused
  engine/apps/alerts/escalation_snapshot/snapshot_classes/escalation_policy_snapshot.py
  engine/apps/alerts/tests/test_escalation_policy_snapshot.py
Labels: pr:no changelog, pr:no public docs

#2895 Fix metrics and dashboard
  CHANGELOG.md
  engine/apps/metrics_exporter/helpers.py
  engine/apps/metrics_exporter/metrics_collectors.py
  grafana-plugin/src/dashboards/oncall_metrics_dashboard.json
  grafana-plugin/src/plugin.json
Labels: pr:no public docs

#2900 rename notify_user_async celery task to notify_user_about_new_alert_group
  engine/apps/mobile_app/backend.py
  engine/apps/mobile_app/tasks/__init__.py
  engine/apps/mobile_app/tasks/new_alert_group.py
  engine/apps/mobile_app/tests/tasks/test_new_alert_group.py
  engine/settings/prod_without_db.py
Labels: pr:no public docs

#2902 Fix slack schedule notification settings dialog
  CHANGELOG.md
  engine/apps/slack/tests/test_interactive_api_endpoint.py
  engine/apps/slack/views.py
Labels: pr:no public docs

#2904 Update appVersion in telegram polling test
  helm/oncall/tests/telegram_polling_deployment_test.yaml
Labels: pr:no changelog, pr:no public docs

#2903 v1.3.29
  CHANGELOG.md
  Makefile
  dev/README.md
  engine/apps/alerts/escalation_snapshot/snapshot_classes/escalation_policy_snapshot.py
  engine/apps/alerts/tests/test_escalation_policy_snapshot.py
  engine/apps/metrics_exporter/helpers.py
  engine/apps/metrics_exporter/metrics_collectors.py
  engine/apps/mobile_app/backend.py
  engine/apps/mobile_app/demo_push.py
  engine/apps/mobile_app/tasks.py
  engine/apps/mobile_app/tasks/__init__.py
  engine/apps/mobile_app/tasks/going_oncall_notification.py
  engine/apps/mobile_app/tasks/new_alert_group.py
  engine/apps/mobile_app/tasks/new_shift_swap_request.py
  engine/apps/mobile_app/tests/tasks/__init__.py
  engine/apps/mobile_app/tests/tasks/test_going_oncall_notification.py
  engine/apps/mobile_app/tests/tasks/test_new_alert_group.py
  engine/apps/mobile_app/tests/tasks/test_new_shift_swap_request.py
  engine/apps/mobile_app/tests/test_fcm_relay.py
  engine/apps/mobile_app/tests/test_utils.py
  engine/apps/mobile_app/utils.py
  engine/apps/slack/tests/test_interactive_api_endpoint.py
  engine/apps/slack/views.py
  engine/settings/base.py
  engine/settings/prod_without_db.py
  grafana-plugin/src/dashboards/oncall_metrics_dashboard.json
  grafana-plugin/src/plugin.json
Labels: pr:no public docs

#2869 Tweaks for integrations
  CHANGELOG.md
  grafana-plugin/src/components/CursorPagination/CursorPagination.tsx
  grafana-plugin/src/components/IntegrationCollapsibleTreeView/IntegrationCollapsibleTreeView.module.scss
  grafana-plugin/src/components/IntegrationCollapsibleTreeView/IntegrationCollapsibleTreeView.tsx
  grafana-plugin/src/components/IntegrationContactPoint/IntegrationContactPoint.tsx
  grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/RemoteFilters/RemoteFilters.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/models/user/user.ts
  grafana-plugin/src/pages/escalation-chains/EscalationChains.tsx
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/index.tsx
  grafana-plugin/src/pages/integration/Integration.helper.ts
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/pages/integrations/Integrations.tsx
  grafana-plugin/src/pages/maintenance/Maintenance.module.css
  grafana-plugin/src/pages/maintenance/Maintenance.tsx
  grafana-plugin/src/pages/outgoing_webhooks/OutgoingWebhooks.tsx
  grafana-plugin/src/pages/routes.tsx
  grafana-plugin/src/pages/schedules/Schedules.tsx
  grafana-plugin/src/plugin.json
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/state/rootBaseStore/index.ts
  grafana-plugin/src/utils/consts.ts
Labels: pr:no public docs

#2919 Show build log in the local env
  Makefile
Labels: pr:no changelog, pr:no public docs

#2914 Update `STEP_NOTIFY_IF_TIME` step description
  engine/apps/alerts/models/escalation_policy.py
Labels: pr:no changelog, pr:no public docs

#2821 Add direct paging events when checking logs for license
  engine/apps/alerts/models/alert_group_log_record.py
Labels: pr:no changelog, pr:no public docs

#2921 Expand users details in filter swaps endpoint
  CHANGELOG.md
  engine/apps/api/serializers/shift_swap.py
  engine/apps/api/tests/test_schedules.py
  engine/apps/api/views/schedule.py
Labels: pr:no public docs

#2927 patch helm broker env variable issue
  CHANGELOG.md
  Makefile
  helm/oncall/templates/_env.tpl
  helm/oncall/tests/__snapshot__/telegram_polling_deployment_test.yaml.snap
  helm/oncall/tests/__snapshot__/wait_for_db_test.yaml.snap
  helm/oncall/tests/redis_env_test.yaml
Labels: pr:no public docs

#2930 Rares/fix npe on migration
  CHANGELOG.md
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/pages/integration/Integration.helper.ts
  grafana-plugin/src/pages/integration/Integration.tsx
Labels: pr:no public docs

#2929 Fix silence for paused escalations or alert groups with empty escalation chain
  CHANGELOG.md
  engine/apps/alerts/escalation_snapshot/escalation_snapshot_mixin.py
  engine/apps/alerts/tests/test_escalation_snapshot_mixin.py
Labels: pr:no public docs

#2923 Add optional param to return shift swaps detailed user information
  CHANGELOG.md
  engine/apps/api/serializers/shift_swap.py
  engine/apps/api/tests/test_shift_swaps.py
  engine/apps/api/views/schedule.py
  engine/apps/api/views/shift_swap.py
Labels: pr:no public docs

#2922 Test celery tasks have queue assignment
  engine/common/tests/test_task_queue_assignment.py
  engine/settings/celery_task_routes.py
  engine/settings/prod_without_db.py
Labels: pr:no changelog, pr:no public docs

#2934 Remove duplicate line
  docs/sources/oncall-api-reference/users.md
Labels: pr:no changelog
