Repository grafana/oncall, pull requests merged in 2023-10, with the labels that each got.

#3092 Fix slack notification for shift end affected by taken swap
  CHANGELOG.md
  engine/apps/alerts/tasks/notify_ical_schedule_shift.py
  engine/apps/alerts/tests/test_notify_ical_schedule_shift.py
  engine/apps/schedules/ical_utils.py
Labels: pr:no public docs

#3075 Update labels and add note for cloud-only integrations in docs
  docs/sources/integrations/amazon-sns/index.md
  docs/sources/integrations/appdynamics/index.md
  docs/sources/integrations/datadog/index.md
  docs/sources/integrations/fabric/index.md
  docs/sources/integrations/jira/index.md
  docs/sources/integrations/newrelic/index.md
  docs/sources/integrations/pingdom/index.md
  docs/sources/integrations/prtg/index.md
  docs/sources/integrations/sentry/index.md
  docs/sources/integrations/servicenow/index.md
  docs/sources/integrations/stackdriver/index.md
  docs/sources/integrations/uptimerobot/index.md
  docs/sources/integrations/zendesk/index.md
Labels: pr:no changelog

#3029 feature: Hardening the Helm deployment with Redis and Postgres TLS
  engine/settings/base.py
  helm/oncall/templates/_env.tpl
  helm/oncall/templates/celery/deployment.yaml
  helm/oncall/templates/engine/deployment.yaml
  helm/oncall/templates/engine/job-migrate.yaml
  helm/oncall/templates/telegram-polling/deployment.yaml
  helm/oncall/tests/__snapshot__/telegram_polling_deployment_test.yaml.snap
  helm/oncall/tests/__snapshot__/wait_for_db_test.yaml.snap
  helm/oncall/tests/extra_volume_mounts_test.yaml
  helm/oncall/tests/mysql_env_test.yaml
  helm/oncall/tests/mysql_password_env_test.yaml
  helm/oncall/tests/postgres_env_test.yaml
  helm/oncall/tests/postgres_password_env_test.yaml
  helm/oncall/tests/rabbitmq_env_test.yaml
  helm/oncall/tests/redis_env_test.yaml
  helm/oncall/tests/redis_password_env_test.yaml
  helm/oncall/tests/telegram_polling_deployment_test.yaml
  helm/oncall/values.yaml
Labels: pr:no changelog, pr:no public docs

#3094 Fix action/webhook API not accepting empty/null user
  CHANGELOG.md
  engine/apps/public_api/serializers/action.py
  engine/apps/public_api/tests/test_custom_actions.py
  engine/apps/public_api/views/action.py
Labels: pr:no public docs

#3114 unskip sms verification e2e test
  grafana-plugin/e2e-tests/alerts/sms.test.ts
Labels: pr:no changelog, pr:no public docs

#3120 v1.3.42
  CHANGELOG.md
  engine/apps/api/serializers/on_call_shifts.py
  engine/apps/api/tests/test_oncall_shift.py
  engine/apps/api/tests/test_schedules.py
  engine/apps/api/views/schedule.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_on_call_schedule.py
  grafana-plugin/e2e-tests/alerts/sms.test.ts
Labels: pr:no public docs

#3097 Fixing broken links in docs
  docs/sources/integrations/_index.md
  docs/sources/integrations/alertmanager/index.md
  docs/sources/integrations/grafana-alerting/index.md
  docs/sources/integrations/inbound-email/index.md
  docs/sources/integrations/sentry/index.md
  docs/sources/integrations/webhook/index.md
  docs/sources/integrations/zabbix/index.md
  docs/sources/notify/ms-teams/index.md
  docs/sources/notify/slack/index.md
  docs/sources/notify/telegram/index.md
  docs/sources/oncall-api-reference/outgoing_webhooks.md
Labels: pr:no changelog, pr:no public docs

#3125 v1.3.43 changelog
  CHANGELOG.md
Labels: pr:no public docs

#3134 Use partial instead of lambda when queuing ack task
  engine/apps/alerts/tasks/acknowledge_reminder.py
Labels: pr:no changelog, pr:no public docs

#3145 Update plugin role permissions
  CHANGELOG.md
  grafana-plugin/src/plugin.json
Labels: pr:no public docs

#3122 Fix inconsistency with API URL returned by plugin status
  CHANGELOG.md
  engine/apps/grafana_plugin/tests/test_status.py
  engine/apps/grafana_plugin/views/status.py
Labels: pr:no public docs

#3123 Add truncation for content beyond 2 lines and show tooltip with original value if content was truncated
  CHANGELOG.md
  grafana-plugin/src/assets/style/global.css
  grafana-plugin/src/assets/style/responsive.css
  grafana-plugin/src/assets/style/utils.css
  grafana-plugin/src/components/MatchMediaTooltip/MatchMediaTooltip.tsx
  grafana-plugin/src/components/TextEllipsisTooltip/TextEllipsisTooltip.tsx
  grafana-plugin/src/components/TooltipBadge/TooltipBadge.tsx
  grafana-plugin/src/containers/TeamName/TeamName.tsx
  grafana-plugin/src/pages/incident/Incident.helpers.tsx
  grafana-plugin/src/pages/incident/Incident.module.scss
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/integrations/Integrations.module.scss
  grafana-plugin/src/pages/integrations/Integrations.tsx
  grafana-plugin/src/pages/outgoing_webhooks/OutgoingWebhooks.tsx
  grafana-plugin/src/pages/schedules/Schedules.module.css
  grafana-plugin/src/pages/schedules/Schedules.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/utils/consts.ts
Labels: pr:no public docs

#3156 Update ical schedule creation/update to trigger final schedule refresh
  CHANGELOG.md
  engine/apps/api/serializers/schedule_ical.py
  engine/apps/api/tests/test_schedules.py
  engine/apps/public_api/serializers/schedules_ical.py
  engine/apps/public_api/tests/test_schedules.py
Labels: pr:no public docs

#3157 Add user TZ information to next shifts per user endpoint
  CHANGELOG.md
  engine/apps/api/tests/test_schedules.py
  engine/apps/api/views/schedule.py
Labels: pr:no public docs

#3100 Build ‘When I am on-call’ for web UI #2915
  CHANGELOG.md
  grafana-plugin/src/containers/Rotation/Rotation.tsx
  grafana-plugin/src/containers/Rotations/ScheduleFinal.tsx
  grafana-plugin/src/containers/Rotations/ScheduleOverrides.tsx
  grafana-plugin/src/containers/Rotations/SchedulePersonal.tsx
  grafana-plugin/src/containers/ScheduleSlot/ScheduleSlot.tsx
  grafana-plugin/src/models/schedule/schedule.helpers.ts
  grafana-plugin/src/models/schedule/schedule.ts
  grafana-plugin/src/models/schedule/schedule.types.ts
  grafana-plugin/src/pages/schedule/Schedule.tsx
  grafana-plugin/src/pages/schedules/Schedules.tsx
Labels: pr:no public docs

#3165 Update shifts public API to improve web shifts support
  CHANGELOG.md
  engine/apps/public_api/serializers/on_call_shifts.py
  engine/apps/public_api/tests/test_on_call_shifts.py
  engine/apps/public_api/views/on_call_shifts.py
Labels: pr:no public docs

#3147 Handle None role when syncing users from Grafana
  CHANGELOG.md
  engine/apps/api/permissions.py
  engine/apps/api/tests/test_alert_group.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/tests/test_alert_receive_channel_template.py
  engine/apps/api/tests/test_channel_filter.py
  engine/apps/api/tests/test_custom_button.py
  engine/apps/api/tests/test_escalation_policy.py
  engine/apps/api/tests/test_integration_heartbeat.py
  engine/apps/api/tests/test_oncall_shift.py
  engine/apps/api/tests/test_organization.py
  engine/apps/api/tests/test_postmortem_messages.py
  engine/apps/api/tests/test_public_api_tokens.py
  engine/apps/api/tests/test_schedule_export.py
  engine/apps/api/tests/test_schedules.py
  engine/apps/api/tests/test_set_general_log_channel.py
  engine/apps/api/tests/test_shift_swaps.py
  engine/apps/api/tests/test_slack_channels.py
  engine/apps/api/tests/test_slack_team_settings.py
  engine/apps/api/tests/test_team.py
  engine/apps/api/tests/test_telegram_channel.py
  engine/apps/api/tests/test_user.py
  engine/apps/api/tests/test_user_groups.py
  engine/apps/api/tests/test_user_schedule_export.py
  engine/apps/api/tests/test_webhooks.py
  engine/apps/api/views/organization.py
  engine/apps/api/views/slack_channel.py
  engine/apps/api/views/slack_team_settings.py
  engine/apps/api/views/user_group.py
  engine/apps/slack/tests/test_reset_slack.py
  engine/apps/slack/tests/test_scenario_steps/test_alert_group_actions.py
  engine/apps/user_management/migrations/0016_alter_user_role.py
  engine/apps/user_management/models/user.py
  engine/apps/user_management/tests/test_sync.py
  engine/conftest.py
Labels: pr:no public docs

#3014 Add labels implementation for integration
  CHANGELOG.md
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/serializers/labels.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/tests/test_labels.py
  engine/apps/api/urls.py
  engine/apps/api/views/alert_receive_channel.py
  engine/apps/api/views/features.py
  engine/apps/api/views/labels.py
  engine/apps/grafana_plugin/helpers/client.py
  engine/apps/labels/__init__.py
  engine/apps/labels/client.py
  engine/apps/labels/migrations/0001_initial.py
  engine/apps/labels/migrations/__init__.py
  engine/apps/labels/models.py
  engine/apps/labels/tasks.py
  engine/apps/labels/tests/__init__.py
  engine/apps/labels/tests/factories.py
  engine/apps/labels/tests/test_labels.py
  engine/apps/labels/tests/test_labels_cache.py
  engine/apps/labels/utils.py
  engine/conftest.py
  engine/settings/base.py
  engine/settings/celery_task_routes.py
  grafana-plugin/package.json
  grafana-plugin/src/components/IntegrationsFilters/IntegrationsFilters.module.css
  grafana-plugin/src/components/IntegrationsFilters/IntegrationsFilters.tsx
  grafana-plugin/src/components/LabelsFilter/LabelsFilter.tsx
  grafana-plugin/src/components/TooltipBadge/TooltipBadge.module.scss
  grafana-plugin/src/components/TooltipBadge/TooltipBadge.tsx
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.helpers.ts
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.module.scss
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/containers/Labels/Labels.module.css
  grafana-plugin/src/containers/Labels/Labels.tsx
  grafana-plugin/src/containers/Labels/LabelsFilter.tsx
  grafana-plugin/src/containers/RemoteFilters/RemoteFilters.helpers.ts
  grafana-plugin/src/containers/RemoteFilters/RemoteFilters.tsx
  grafana-plugin/src/containers/RemoteFilters/RemoteFilters.types.ts
  grafana-plugin/src/containers/Rotations/SchedulePersonal.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.types.ts
  grafana-plugin/src/models/base_store.ts
  grafana-plugin/src/models/filters/filters.ts
  grafana-plugin/src/models/label/label.ts
  grafana-plugin/src/models/label/label.types.ts
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/pages/integrations/Integrations.tsx
  grafana-plugin/src/state/features.ts
  grafana-plugin/src/state/rootBaseStore/index.ts
  grafana-plugin/yarn.lock
Labels: pr:no public docs

#3172 Added mechanism to discard older network requests
  CHANGELOG.md
  grafana-plugin/e2e-tests/users/usersActions.test.ts
  grafana-plugin/src/components/UsersFilters/UsersFilters.tsx
  grafana-plugin/src/containers/RemoteFilters/RemoteFilters.tsx
  grafana-plugin/src/models/schedule/schedule.ts
  grafana-plugin/src/models/user/user.ts
  grafana-plugin/src/pages/incident/Incident.helpers.tsx
  grafana-plugin/src/pages/schedules/Schedules.tsx
  grafana-plugin/src/pages/users/Users.tsx
Labels: pr:no public docs

#3175 Copy change for Schedules
  grafana-plugin/src/pages/escalation-chains/EscalationChains.tsx
  grafana-plugin/src/pages/schedules/Schedules.tsx
Labels: pr:no changelog, pr:no public docs

#3174 Resolution note source mobile app
  CHANGELOG.md
  engine/apps/alerts/migrations/0034_alter_resolutionnote_source.py
  engine/apps/alerts/models/resolution_note.py
  engine/apps/api/serializers/resolution_note.py
  engine/apps/api/tests/test_alert_group.py
  engine/apps/api/tests/test_resolution_note.py
  engine/apps/api/views/alert_group.py
  grafana-plugin/src/models/resolution_note/resolution_note.types.ts
  grafana-plugin/src/pages/incident/Incident.tsx
Labels: pr:no public docs

#3173 Permissions for labels
  CHANGELOG.md
  engine/apps/api/permissions.py
  engine/apps/api/tests/test_labels.py
  engine/apps/api/tests/test_permissions.py
  engine/apps/api/views/labels.py
Labels: pr:no public docs

#3184 Change functions for access control
  CHANGELOG.md
  grafana-plugin/src/components/Unauthorized/Unauthorized.test.tsx
  grafana-plugin/src/components/Unauthorized/index.tsx
  grafana-plugin/src/index.d.ts
  grafana-plugin/src/state/rootBaseStore/index.ts
  grafana-plugin/src/state/rootBaseStore/rootBaseStore.test.ts
Labels: pr:no public docs

#3178 Fix iCal imported schedules related users and next shifts per user
  CHANGELOG.md
  engine/apps/api/tests/test_schedules.py
  engine/apps/api/views/schedule.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_on_call_schedule.py
Labels: pr:no public docs

#3192 Fix channel filter endpoint
  CHANGELOG.md
  engine/apps/alerts/models/channel_filter.py
  engine/apps/api/serializers/channel_filter.py
  engine/apps/api/tests/test_channel_filter.py
  engine/apps/public_api/serializers/routes.py
  engine/apps/public_api/tests/test_routes.py
Labels: pr:no public docs

#3195 Quickfix for getting alert group from slack message payload
  engine/apps/alerts/incident_appearance/renderers/slack_renderer.py
  engine/apps/slack/scenarios/step_mixins.py
  engine/apps/slack/tests/test_scenario_steps/test_alert_group_actions.py
  engine/apps/slack/tests/test_scenario_steps/test_manage_responders.py
  engine/apps/slack/tests/test_slack_renderer.py
Labels: pr:no changelog, pr:no public docs

#2780 Add missing step in Zvonok
  docs/sources/open-source/_index.md
Labels: pr:no changelog

#3203 Add settings to allow detaching integrations server
  engine/engine/integrations_urls.py
  engine/engine/urls.py
  engine/settings/base.py
Labels: pr:no changelog, pr:no public docs

#3176 Upgrade to django 4.2.6 and other deps updates
  CHANGELOG.md
  engine/apps/schedules/ical_events/adapter/amixr_recurring_ical_events_adapter.py
  engine/apps/schedules/models/custom_on_call_shift.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_custom_on_call_shift.py
  engine/apps/social_auth/live_setting_django_strategy.py
  engine/apps/user_management/models/user.py
  engine/requirements.txt
Labels: pr:no public docs

#3208 address some minor direct paging backend issues
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/paging.py
  engine/apps/alerts/tests/test_alert_group.py
  engine/apps/api/tests/test_alert_group.py
Labels: pr:no changelog, pr:no public docs

#3103 add support for datetime on final_shifts API parameters
  CHANGELOG.md
  engine/apps/public_api/serializers/schedules_base.py
  engine/apps/public_api/tests/test_schedules.py
  engine/apps/public_api/views/schedules.py
Labels: pr:no public docs

#3213 fix RBAC authz issue for Slack Alert Group actions
  CHANGELOG.md
  engine/apps/slack/scenarios/distribute_alerts.py
Labels: pr:no public docs

#3187 "Going oncall" notification settings
  CHANGELOG.md
  engine/apps/mobile_app/migrations/0011_alter_mobileappusersettings_going_oncall_notification_timing.py
  engine/apps/mobile_app/models.py
  engine/apps/mobile_app/serializers.py
  engine/apps/mobile_app/tasks/going_oncall_notification.py
  engine/apps/mobile_app/tests/tasks/test_going_oncall_notification.py
  engine/apps/mobile_app/tests/test_user_settings.py
  engine/apps/mobile_app/urls.py
  engine/apps/mobile_app/views.py
Labels: pr:no public docs

#3205 Pagination refactoring/cleanup
  CHANGELOG.md
  grafana-plugin/src/containers/RemoteFilters/RemoteFilters.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/models/alertgroup/alertgroup.ts
  grafana-plugin/src/models/filters/filters.ts
  grafana-plugin/src/models/user/user.ts
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/integrations/Integrations.tsx
  grafana-plugin/src/pages/outgoing_webhooks/OutgoingWebhooks.tsx
  grafana-plugin/src/pages/schedules/Schedules.tsx
  grafana-plugin/src/pages/users/Users.tsx
  grafana-plugin/src/state/rootBaseStore/index.ts
  grafana-plugin/src/utils/consts.ts
Labels: pr:no public docs

#3224 Disable updates for API/terraform shifts in internal API
  CHANGELOG.md
  engine/apps/api/serializers/on_call_shifts.py
  engine/apps/api/tests/test_oncall_shift.py
Labels: pr:no public docs

#3220 few add responders patches
  CHANGELOG.md
  engine/apps/api/serializers/team.py
  engine/apps/api/tests/test_team.py
  engine/apps/api/views/team.py
  engine/apps/api/views/user.py
  grafana-plugin/src/containers/AddResponders/parts/AddRespondersPopup/AddRespondersPopup.module.scss
  grafana-plugin/src/containers/AddResponders/parts/AddRespondersPopup/AddRespondersPopup.tsx
  grafana-plugin/src/models/grafana_team/grafana_team.ts
  grafana-plugin/src/models/grafana_team/grafana_team.types.ts
  grafana-plugin/src/models/user/user.types.ts
Labels: pr:no public docs

#3219 remove is_restricted from frontend codebase
  grafana-plugin/src/models/alertgroup/alertgroup.types.ts
  grafana-plugin/src/pages/incident/Incident.helpers.tsx
  grafana-plugin/src/pages/incident/Incident.tsx
Labels: pr:no changelog, pr:no public docs

#3234 add missing db migrations + add additional backend db migration check to CI
  .github/workflows/linting-and-tests.yml
  engine/apps/alerts/migrations/0035_alter_alertreceivechannel_maintenance_author.py
  engine/apps/schedules/migrations/0017_alter_oncallschedule_polymorphic_ctype.py
  engine/apps/twilioapp/migrations/0008_alter_twiliophonecallsender_account_and_more.py
  engine/apps/user_management/migrations/0017_alter_organization_maintenance_author.py
  engine/apps/zvonok/migrations/0002_alter_zvonokphonecall_phone_call_record.py
Labels: pr:no changelog, pr:no public docs

#3228 remove all references to deprecated AlertGroup.is_restricted field
  engine/apps/alerts/escalation_snapshot/escalation_snapshot_mixin.py
  engine/apps/alerts/incident_appearance/renderers/classic_markdown_renderer.py
  engine/apps/alerts/incident_appearance/renderers/web_renderer.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/api/serializers/alert.py
  engine/apps/api/serializers/alert_group.py
  engine/apps/public_api/serializers/alerts.py
  engine/apps/public_api/serializers/incidents.py
  engine/common/constants/alert_group_restrictions.py
Labels: pr:no changelog, pr:no public docs
