Repository grafana/oncall, pull requests merged in 2023-02, with the labels that each got.

#1264 Add utility function to get readonly db key if defined
  engine/apps/slack/models/slack_message.py
  engine/apps/slack/models/slack_user_identity.py
  engine/common/database.py
  engine/common/tests/test_database.py
Labels: no changelog, no public docs

#1263 Add default slack channel info to direct paging dialog
  engine/apps/api/tests/test_schedules.py
  engine/apps/slack/scenarios/paging.py
Labels: no changelog, no public docs

#1267 Better FCM error handling / retries
  engine/apps/mobile_app/fcm_relay.py
  engine/apps/mobile_app/tasks.py
  engine/apps/mobile_app/tests/test_fcm_relay.py
  engine/apps/mobile_app/tests/test_notify_user.py
Labels: no changelog, no public docs

#1261 Cache web template rendered fields for alert and alertgroup endpoints
  CHANGELOG.md
  engine/apps/api/serializers/alert.py
  engine/apps/api/serializers/alert_group.py
Labels: no public docs

#1248 Use organization ISSUE_COMMANDS_TOKEN with reduced scope
  .github/workflows/issue_commands.yml
Labels: no changelog, no public docs

#1227 Use latest Grafana Container Images
  docker-compose-mysql-rabbitmq.yml
  docker-compose.yml
Labels: no changelog, no public docs

#1243 Correct init command for Postgres Database
  helm/oncall/README.md
Labels: no changelog, no public docs

#1259 Plugin description copy
  grafana-plugin/src/plugin.json
Labels: no changelog, no public docs

#1256 Rares/1083 fix integrations
  CHANGELOG.md
  grafana-plugin/src/containers/AlertRules/AlertRules.tsx
  grafana-plugin/src/containers/IntegrationSettings/IntegrationSettings.tsx
  grafana-plugin/src/pages/integrations/Integrations.tsx
Labels: no public docs

#1141 1097 - Refactor alerts outside DefaultPageLayout
  grafana-plugin/src/PluginPage.tsx
  grafana-plugin/src/containers/Alerts/Alerts.module.scss
  grafana-plugin/src/containers/Alerts/Alerts.tsx
  grafana-plugin/src/containers/DefaultPageLayout/DefaultPageLayout.module.scss
  grafana-plugin/src/containers/DefaultPageLayout/DefaultPageLayout.tsx
  grafana-plugin/src/utils/hooks.tsx
Labels: no changelog, no public docs

#1270 Fix local dev setup slowness
  Makefile
  dev/README.md
  docker-compose-developer.yml
  engine/engine/management/commands/start_celery.py
  engine/settings/dev.py
Labels: no changelog, no public docs

#1269 Keep track of direct paging schedule/importance in logs
  engine/apps/alerts/paging.py
  engine/apps/alerts/tests/test_paging.py
Labels: no changelog, no public docs

#1272 Rares/coming soon
  CHANGELOG.md
  grafana-plugin/src/containers/MobileAppConnection/__snapshots__/MobileAppConnection.test.tsx.snap
  grafana-plugin/src/containers/MobileAppConnection/parts/DownloadIcons/DownloadIcons.module.scss
  grafana-plugin/src/containers/MobileAppConnection/parts/DownloadIcons/__snapshots__/DownloadIcons.test.tsx.snap
  grafana-plugin/src/containers/MobileAppConnection/parts/DownloadIcons/index.tsx
  grafana-plugin/src/pages/incident/Incident.helpers.tsx
  grafana-plugin/src/utils/consts.ts
Labels: no public docs

#1268 Remove mobile_app_settings DynamicSetting
  Makefile
  dev/README.md
  engine/apps/api/views/features.py
  engine/apps/mobile_app/backend.py
  engine/engine/management/commands/enable_mobile_app.py
Labels: no changelog, no public docs

#1207 Mobile app documentation draft.
  docs/sources/mobile-app/_index.md
  docs/sources/open-source/_index.md
  engine/apps/mobile_app/backend.py
Labels: type/docs, no changelog

#1281 Fix on teams switch NPE
  CHANGELOG.md
  grafana-plugin/src/PluginPage.tsx
  grafana-plugin/src/containers/DefaultPageLayout/DefaultPageLayout.tsx
  grafana-plugin/src/containers/GrafanaTeamSelect/GrafanaTeamSelect.tsx
  grafana-plugin/src/navbar/Header/Header.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
Labels: no public docs

#1284 Fix bug with root/dependant alert groups list api endpoint
  CHANGELOG.md
  engine/apps/api/serializers/alert_group.py
Labels: no public docs

#1285 Revert count query in alert groups internal api endpoint
  engine/apps/public_api/serializers/incidents.py
  engine/apps/public_api/views/incidents.py
Labels: no changelog, no public docs

#1279 Disable listing alert groups using Grafana Incident API
  engine/apps/api_for_grafana_incident/views.py
Labels: no changelog, no public docs

#1286 Enable mobile app backend by default on OSS
  CHANGELOG.md
  engine/apps/api/tests/test_features.py
  engine/apps/api/views/features.py
  engine/settings/base.py
Labels: no public docs

#1280 Include alert details in Grafana Incident alert-group endpoint
  engine/apps/api_for_grafana_incident/serializers.py
Labels: no changelog, no public docs

#790 updating warning text color to Grafana Orange
  grafana-plugin/src/style/vars.css
Labels: no changelog, no public docs

#1020 Add database migrations linter
  .github/workflows/ci.yml
  dev/README.md
  engine/apps/alerts/migrations/0001_squashed_initial.py
  engine/apps/alerts/migrations/0002_squashed_initial.py
  engine/apps/alerts/migrations/0003_grafanaalertingcontactpoint_datasource_uid.py
  engine/apps/alerts/migrations/0004_auto_20220711_1106.py
  engine/apps/alerts/migrations/0005_alertgroup_cached_render_for_web.py
  engine/apps/alerts/migrations/0006_alertgroup_alerts_aler_channel_ee84a7_idx.py
  engine/apps/alerts/migrations/0007_populate_web_title_cache.py
  engine/apps/alerts/migrations/0008_alter_alertgrouplogrecord_type.py
  engine/apps/auth_token/migrations/0001_squashed_initial.py
  engine/apps/auth_token/migrations/0002_squashed_initial.py
  engine/apps/auth_token/migrations/0003_auto_20221121_1610.py
  engine/apps/base/migrations/0001_squashed_initial.py
  engine/apps/base/migrations/0002_squashed_initial.py
  engine/apps/base/migrations/0003_delete_organizationlogrecord.py
  engine/apps/email/migrations/0001_initial.py
  engine/apps/heartbeat/migrations/0001_squashed_initial.py
  engine/apps/mobile_app/migrations/0001_initial.py
  engine/apps/oss_installation/migrations/0001_squashed_initial.py
  engine/apps/schedules/migrations/0001_squashed_initial.py
  engine/apps/schedules/migrations/0002_squashed_initial.py
  engine/apps/schedules/migrations/0003_alter_customoncallshift_frequency.py
  engine/apps/schedules/migrations/0004_customoncallshift_until.py
  engine/apps/schedules/migrations/0005_auto_20220704_1947.py
  engine/apps/schedules/migrations/0006_customoncallshift_rotation_start.py
  engine/apps/schedules/migrations/0007_customoncallshift_updated_shift.py
  engine/apps/schedules/migrations/0008_auto_20221201_0809.py
  engine/apps/slack/migrations/0001_squashed_initial.py
  engine/apps/slack/migrations/0002_squashed_initial.py
  engine/apps/telegram/migrations/0001_squashed_initial.py
  engine/apps/telegram/migrations/0002_alter_telegrammessage_message_type.py
  engine/apps/twilioapp/migrations/0001_squashed_initial.py
  engine/apps/twilioapp/migrations/0002_auto_20220604_1008.py
  engine/apps/user_management/migrations/0001_squashed_initial.py
  engine/apps/user_management/migrations/0002_auto_20220705_1214.py
  engine/apps/user_management/migrations/0003_user_hide_phone_number.py
  engine/apps/user_management/migrations/0004_auto_20221025_0316.py
  engine/apps/user_management/migrations/0005_rbac_permissions.py
  engine/apps/user_management/migrations/0006_organization_uuid.py
  engine/apps/user_management/migrations/0007_organization_deleted_at.py
  engine/apps/user_management/migrations/0008_organization_is_grafana_incident_enabled.py
  engine/requirements.txt
  engine/settings/base.py
Labels: no changelog, no public docs

#1297 Make emails case-insensitive for ICal schedules
  CHANGELOG.md
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/tests/calendars/override_email_case_sensitivity.ics
  engine/apps/schedules/tests/test_custom_on_call_shift.py
Labels: no public docs

#1258 Update docs to include details about direct paging command
  docs/sources/integrations/chatops-integrations/configure-slack/index.md
  docs/sources/open-source/_index.md
Labels: type/docs, no changelog

#1290 Polishing design for User tooltip in Schedules
  CHANGELOG.md
  grafana-plugin/src/components/ScheduleUserDetails/ScheduleUserDetails.module.css
  grafana-plugin/src/components/ScheduleUserDetails/ScheduleUserDetails.tsx
  grafana-plugin/src/containers/UsersTimezones/UsersTimezones.tsx
  grafana-plugin/src/pages/incident/Incident.module.css
  grafana-plugin/src/pages/incident/Incident.tsx
Labels: no public docs

#1237 Changes to make screens more responsive + incident status toggler change
  CHANGELOG.md
  grafana-plugin/src/components/MatchMediaTooltip/MatchMediaTooltip.tsx
  grafana-plugin/src/components/SchedulesFilters/SchedulesFilters.module.css
  grafana-plugin/src/components/SchedulesFilters/SchedulesFilters.module.scss
  grafana-plugin/src/components/SchedulesFilters/SchedulesFilters.tsx
  grafana-plugin/src/components/SchedulesFilters/SchedulesFilters.types.ts
  grafana-plugin/src/components/SchedulesFilters_NEW/SchedulesFilters.helpers.ts
  grafana-plugin/src/components/SchedulesFilters_NEW/SchedulesFilters.module.css
  grafana-plugin/src/components/SchedulesFilters_NEW/SchedulesFilters.tsx
  grafana-plugin/src/components/SchedulesFilters_NEW/SchedulesFilters.types.ts
  grafana-plugin/src/components/Tag/Tag.tsx
  grafana-plugin/src/components/Tutorial/Tutorial.module.css
  grafana-plugin/src/components/WithContextMenu/WithContextMenu.tsx
  grafana-plugin/src/containers/AlertRules/AlertRules.module.css
  grafana-plugin/src/containers/AlertRules/AlertRules.tsx
  grafana-plugin/src/containers/AlertRules/parts/index.tsx
  grafana-plugin/src/containers/EscalationChainSteps/EscalationChainSteps.tsx
  grafana-plugin/src/containers/IncidentsFilters/IncidentsFilters.tsx
  grafana-plugin/src/containers/MobileAppConnection/__snapshots__/MobileAppConnection.test.tsx.snap
  grafana-plugin/src/containers/MobileAppConnection/parts/DownloadIcons/__snapshots__/DownloadIcons.test.tsx.snap
  grafana-plugin/src/containers/MobileAppConnection/parts/DownloadIcons/index.tsx
  grafana-plugin/src/containers/RotationForm/ScheduleOverrideForm.tsx
  grafana-plugin/src/img/grafanaGlobalStyles.css
  grafana-plugin/src/models/alertgroup/alertgroup.ts
  grafana-plugin/src/models/alertgroup/alertgroup.types.ts
  grafana-plugin/src/models/cloud/cloud.ts
  grafana-plugin/src/navbar/Header/Header.module.scss
  grafana-plugin/src/navbar/Header/Header.tsx
  grafana-plugin/src/pages/incident/Incident.helpers.tsx
  grafana-plugin/src/pages/incidents/Incidents.module.scss
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/incidents/parts/IncidentDropdown.module.scss
  grafana-plugin/src/pages/incidents/parts/IncidentDropdown.tsx
  grafana-plugin/src/pages/incidents/parts/SilenceButtonCascader.tsx
  grafana-plugin/src/pages/incidents/parts/SilenceSelect.tsx
  grafana-plugin/src/pages/schedule/Schedule.module.css
  grafana-plugin/src/pages/schedules/Schedules.module.css
  grafana-plugin/src/pages/schedules/Schedules.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/style/global.css
  grafana-plugin/src/style/responsive.css
  grafana-plugin/src/style/utils.css
  grafana-plugin/src/style/vars.css
  grafana-plugin/src/utils/consts.ts
Labels: no public docs

#1306 Rework slack login to check backend before redirecting
  CHANGELOG.md
  engine/apps/api/views/auth.py
  engine/apps/social_auth/middlewares.py
  engine/apps/social_auth/urls.py
  engine/apps/social_auth/views.py
  engine/engine/urls.py
  grafana-plugin/src/containers/UserSettings/parts/connectors/SlackConnector.tsx
  grafana-plugin/src/containers/UserSettings/parts/connectors/TelegramConnector.tsx
Labels: no public docs

#704 Cleaning out Incident word from frontend
  CHANGELOG.md
  grafana-plugin/src/components/AlertTemplates/AlertTemplatesForm.tsx
  grafana-plugin/src/containers/AlertReceiveChannelCard/AlertReceiveChannelCard.tsx
  grafana-plugin/src/containers/IncidentMatcher/IncidentMatcher.tsx
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/settings/tabs/MainSettings/MainSettings.tsx
  grafana-plugin/src/plugin.json
Labels: no public docs

#1312 Rework schedules cached ical file values
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_on_call_schedule.py
Labels: no changelog, no public docs

#1215 823 direct paging users
  CHANGELOG.md
  grafana-plugin/CHANGELOG.md
  grafana-plugin/README.md
  grafana-plugin/src/PluginPage.tsx
  grafana-plugin/src/components/GTable/GTable.tsx
  grafana-plugin/src/components/ManualAlertGroup/ManualAlertGroup.module.css
  grafana-plugin/src/components/ManualAlertGroup/ManualAlertGroup.tsx
  grafana-plugin/src/components/ScheduleUserDetails/ScheduleUserDetails.tsx
  grafana-plugin/src/components/SearchInput/SearchInput.module.scss
  grafana-plugin/src/components/SearchInput/SearchInput.tsx
  grafana-plugin/src/containers/DefaultPageLayout/DefaultPageLayout.tsx
  grafana-plugin/src/containers/EscalationVariants/EscalationVariants.helpers.ts
  grafana-plugin/src/containers/EscalationVariants/EscalationVariants.module.scss
  grafana-plugin/src/containers/EscalationVariants/EscalationVariants.tsx
  grafana-plugin/src/containers/EscalationVariants/EscalationVariants.types.ts
  grafana-plugin/src/containers/EscalationVariants/parts/EscalationVariantsPopup.tsx
  grafana-plugin/src/containers/GSelect/GSelect.tsx
  grafana-plugin/src/containers/UserWarningModal/UserWarning.module.scss
  grafana-plugin/src/containers/UserWarningModal/UserWarning.tsx
  grafana-plugin/src/models/alertgroup/alertgroup.ts
  grafana-plugin/src/models/alertgroup/alertgroup.types.ts
  grafana-plugin/src/models/direct_paging/direct_paging.ts
  grafana-plugin/src/models/direct_paging/direct_paging.types.ts
  grafana-plugin/src/models/user/user.ts
  grafana-plugin/src/pages/incident/Incident.helpers.tsx
  grafana-plugin/src/pages/incident/Incident.module.scss
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/incident/parts/PagedUsers.tsx
  grafana-plugin/src/pages/incidents/Incidents.module.scss
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/index.tsx
  grafana-plugin/src/plugin.json
  grafana-plugin/src/state/rootBaseStore/index.ts
  grafana-plugin/src/utils/hooks.tsx
  grafana-plugin/yarn.lock
Labels: pr:no public docs

#1318 Changing names for GitHub Labels
  .github/workflows/verify-changelog-updated.yml
  .github/workflows/verify-public-docs-updated.yml
Labels: pr:no changelog, pr:no public docs

#1320 PD migrator: fix case sensitivity issues
  tools/pagerduty-migrator/migrator/report.py
  tools/pagerduty-migrator/migrator/resources/escalation_policies.py
  tools/pagerduty-migrator/migrator/resources/integrations.py
  tools/pagerduty-migrator/migrator/resources/schedules.py
  tools/pagerduty-migrator/migrator/tests/test_matching.py
  tools/pagerduty-migrator/migrator/tests/test_matching_case_sensitivity.py
  tools/pagerduty-migrator/migrator/tests/test_user_matching.py
Labels: pr:no changelog, pr:no public docs

#1325 Improve PD migrator traceback on HTTP 400
  tools/pagerduty-migrator/migrator/oncall_api_client.py
Labels: pr:no changelog, pr:no public docs

#1327 PD migrator: handle resource names with extra spaces
  tools/pagerduty-migrator/migrator/report.py
  tools/pagerduty-migrator/migrator/resources/escalation_policies.py
  tools/pagerduty-migrator/migrator/resources/integrations.py
  tools/pagerduty-migrator/migrator/resources/schedules.py
  tools/pagerduty-migrator/migrator/tests/test_matching_extra_spaces.py
Labels: pr:no changelog, pr:no public docs

#1329 Show direct paging integrations in list filter options
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/views/alert_receive_channel.py
Labels: pr:no changelog, pr:no public docs

#1313 Handle OnCall gateway connector delete 204
  .github/ISSUE_TEMPLATE/issue-template.md
  engine/common/oncall_gateway/oncall_gateway_client.py
Labels: pr:no changelog, pr:no public docs

#1342 Fix too long declare incident link
  CHANGELOG.md
  engine/apps/alerts/models/alert_group.py
Labels: pr:no public docs

#1344 Release 1.1.25
  .github/ISSUE_TEMPLATE/issue-template.md
  CHANGELOG.md
  engine/apps/alerts/models/alert_group.py
  engine/common/oncall_gateway/oncall_gateway_client.py
Labels: pr:no public docs

#1311 Fixing the checking filters for incidents from the store
  grafana-plugin/src/containers/IncidentsFilters/IncidentsFilters.tsx
Labels: pr:no changelog, pr:no public docs

#1308 Explanation message added to confirmation of deleting rotation
  grafana-plugin/src/containers/RotationForm/RotationForm.module.css
  grafana-plugin/src/containers/RotationForm/RotationForm.tsx
Labels: pr:no changelog, pr:no public docs

#1350 Update phone verification error message
  grafana-plugin/src/containers/UserSettings/parts/tabs/PhoneVerification/PhoneVerification.tsx
Labels: pr:no changelog, pr:no public docs

#1354 Add ratelimit for phone number verification
  CHANGELOG.md
  engine/apps/api/tests/test_user.py
  engine/apps/api/throttlers/__init__.py
  engine/apps/api/throttlers/phone_verification_throttler.py
  engine/apps/api/throttlers/test_call_throttler.py
  engine/apps/api/views/user.py
  engine/apps/public_api/tests/test_ratelimit.py
  engine/apps/public_api/throttlers/user_throttle.py
  engine/common/api_helpers/custom_rate_scoped_throttler.py
Labels: pr:no public docs

#1301 Update publishing workflows to use organization secret
  .github/workflows/publish-technical-documentation-next.yml
  .github/workflows/publish-technical-documentation-release.yml
Labels: type/docs, pr:no changelog

#1347 code-ify dependabot configuration
  .github/dependabot.yml
Labels: pr:no changelog, pr:no public docs

#1373 Add Google reCAPTCHA for mobile app phone verification
  CHANGELOG.md
  engine/apps/api/serializers/user.py
  engine/apps/api/tests/test_user.py
  engine/apps/api/views/user.py
  engine/requirements.txt
  engine/settings/base.py
  grafana-plugin/src/containers/UserSettings/parts/tabs/PhoneVerification/PhoneVerification.tsx
  grafana-plugin/src/models/user/user.ts
  grafana-plugin/src/network/index.ts
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/style/global.css
  grafana-plugin/src/utils/consts.ts
  grafana-plugin/src/utils/loadJs.ts
Labels: pr:no public docs

#1213 Cleanup ScenarioStep
  engine/apps/alerts/escalation_snapshot/escalation_snapshot_mixin.py
  engine/apps/alerts/incident_appearance/renderers/slack_renderer.py
  engine/apps/integrations/tasks.py
  engine/apps/slack/alert_group_slack_service.py
  engine/apps/slack/models/slack_action_record.py
  engine/apps/slack/models/slack_message.py
  engine/apps/slack/scenarios/alertgroup_appearance.py
  engine/apps/slack/scenarios/declare_incident.py
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/slack/scenarios/invited_to_channel.py
  engine/apps/slack/scenarios/manual_incident.py
  engine/apps/slack/scenarios/notification_delivery.py
  engine/apps/slack/scenarios/onboarding.py
  engine/apps/slack/scenarios/paging.py
  engine/apps/slack/scenarios/profile_update.py
  engine/apps/slack/scenarios/resolution_note.py
  engine/apps/slack/scenarios/scenario_step.py
  engine/apps/slack/scenarios/schedules.py
  engine/apps/slack/scenarios/slack_channel.py
  engine/apps/slack/scenarios/slack_channel_integration.py
  engine/apps/slack/scenarios/slack_usergroup.py
  engine/apps/slack/scenarios/step_mixins.py
  engine/apps/slack/tasks.py
  engine/apps/slack/views.py
Labels: pr:no changelog, pr:no public docs

#1377 Revert "Rework schedules cached ical file values"
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_on_call_schedule.py
Labels: pr:no changelog, pr:no public docs

#1381 Fix load of ical file from google
  engine/apps/schedules/ical_utils.py
  engine/common/api_helpers/utils.py
Labels: pr:no changelog, pr:no public docs

#1382 Revert "Revert "Rework schedules cached ical file values""
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_on_call_schedule.py
Labels: pr:no changelog, pr:no public docs

#1383 dev -> main
  .github/dependabot.yml
  .github/workflows/publish-technical-documentation-next.yml
  .github/workflows/publish-technical-documentation-release.yml
  CHANGELOG.md
  engine/apps/alerts/escalation_snapshot/escalation_snapshot_mixin.py
  engine/apps/alerts/incident_appearance/renderers/slack_renderer.py
  engine/apps/api/serializers/user.py
  engine/apps/api/tests/test_user.py
  engine/apps/api/throttlers/__init__.py
  engine/apps/api/throttlers/phone_verification_throttler.py
  engine/apps/api/throttlers/test_call_throttler.py
  engine/apps/api/views/user.py
  engine/apps/integrations/tasks.py
  engine/apps/public_api/tests/test_ratelimit.py
  engine/apps/public_api/throttlers/user_throttle.py
  engine/apps/schedules/ical_utils.py
  engine/apps/slack/alert_group_slack_service.py
  engine/apps/slack/models/slack_action_record.py
  engine/apps/slack/models/slack_message.py
  engine/apps/slack/scenarios/alertgroup_appearance.py
  engine/apps/slack/scenarios/declare_incident.py
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/slack/scenarios/invited_to_channel.py
  engine/apps/slack/scenarios/manual_incident.py
  engine/apps/slack/scenarios/notification_delivery.py
  engine/apps/slack/scenarios/onboarding.py
  engine/apps/slack/scenarios/paging.py
  engine/apps/slack/scenarios/profile_update.py
  engine/apps/slack/scenarios/resolution_note.py
  engine/apps/slack/scenarios/scenario_step.py
  engine/apps/slack/scenarios/schedules.py
  engine/apps/slack/scenarios/slack_channel.py
  engine/apps/slack/scenarios/slack_channel_integration.py
  engine/apps/slack/scenarios/slack_usergroup.py
  engine/apps/slack/scenarios/step_mixins.py
  engine/apps/slack/tasks.py
  engine/apps/slack/views.py
  engine/common/api_helpers/custom_rate_scoped_throttler.py
  engine/common/api_helpers/utils.py
  engine/requirements.txt
  engine/settings/base.py
  grafana-plugin/src/containers/UserSettings/parts/tabs/PhoneVerification/PhoneVerification.tsx
  grafana-plugin/src/models/alertgroup/alertgroup.types.ts
  grafana-plugin/src/models/user/user.ts
  grafana-plugin/src/network/index.ts
  grafana-plugin/src/pages/incident/Incident.helpers.tsx
  grafana-plugin/src/pages/incident/Incident.module.scss
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/style/global.css
  grafana-plugin/src/utils/consts.ts
  grafana-plugin/src/utils/loadJs.ts
Labels: pr:no public docs

#1346 trigger github actions jobs on merge_group event
  .github/workflows/ci.yml
  .github/workflows/snyk.yml
  .github/workflows/verify-changelog-updated.yml
  .github/workflows/verify-public-docs-updated.yml
Labels: pr:no changelog, pr:no public docs

#1388 don't run changelog/public-docs CI checks on merge_group Github events
  .github/workflows/verify-changelog-updated.yml
  .github/workflows/verify-public-docs-updated.yml
Labels: pr:no changelog, pr:no public docs

#1340 Refactor maintenance
  engine/apps/alerts/escalation_snapshot/escalation_snapshot_mixin.py
  engine/apps/alerts/incident_appearance/renderers/slack_renderer.py
  engine/apps/alerts/models/alert.py
  engine/apps/alerts/models/alert_group_log_record.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/models/maintainable_object.py
  engine/apps/alerts/tasks/distribute_alert.py
  engine/apps/alerts/tasks/escalate_alert_group.py
  engine/apps/alerts/tasks/send_update_log_report_signal.py
  engine/apps/api/tests/conftest.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/slack/representatives/alert_group_representative.py
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/slack/tests/test_scenario_steps/test_distribute_alerts.py
  engine/apps/user_management/models/organization.py
Labels: pr:no changelog, pr:no public docs

#1389 Release v1.1.28
  .github/workflows/ci.yml
  .github/workflows/snyk.yml
  CHANGELOG.md
  engine/apps/alerts/escalation_snapshot/escalation_snapshot_mixin.py
  engine/apps/alerts/incident_appearance/renderers/slack_renderer.py
  engine/apps/alerts/models/alert.py
  engine/apps/alerts/models/alert_group_log_record.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/models/maintainable_object.py
  engine/apps/alerts/tasks/distribute_alert.py
  engine/apps/alerts/tasks/escalate_alert_group.py
  engine/apps/alerts/tasks/send_update_log_report_signal.py
  engine/apps/api/tests/conftest.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/slack/representatives/alert_group_representative.py
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/slack/tests/test_scenario_steps/test_distribute_alerts.py
  engine/apps/user_management/models/organization.py
  grafana-plugin/src/containers/UserSettings/parts/tabs/PhoneVerification/PhoneVerification.tsx
  grafana-plugin/src/models/user/user.ts
  grafana-plugin/src/utils/index.ts
  grafana-plugin/yarn.lock
Labels: pr:no changelog, pr:no public docs

#1317 PD migrator: migrate on-call shifts using public API
  CHANGELOG.md
  engine/apps/public_api/serializers/on_call_shifts.py
  engine/apps/public_api/tests/test_schedules.py
  engine/apps/public_api/views/schedules.py
  tools/pagerduty-migrator/migrator/__main__.py
  tools/pagerduty-migrator/migrator/config.py
  tools/pagerduty-migrator/migrator/report.py
  tools/pagerduty-migrator/migrator/resources/schedules.py
  tools/pagerduty-migrator/migrator/resources/users.py
  tools/pagerduty-migrator/migrator/tests/test_matching.py
  tools/pagerduty-migrator/migrator/tests/test_matching_case_sensitivity.py
  tools/pagerduty-migrator/migrator/tests/test_matching_extra_spaces.py
  tools/pagerduty-migrator/migrator/tests/test_schedules.py
Labels: pr:no public docs

#1393 patch minor sync issue when HTTP 302 is received from Grafana API instance
  CHANGELOG.md
  engine/apps/grafana_plugin/helpers/client.py
  engine/apps/grafana_plugin/tests/test_grafana_api_client.py
  engine/apps/user_management/sync.py
  engine/apps/user_management/tests/test_sync.py
Labels: pr:no public docs

#1394 Release v1.1.29
  CHANGELOG.md
  engine/apps/alerts/tasks/notify_all.py
  engine/apps/alerts/tasks/notify_group.py
  engine/apps/grafana_plugin/helpers/client.py
  engine/apps/grafana_plugin/tests/test_grafana_api_client.py
  engine/apps/public_api/serializers/on_call_shifts.py
  engine/apps/public_api/tests/test_schedules.py
  engine/apps/public_api/views/schedules.py
  engine/apps/user_management/sync.py
  engine/apps/user_management/tests/test_sync.py
  tools/pagerduty-migrator/migrator/__main__.py
  tools/pagerduty-migrator/migrator/config.py
  tools/pagerduty-migrator/migrator/report.py
  tools/pagerduty-migrator/migrator/resources/schedules.py
  tools/pagerduty-migrator/migrator/resources/users.py
  tools/pagerduty-migrator/migrator/tests/test_matching.py
  tools/pagerduty-migrator/migrator/tests/test_matching_case_sensitivity.py
  tools/pagerduty-migrator/migrator/tests/test_matching_extra_spaces.py
  tools/pagerduty-migrator/migrator/tests/test_schedules.py
Labels: pr:no public docs

#1397 Fix/rewrite flaky schedule tests
  engine/apps/api/tests/test_schedules.py
  engine/apps/public_api/tests/test_schedule_export.py
  engine/apps/public_api/tests/test_schedules.py
Labels: pr:no changelog, pr:no public docs

#804 tabs added to url for chatops
  grafana-plugin/src/pages/settings/tabs/ChatOps/ChatOps.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
Labels: pr:no changelog, pr:no public docs

#1407 PD migrator: handle deactivated users in PD when migrating schedules
  tools/pagerduty-migrator/migrator/resources/schedules.py
  tools/pagerduty-migrator/migrator/tests/test_schedules.py
Labels: pr:no changelog, pr:no public docs

#1348 Append grafana styles to head instead of referencing the wrong path
  CHANGELOG.md
  grafana-plugin/package.json
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/yarn.lock
Labels: pr:no public docs

#1402 Change Organization Deleted/Moved Precedence
  engine/apps/auth_token/auth.py
  engine/apps/integrations/mixins/alert_channel_defining_mixin.py
Labels: pr:no changelog, pr:no public docs

#1309 Add schedule pagination to plugin API
  CHANGELOG.md
  engine/apps/api/tests/test_schedules.py
  engine/apps/api/views/schedule.py
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/containers/EscalationVariants/parts/EscalationVariantsPopup.tsx
  grafana-plugin/src/models/schedule/schedule.ts
  grafana-plugin/src/models/user/user.ts
  grafana-plugin/src/pages/schedules/Schedules.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/utils/index.ts
Labels: pr:no public docs

#1411 PD migrator: create shifts in UTC timezone
  tools/pagerduty-migrator/migrator/__main__.py
  tools/pagerduty-migrator/migrator/resources/schedules.py
  tools/pagerduty-migrator/migrator/tests/test_schedules.py
Labels: pr:no changelog, pr:no public docs

#1412 fixed UI permission related bug where Editors could not export their user iCal link
  CHANGELOG.md
  grafana-plugin/src/containers/UserSettings/parts/connectors/ICalConnector.tsx
Labels: pr:no public docs

#1400 Get reCAPTCHA site key from backend env
  CHANGELOG.md
  engine/apps/grafana_plugin/views/sync.py
  engine/settings/base.py
  grafana-plugin/src/containers/UserSettings/parts/tabs/PhoneVerification/PhoneVerification.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/state/plugin/index.ts
  grafana-plugin/src/state/plugin/plugin.test.ts
  grafana-plugin/src/state/rootBaseStore/index.ts
  grafana-plugin/src/utils/consts.ts
Labels: pr:no public docs

#1414 Use UTC instead of Etc/UTC when passing tz to dateutil rrule
  CHANGELOG.md
  engine/apps/schedules/models/custom_on_call_shift.py
  engine/apps/schedules/tests/test_custom_on_call_shift.py
Labels: pr:no public docs

#1401 Matiasb/fix task refresh ical when empty value
  CHANGELOG.md
  engine/apps/alerts/tasks/notify_ical_schedule_shift.py
  engine/apps/schedules/tasks/refresh_ical_files.py
  engine/apps/schedules/tests/test_tasks_refresh_ical_files.py
Labels: pr:no public docs

#1410 Fix NPE on ScheduleForm
  grafana-plugin/src/pages/schedule/Schedule.tsx
Labels: pr:no changelog, pr:no public docs

#1356 #415 #1292 #940 #1293 #1002 bug fixes
  CHANGELOG.md
  grafana-plugin/src/components/Modal/Modal.module.css
  grafana-plugin/src/components/UserGroups/UserGroups.module.css
  grafana-plugin/src/containers/RotationForm/RotationForm.module.css
  grafana-plugin/src/containers/RotationForm/RotationForm.tsx
  grafana-plugin/src/containers/ScheduleSlot/ScheduleSlot.module.css
  grafana-plugin/src/containers/ScheduleSlot/ScheduleSlot.tsx
  grafana-plugin/src/img/grafanaGlobalStyles.css
  grafana-plugin/src/models/schedule/schedule.ts
  grafana-plugin/src/pages/integrations/Integrations.tsx
  grafana-plugin/src/pages/schedule/Schedule.module.css
  grafana-plugin/src/pages/schedule/Schedule.tsx
  grafana-plugin/src/pages/schedules/Schedules.module.css
Labels: pr:no public docs

#1417 Show 100 latest alerts on alert group page
  CHANGELOG.md
  engine/apps/api/serializers/alert_group.py
  engine/apps/api/tests/test_alert_group.py
  grafana-plugin/src/pages/incident/Incident.tsx
Labels: pr:no public docs
