Repository grafana/oncall, pull requests merged in 2024-07, with the labels that each got.

#4607 Make Slack URLs work without trailing slashes
  engine/apps/slack/urls.py
Labels: pr:no public docs, release:ignore

#4613 Update channel filter model and API to allow label-based routing
  engine/apps/alerts/migrations/0052_alter_channelfilter_filtering_term_type.py
  engine/apps/alerts/models/channel_filter.py
  engine/apps/alerts/tests/test_channel_filter.py
  engine/apps/api/serializers/channel_filter.py
  engine/apps/api/tests/test_channel_filter.py
Labels: pr:no public docs, release:ignore

#4608 don't force create default user notification policies
  docs/sources/oncall-api-reference/personal_notification_rules.md
  engine/apps/alerts/incident_log_builder/incident_log_builder.py
  engine/apps/alerts/tasks/notify_group.py
  engine/apps/alerts/tasks/notify_user.py
  engine/apps/api/views/user_notification_policy.py
  engine/apps/base/models/user_notification_policy.py
  engine/apps/base/tests/test_user_notification_policy.py
  engine/apps/public_api/views/personal_notifications.py
  engine/apps/user_management/models/user.py
  engine/apps/user_management/tests/test_sync.py
  engine/common/exceptions/__init__.py
  engine/common/exceptions/exceptions.py
Labels: release:patch

#4575 Add filtering by team, is_currently_oncall and search on the user page
  Tiltfile
  engine/apps/api/views/user.py
  grafana-plugin/e2e-tests/users/usersActions.test.ts
  grafana-plugin/src/models/user/user.helpers.tsx
  grafana-plugin/src/models/user/user.ts
  grafana-plugin/src/pages/users/Users.styles.ts
  grafana-plugin/src/pages/users/Users.tsx
Labels: pr:no public docs, release:enhancement

#4612 Fix column caret display on schedules
  grafana-plugin/src/components/GTable/GTable.tsx
  grafana-plugin/src/components/Table/Table.styles.ts
  grafana-plugin/src/containers/ServiceNowConfigDrawer/ServiceNowTokenSection.tsx
  grafana-plugin/src/pages/schedules/Schedules.styles.ts
  grafana-plugin/src/pages/schedules/Schedules.tsx
Labels: pr:no public docs, release:patch

#4615 Leftover tweaks
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/components/Policy/NotificationPolicy.tsx
  grafana-plugin/src/components/Policy/Policy.consts.ts
  grafana-plugin/src/pages/incident/Incident.helpers.tsx
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/incidents/parts/SilenceButtonCascader.tsx
  grafana-plugin/src/pages/incidents/parts/SilenceSelect.tsx
Labels: pr:no public docs, release:ignore

#4621 fix faro reporting errors from local env
  grafana-plugin/src/utils/consts.ts
Labels: pr:no public docs, release:ignore

#4625 remove duplicated Table component
  grafana-plugin/src/components/GTable/GTable.tsx
  grafana-plugin/src/components/Table/Table.styles.ts
  grafana-plugin/src/components/Table/Table.tsx
  grafana-plugin/src/pages/schedules/Schedules.styles.ts
  grafana-plugin/src/pages/schedules/Schedules.tsx
Labels: pr:no public docs, release:ignore

#4622 Webhook form - changed Forward all
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookFormFields.tsx
Labels: pr:no public docs, release:patch

#4626 Handle unexpected recipient value. Add logging.
  engine/apps/email/inbound.py
Labels: pr:no public docs, release:ignore

#4604 Sync teams on user creation during first login
  .github/CODEOWNERS
  engine/apps/auth_token/auth.py
  engine/apps/auth_token/tests/test_plugin_auth.py
  engine/apps/grafana_plugin/tests/test_sync_v2.py
  engine/apps/grafana_plugin/views/install_v2.py
  engine/apps/grafana_plugin/views/sync_v2.py
  engine/apps/user_management/sync.py
  engine/apps/user_management/tests/test_sync.py
  grafana-plugin/pkg/plugin/proxy.go
  grafana-plugin/pkg/plugin/sync.go
Labels: pr:no public docs, release:ignore

#4627 Tweak chatops-proxy sync
  engine/apps/chatops_proxy/tasks.py
  engine/settings/celery_task_routes.py
Labels: pr:no public docs, release:ignore

#4628 notify user task patch + small update to user notification rules public API docs
  docs/sources/oncall-api-reference/personal_notification_rules.md
  engine/apps/alerts/tasks/notify_user.py
Labels: release:patch

#4633 Don't retry cleanup tasks
  engine/apps/grafana_plugin/tasks/sync.py
Labels: pr:no public docs, release:patch

#3927 Add tilt button to run pytest, fix local dev config for pytest, minor improvements to til
  Tiltfile
  dev/helm-local.yml
  engine/apps/alerts/tests/test_alert_receiver_channel.py
  engine/apps/integrations/tasks.py
  engine/apps/webhooks/tests/test_webhook.py
  engine/settings/dev.py
  engine/settings/prod_without_db.py
Labels: pr:no public docs, release:ignore

#4620 install Mage, Go and build plugin backend on Github CI
  .github/actions/build-sign-and-package-plugin/action.yml
Labels: pr:no public docs, release:ignore

#4637 Remove mention from aler group main slack message
  engine/apps/alerts/incident_appearance/renderers/slack_renderer.py
Labels: pr:no public docs, release:patch

#4636 Add misc useful scripts using public API
  tools/scripts/discord_webhooks.py
  tools/scripts/mattermost_webhooks.py
  tools/scripts/oncall_hours_report.py
  tools/scripts/oncall_reports.py
  tools/scripts/readme.md
  tools/scripts/shift_shifts.py
  tools/scripts/swap_requests_workday.py
Labels: pr:no public docs, release:ignore

#4647 fix outgoing webhook form race condition which causes integrations to sometimes not be populated
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookFormFields.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
Labels: pr:no public docs, release:patch

#4642 Show incident button first when alert group is acknowledged
  engine/apps/alerts/incident_appearance/renderers/slack_renderer.py
  engine/apps/slack/tests/test_slack_renderer.py
Labels: pr:no public docs, release:ignore

#4638 Fix monthly masked rotation bug
  grafana-plugin/src/containers/RotationForm/RotationForm.tsx
Labels: pr:no public docs, release:patch

#4658 run `mage buildAll || true` when building the plugin
  .github/actions/build-sign-and-package-plugin/action.yml
Labels: pr:no public docs, release:ignore

#4424 Enable schedule view e2e test
  grafana-plugin/e2e-tests/schedules/scheduleView.test.ts
  grafana-plugin/src/containers/TimelineMarks/TimelineMarks.tsx
  grafana-plugin/src/pages/schedule/Schedule.tsx
Labels: pr:no public docs, release:ignore

#4660 Fix changing recurrence for weekday masked shifts
  grafana-plugin/src/containers/RotationForm/RotationForm.tsx
Labels: pr:no public docs, release:patch

#4655 Handle inbound email integration alert getting multiple recipients
  engine/apps/email/inbound.py
  engine/apps/email/tests/test_inbound_email.py
Labels: pr:no public docs, release:patch

#4649 Allow empty labels routing
  engine/apps/alerts/models/channel_filter.py
  engine/apps/alerts/tests/test_channel_filter.py
  engine/apps/api/serializers/channel_filter.py
  engine/apps/api/tests/test_channel_filter.py
Labels: pr:no public docs, release:ignore

#4661 Fix `start_sync_org_with_chatops_proxy` crontab
  engine/settings/base.py
Labels: pr:no public docs, release:ignore

#4662 Make docs clearer for "Notify users one by one" policy
  docs/sources/configure/escalation-chains-and-routes/index.md
Labels: release:ignore

#4641 Add slack button to show log report
  engine/apps/alerts/incident_appearance/renderers/slack_renderer.py
  engine/apps/slack/scenarios/alertgroup_timeline.py
  engine/apps/slack/scenarios/slack_renderer.py
  engine/apps/slack/views.py
Labels: pr:no public docs, release:patch

#4671 Fix Slack channel and user group values not populating on first visit of schedule notification settings
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/containers/AlertRules/parts/connectors/MSTeamsConnector.tsx
  grafana-plugin/src/containers/AlertRules/parts/connectors/SlackConnector.tsx
  grafana-plugin/src/containers/AlertRules/parts/connectors/TelegramConnector.tsx
  grafana-plugin/src/containers/AttachIncidentForm/AttachIncidentForm.tsx
  grafana-plugin/src/containers/EscalationChainForm/EscalationChainForm.tsx
  grafana-plugin/src/containers/GrafanaTeamSelect/GrafanaTeamSelect.tsx
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/containers/MaintenanceForm/MaintenanceForm.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookFormFields.tsx
  grafana-plugin/src/containers/ScheduleForm/ScheduleForm.tsx
  grafana-plugin/src/containers/UserSettings/parts/tabs/GoogleCalendar/GoogleCalendar.tsx
  grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/SlackSettings/SlackSettings.tsx
Labels: pr:no public docs, release:patch

#3850 Allow routing via labels on the Integration page
  engine/apps/alerts/migrations/0052_alter_channelfilter_filtering_term_type.py
  engine/apps/alerts/migrations/0053_channelfilter_filtering_labels.py
  engine/apps/alerts/models/channel_filter.py
  engine/apps/alerts/tests/test_channel_filter.py
  engine/apps/api/serializers/channel_filter.py
  engine/apps/api/tests/test_channel_filter.py
  grafana-plugin/src/assets/style/utils.css
  grafana-plugin/src/components/IntegrationCollapsibleTreeView/IntegrationCollapsibleTreeView.styles.ts
  grafana-plugin/src/components/IntegrationSendDemoAlertModal/IntegrationSendDemoAlertModal.tsx
  grafana-plugin/src/components/LabelsTooltipBadge/LabelsTooltipBadge.tsx
  grafana-plugin/src/components/MonacoEditor/MonacoEditor.tsx
  grafana-plugin/src/components/ScheduleQualityDetails/ScheduleQualityProgressBar.styles.ts
  grafana-plugin/src/components/Text/Text.styles.ts
  grafana-plugin/src/components/UserGroups/UserGroups.styles.ts
  grafana-plugin/src/containers/ColumnsSelectorWrapper/ColumnsModal.tsx
  grafana-plugin/src/containers/ColumnsSelectorWrapper/ColumnsSelectorWrapper.styles.ts
  grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.module.scss
  grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.module.scss
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationContainers/RouteHeading.tsx
  grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
  grafana-plugin/src/containers/RotationForm/parts/UserItem.tsx
  grafana-plugin/src/containers/RouteLabelsDisplay/RouteLabelsDisplay.tsx
  grafana-plugin/src/containers/ScheduleSlot/ScheduleSlot.tsx
  grafana-plugin/src/containers/TemplatePreview/TemplatePreview.tsx
  grafana-plugin/src/containers/TemplateResult/TemplateResult.tsx
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
  grafana-plugin/src/containers/WebhooksTemplateEditor/WebhooksTemplateEditor.tsx
  grafana-plugin/src/models/alertgroup/alertgroup.helpers.ts
  grafana-plugin/src/models/channel_filter/channel_filter.types.ts
  grafana-plugin/src/models/label/label.helpers.ts
  grafana-plugin/src/models/label/label.ts
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/integration/CommonIntegration.helper.ts
  grafana-plugin/src/pages/integration/Integration.module.scss
  grafana-plugin/src/pages/integrations/Integrations.styles.tsx
  grafana-plugin/src/styles/utils.styles.ts
Labels: pr:no public docs, release:enhancement

#4674 Allow submitting forms in the UI by pressing "Enter"
  grafana-plugin/src/components/ManualAlertGroup/ManualAlertGroup.tsx
  grafana-plugin/src/containers/ApiTokenSettings/ApiTokenForm.module.css
  grafana-plugin/src/containers/ApiTokenSettings/ApiTokenForm.tsx
  grafana-plugin/src/containers/EscalationChainForm/EscalationChainForm.tsx
Labels: pr:no public docs, release:patch

#4665 Add additional information to the reports script
  tools/scripts/oncall_reports.py
Labels: pr:no public docs, release:ignore

#4675 explicitly install oncall resources in default namespace
  Tiltfile
Labels: pr:no public docs, release:ignore

#4678 bump nodejs version to latest stable
  .github/actions/install-frontend-dependencies/action.yml
  dev/README.md
  grafana-plugin/Dockerfile.dev
  grafana-plugin/package.json
  grafana-plugin/yarn.lock
Labels: pr:no public docs, release:ignore

#4457 User notifications bundle
  engine/apps/alerts/constants.py
  engine/apps/alerts/migrations/0054_usernotificationbundle_bundlednotification_and_more.py
  engine/apps/alerts/models/__init__.py
  engine/apps/alerts/models/user_has_notification.py
  engine/apps/alerts/models/user_notification_bundle.py
  engine/apps/alerts/paging.py
  engine/apps/alerts/tasks/notify_user.py
  engine/apps/alerts/tests/factories.py
  engine/apps/alerts/tests/test_notify_user.py
  engine/apps/metrics_exporter/helpers.py
  engine/apps/metrics_exporter/tasks.py
  engine/apps/metrics_exporter/tests/test_update_metrics_cache.py
  engine/apps/phone_notifications/phone_backend.py
  engine/conftest.py
  engine/settings/base.py
  engine/settings/celery_task_routes.py
Labels: pr:no public docs, release:patch

#4676 Fix user search param name when adding participants
  grafana-plugin/src/containers/AddResponders/parts/AddRespondersPopup/AddRespondersPopup.module.scss
  grafana-plugin/src/containers/AddResponders/parts/AddRespondersPopup/AddRespondersPopup.tsx
  grafana-plugin/src/models/user/user.helpers.tsx
  grafana-plugin/src/models/user/user.ts
  grafana-plugin/src/pages/users/Users.tsx
Labels: pr:no public docs, release:patch

#4677 Only run cleanup for integrations deleted recently
  engine/apps/grafana_plugin/tasks/sync.py
  engine/settings/base.py
  engine/settings/celery_task_routes.py
Labels: pr:no public docs, release:patch

#4624 Add method to send notification bundle by SMS
  engine/apps/alerts/incident_appearance/renderers/base_renderer.py
  engine/apps/alerts/incident_appearance/renderers/sms_renderer.py
  engine/apps/alerts/tests/test_alert_group_renderer.py
  engine/apps/exotel/status_callback.py
  engine/apps/phone_notifications/migrations/0003_smsrecord_represents_bundle_uuid.py
  engine/apps/phone_notifications/models/sms.py
  engine/apps/phone_notifications/phone_backend.py
  engine/apps/phone_notifications/tests/test_phone_backend_sms.py
  engine/apps/twilioapp/status_callback.py
  engine/apps/twilioapp/tests/test_sms_message.py
  engine/apps/zvonok/status_callback.py
  engine/settings/celery_task_routes.py
Labels: pr:no public docs, release:patch

#4680 Plugin Init - fe improvements
  grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.tsx
  grafana-plugin/src/containers/PluginInitializer/PluginInitializer.tsx
  grafana-plugin/src/models/plugin/plugin.ts
Labels: pr:no public docs, release:ignore

#4687 Label error handling tweaks
  grafana-plugin/src/containers/ColumnsSelectorWrapper/ColumnsModal.tsx
  grafana-plugin/src/containers/ColumnsSelectorWrapper/ColumnsSelectorWrapper.tsx
  grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.tsx
  grafana-plugin/src/containers/Labels/Labels.tsx
  grafana-plugin/src/containers/RouteLabelsDisplay/RouteLabelsDisplay.tsx
  grafana-plugin/src/models/alertgroup/alertgroup.ts
  grafana-plugin/src/models/label/label.ts
  grafana-plugin/src/utils/consts.ts
Labels: pr:no public docs, release:ignore

#4693 PR template: "Closes" -> "Related to"
  .github/pull_request_template.md
Labels: pr:no public docs, release:ignore

#4695 Drop stale metrics cache
  engine/apps/metrics_exporter/metrics_collectors.py
  engine/apps/metrics_exporter/tests/conftest.py
  engine/apps/metrics_exporter/tests/test_metrics_collectors.py
Labels: pr:no public docs, release:ignore

#4696 Fix `send_bundled_notification` task
  engine/apps/alerts/tasks/notify_user.py
Labels: pr:no public docs, release:ignore

#4700 Add missing app_type argument to uninstall request
  engine/apps/chatops_proxy/client.py
  engine/apps/chatops_proxy/register_oncall_tenant.py
  engine/apps/chatops_proxy/utils.py
Labels: pr:no public docs, release:ignore

#4697 Update schedule events internal API to return default priority level
  engine/apps/api/tests/test_oncall_shift.py
  engine/apps/api/tests/test_schedules.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_on_call_schedule.py
Labels: pr:no public docs, release:ignore

#4698 Handle multiple unpage event logs when getting paged users
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/tests/test_alert_group.py
Labels: pr:no public docs, release:patch

#4691 Cleanup and split tiltfile by profiles
  .github/workflows/e2e-tests.yml
  .tilt/backend/Tiltfile
  .tilt/deps/Tiltfile
  .tilt/plugin/Tiltfile
  .tilt/tests/Tiltfile
  Tiltfile
  dev/README.md
Labels: pr:no public docs, release:ignore

#4578 Support stack header from chatops-proxy
  engine/apps/slack/scenarios/alertgroup_appearance.py
  engine/apps/slack/scenarios/alertgroup_timeline.py
  engine/apps/slack/scenarios/declare_incident.py
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/slack/scenarios/invited_to_channel.py
  engine/apps/slack/scenarios/manage_responders.py
  engine/apps/slack/scenarios/notified_user_not_in_channel.py
  engine/apps/slack/scenarios/onboarding.py
  engine/apps/slack/scenarios/paging.py
  engine/apps/slack/scenarios/profile_update.py
  engine/apps/slack/scenarios/resolution_note.py
  engine/apps/slack/scenarios/scenario_step.py
  engine/apps/slack/scenarios/schedules.py
  engine/apps/slack/scenarios/shift_swap_requests.py
  engine/apps/slack/scenarios/slack_channel.py
  engine/apps/slack/scenarios/slack_channel_integration.py
  engine/apps/slack/scenarios/slack_usergroup.py
  engine/apps/slack/tests/test_interactive_api_endpoint.py
  engine/apps/slack/tests/test_scenario_steps/test_paging.py
  engine/apps/slack/views.py
Labels: pr:no public docs, release:ignore

#4682 Unified Slack app reinstall
  engine/apps/api/serializers/organization.py
  engine/apps/slack/installation.py
  engine/apps/slack/migrations/0005_slackteamidentity__unified_slack_app_installed.py
  engine/apps/slack/models/slack_team_identity.py
  engine/apps/slack/tests/test_installation.py
  grafana-plugin/src/models/organization/organization.types.ts
  grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/SlackSettings/SlackSettings.tsx
Labels: pr:no public docs, release:ignore

#4705 Update regex to jinja route conversion to correctly escape double quotes
  engine/apps/api/serializers/channel_filter.py
  engine/apps/api/tests/test_channel_filter.py
Labels: pr:no public docs, release:ignore

#4706 Update OrderedModel serializer not to save previously updated order
  engine/common/ordered_model/serializer.py
  engine/common/tests/test_ordered_model.py
Labels: pr:no public docs, release:ignore

#4707 Fix bug for incorrect arguments used to invoke cleanup_empty_deleted_integrations
  engine/apps/grafana_plugin/tasks/sync.py
  engine/settings/celery_task_routes.py
Labels: pr:no public docs, release:ignore

#4712 Set external URL for Grafana in tiltfile
  Tiltfile
  grafana-plugin/pkg/plugin/settings.go
Labels: pr:no public docs, release:ignore

#4713 Make it clear alert groups can't be searched
  engine/apps/api/views/alert_group.py
  engine/apps/api/views/alert_receive_channel.py
  engine/apps/api/views/escalation_chain.py
  engine/apps/api/views/schedule.py
  engine/apps/api/views/user.py
  engine/apps/api/views/webhooks.py
  grafana-plugin/e2e-tests/utils/alertGroup.ts
  grafana-plugin/src/containers/RemoteFilters/RemoteFilters.tsx
  grafana-plugin/src/models/filters/filters.ts
Labels: pr:no public docs, release:patch

#4708 hide forbidden actions from Add menu in schedule
  grafana-plugin/src/pages/schedule/Schedule.tsx
Labels: pr:no public docs, release:ignore

#4718 AG filters
  grafana-plugin/src/containers/RemoteFilters/RemoteFilters.tsx
  grafana-plugin/src/containers/RemoteFilters/TimeRangePickerWrapper.tsx
  grafana-plugin/src/models/alertgroup/alertgroup.ts
  grafana-plugin/src/models/filters/filters.types.ts
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/types.ts
Labels: pr:no public docs, release:patch

#4579 Alert group search feature flags
  engine/apps/api/tests/test_alert_group.py
  engine/apps/api/views/alert_group.py
  engine/common/api_helpers/paginators.py
  engine/common/utils.py
  engine/settings/base.py
  grafana-plugin/src/containers/RemoteFilters/RemoteFilters.tsx
Labels: pr:no public docs, release:ignore

#4715 Prepare for changes to OnCall plugin initialization
  grafana-plugin/src/plugin.json
Labels: pr:no public docs, release:ignore

#4719 show chatops proxy error
  grafana-plugin/src/pages/settings/tabs/ChatOps/ChatOps.helpers.ts
  grafana-plugin/src/pages/settings/tabs/ChatOps/ChatOps.tsx
Labels: pr:no public docs, release:ignore

#4721 Set unique key on each rendered route
  grafana-plugin/src/containers/IntegrationContainers/RouteHeading.tsx
  grafana-plugin/src/containers/RouteLabelsDisplay/RouteLabelsDisplay.tsx
  grafana-plugin/src/pages/integration/Integration.tsx
Labels: pr:no public docs, release:ignore

#4717 Introduce slash command matcher
  engine/apps/slack/scenarios/paging.py
  engine/apps/slack/slash_command.py
  engine/apps/slack/tests/test_slash_command.py
  engine/apps/slack/types/scenario_routes.py
  engine/apps/slack/views.py
Labels: pr:no public docs, release:ignore

#4725 Fix app redirect
  engine/apps/chatops_proxy/utils.py
Labels: pr:no public docs, release:ignore

#4723 Fix `/escalate` predefined org
  engine/apps/slack/scenarios/paging.py
Labels: pr:no public docs, release:ignore

#4562 fix: indentation in alert manager integration docs
  docs/sources/integrations/alertmanager/index.md
Labels: release:ignore

#4726 Fix notification plan builder
  engine/apps/alerts/incident_log_builder/incident_log_builder.py
  engine/apps/alerts/migrations/0055_alter_bundlednotification_alert_group.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/models/user_notification_bundle.py
  engine/apps/alerts/tasks/notify_user.py
  engine/apps/alerts/tests/test_incident_log_builder.py
  engine/apps/alerts/tests/test_notify_user.py
Labels: pr:no public docs, release:ignore

#4731 Update alert group search to force index in MySQL
  engine/apps/api/views/alert_group.py
  engine/common/api_helpers/paginators.py
  engine/settings/base.py
Labels: pr:no public docs, release:ignore

#4727 Adjustments to IRM unified plugin
  Tiltfile
  grafana-plugin/.eslintrc.js
  grafana-plugin/package.json
  grafana-plugin/src/components/CardButton/CardButton.test.tsx
  grafana-plugin/src/components/Collapse/Collapse.test.tsx
  grafana-plugin/src/components/ScheduleQualityDetails/ScheduleQualityProgressBar.test.tsx
  grafana-plugin/src/components/SourceCode/SourceCode.test.tsx
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/plugin/PluginSetup/PluginSetup.test.tsx
  grafana-plugin/src/plugin/PluginSetup/__snapshots__/PluginSetup.test.tsx.snap
  grafana-plugin/src/state/rootBaseStore/RootBaseStore.ts
  grafana-plugin/src/types.ts
  grafana-plugin/src/utils/faro.test.tsx
  grafana-plugin/yarn.lock
Labels: pr:no public docs, release:ignore

#4734 Force index only on list & stats
  engine/apps/api/views/alert_group.py
Labels: pr:no public docs, release:ignore

#4737 Enable alert group search by default
  engine/settings/base.py
Labels: pr:no public docs, release:enhancement

#4738 Fix N+1 issue on alert group list page
  engine/apps/alerts/models/alert_group.py
  engine/apps/api/serializers/alert_group.py
  engine/settings/base.py
Labels: pr:no public docs, release:ignore

#4740 change version in package.json to 1.0.0
  grafana-plugin/package.json
Labels: pr:no public docs, release:ignore

#4744 Prevent AG call refresh if a timeout is already pending + few tweaks to the AG table sizing
  grafana-plugin/src/assets/style/utils.css
  grafana-plugin/src/pages/incidents/Incidents.tsx
Labels: pr:no public docs, release:patch

#4703 Migrate react-router to v6
  grafana-plugin/.config/.eslintrc
  grafana-plugin/.config/webpack/webpack.config.ts
  grafana-plugin/.eslintrc.js
  grafana-plugin/package.json
  grafana-plugin/src/components/PluginLink/PluginLink.tsx
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.test.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.tsx
  grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.test.tsx
  grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.tsx
  grafana-plugin/src/containers/Rotations/SchedulePersonal.tsx
  grafana-plugin/src/pages/NoMatch.tsx
  grafana-plugin/src/pages/escalation-chains/EscalationChains.tsx
  grafana-plugin/src/pages/incident/Incident.styles.ts
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/incidents/Incidents.styles.ts
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/pages/integration/IntegrationActions.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingTab.hooks.ts
  grafana-plugin/src/pages/integrations/Integrations.tsx
  grafana-plugin/src/pages/outgoing_webhooks/OutgoingWebhooks.tsx
  grafana-plugin/src/pages/pages.tsx
  grafana-plugin/src/pages/schedule/Schedule.tsx
  grafana-plugin/src/pages/schedules/Schedules.tsx
  grafana-plugin/src/pages/settings/tabs/Cloud/CloudPage.tsx
  grafana-plugin/src/pages/users/Users.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/utils/hoc.tsx
  grafana-plugin/src/utils/hooks.tsx
  grafana-plugin/webpack.config.ts
  grafana-plugin/yarn.lock
Labels: pr:no public docs, release:patch

#4746 fix tests and types generator
  grafana-plugin/jest.config.js
  grafana-plugin/package.json
  grafana-plugin/src/network/oncall-api/types-generator/package.json
  grafana-plugin/src/network/oncall-api/types-generator/tsconfig.json
Labels: pr:no public docs, release:ignore

#4648 Update consts.ts
  grafana-plugin/src/utils/consts.ts
Labels: pr:no public docs, release:ignore

#4750 Stop posting new slack log reports
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/slack/tasks.py
Labels: pr:no public docs, release:patch

#4301 Replace docs/reference shortcode with ref URIs
  docs/sources/configure/_index.md
  docs/sources/configure/escalation-chains-and-routes/index.md
  docs/sources/configure/integrations/_index.md
  docs/sources/configure/integrations/integration-management/index.md
  docs/sources/configure/integrations/outgoing-webhooks/index.md
  docs/sources/configure/integrations/references/alertmanager/index.md
  docs/sources/configure/integrations/references/amazon-sns/index.md
  docs/sources/configure/integrations/references/appdynamics/index.md
  docs/sources/configure/integrations/references/datadog/index.md
  docs/sources/configure/integrations/references/elastalert/index.md
  docs/sources/configure/integrations/references/fabric/index.md
  docs/sources/configure/integrations/references/grafana-alerting/index.md
  docs/sources/configure/integrations/references/inbound-email/index.md
  docs/sources/configure/integrations/references/jira/index.md
  docs/sources/configure/integrations/references/kapacitor/index.md
  docs/sources/configure/integrations/references/manual/index.md
  docs/sources/configure/integrations/references/newrelic/index.md
  docs/sources/configure/integrations/references/pingdom/index.md
  docs/sources/configure/integrations/references/prtg/index.md
  docs/sources/configure/integrations/references/sentry/index.md
  docs/sources/configure/integrations/references/servicenow/index.md
  docs/sources/configure/integrations/references/stackdriver/index.md
  docs/sources/configure/integrations/references/uptimerobot/index.md
  docs/sources/configure/integrations/references/webhook/index.md
  docs/sources/configure/integrations/references/zendesk/index.md
  docs/sources/configure/jinja2-templating/_index.md
  docs/sources/configure/jinja2-templating/advanced-templates/index.md
  docs/sources/intro/_index.md
  docs/sources/manage/insights-and-metrics/index.md
  docs/sources/manage/mobile-app/alert-groups-feed/index.md
  docs/sources/manage/mobile-app/push-notifications/index.md
  docs/sources/manage/notify/_index.md
  docs/sources/manage/notify/phone-calls-sms/index.md
  docs/sources/manage/notify/slack/index.md
  docs/sources/manage/on-call-schedules/_index.md
  docs/sources/manage/on-call-schedules/api-terraform-schedule/index.md
  docs/sources/manage/on-call-schedules/ical-schedules/index.md
  docs/sources/manage/on-call-schedules/shift-swaps/index.md
  docs/sources/manage/on-call-schedules/web-schedule/index.md
  docs/sources/oncall-api-reference/integrations.md
  docs/sources/oncall-api-reference/outgoing_webhooks.md
  docs/sources/set-up/get-started/index.md
  docs/sources/set-up/open-source/index.md
Labels: type/docs, release:ignore

#4753 Don't update RBAC status on Grafana server error
  engine/apps/grafana_plugin/helpers/client.py
  engine/apps/grafana_plugin/tests/test_grafana_api_client.py
  engine/apps/grafana_plugin/tests/test_self_hosted_install.py
  engine/apps/grafana_plugin/views/self_hosted_install.py
  engine/apps/user_management/sync.py
  engine/apps/user_management/tests/test_sync.py
Labels: pr:no public docs, release:patch

#4751 allow plugin id customization (for IRM monorepo)
  grafana-plugin/src/components/ExtensionLinkMenu/ExtensionLinkMenu.tsx
  grafana-plugin/src/components/Unauthorized/Unauthorized.test.tsx
  grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.tsx
  grafana-plugin/src/containers/UserSettings/parts/tabs/SlackTab/SlackTab.tsx
  grafana-plugin/src/network/network.ts
  grafana-plugin/src/network/oncall-api/http-client.ts
  grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/SlackSettings/SlackSettings.tsx
  grafana-plugin/src/plugin/PluginSetup/PluginSetup.tsx
  grafana-plugin/src/state/plugin/plugin.test.ts
  grafana-plugin/src/state/plugin/plugin.ts
  grafana-plugin/src/state/rootBaseStore/RootBaseStore.ts
  grafana-plugin/src/types.ts
  grafana-plugin/src/utils/authorization/authorization.test.ts
  grafana-plugin/src/utils/authorization/authorization.ts
  grafana-plugin/src/utils/consts.ts
  grafana-plugin/src/utils/faro.ts
  grafana-plugin/webpack.config.ts
Labels: pr:no public docs, release:ignore

#4762 chore: grafana-irm command
  engine/apps/slack/slash_command.py
  engine/apps/slack/tests/test_interactive_api_endpoint.py
  engine/apps/slack/tests/test_slash_command.py
Labels: pr:no public docs, release:ignore

#4766 Chore: update the `.nvmrc`
  grafana-plugin/.nvmrc
Labels: pr:no public docs, release:ignore

#4763 Fix deleted schedule on getting on-call users from cache
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/tests/test_ical_utils.py
Labels: pr:no public docs, release:ignore

#4756 Rework organization sync and grafana plugin engine backend
  engine/apps/auth_token/auth.py
  engine/apps/auth_token/tests/test_plugin_auth.py
  engine/apps/grafana_plugin/helpers/client.py
  engine/apps/grafana_plugin/helpers/gcom.py
  engine/apps/grafana_plugin/serializers/sync_data.py
  engine/apps/grafana_plugin/sync_data.py
  engine/apps/grafana_plugin/tasks/__init__.py
  engine/apps/grafana_plugin/tasks/sync_v2.py
  engine/apps/grafana_plugin/tests/test_grafana_api_client.py
  engine/apps/grafana_plugin/tests/test_sync_v2.py
  engine/apps/grafana_plugin/urls.py
  engine/apps/grafana_plugin/views/__init__.py
  engine/apps/grafana_plugin/views/install_v2.py
  engine/apps/grafana_plugin/views/recaptcha.py
  engine/apps/grafana_plugin/views/status_v2.py
  engine/apps/grafana_plugin/views/sync_v2.py
  engine/apps/user_management/models/team.py
  engine/apps/user_management/models/user.py
  engine/apps/user_management/sync.py
  engine/apps/user_management/tests/test_sync.py
  engine/common/api_helpers/errors.py
  engine/engine/urls.py
  engine/settings/celery_task_routes.py
Labels: pr:no public docs, release:ignore

#4769 fix ms teams doc product label
  docs/sources/manage/notify/ms-teams/index.md
Labels: type/docs, release:ignore

#4771 Fix refactored permissions sync
  engine/apps/auth_token/auth.py
  engine/apps/user_management/sync.py
  engine/apps/user_management/tests/test_sync.py
Labels: pr:no public docs, release:ignore
