Repository grafana/oncall, pull requests merged in 2024-04, with the labels that each got.

#4131 Pass existing integration id to test_connection
  grafana-plugin/src/containers/ServiceNowConfigDrawer/ServiceNowAuthSection.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.helpers.ts
Labels: pr:no public docs, release:ignore

#4141 upgrade flake8 to v7
  .pre-commit-config.yaml
  engine/apps/alerts/models/alert_group.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/views/alert_receive_channel.py
  engine/apps/base/tests/test_live_settings.py
  engine/apps/public_api/tests/test_schedule_export.py
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/slack/scenarios/slack_renderer.py
  engine/common/utils.py
Labels: pr:no public docs, release:ignore

#4143 cleanup orphaned `CustomButton` escalation policy steps
  engine/apps/alerts/migrations/0051_remove_escalationpolicy_custom_button_trigger.py
  engine/apps/alerts/models/escalation_policy.py
  engine/apps/webhooks/migrations/0008_auto_20230712_1613.py
  engine/apps/webhooks/migrations/0016_auto_20240402_1341.py
Labels: pr:no public docs, release:ignore

#4104 Google Calendar Out of Office events - autogenerated shift swap requests
  engine/apps/api/tests/test_shift_swaps.py
  engine/apps/api/views/shift_swap.py
  engine/apps/google/client.py
  engine/apps/google/constants.py
  engine/apps/google/models/google_oauth2_user.py
  engine/apps/google/tasks.py
  engine/apps/google/tests/__init__.py
  engine/apps/google/tests/factories.py
  engine/apps/google/tests/test_sync_out_of_office_calendar_events_for_user.py
  engine/apps/google/types.py
  engine/apps/google/utils.py
  engine/apps/public_api/tests/test_shift_swap.py
  engine/apps/public_api/views/shift_swap.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/models/shift_swap_request.py
  engine/apps/schedules/tests/test_on_call_schedule.py
  engine/apps/user_management/tests/test_user.py
  engine/conftest.py
Labels: pr:no public docs, release:ignore

#4146 Add more logs for updating slack user group members
  engine/apps/slack/models/slack_usergroup.py
Labels: pr:no public docs, release:ignore

#4116 update docs landing page
  docs/sources/_index.md
Labels: type/docs, release:ignore

#4156 Minor wording update in rotation form when weekdays mask is set
  grafana-plugin/src/containers/RotationForm/RotationForm.tsx
Labels: pr:no public docs, release:ignore

#4147 Google Calendar integration improvements
  engine/apps/social_auth/pipeline/google.py
  grafana-plugin/src/containers/UserSettings/parts/tabs/GoogleCalendar/GoogleCalendar.tsx
Labels: pr:no public docs, release:ignore

#4137 Improve performance for rate-limited, banned and deleted integrations
  engine/apps/integrations/mixins/alert_channel_defining_mixin.py
  engine/apps/integrations/mixins/ratelimit_mixin.py
  engine/apps/integrations/tests/test_views.py
  engine/engine/middlewares.py
  engine/settings/base.py
Labels: pr:no public docs, release:patch

#4162 Fix bug in ratelimit logic introduced in #4137
  engine/apps/integrations/mixins/ratelimit_mixin.py
Labels: pr:no public docs, release:ignore

#4157 Remove updating user's timezone on backend if there are no changes
  grafana-plugin/src/models/user/user.ts
Labels: pr:no public docs, release:patch

#4160 Google Calendar Integration - consider current oncall shifts for autogeneration of shift swap requests
  engine/apps/google/tasks.py
  engine/apps/google/tests/test_sync_out_of_office_calendar_events_for_user.py
Labels: pr:no public docs, release:ignore

#4170 add `X-Grafana-User` header in proxied mobile app proxy gateway requests
  engine/apps/mobile_app/tests/test_mobile_app_gateway.py
  engine/apps/mobile_app/views.py
Labels: pr:no public docs, release:patch

#4150 Added Outgoing Web hooks to escalation policy log
  engine/apps/alerts/incident_log_builder/incident_log_builder.py
  engine/apps/alerts/tests/test_incident_log_builder.py
Labels: pr:no public docs, release:patch

#4159 Update backsync method to take source channel as param
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/tests/test_alert_group.py
  engine/apps/slack/scenarios/distribute_alerts.py
Labels: pr:no public docs, release:ignore

#4163 Improve performance for deleted integration lookups
  engine/apps/integrations/mixins/alert_channel_defining_mixin.py
  engine/apps/integrations/tests/test_views.py
  engine/engine/tests/test_views.py
  engine/engine/views.py
Labels: pr:no public docs, release:patch

#4173 Add test for caching deleted integration, fix test wrap methods
  engine/apps/integrations/tests/test_views.py
Labels: pr:no public docs, release:ignore

#4181 Fix Insights e2e test
  grafana-plugin/e2e-tests/insights/insights.test.ts
Labels: pr:no public docs, release:ignore

#4153 Allow getting details from connected integration webhooks
  engine/apps/api/tests/test_webhooks.py
  engine/apps/api/views/webhooks.py
  engine/apps/slack/tests/test_scenario_steps/test_alert_group_actions.py
  engine/tox.ini
Labels: pr:no public docs, release:ignore

#4149 Check for backsync updates before triggering connected webhooks
  engine/apps/webhooks/listeners.py
  engine/apps/webhooks/tasks/alert_group_status.py
  engine/apps/webhooks/tasks/trigger_webhook.py
  engine/apps/webhooks/tests/test_alert_group_status_change.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
Labels: pr:no public docs, release:ignore

#4172 Update integration token generation endpoint to include usage details
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/views/alert_receive_channel.py
Labels: pr:no public docs, release:ignore

#4187 Update xdist load to use loadscope setting
  engine/apps/alerts/tests/test_acknowledge_reminder.py
  engine/apps/slack/tests/test_scenario_steps/test_alert_group_actions.py
  engine/tox.ini
Labels: pr:no public docs, release:ignore

#4185 Fix incident error handling
  grafana-plugin/src/components/PageErrorHandlingWrapper/PageErrorHandlingWrapper.helpers.tsx
  grafana-plugin/src/network/oncall-api/http-client.test.ts
  grafana-plugin/src/network/oncall-api/http-client.ts
Labels: pr:no public docs, release:ignore

#4183 Proposal for dayJSAddWithDSTFixed fn fix
  grafana-plugin/src/containers/RotationForm/RotationForm.helpers.ts
Labels: pr:no public docs, release:patch

#4192 unit test dayJSAddWithDSTFixed
  grafana-plugin/jest.config.js
  grafana-plugin/package.json
  grafana-plugin/src/containers/RotationForm/RotationForm.helpers.test.ts
Labels: pr:no public docs, release:ignore

#4193 Fix source integration filter query
  engine/apps/webhooks/models/webhook.py
  engine/apps/webhooks/utils.py
Labels: pr:no public docs, release:ignore

#4195 Handle webhooks update on source integration settings update
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/webhooks/models/webhook.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
  engine/apps/webhooks/tests/test_webhook.py
  engine/apps/webhooks/utils.py
Labels: pr:no public docs, release:ignore

#4189 Add retry queue to helm chart
  helm/oncall/values.yaml
Labels: release:patch

#4199 Show error if resolve AG request fails
  grafana-plugin/src/models/alertgroup/alertgroup.ts
  grafana-plugin/src/network/oncall-api/http-client.test.ts
  grafana-plugin/src/network/oncall-api/http-client.ts
  grafana-plugin/src/utils/consts.ts
  grafana-plugin/src/utils/decorators.ts
Labels: pr:no public docs, release:patch

#4194 update mobile app proxy's usage of the Cloud Auth API
  engine/apps/mobile_app/tests/test_mobile_app_gateway.py
  engine/apps/mobile_app/views.py
  engine/common/cloud_auth_api/client.py
  engine/common/cloud_auth_api/tests/test_client.py
Labels: pr:no public docs, release:ignore

#4168 Optimize GET /users internal api endpoint
  engine/apps/api/serializers/user.py
  engine/apps/api/views/user.py
  engine/apps/mobile_app/backend.py
Labels: pr:no public docs, release:ignore

#4169 Optimize GET /schedules and /current_user_events internal api endpoints
  engine/apps/api/views/schedule.py
  engine/apps/schedules/constants.py
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/models/on_call_schedule.py
Labels: pr:no public docs, release:ignore

#4204 Add endpoint for organization config checks
  engine/apps/api/serializers/organization.py
  engine/apps/api/tests/test_organization.py
  engine/apps/api/urls.py
  engine/apps/api/views/organization.py
  engine/apps/base/messaging.py
Labels: pr:no public docs, release:ignore

#4213 Update PromQL queries on Insights page and dashboard
  grafana-plugin/src/dashboards/oncall_metrics_dashboard.json
  grafana-plugin/src/pages/insights/scenes/AlertGroupsByIntegration.tsx
  grafana-plugin/src/pages/insights/scenes/AlertGroupsByTeam.tsx
  grafana-plugin/src/pages/insights/scenes/MTTRAverageStat.tsx
  grafana-plugin/src/pages/insights/scenes/MTTRByIntegration.tsx
  grafana-plugin/src/pages/insights/scenes/MTTRByTeam.tsx
  grafana-plugin/src/pages/insights/scenes/MTTRChangedTimeseries.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroups.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroupsNotificationsTable.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroupsNotificationsTimeseries.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroupsTimeseries.tsx
Labels: pr:no public docs, release:ignore

#4214 SNOW tweaks
  grafana-plugin/src/components/SourceCode/SourceCode.module.scss
  grafana-plugin/src/components/SourceCode/SourceCode.tsx
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/containers/ServiceNowConfigDrawer/ServiceNowAuthSection.tsx
  grafana-plugin/src/containers/ServiceNowConfigDrawer/ServiceNowConfigDrawer.tsx
  grafana-plugin/src/containers/ServiceNowConfigDrawer/ServiceNowTokenSection.tsx
  grafana-plugin/src/network/oncall-api/autogenerated-api.types.d.ts
Labels: pr:no public docs, release:ignore

#4205 Add Slack deep link entry to alert group permalinks
  engine/apps/alerts/models/alert_group.py
  engine/apps/public_api/tests/test_alert_groups.py
  engine/apps/slack/models/slack_message.py
  engine/apps/slack/tests/test_slack_message.py
  grafana-plugin/src/network/oncall-api/autogenerated-api.types.d.ts
Labels: pr:no public docs, release:patch

#4211 Avoid creating a webhook response if request is not triggered
  engine/apps/webhooks/tasks/trigger_webhook.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
Labels: pr:no public docs, release:patch

#4216 Move deep link login to the top to be more visible
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.tsx
Labels: pr:no public docs, release:ignore

#4217 fix incorrect args passed to `apps.webhooks.tasks.trigger_webhook.execute_webhook`
  engine/apps/webhooks/tasks/trigger_webhook.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
Labels: pr:no public docs, release:patch

#4203 Add Google privacy policy note for Google Calendar integration
  grafana-plugin/src/containers/UserSettings/parts/tabs/GoogleCalendar/GoogleCalendar.tsx
Labels: pr:no public docs, release:ignore

#4219 Prevent SN modal closing on outer click
  grafana-plugin/src/containers/ServiceNowConfigDrawer/CompleteServiceNowConfigModal.tsx
Labels: pr:no public docs, release:ignore

#4220 Google Calendar Integration + automatic Shift Swap Request generation
  docs/sources/manage/on-call-schedules/shift-swaps/index.md
  engine/apps/api/views/features.py
  engine/settings/base.py
Labels: release:enhancement

#4226 Add alert groups external URLs information to details API
  engine/apps/api/serializers/alert_group.py
  engine/apps/api/tests/test_alert_group.py
  grafana-plugin/src/network/oncall-api/autogenerated-api.types.d.ts
Labels: pr:no public docs, release:ignore

#4229 SNOW minor wording & docs URL updates
  .pre-commit-config.yaml
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/containers/ServiceNowConfigDrawer/ServiceNowAuthSection.tsx
  grafana-plugin/src/containers/ServiceNowConfigDrawer/ServiceNowConfigDrawer.tsx
  grafana-plugin/src/containers/ServiceNowConfigDrawer/ServiceNowTokenSection.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/ConnectedIntegrationsTable.tsx
Labels: pr:no public docs, release:ignore

#4215 SNOW docs
  docs/sources/configure/outgoing-webhooks/index.md
  docs/sources/integrations/_index.md
  docs/sources/integrations/servicenow/index.md
Labels: release:ignore

#4230 Handle alert group deleted when task is already queued
  engine/apps/alerts/models/alert.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/tasks/__init__.py
  engine/apps/alerts/tasks/distribute_alert.py
  engine/apps/alerts/tests/test_alert.py
  engine/apps/webhooks/listeners.py
  engine/settings/celery_task_routes.py
Labels: pr:no public docs, release:patch

#4237 Fix deleting integration with connected webhooks
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/webhooks/tests/test_webhook.py
Labels: pr:no public docs, release:patch

#4233 Fixed labels update within Integration Form
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
Labels: pr:no public docs, release:ignore

#4228 ignore shift swap generation for gcal events with specific keyword in title
  docs/sources/manage/on-call-schedules/shift-swaps/index.md
  engine/apps/google/constants.py
  engine/apps/google/tasks.py
  engine/apps/google/tests/test_sync_out_of_office_calendar_events_for_user.py
Labels: release:patch

#4167 Cleanup error logs on frontend unit test run
  grafana-plugin/jest.setup.ts
  grafana-plugin/src/containers/AddResponders/parts/AddRespondersPopup/AddRespondersPopup.test.tsx
  grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.test.tsx
Labels: pr:no public docs, release:ignore

#4240 Added new SNOW logo
  grafana-plugin/src/assets/img/ServiceNow.png
  grafana-plugin/src/components/IntegrationLogo/IntegrationLogo.module.css
Labels: pr:no public docs, release:ignore

#4171 Replace GForm with react-hook-form
  grafana-plugin/src/components/GForm/GForm.module.scss
  grafana-plugin/src/components/GForm/GForm.tsx
  grafana-plugin/src/components/GForm/GForm.types.ts
  grafana-plugin/src/components/ManualAlertGroup/ManualAlertGroup.config.ts
  grafana-plugin/src/components/ManualAlertGroup/ManualAlertGroup.tsx
  grafana-plugin/src/containers/AddResponders/AddResponders.helpers.ts
  grafana-plugin/src/containers/GSelect/GSelect.tsx
  grafana-plugin/src/containers/MaintenanceForm/MaintenanceForm.config.tsx
  grafana-plugin/src/containers/MaintenanceForm/MaintenanceForm.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.config.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.styles.ts
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.types.ts
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookFormFields.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/WebhookPresetBlocks.tsx
  grafana-plugin/src/containers/RemoteSelect/RemoteSelect.tsx
  grafana-plugin/src/containers/ScheduleForm/ScheduleForm.config.ts
  grafana-plugin/src/containers/ScheduleForm/ScheduleForm.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/models/outgoing_webhook/outgoing_webhook.ts
  grafana-plugin/src/pages/integration/Integration.tsx
Labels: pr:no public docs, release:ignore

#4250 Prevent calling contact point endpoint for other integrations
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
Labels: pr:no public docs, release:patch

#4249 Updated labels version + autogenerated types
  grafana-plugin/package.json
  grafana-plugin/src/network/oncall-api/autogenerated-api.types.d.ts
  grafana-plugin/yarn.lock
Labels: pr:no public docs, release:ignore

#4244 Polish GCal UI texting
  grafana-plugin/src/containers/UserSettings/parts/tabs/GoogleCalendar/GoogleCalendar.tsx
  grafana-plugin/src/models/user/user.ts
Labels: pr:no public docs, release:patch

#4254 SNOW final tweaks
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/containers/ServiceNowConfigDrawer/CompleteServiceNowConfigModal.tsx
  grafana-plugin/src/containers/ServiceNowConfigDrawer/ServiceNowAuthSection.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.helpers.ts
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/integration/Integration.helper.ts
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/utils/consts.ts
Labels: pr:no public docs, release:ignore

#4255 Enable search for integration type options filter internal endpoint
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/views/alert_receive_channel.py
Labels: pr:no public docs, release:patch

#4246 Update cached schedule users to consider deleted users
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/tests/test_ical_utils.py
Labels: pr:no public docs, release:ignore

#4260 Ignore uncompleted notifications if policy is deleted
  engine/apps/alerts/tasks/check_escalation_finished.py
  engine/apps/alerts/tests/test_check_escalation_finished_task.py
Labels: pr:no public docs, release:ignore

#4268 Update chatops connected integration organization check
  engine/apps/api/serializers/organization.py
  engine/apps/api/tests/test_organization.py
Labels: pr:no public docs, release:ignore

#4175 Allow webhook modification by API for advanced webhook
  engine/apps/public_api/serializers/webhooks.py
  engine/apps/public_api/tests/test_webhooks.py
  engine/apps/webhooks/presets/preset_options.py
  engine/apps/webhooks/tests/test_webhook_presets.py
  engine/conftest.py
  engine/settings/base.py
Labels: pr:no public docs, release:patch

#4243 Fix docs and UI for connecting Grafana Alerting from other stack
  docs/sources/integrations/grafana-alerting/index.md
  engine/apps/alerts/tests/test_alert_group.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/telegram/tests/test_message_renderer.py
  engine/config_integrations/alertmanager.py
  engine/config_integrations/grafana.py
  engine/config_integrations/legacy_alertmanager.py
  engine/config_integrations/legacy_grafana_alerting.py
  engine/settings/base.py
  grafana-plugin/src/assets/img/grafana-legacy-alerting-icon.svg
  grafana-plugin/src/components/IntegrationLogo/IntegrationLogo.module.css
  grafana-plugin/src/components/IntegrationLogo/IntegrationLogo.tsx
Labels: release:ignore

#4264 Update mobile app sign in page
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.tsx
  grafana-plugin/src/containers/MobileAppConnection/__snapshots__/MobileAppConnection.test.tsx.snap
  grafana-plugin/src/containers/MobileAppConnection/parts/LinkLoginButton/LinkLoginButton.tsx
  grafana-plugin/src/containers/MobileAppConnection/parts/LinkLoginButton/__snapshots__/LinkLoginButton.test.tsx.snap
Labels: pr:no public docs, release:patch

#4271 SNOW docs fix
  docs/sources/integrations/servicenow/index.md
Labels: release:ignore

#4222 Configure cross plugin e2e tests
  .github/helm-ci.yml
  .github/workflows/daily-e2e-tests.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/linting-and-tests.yml
  Tiltfile
  grafana-plugin/e2e-tests/labels/createNewLabelKeysAndValues.test.ts
  grafana-plugin/e2e-tests/users/usersActions.test.ts
  grafana-plugin/e2e-tests/utils/forms.ts
  grafana-plugin/playwright.config.ts
Labels: pr:no public docs, release:patch

#4005 Switch to uv Python package installer/resolver
  .drone.yml
  .github/workflows/linting-and-tests.yml
  Makefile
  engine/Dockerfile
  tools/pagerduty-migrator/requirements.in
  tools/pagerduty-migrator/requirements.txt
Labels: pr:no public docs, release:ignore

#4275 Docs review on SNOW integration doc
  docs/sources/integrations/servicenow/index.md
  grafana-plugin/src/containers/ServiceNowConfigDrawer/ServiceNowTokenSection.tsx
Labels: type/docs, release:ignore

#4285 Use ops-devenv only in expensive tests
  .github/workflows/e2e-tests.yml
  .github/workflows/expensive-e2e-tests.yml
  .github/workflows/linting-and-tests.yml
  grafana-plugin/e2e-tests/labels/createNewLabelKeysAndValues.test.ts
Labels: pr:no public docs, release:ignore

#4176 Add acknowledged, resolved user information on webhook payload
  docs/sources/configure/outgoing-webhooks/index.md
  engine/apps/webhooks/tests/test_trigger_webhook.py
  engine/apps/webhooks/utils.py
Labels: release:enhancement

#4280 Tag component tweaks to get rid of hardcoded tag variables
  grafana-plugin/package.json
  grafana-plugin/src/components/CardButton/CardButton.styles.ts
  grafana-plugin/src/components/Integrations/IntegrationTag.tsx
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/components/ScheduleQuality/ScheduleQuality.styles.ts
  grafana-plugin/src/components/ScheduleQuality/ScheduleQuality.tsx
  grafana-plugin/src/components/Tag/Tag.tsx
  grafana-plugin/src/components/Text/Text.styles.ts
  grafana-plugin/src/components/Text/Text.tsx
  grafana-plugin/src/components/TooltipBadge/TooltipBadge.styles.ts
  grafana-plugin/src/components/TooltipBadge/TooltipBadge.tsx
  grafana-plugin/src/components/Unauthorized/__snapshots__/Unauthorized.test.tsx.snap
  grafana-plugin/src/containers/AddResponders/__snapshots__/AddResponders.test.tsx.snap
  grafana-plugin/src/containers/AddResponders/parts/TeamResponder/__snapshots__/TeamResponder.test.tsx.snap
  grafana-plugin/src/containers/AddResponders/parts/UserResponder/__snapshots__/UserResponder.test.tsx.snap
  grafana-plugin/src/containers/AlertRules/AlertRules.tsx
  grafana-plugin/src/containers/EscalationChainSteps/EscalationChainSteps.tsx
  grafana-plugin/src/containers/IntegrationForm/IntegrationFormContainer.tsx
  grafana-plugin/src/containers/MobileAppConnection/__snapshots__/MobileAppConnection.test.tsx.snap
  grafana-plugin/src/containers/MobileAppConnection/parts/DownloadIcons/__snapshots__/DownloadIcons.test.tsx.snap
  grafana-plugin/src/containers/MobileAppConnection/parts/LinkLoginButton/__snapshots__/LinkLoginButton.test.tsx.snap
  grafana-plugin/src/containers/PluginConfigPage/__snapshots__/PluginConfigPage.test.tsx.snap
  grafana-plugin/src/containers/PluginConfigPage/parts/ConfigurationForm/__snapshots__/ConfigurationForm.test.tsx.snap
  grafana-plugin/src/containers/PluginConfigPage/parts/StatusMessageBlock/__snapshots__/StatusMessageBlock.test.tsx.snap
  grafana-plugin/src/containers/RotationForm/ScheduleOverrideForm.tsx
  grafana-plugin/src/containers/RotationForm/parts/UserItem.tsx
  grafana-plugin/src/containers/UserSettings/parts/connectors/PhoneConnector.tsx
  grafana-plugin/src/navbar/Header/Header.module.scss
  grafana-plugin/src/navbar/Header/Header.styles.ts
  grafana-plugin/src/navbar/Header/Header.tsx
  grafana-plugin/src/pages/incident/Incident.helpers.tsx
  grafana-plugin/src/pages/incidents/parts/IncidentDropdown.module.scss
  grafana-plugin/src/pages/incidents/parts/IncidentDropdown.styles.ts
  grafana-plugin/src/pages/incidents/parts/IncidentDropdown.tsx
  grafana-plugin/src/styles/utils.styles.ts
  grafana-plugin/src/utils/DOM.ts
  grafana-plugin/yarn.lock
Labels: pr:no public docs, release:ignore

#4227 Prepare insight metrics structure for adding service_name label
  engine/apps/metrics_exporter/constants.py
  engine/apps/metrics_exporter/helpers.py
  engine/apps/metrics_exporter/metrics_cache_manager.py
  engine/apps/metrics_exporter/metrics_collectors.py
  engine/apps/metrics_exporter/tasks.py
  engine/apps/metrics_exporter/tests/conftest.py
  engine/apps/metrics_exporter/tests/test_calculation_metrics.py
  engine/apps/metrics_exporter/tests/test_metrics_collectors.py
  engine/apps/metrics_exporter/tests/test_update_metrics_cache.py
Labels: pr:no public docs, release:ignore

#4297 Fix calculating metrics from different services in metrics collector
  engine/apps/metrics_exporter/metrics_collectors.py
  engine/apps/metrics_exporter/tests/conftest.py
  engine/apps/metrics_exporter/tests/test_metrics_collectors.py
Labels: pr:no public docs, release:ignore

#4294 Show info about missing users in schedules
  grafana-plugin/src/components/NonExistentUserName/NonExistentUserName.tsx
  grafana-plugin/src/containers/RotationForm/parts/UserItem.tsx
  grafana-plugin/src/containers/ScheduleSlot/ScheduleSlot.module.css
  grafana-plugin/src/containers/ScheduleSlot/ScheduleSlot.tsx
  grafana-plugin/src/models/schedule/schedule.ts
  grafana-plugin/src/models/schedule/schedule.types.ts
Labels: pr:no public docs, release:enhancement

#4290 Fix missing Avatar on the schedule user's popup
  grafana-plugin/src/components/ScheduleBorderedAvatar/ScheduleBorderedAvatar.tsx
Labels: pr:no public docs, release:patch
