Repository grafana/oncall, pull requests merged in 2024-09, with the labels that each got.

#4970 Handle Slack invalid_auth error when posting alert group notification
  engine/apps/alerts/migrations/0058_alter_alertgroup_reason_to_skip_escalation.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/slack/tests/test_scenario_steps/test_distribute_alerts.py
  engine/apps/telegram/client.py
Labels: pr:no public docs, release:patch

#4972 Use cloud access policy to publish plugin to grafana.com
  .github/workflows/on-release-published.yml
Labels: pr:no public docs, release:ignore

#4976 Relax sync team serializer validation to match underlying model
  engine/apps/grafana_plugin/serializers/sync_data.py
  engine/apps/grafana_plugin/tests/test_sync_v2.py
Labels: pr:no public docs, release:ignore

#4980 fix: support running install-frontend-dependency from subdirectory
  .github/actions/install-frontend-dependencies/action.yml
Labels: pr:no public docs, release:ignore

#4984 Update cryptography dependency to 43.0.1
  engine/requirements.in
  engine/requirements.txt
Labels: pr:no public docs, release:ignore

#4983 Add missing permission to call machine learning plugin
  grafana-plugin/src/plugin.json
Labels: pr:no public docs, release:ignore

#4973 Add doc references to `regex_search` jinja filter
  docs/sources/configure/jinja2-templating/advanced-templates/index.md
  engine/common/jinja_templater/filters.py
  engine/common/tests/test_apply_jinja_template.py
  engine/pyproject.toml
  engine/requirements.in
  engine/requirements.txt
  grafana-plugin/src/components/CheatSheet/CheatSheet.config.ts
Labels: release:ignore

#4987 [IRM] - changes to get incident working in IRM plugin
  grafana-plugin/.bra.toml
  grafana-plugin/go.mod
  grafana-plugin/pkg/main.go
  grafana-plugin/pkg/plugin/app.go
  grafana-plugin/pkg/plugin/debug.go
  grafana-plugin/pkg/plugin/install.go
  grafana-plugin/pkg/plugin/resources.go
  grafana-plugin/pkg/plugin/resources_test.go
  grafana-plugin/pkg/plugin/settings.go
  grafana-plugin/pkg/plugin/status.go
  grafana-plugin/pkg/plugin/sync.go
  grafana-plugin/src/network/grafana-api/http-client.ts
Labels: pr:no public docs, release:ignore

#4876 Update helm chart for newer grafana + enable externalServiceAccounts
  README.md
  docker-compose-mysql-rabbitmq.yml
  docker-compose.yml
  helm/README.md
  helm/oncall/Chart.yaml
  helm/oncall/charts/grafana-6.57.1.tgz
  helm/oncall/charts/grafana-8.4.6.tgz
  helm/oncall/templates/_env.tpl
  helm/oncall/templates/plugin-provisioning.yaml
  helm/oncall/tests/__snapshot__/integrations_deployment_test.yaml.snap
  helm/oncall/tests/__snapshot__/telegram_polling_deployment_test.yaml.snap
  helm/oncall/tests/__snapshot__/wait_for_db_test.yaml.snap
  helm/oncall/tests/telegram_env_test.yaml
  helm/oncall/values.yaml
  helm/simple.yml
Labels: pr:no public docs, release:ignore

#4995 Main to dev
  helm/oncall/Chart.yaml
Labels: pr:no public docs, release:ignore

#4934 Add manual trigger support for webhooks
  docs/sources/configure/integrations/outgoing-webhooks/index.md
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/tests/test_webhooks.py
  engine/apps/api/views/webhooks.py
  engine/apps/webhooks/migrations/0008_auto_20230712_1613.py
  engine/apps/webhooks/migrations/0017_alter_webhook_trigger_type_and_more.py
  engine/apps/webhooks/models/webhook.py
  engine/apps/webhooks/presets/simple.py
  engine/apps/webhooks/tasks/trigger_webhook.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
  engine/settings/base.py
  grafana-plugin/package.json
  grafana-plugin/pnpm-lock.yaml
  grafana-plugin/src/components/ExtensionLinkMenu/ExtensionLinkDropdown.tsx
  grafana-plugin/src/components/ExtensionLinkMenu/ExtensionLinkMenu.tsx
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/containers/ColumnsSelectorWrapper/ColumnsModal.tsx
  grafana-plugin/src/containers/ColumnsSelectorWrapper/ColumnsSelectorWrapper.tsx
  grafana-plugin/src/containers/TemplatePreview/TemplatePreview.tsx
  grafana-plugin/src/models/loader/action-keys.ts
  grafana-plugin/src/models/outgoing_webhook/outgoing_webhook.ts
  grafana-plugin/src/models/outgoing_webhook/outgoing_webhook.types.ts
  grafana-plugin/src/network/oncall-api/autogenerated-api.types.d.ts
  grafana-plugin/src/pages/incident/Incident.tsx
Labels: release:enhancement

#5000 chore: provide mod:download command and stabilize schedule test
  grafana-plugin/e2e-tests/schedules/schedulesList.test.ts
  grafana-plugin/package.json
Labels: pr:no public docs, release:ignore

#5001 [IRM]: updates to e2e tests
  grafana-plugin/e2e-tests/.env.example
  grafana-plugin/package.json
  grafana-plugin/playwright.config.ts
  grafana-plugin/pnpm-lock.yaml
Labels: pr:no public docs, release:ignore

#5003 Fix for resolution note switch
  grafana-plugin/src/pages/settings/tabs/MainSettings/MainSettings.tsx
Labels: pr:no public docs, release:patch

#5002 Make sync settings configurable
  engine/apps/grafana_plugin/tasks/sync_v2.py
  engine/apps/grafana_plugin/tests/test_sync_v2.py
  engine/settings/base.py
Labels: pr:no public docs, release:ignore

#5005 Change default source link template for alertmanager
  engine/config_integrations/alertmanager.py
  engine/config_integrations/grafana_alerting.py
Labels: pr:no public docs, release:enhancement

#5009 Tweak bulk sync settings
  engine/settings/base.py
Labels: pr:no public docs, release:ignore

#5010 v1.9.24
  engine/apps/slack/tests/test_interactive_api_endpoint.py
  engine/apps/slack/views.py
  engine/config_integrations/alertmanager.py
  engine/config_integrations/grafana_alerting.py
  engine/settings/base.py
Labels: pr:no public docs

#5013 fix some Tilt hiccups
  Tiltfile
Labels: pr:no public docs, release:ignore

#4997 Bump Redis deps
  helm/oncall/Chart.yaml
Labels: pr:no public docs, release:ignore

#4992 Enable schedule for new sync process
  engine/settings/base.py
Labels: pr:no public docs, release:ignore

#5014 v1.9.25
  Tiltfile
  engine/settings/base.py
  helm/oncall/Chart.yaml
Labels: pr:no public docs

#5015 docs: hide slack doc from toc
  docs/sources/configure/integrations/references/slack/index.md
Labels: type/docs, release:ignore

#5021 chore: serve local dist
  .tilt/plugin/Tiltfile
  grafana-plugin/package.json
  grafana-plugin/pnpm-lock.yaml
Labels: pr:no public docs, release:ignore

#5019 Fix <a> link escaping in web template
  engine/apps/alerts/incident_appearance/templaters/web_templater.py
  engine/apps/alerts/tests/test_alert_group_renderer.py
Labels: pr:no public docs, release:patch

#5023 improve reliability of scheduleList +timezone e2e tests
  grafana-plugin/e2e-tests/schedules/schedulesList.test.ts
  grafana-plugin/e2e-tests/schedules/timezones.test.ts
Labels: pr:no public docs, release:ignore

#5024 Revert "Fix <a> link escaping in web template"
  engine/apps/alerts/incident_appearance/templaters/web_templater.py
  engine/apps/alerts/tests/test_alert_group_renderer.py
Labels: pr:no public docs, release:ignore

#5029 chore: always point livereload to localhost
  grafana-plugin/webpack.config.ts
Labels: pr:no public docs, release:ignore

#5004 Add custom ratelimits per org
  engine/apps/api/tests/test_user.py
  engine/apps/api/throttlers/demo_alert_throttler.py
  engine/apps/api/throttlers/phone_verification_throttler.py
  engine/apps/api/throttlers/test_call_throttler.py
  engine/apps/integrations/mixins/__init__.py
  engine/apps/integrations/mixins/ratelimit_mixin.py
  engine/apps/integrations/tests/test_ratelimit.py
  engine/apps/mobile_app/fcm_relay.py
  engine/apps/public_api/tests/test_ratelimit.py
  engine/apps/public_api/throttlers/info_throttler.py
  engine/apps/public_api/throttlers/phone_notification_throttler.py
  engine/apps/public_api/throttlers/user_throttle.py
  engine/common/api_helpers/custom_rate_scoped_throttler.py
  engine/common/api_helpers/custom_ratelimit.py
  engine/settings/base.py
Labels: pr:no public docs, release:ignore

#5033 Bump base image version
  engine/Dockerfile
Labels: pr:no public docs, release:ignore

#5036 Use dataclass methods in custom ratelimits and fix tests
  engine/apps/integrations/mixins/ratelimit_mixin.py
  engine/apps/integrations/tests/test_ratelimit.py
  engine/apps/public_api/tests/test_ratelimit.py
  engine/common/api_helpers/custom_rate_scoped_throttler.py
  engine/common/api_helpers/custom_ratelimit.py
  engine/settings/base.py
Labels: pr:no public docs, release:ignore

#5038 Bump @grafana/labels to 1.6.4
  grafana-plugin/package.json
  grafana-plugin/pnpm-lock.yaml
Labels: pr:no public docs, release:ignore

#5044 test: use 4 workers, disable timezone test
  grafana-plugin/e2e-tests/schedules/timezones.test.ts
  grafana-plugin/playwright.config.ts
Labels: pr:no public docs, release:ignore

#5042 Rares/v1.6.5 labels
  grafana-plugin/package.json
  grafana-plugin/pnpm-lock.yaml
Labels: pr:no public docs, release:ignore

#5040 Add incident API client
  engine/common/incident_api/__init__.py
  engine/common/incident_api/client.py
  engine/common/incident_api/tests/__init__.py
  engine/common/incident_api/tests/test_client.py
Labels: pr:no public docs, release:ignore

#5045 Use centralized 'Add to docs project' workflow with GitHub App auth
  .github/issue_and_pr_commands.json
  .github/workflows/add-to-docs-project.yml
  .github/workflows/issue_commands.yml
Labels: release:ignore

#5046 ci: fix snyk security scans
  .github/workflows/snyk-security-scan.yml
Labels: release:ignore

#5050 fix: Add rolling users validation for oncall shift API
  engine/apps/api/serializers/on_call_shifts.py
  engine/apps/api/tests/test_oncall_shift.py
  engine/apps/public_api/serializers/on_call_shifts.py
  engine/apps/public_api/tests/test_on_call_shifts.py
  engine/common/api_helpers/custom_fields.py
Labels: pr:no public docs, release:patch

#5055 Check for invalid urls in slack
  engine/config_integrations/alertmanager.py
  engine/config_integrations/grafana_alerting.py
Labels: pr:no public docs, release:ignore

#5031 feat: Add silence and unsilence public api endpoint
  docs/sources/oncall-api-reference/alertgroups.md
  engine/apps/public_api/tests/test_alert_groups.py
  engine/apps/public_api/views/alert_groups.py
Labels: release:patch

#5051 ci: update oss plugin release process
  .github/actions/build-sign-and-package-plugin/action.yml
  .github/workflows/on-release-published.yml
  .pre-commit-config.yaml
  grafana-plugin/e2e-tests/schedules/addOverride.test.ts
  grafana-plugin/e2e-tests/schedules/timezones.test.ts
  grafana-plugin/e2e-tests/utils/userSettings.ts
  grafana-plugin/package.json
  grafana-plugin/pkg/plugin/settings.go
  grafana-plugin/src/containers/AddResponders/parts/NotificationPoliciesSelect/NotificationPoliciesSelect.tsx
  grafana-plugin/src/containers/Alerts/Alerts.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.tsx
  grafana-plugin/src/containers/PersonalNotificationSettings/PersonalNotificationSettings.tsx
  grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.tsx
  grafana-plugin/src/containers/PluginInitializer/PluginInitializer.tsx
  grafana-plugin/src/helpers/consts.ts
  grafana-plugin/src/helpers/faro.test.tsx
  grafana-plugin/src/helpers/faro.ts
  grafana-plugin/src/helpers/helpers.ts
  grafana-plugin/src/navbar/Header/Header.tsx
  grafana-plugin/src/pages/insights/Insights.tsx
  grafana-plugin/src/pages/settings/tabs/ChatOps/ChatOps.tsx
  grafana-plugin/src/pages/users/Users.tsx
  grafana-plugin/src/state/rootBaseStore/RootBaseStore.ts
  grafana-plugin/src/version.ts
Labels: pr:no public docs, release:ignore

#5061 ci: patch issue in gcom curl command
  .github/actions/build-sign-and-package-plugin/action.yml
  .github/workflows/on-release-published.yml
Labels: release:ignore

#5054 docs: add `templates.mobile_app` entry to Integrations API docs
  docs/sources/oncall-api-reference/integrations.md
Labels: release:patch

#5067 Add default value for `started_at` filter for `/alertgroups` internal endpoint
  engine/apps/api/views/alert_group.py
Labels: pr:no public docs, release:ignore

#5069 fix "on helm release pr merged" GitHub Actions workflow
  .github/workflows/on-helm-release-pr-merged.yml
  helm/oncall/Chart.yaml
Labels: pr:no public docs, release:patch

#5075 feat: add Grafana IDs to users and teams public API endpoints
  docs/sources/oncall-api-reference/schedules.md
  docs/sources/oncall-api-reference/teams.md
  docs/sources/oncall-api-reference/users.md
  engine/apps/public_api/serializers/teams.py
  engine/apps/public_api/serializers/users.py
  engine/apps/public_api/tests/test_teams.py
  engine/apps/public_api/tests/test_users.py
Labels: release:patch

#5078 chore: merge helm request PRs using the `grafana-irm-app` GitHub App
  .github/workflows/on-release-published.yml
Labels: pr:no public docs, release:ignore

#5087 fix: address RBAC Admin issue
  engine/apps/api/permissions.py
  engine/apps/api/serializers/user_notification_policy.py
  engine/apps/user_management/models/user.py
  engine/apps/user_management/tests/test_user.py
  engine/common/api_helpers/mixins.py
  grafana-plugin/src/plugin.json
Labels: pr:no public docs, release:patch

#5030 docs: update notifications wording
  docs/sources/manage/notify/_index.md
Labels: release:ignore

#5092 Chore: Remove `topnav` references
  dev/helm-local.yml
  grafana-plugin/jest.setup.ts
  grafana-plugin/src/PluginPage.tsx
  grafana-plugin/src/containers/Alerts/Alerts.tsx
  grafana-plugin/src/containers/DefaultPageLayout/DefaultPageLayout.tsx
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.test.tsx
  grafana-plugin/src/containers/RotationForm/RotationForm.helpers.ts
  grafana-plugin/src/navbar/Header/Header.tsx
  grafana-plugin/src/navbar/LegacyNavHeading.tsx
  grafana-plugin/src/pages/pages.tsx
  grafana-plugin/src/pages/settings/SettingsPage.tsx
  grafana-plugin/src/pages/settings/tabs/MainSettings/MainSettings.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.helpers.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
Labels: pr:no public docs, release:ignore
