Repository grafana/oncall, pull requests merged in 2024-02, with the labels that each got.

#3806 Dev to main
  CHANGELOG.md
  engine/apps/user_management/sync.py
Labels: pr:no public docs

#3792 fix incorrect month increment
  grafana-plugin/src/containers/RotationForm/RotationForm.helpers.test.ts
  grafana-plugin/src/containers/RotationForm/RotationForm.helpers.ts
  grafana-plugin/src/containers/RotationForm/parts/DateTimePicker.tsx
Labels: pr:no changelog, pr:no public docs

#3809 Add ability to migrate one org
  engine/apps/alerts/tests/test_alert_receiver_channel.py
  engine/engine/management/commands/alertmanager_v2_migrate.py
Labels: pr:no changelog, pr:no public docs

#3685 AM v2 docs
  docs/sources/integrations/alertmanager/index.md
  docs/sources/integrations/grafana-alerting/index.md
Labels: pr:no changelog

#3752 Integration incoming tab
  grafana-plugin/src/assets/style/vars.css
  grafana-plugin/src/components/IntegrationCollapsibleTreeView/IntegrationCollapsibleTreeView.module.scss
  grafana-plugin/src/components/IntegrationCollapsibleTreeView/IntegrationCollapsibleTreeView.tsx
  grafana-plugin/src/components/IntegrationInputField/IntegrationInputField.tsx
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/components/Policy/NotificationPolicy.tsx
  grafana-plugin/src/components/Text/Text.tsx
  grafana-plugin/src/components/Timeline/TimelineItem.tsx
  grafana-plugin/src/containers/AlertRules/parts/index.tsx
  grafana-plugin/src/containers/EscalationChainSteps/EscalationChainSteps.tsx
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.module.scss
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/PersonalNotificationSettings/PersonalNotificationSettings.tsx
  grafana-plugin/src/pages/integration/Integration.module.scss
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/pages/integrations/Integrations.tsx
Labels: pr:no changelog, pr:no public docs

#3796 fix timezone e2e test
  Tiltfile
  grafana-plugin/e2e-tests/schedules/timezones.test.ts
  grafana-plugin/e2e-tests/utils/grafanaProfile.ts
  grafana-plugin/src/containers/ScheduleSlot/ScheduleSlot.tsx
Labels: pr:no changelog, pr:no public docs

#3818 Update notification checker
  engine/apps/alerts/tasks/check_escalation_finished.py
  engine/apps/alerts/tests/test_check_escalation_finished_task.py
Labels: pr:no changelog, pr:no public docs

#3814 Handle alert group does not exist on telegram button press
  CHANGELOG.md
  engine/apps/telegram/tests/test_button_update_handler.py
  engine/apps/telegram/tests/test_update_handlers.py
  engine/apps/telegram/updates/update_handlers/button_press.py
Labels: pr:no public docs

#3820 attempt to address some `SlackAPIRatelimitError` exceptions
  engine/apps/slack/models/slack_message.py
  engine/apps/slack/utils.py
Labels: pr:no changelog, pr:no public docs

#3816 Fix links
  docs/sources/_index.md
  docs/sources/configure/_index.md
  docs/sources/configure/escalation-chains-and-routes/index.md
  docs/sources/configure/jinja2-templating/index.md
  docs/sources/configure/outgoing-webhooks/index.md
  docs/sources/integrations/_index.md
  docs/sources/integrations/alertmanager/index.md
  docs/sources/integrations/amazon-sns/index.md
  docs/sources/integrations/appdynamics/index.md
  docs/sources/integrations/datadog/index.md
  docs/sources/integrations/elastalert/index.md
  docs/sources/integrations/fabric/index.md
  docs/sources/integrations/grafana-alerting/index.md
  docs/sources/integrations/inbound-email/index.md
  docs/sources/integrations/jira/index.md
  docs/sources/integrations/kapacitor/index.md
  docs/sources/integrations/manual/index.md
  docs/sources/integrations/newrelic/index.md
  docs/sources/integrations/pingdom/index.md
  docs/sources/integrations/prtg/index.md
  docs/sources/integrations/sentry/index.md
  docs/sources/integrations/servicenow/index.md
  docs/sources/integrations/stackdriver/index.md
  docs/sources/integrations/uptimerobot/index.md
  docs/sources/integrations/webhook/index.md
  docs/sources/integrations/zendesk/index.md
  docs/sources/intro/_index.md
  docs/sources/manage/insights-and-metrics/index.md
  docs/sources/manage/mobile-app/alert-groups-feed/index.md
  docs/sources/manage/mobile-app/push-notifications/index.md
  docs/sources/manage/notify/_index.md
  docs/sources/manage/notify/phone-calls-sms/index.md
  docs/sources/manage/notify/slack/index.md
  docs/sources/manage/on-call-schedules/_index.md
  docs/sources/manage/on-call-schedules/api-terraform-schedule/_index.md
  docs/sources/manage/on-call-schedules/ical-schedules/index.md
  docs/sources/manage/on-call-schedules/shift-swaps/_index.md
  docs/sources/manage/on-call-schedules/web-schedule/_index.md
  docs/sources/manage/user-and-team-management/_index.md
  docs/sources/oncall-api-reference/integrations.md
  docs/sources/oncall-api-reference/on_call_shifts.md
  docs/sources/oncall-api-reference/outgoing_webhooks.md
  docs/sources/set-up/_index.md
  docs/sources/set-up/get-started/index.md
  docs/sources/set-up/open-source/index.md
Labels: pr:no changelog

#3829 Fix plugin schema URL to point to main
  grafana-plugin/src/plugin.json
Labels: pr:no changelog, pr:no public docs

#3832 patch occasional `UnicodeEncodeError` that occurs with outgoing webhooks
  CHANGELOG.md
  engine/apps/webhooks/models/webhook.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
  engine/apps/webhooks/tests/test_webhook.py
  engine/pyproject.toml
  engine/requirements-dev.txt
Labels: pr:no public docs

#3762 Labels docs
  docs/sources/escalation-chains-and-routes/_index.md
  docs/sources/integrations/_index.md
  docs/sources/jinja2-templating/_index.md
  docs/sources/outgoing-webhooks/_index.md
  grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.tsx
Labels: pr:no changelog

#3833 Add acknowledged/resolved by data to alert groups public API
  docs/sources/oncall-api-reference/alertgroups.md
  engine/apps/public_api/serializers/incidents.py
  engine/apps/public_api/tests/test_alert_groups.py
  engine/apps/public_api/views/incidents.py
Labels: pr:no changelog

#3839 add `pytest-xdist` to speed up backend tests
  engine/apps/integrations/tests/test_views.py
  engine/requirements-dev.txt
  engine/tox.ini
Labels: pr:no changelog, pr:no public docs

#3840 address occasional failing tests when run w/ pytest-xdist
  .github/workflows/linting-and-tests.yml
  engine/conftest.py
  engine/settings/ci-test.py
  engine/tox.ini
Labels: pr:no changelog, pr:no public docs

#3847 let mobile app use escalation options endpoints
  CHANGELOG.md
  engine/apps/api/views/escalation_policy.py
Labels: pr:no public docs

#3854 Update escalation step wording
  engine/apps/alerts/models/escalation_policy.py
  engine/apps/base/models/user_notification_policy_log_record.py
Labels: pr:no changelog, pr:no public docs

#3861 Add permission checks for Slack paging and shift swaps actions
  CHANGELOG.md
  engine/apps/slack/scenarios/paging.py
  engine/apps/slack/scenarios/scenario_step.py
  engine/apps/slack/scenarios/shift_swap_requests.py
  engine/apps/slack/scenarios/step_mixins.py
  engine/apps/slack/tests/test_scenario_steps/test_paging.py
  engine/apps/slack/tests/test_scenario_steps/test_shift_swap_requests.py
Labels: pr:no public docs

#3862 Change email templating to not wrap user defined templates
  CHANGELOG.md
  engine/apps/email/alert_rendering.py
  engine/apps/email/templates/email_notification.html
  engine/apps/email/tests/test_notify_user.py
Labels: pr:no public docs

#3872 Fix rounding issue with displayed time when sending "You're going oncall" push notification
  CHANGELOG.md
  engine/apps/mobile_app/models.py
  engine/apps/mobile_app/tasks/going_oncall_notification.py
  engine/apps/mobile_app/tests/tasks/test_going_oncall_notification.py
Labels: pr:no public docs

#3871 Include all upcoming shifts in upcoming shifts internal endpoint
  CHANGELOG.md
  engine/apps/api/tests/test_user.py
  engine/apps/api/views/user.py
Labels: pr:no public docs

#3863 Restrict integration name uniqueness per team
  CHANGELOG.md
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/public_api/serializers/integrations.py
  engine/apps/public_api/tests/test_integrations.py
Labels: pr:no public docs

#3881 Revert requiring permission on Slack direct paging
  CHANGELOG.md
  engine/apps/slack/scenarios/paging.py
  engine/apps/slack/tests/test_scenario_steps/test_paging.py
Labels: pr:no changelog, pr:no public docs

#3882 v1.3.104
  CHANGELOG.md
  engine/apps/slack/scenarios/paging.py
  engine/apps/slack/tests/test_scenario_steps/test_paging.py
Labels: pr:no changelog, pr:no public docs

#3884 Don't html escape quotes when rendering
  CHANGELOG.md
  engine/apps/api/tests/test_alert_group.py
  engine/common/utils.py
Labels: pr:no public docs

#3886 Handle 400 status codes from Chatops Proxy
  engine/common/oncall_gateway/tasks.py
Labels: pr:no changelog, pr:no public docs

#3888 dev to main
  CHANGELOG.md
  engine/apps/api/tests/test_alert_group.py
  engine/common/oncall_gateway/tasks.py
  engine/common/utils.py
Labels: pr:no public docs

#3891 Check for permissions on Slack escalate command
  CHANGELOG.md
  engine/apps/slack/scenarios/paging.py
  engine/apps/slack/tests/test_scenario_steps/test_paging.py
Labels: pr:no public docs

#3542 Plugin: remove duplicate Declare Incident button
  grafana-plugin/src/pages/incident/Incident.tsx
Labels: pr:no changelog, pr:no public docs

#3899 Quick fix for labels error on labels cache update
  engine/apps/labels/client.py
  engine/apps/labels/tasks.py
  engine/apps/labels/tests/test_labels_cache.py
Labels: pr:no changelog, pr:no public docs

#3896 Improve insights
  grafana-plugin/e2e-tests/insights/insights.test.ts
  grafana-plugin/src/models/alertgroup/alertgroup.ts
  grafana-plugin/src/models/loader/loader.ts
  grafana-plugin/src/pages/insights/Insights.hooks.ts
  grafana-plugin/src/pages/insights/Insights.module.scss
  grafana-plugin/src/pages/insights/Insights.tsx
  grafana-plugin/src/pages/insights/scenes/AlertGroupsByIntegration.tsx
  grafana-plugin/src/pages/insights/scenes/AlertGroupsByTeam.tsx
  grafana-plugin/src/pages/insights/scenes/MTTRAverageStat.tsx
  grafana-plugin/src/pages/insights/scenes/MTTRByIntegration.tsx
  grafana-plugin/src/pages/insights/scenes/MTTRByTeam.tsx
  grafana-plugin/src/pages/insights/scenes/MTTRChangedForPeriodStat.tsx
  grafana-plugin/src/pages/insights/scenes/MTTRChangedTimeseries.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroups.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroupsForSelectedPeriod.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroupsNotificationsInTotal.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroupsNotificationsTable.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroupsNotificationsTimeseries.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroupsTimeseries.tsx
  grafana-plugin/src/pages/insights/scenes/TotalAlertGroupsByState.tsx
  grafana-plugin/src/pages/insights/variables.ts
  grafana-plugin/src/utils/hooks.tsx
Labels: pr:no changelog, pr:no public docs

#3873 When team is removed do not delete webhooks belonging to it
  CHANGELOG.md
  engine/apps/webhooks/migrations/0012_alter_webhook_team.py
  engine/apps/webhooks/models/webhook.py
  engine/apps/webhooks/tests/test_webhook.py
Labels: pr:no public docs

#3904 Fixed schedule rotations form
  CHANGELOG.md
  grafana-plugin/src/components/UserGroups/UserGroups.module.css
  grafana-plugin/src/components/WorkingHours/WorkingHours.tsx
  grafana-plugin/src/containers/RotationForm/RotationForm.module.css
  grafana-plugin/src/containers/RotationForm/RotationForm.tsx
  grafana-plugin/src/utils/consts.ts
Labels: pr:no public docs

#3900 Update user details internal API perms
  CHANGELOG.md
  engine/apps/api/tests/test_team.py
  engine/apps/api/tests/test_user.py
  engine/apps/api/views/user.py
Labels: pr:no changelog, pr:no public docs

#3905 fix issues related to alert groups table
  CHANGELOG.md
  grafana-plugin/src/components/GTable/GTable.tsx
  grafana-plugin/src/containers/ColumnsSelector/ColumnsSelector.tsx
  grafana-plugin/src/containers/ColumnsSelectorWrapper/ColumnsModal.tsx
  grafana-plugin/src/containers/ColumnsSelectorWrapper/ColumnsSelectorWrapper.tsx
  grafana-plugin/src/containers/Rotations/SchedulePersonal.tsx
  grafana-plugin/src/models/alertgroup/alertgroup.ts
  grafana-plugin/src/models/loader/action-keys.ts
  grafana-plugin/src/models/loader/loader.helpers.ts
  grafana-plugin/src/models/loader/loader.ts
  grafana-plugin/src/pages/incidents/Incidents.module.scss
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/insights/Insights.hooks.ts
  grafana-plugin/src/pages/insights/Insights.module.scss
  grafana-plugin/src/pages/insights/Insights.tsx
  grafana-plugin/src/pages/integrations/Integrations.tsx
  grafana-plugin/src/pages/schedules/Schedules.tsx
  grafana-plugin/src/utils/decorators.ts
  grafana-plugin/src/utils/hooks.tsx
Labels: pr:no public docs

#3917 Fix OnCall Insights dashboard version
  grafana-plugin/src/dashboards/oncall_metrics_dashboard.json
Labels: pr:no changelog, pr:no public docs

#3919 Fix user hidden fields tests
  engine/apps/api/tests/test_team.py
  engine/apps/api/tests/test_user.py
Labels: pr:no changelog, pr:no public docs

#3860 add labels to routing templating cheatsheet
  grafana-plugin/src/components/CheatSheet/CheatSheet.config.ts
Labels: pr:no changelog, pr:no public docs

#3305 Add architecture diagram to the dev docs
  dev/README.md
Labels: pr:no changelog, pr:no public docs

#3848 Support prescribed labels
  CHANGELOG.md
  engine/apps/alerts/models/alert.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/models/channel_filter.py
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/serializers/labels.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/tests/test_labels.py
  engine/apps/api/tests/test_webhooks.py
  engine/apps/api/views/labels.py
  engine/apps/labels/alert_group_labels.py
  engine/apps/labels/client.py
  engine/apps/labels/migrations/0005_labelkeycache_prescribed_labelvaluecache_prescribed.py
  engine/apps/labels/models.py
  engine/apps/labels/tasks.py
  engine/apps/labels/tests/test_labels.py
  engine/apps/labels/tests/test_labels_cache.py
  engine/apps/labels/types.py
  engine/apps/labels/utils.py
  engine/common/jinja_templater/apply_jinja_template.py
  engine/settings/celery_task_routes.py
  grafana-plugin/package.json
  grafana-plugin/src/components/LabelTag/LabelTag.tsx
  grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.tsx
  grafana-plugin/src/containers/Labels/Labels.tsx
  grafana-plugin/src/models/label/label.helpers.ts
  grafana-plugin/src/models/label/label.ts
  grafana-plugin/src/network/oncall-api/autogenerated-api.types.d.ts
  grafana-plugin/yarn.lock
Labels: pr:no public docs

#3911 Allow setting email app to use SSL instead of TLS
  CHANGELOG.md
  engine/apps/base/models/live_setting.py
  engine/apps/base/utils.py
  engine/apps/email/tasks.py
  engine/settings/base.py
  helm/oncall/templates/_env.tpl
  helm/oncall/tests/__snapshot__/integrations_deployment_test.yaml.snap
  helm/oncall/tests/smtp_env_test.yaml
  helm/oncall/values.yaml
Labels: pr:no public docs

#3922 remove `disableByPaywall` prop on `WithPermissionControlTooltip` component
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/components/Policy/NotificationPolicy.tsx
  grafana-plugin/src/containers/WithPermissionControl/WithPermissionControlTooltip.tsx
Labels: pr:no changelog, pr:no public docs

#3930 Expose status change trigger type when setting up a webhook
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.config.tsx
Labels: pr:no changelog, pr:no public docs

#3876 update mobile app docs
  docs/sources/manage/mobile-app/_index.md
  docs/sources/manage/mobile-app/alert-groups-feed/index.md
  docs/sources/manage/mobile-app/installation-and-setup/index.md
  docs/sources/manage/mobile-app/push-notifications/index.md
  docs/sources/mobile-app/on-call-status-and-shifts/index.md
  docs/sources/mobile-app/schedules/index.md
Labels: pr:no changelog

#3892 Use pip-tools to handle Python deps
  .github/workflows/linting-and-tests.yml
  Makefile
  Tiltfile
  dev/README.md
  engine/requirements-dev.in
  engine/requirements-dev.txt
  engine/requirements.in
  engine/requirements.txt
Labels: pr:no changelog, pr:no public docs

#3933 Fix .drone grepping for pre-commit
  .drone.yml
Labels: pr:no changelog, pr:no public docs

#3903 :bug: Allow external redis/rabbitmq secret creation even if the broke…
  CHANGELOG.md
  helm/oncall/templates/secrets.yaml
  helm/oncall/tests/broker_secret_test.yaml
Labels: pr:no public docs

#3928 Add revision param to dashboard settings
  grafana-plugin/src/dashboards/oncall_metrics_dashboard.json
Labels: pr:no changelog, pr:no public docs

#3837 Migrate from grafana-toolkit to grafana plugin tools
  .drone.yml
  CHANGELOG.md
  grafana-plugin/.config/.eslintrc
  grafana-plugin/.config/.prettierrc.js
  grafana-plugin/.config/jest-setup.js
  grafana-plugin/.config/jest.config.js
  grafana-plugin/.config/jest/mocks/react-inlinesvg.tsx
  grafana-plugin/.config/jest/utils.js
  grafana-plugin/.config/tsconfig.json
  grafana-plugin/.config/types/custom.d.ts
  grafana-plugin/.config/webpack/constants.ts
  grafana-plugin/.config/webpack/utils.ts
  grafana-plugin/.config/webpack/webpack.config.ts
  grafana-plugin/.eslintrc.js
  grafana-plugin/.nvmrc
  grafana-plugin/.prettierrc.js
  grafana-plugin/babel.config.json
  grafana-plugin/jest.config.js
  grafana-plugin/jest.setup.ts
  grafana-plugin/package.json
  grafana-plugin/src/components/LabelTag/LabelTag.tsx
  grafana-plugin/src/components/Unauthorized/__snapshots__/Unauthorized.test.tsx.snap
  grafana-plugin/src/containers/AddResponders/parts/AddRespondersPopup/AddRespondersPopup.test.tsx
  grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.test.tsx
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/settings/tabs/ChatOps/ChatOps.tsx
  grafana-plugin/src/state/plugin/plugin.test.ts
  grafana-plugin/src/utils/DOM.ts
  grafana-plugin/src/utils/consts.ts
  grafana-plugin/src/utils/datetime.ts
  grafana-plugin/tsconfig.json
  grafana-plugin/webpack.config.js
  grafana-plugin/webpack.config.ts
  grafana-plugin/yarn.lock
Labels: pr:no public docs

#3937 Fix template preview
  CHANGELOG.md
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.helpers.ts
Labels: pr:no public docs

#3939 Fix for update to axios that changed how paramsSerializer is setup
  grafana-plugin/src/network/network.ts
Labels: pr:no changelog, pr:no public docs

#3934 Add status debug to oss plugin publish
  .drone.yml
Labels: pr:no changelog, pr:no public docs

#3943 Brojd/plugin fixes
  grafana-plugin/package.json
  grafana-plugin/webpack.config.ts
Labels: pr:no changelog, pr:no public docs

#3947 Brojd/plugin fixes
  grafana-plugin/webpack.config.ts
Labels: pr:no changelog, pr:no public docs

#3938 fix yarn.lock drift
  grafana-plugin/yarn.lock
Labels: pr:no changelog, pr:no public docs

#3878 Remove explicit request size limits
  CHANGELOG.md
  engine/apps/integrations/tests/test_views.py
  engine/engine/parsers.py
  engine/settings/base.py
  engine/uwsgi.ini
Labels: pr:no public docs

#3949 Update CHANGELOG.md
  CHANGELOG.md
Labels: pr:no changelog, pr:no public docs

#3948 fix `process` is not defined UI issue
  grafana-plugin/src/utils/consts.ts
Labels: pr:no changelog, pr:no public docs

#3950 fix e2e tests
  grafana-plugin/e2e-tests/escalationChains/escalationPolicy.test.ts
  grafana-plugin/e2e-tests/globalSetup.ts
  grafana-plugin/e2e-tests/schedules/quality.test.ts
  grafana-plugin/e2e-tests/utils/schedule.ts
  grafana-plugin/src/containers/ScheduleForm/ScheduleForm.tsx
  grafana-plugin/src/state/rootBaseStore/RootBaseStore.ts
Labels: pr:no changelog, pr:no public docs

#3940 Update OrderedModel.swap to retry on IntegrityError
  engine/common/ordered_model/ordered_model.py
  engine/common/tests/test_ordered_model.py
Labels: pr:no changelog, pr:no public docs

#3951 Add is_from_connected_integration field to webhook model
  engine/apps/api/tests/test_webhooks.py
  engine/apps/api/views/webhooks.py
  engine/apps/public_api/tests/test_webhooks.py
  engine/apps/public_api/views/webhooks.py
  engine/apps/webhooks/migrations/0015_webhook_is_from_connected_integration.py
  engine/apps/webhooks/models/webhook.py
Labels: pr:no changelog, pr:no public docs

#3918 Snow outgoing webhooks tab
  grafana-plugin/.eslintrc.js
  grafana-plugin/e2e-tests/integrations/maintenanceMode.test.ts
  grafana-plugin/e2e-tests/outgoingWebhooks/createAdvancedWebhook.test.ts
  grafana-plugin/e2e-tests/outgoingWebhooks/createSimpleWebhook.test.ts
  grafana-plugin/package.json
  grafana-plugin/src/components/CopyToClipboardIcon/CopyToClipboardIcon.tsx
  grafana-plugin/src/components/HamburgerContextMenu/HamburgerContextMenu.tsx
  grafana-plugin/src/components/HamburgerMenuIcon/HamburgerMenuIcon.module.scss
  grafana-plugin/src/components/HamburgerMenuIcon/HamburgerMenuIcon.tsx
  grafana-plugin/src/components/IntegrationCollapsibleTreeView/IntegrationCollapsibleTreeView.tsx
  grafana-plugin/src/components/IntegrationContactPoint/IntegrationContactPoint.tsx
  grafana-plugin/src/components/IntegrationHowToConnect/IntegrationHowToConnect.tsx
  grafana-plugin/src/components/IntegrationInputField/IntegrationInputField.tsx
  grafana-plugin/src/components/IntegrationLogo/IntegrationLogo.tsx
  grafana-plugin/src/components/IntegrationLogo/IntegrationLogoWithTitle.tsx
  grafana-plugin/src/components/Integrations/IntegrationBlock.tsx
  grafana-plugin/src/components/Integrations/IntegrationTag.tsx
  grafana-plugin/src/components/MonacoEditor/MonacoEditor.tsx
  grafana-plugin/src/components/SourceCode/SourceCode.tsx
  grafana-plugin/src/components/Tabs/Tabs.tsx
  grafana-plugin/src/components/Tag/Tag.module.css
  grafana-plugin/src/components/Tag/Tag.tsx
  grafana-plugin/src/components/Webhooks/WebhookLastEventDetails.tsx
  grafana-plugin/src/components/Webhooks/WebhookLastEventTimestamp.tsx
  grafana-plugin/src/components/Webhooks/WebhookName.tsx
  grafana-plugin/src/components/Webhooks/WebhookStatusCodeBadge.tsx
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.config.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.module.css
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.tsx
  grafana-plugin/src/containers/OutgoingWebhookStatus/OutgoingWebhookStatus.tsx
  grafana-plugin/src/containers/WebhooksTemplateEditor/WebhooksTemplateEditor.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/models/outgoing_webhook/outgoing_webhook.types.ts
  grafana-plugin/src/pages/integration/Integration.module.scss
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/ConnectIntegrationModal.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/ConnectedIntegrationsTable.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/NewOutgoingWebhookDrawerContent.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/OtherIntegrations.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingTab.styles.ts
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingTab.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingTab.types.ts
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingWebhookDetailsDrawerTabs.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingWebhookFormFields.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingWebhooksTable.tsx
  grafana-plugin/src/pages/integrations/Integrations.tsx
  grafana-plugin/src/pages/outgoing_webhooks/OutgoingWebhooks.module.scss
  grafana-plugin/src/pages/outgoing_webhooks/OutgoingWebhooks.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/utils/LocationHelper.ts
  grafana-plugin/src/utils/hooks.tsx
  grafana-plugin/src/utils/string.ts
  grafana-plugin/src/utils/styles.ts
  grafana-plugin/webpack.config.ts
  grafana-plugin/yarn.lock
Labels: pr:no changelog, pr:no public docs

#3954 Integration webhooks API
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/views/alert_receive_channel.py
  engine/common/tests/test_viewset_actions.py
Labels: pr:no changelog, pr:no public docs

#3961 minor UI tweaks for webhooks
  grafana-plugin/src/components/CopyToClipboardIcon/CopyToClipboardIcon.tsx
  grafana-plugin/src/components/IntegrationContactPoint/IntegrationContactPoint.tsx
  grafana-plugin/src/components/IntegrationInputField/IntegrationInputField.tsx
  grafana-plugin/src/components/IntegrationLogo/IntegrationLogoWithTitle.tsx
  grafana-plugin/src/components/Integrations/IntegrationTag.tsx
  grafana-plugin/src/components/SourceCode/SourceCode.module.scss
  grafana-plugin/src/components/SourceCode/SourceCode.tsx
  grafana-plugin/src/components/Webhooks/WebhookLastEventDetails.tsx
  grafana-plugin/src/components/Webhooks/WebhookLastEventTimestamp.tsx
  grafana-plugin/src/components/Webhooks/WebhookStatusCodeBadge.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.module.css
  grafana-plugin/src/containers/OutgoingWebhookStatus/OutgoingWebhookStatus.tsx
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/ConnectedIntegrationsTable.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/NewOutgoingWebhookDrawerContent.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/OtherIntegrations.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingTab.styles.ts
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingTab.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingWebhookDetailsDrawerTabs.tsx
  grafana-plugin/src/utils/styles.ts
Labels: pr:no changelog, pr:no public docs

#3923 Fix daily e2e tests GitHub Actions cron job
  .drone.yml
  .github/workflows/daily-e2e-tests.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/linting-and-tests.yml
  docker-compose-developer.yml
  engine/Dockerfile
  grafana-plugin/e2e-tests/fixtures.ts
  grafana-plugin/e2e-tests/globalSetup.ts
  grafana-plugin/e2e-tests/insights/insights.test.ts
  grafana-plugin/e2e-tests/integrations/heartbeat.test.ts
  grafana-plugin/e2e-tests/integrations/maintenanceMode.test.ts
  grafana-plugin/e2e-tests/utils/clients/grafana.ts
  grafana-plugin/e2e-tests/utils/modals.ts
  grafana-plugin/e2e-tests/utils/userSettings.ts
  grafana-plugin/package.json
  grafana-plugin/src/containers/UserSettings/parts/tabs/NotificationSettingsTab.tsx
  grafana-plugin/yarn.lock
Labels: pr:no changelog, pr:no public docs

#3941 Add task to delete empty deleted integrations from the database
  CHANGELOG.md
  engine/apps/grafana_plugin/tasks/sync.py
  engine/apps/grafana_plugin/tests/test_sync.py
  engine/settings/celery_task_routes.py
Labels: pr:no public docs

#3963 fix information architecture for mobile app docs
  docs/sources/mobile-app/on-call-status-and-shifts/_index.md
  docs/sources/mobile-app/schedules/_index.md
Labels: pr:no changelog, pr:no public docs

#3967 Fix path for plugin release publish
  .drone.yml
Labels: pr:no changelog, pr:no public docs

#3952 Deploy PR e2e test report to GH Pages
  .github/workflows/e2e-tests.yml
  grafana-plugin/e2e-tests/fixtures.ts
  grafana-plugin/playwright.config.ts
Labels: pr:no changelog, pr:no public docs

#3969 Fetch selected value of notify schedule in escalation policy
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/pages/integration/Integration.helper.ts
  grafana-plugin/src/pages/integration/Integration.tsx
Labels: pr:no changelog, pr:no public docs

#3968 Brojd/connect integration to snow
  grafana-plugin/e2e-tests/insights/insights.test.ts
  grafana-plugin/e2e-tests/integrations/maintenanceMode.test.ts
  grafana-plugin/src/components/GTable/GTable.tsx
  grafana-plugin/src/components/Webhooks/WebhookName.tsx
  grafana-plugin/src/containers/AlertReceiveChannelCard/AlertReceiveChannelCard.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.helpers.ts
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/models/loader/action-keys.ts
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/ConnectIntegrationModal.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/ConnectedIntegrationsTable.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/OtherIntegrations.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingTab.styles.ts
  grafana-plugin/src/pages/integrations/Integrations.tsx
Labels: pr:no changelog, pr:no public docs

#3970 Update faro package to 1.3.9
  CHANGELOG.md
  grafana-plugin/package.json
  grafana-plugin/src/network/network.ts
  grafana-plugin/src/network/oncall-api/http-client.test.ts
  grafana-plugin/src/network/oncall-api/http-client.ts
  grafana-plugin/src/utils/faro.test.tsx
  grafana-plugin/src/utils/faro.ts
  grafana-plugin/yarn.lock
Labels: pr:no public docs

#3971 Added --max-warnings=0 to eslint:fix command
  grafana-plugin/package.json
Labels: pr:no changelog, pr:no public docs

#3980 update
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/containers/AlertRules/parts/connectors/MSTeamsConnector.tsx
  grafana-plugin/src/containers/AlertRules/parts/connectors/TelegramConnector.tsx
  grafana-plugin/src/containers/EscalationChainForm/EscalationChainForm.tsx
  grafana-plugin/src/containers/GSelect/GSelect.tsx
  grafana-plugin/src/containers/GrafanaTeamSelect/GrafanaTeamSelect.tsx
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.config.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.config.tsx
  grafana-plugin/src/containers/ScheduleForm/ScheduleForm.config.ts
  grafana-plugin/src/models/grafana_team/grafana_team.ts
  grafana-plugin/src/models/user_group/user_group.ts
Labels: pr:no changelog, pr:no public docs

#3981 Snow integration webhooks CRUD
  grafana-plugin/src/assets/style/grafanaGlobalStyles.css
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/components/Webhooks/WebhookLastEventDetails.tsx
  grafana-plugin/src/components/Webhooks/WebhookLastEventTimestamp.tsx
  grafana-plugin/src/components/Webhooks/WebhookName.tsx
  grafana-plugin/src/components/Webhooks/WebhookStatusCodeBadge.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.tsx
  grafana-plugin/src/containers/OutgoingWebhookStatus/OutgoingWebhookStatus.tsx
  grafana-plugin/src/containers/TemplatePreview/TemplatePreview.tsx
  grafana-plugin/src/containers/TemplateResult/TemplateResult.tsx
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
  grafana-plugin/src/containers/WebhooksTemplateEditor/WebhooksTemplateEditor.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/models/alert_receive_channel_webhooks/alert_receive_channel_webhooks.ts
  grafana-plugin/src/models/escalation_policy/escalation_policy.types.ts
  grafana-plugin/src/models/outgoing_webhook/outgoing_webhook.ts
  grafana-plugin/src/models/outgoing_webhook/outgoing_webhook.types.ts
  grafana-plugin/src/network/oncall-api/autogenerated-api.types.d.ts
  grafana-plugin/src/network/oncall-api/types-generator/custom-schemas.ts
  grafana-plugin/src/network/oncall-api/types-generator/generate-types.ts
  grafana-plugin/src/pages/integration/OutgoingTab/ConnectIntegrationModal.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/NewOutgoingWebhookDrawerContent.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingTab.hooks.ts
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingTab.styles.ts
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingTab.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingTab.types.ts
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingWebhookDetailsDrawerTabs.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingWebhookFormFields.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingWebhooksTable.tsx
  grafana-plugin/src/pages/outgoing_webhooks/OutgoingWebhooks.tsx
  grafana-plugin/src/state/rootBaseStore/RootBaseStore.ts
  grafana-plugin/src/utils/string.ts
Labels: pr:no changelog, pr:no public docs
