Repository grafana/oncall, pull requests merged in 2024-06, with the labels that each got.

#4232 Prepare OnCall for Unified Slack App
  dev/kind-config.yaml
  engine/apps/alerts/incident_appearance/renderers/slack_renderer.py
  engine/apps/api/tests/test_auth.py
  engine/apps/api/views/auth.py
  engine/apps/chatops_proxy/__init__.py
  engine/apps/chatops_proxy/client.py
  engine/apps/chatops_proxy/events/__init__.py
  engine/apps/chatops_proxy/events/handlers.py
  engine/apps/chatops_proxy/events/root_handler.py
  engine/apps/chatops_proxy/events/signature.py
  engine/apps/chatops_proxy/events/types.py
  engine/apps/chatops_proxy/tasks.py
  engine/apps/chatops_proxy/tests/__init__.py
  engine/apps/chatops_proxy/tests/test_events.py
  engine/apps/chatops_proxy/urls.py
  engine/apps/chatops_proxy/utils.py
  engine/apps/chatops_proxy/views.py
  engine/apps/slack/chatops_proxy_routing.py
  engine/apps/slack/installation.py
  engine/apps/slack/models/slack_team_identity.py
  engine/apps/slack/scenarios/alertgroup_appearance.py
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/slack/scenarios/manage_responders.py
  engine/apps/slack/scenarios/paging.py
  engine/apps/slack/scenarios/resolution_note.py
  engine/apps/slack/scenarios/schedules.py
  engine/apps/slack/scenarios/shift_swap_requests.py
  engine/apps/slack/tests/test_installation.py
  engine/apps/slack/tests/test_scenario_steps/test_manage_responders.py
  engine/apps/slack/tests/test_scenario_steps/test_paging.py
  engine/apps/slack/tests/test_scenario_steps/test_resolution_note.py
  engine/apps/slack/tests/test_slack_renderer.py
  engine/apps/slack/urls.py
  engine/apps/slack/views.py
  engine/apps/social_auth/backends.py
  engine/apps/social_auth/pipeline/slack.py
  engine/apps/telegram/client.py
  engine/apps/user_management/models/organization.py
  engine/common/constants/slack_auth.py
  engine/common/oncall_gateway/__init__.py
  engine/common/oncall_gateway/legacy_client.py
  engine/common/oncall_gateway/tasks.py
  engine/common/oncall_gateway/utils.py
  engine/engine/urls.py
  engine/settings/base.py
  engine/settings/celery_task_routes.py
  grafana-plugin/src/models/slack/slack.ts
  grafana-plugin/src/network/network.ts
Labels: pr:no public docs, release:ignore

#4441 Revert "Allow custom wait delays"
  engine/apps/api/serializers/escalation_policy.py
  engine/apps/api/serializers/user_notification_policy.py
  engine/apps/api/tests/test_escalation_policy.py
  engine/apps/api/tests/test_user_notification_policy.py
  engine/apps/api/views/alert_group.py
  engine/apps/api/views/escalation_policy.py
  engine/common/api_helpers/custom_fields.py
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/components/Policy/NotificationPolicy.tsx
  grafana-plugin/src/components/Policy/Policy.consts.ts
  grafana-plugin/src/containers/EscalationChainSteps/EscalationChainSteps.tsx
  grafana-plugin/src/models/alertgroup/alertgroup.ts
  grafana-plugin/src/models/escalation_policy/escalation_policy.ts
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/incidents/parts/IncidentDropdown.tsx
  grafana-plugin/src/pages/incidents/parts/IncidentSilenceModal.tsx
  grafana-plugin/src/pages/incidents/parts/SilenceButtonCascader.tsx
  grafana-plugin/src/pages/incidents/parts/SilenceSelect.tsx
Labels: pr:no public docs, release:ignore

#4420 Oncall initialization frontend cleanup
  .github/workflows/linting-and-tests.yml
  Tiltfile
  dev/grafana/provisioning/plugins/grafana-oncall-app-provisioning.yaml
  grafana-plugin/e2e-tests/alerts/directPaging.test.ts
  grafana-plugin/e2e-tests/globalSetup.ts
  grafana-plugin/e2e-tests/integrations/integrationsTable.test.ts
  grafana-plugin/e2e-tests/users/usersActions.test.ts
  grafana-plugin/pkg/plugin/grafana_client.go
  grafana-plugin/pkg/plugin/resources.go
  grafana-plugin/pkg/plugin/settings.go
  grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.test.tsx
  grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.tsx
  grafana-plugin/src/containers/PluginConfigPage/__snapshots__/PluginConfigPage.test.tsx.snap
  grafana-plugin/src/containers/PluginConfigPage/parts/ConfigurationForm/ConfigurationForm.module.css
  grafana-plugin/src/containers/PluginConfigPage/parts/ConfigurationForm/ConfigurationForm.test.tsx
  grafana-plugin/src/containers/PluginConfigPage/parts/ConfigurationForm/ConfigurationForm.tsx
  grafana-plugin/src/containers/PluginConfigPage/parts/ConfigurationForm/__snapshots__/ConfigurationForm.test.tsx.snap
  grafana-plugin/src/containers/PluginConfigPage/parts/RemoveCurrentConfigurationButton/RemoveCurrentConfigurationButton.test.tsx
  grafana-plugin/src/containers/PluginConfigPage/parts/RemoveCurrentConfigurationButton/RemoveCurrentConfigurationButton.tsx
  grafana-plugin/src/containers/PluginConfigPage/parts/RemoveCurrentConfigurationButton/__snapshots__/RemoveCurrentConfigurationButton.test.tsx.snap
  grafana-plugin/src/containers/PluginConfigPage/parts/StatusMessageBlock/StatusMessageBlock.test.tsx
  grafana-plugin/src/containers/PluginConfigPage/parts/StatusMessageBlock/StatusMessageBlock.tsx
  grafana-plugin/src/containers/PluginConfigPage/parts/StatusMessageBlock/__snapshots__/StatusMessageBlock.test.tsx.snap
  grafana-plugin/src/models/user/user.types.ts
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/plugin/PluginSetup/PluginSetup.test.tsx
  grafana-plugin/src/plugin/PluginSetup/PluginSetup.tsx
  grafana-plugin/src/plugin/PluginSetup/__snapshots__/PluginSetup.test.tsx.snap
  grafana-plugin/src/state/plugin/__snapshots__/plugin.test.ts.snap
  grafana-plugin/src/state/plugin/plugin.test.ts
  grafana-plugin/src/state/plugin/plugin.ts
  grafana-plugin/src/state/rootBaseStore/RootBaseStore.test.ts
  grafana-plugin/src/state/rootBaseStore/RootBaseStore.ts
  grafana-plugin/src/types.ts
  grafana-plugin/src/utils/consts.ts
  grafana-plugin/src/utils/hooks.tsx
Labels: pr:no public docs, release:ignore

#4438 Theming backwards compatibility
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.styles.ts
  grafana-plugin/src/containers/Rotations/Rotations.styles.ts
  grafana-plugin/src/containers/ServiceNowConfigDrawer/ServiceNow.styles.ts
Labels: pr:no public docs, release:ignore

#4436 Allow user unset the escalation chain on the integration
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
Labels: pr:no public docs, release:patch

#4446 Allow custom wait delay
  engine/apps/api/serializers/escalation_policy.py
  engine/apps/api/serializers/user_notification_policy.py
  engine/apps/api/tests/test_escalation_policy.py
  engine/apps/api/tests/test_user_notification_policy.py
  engine/apps/api/views/alert_group.py
  engine/apps/api/views/escalation_policy.py
  engine/common/api_helpers/custom_fields.py
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/components/Policy/NotificationPolicy.tsx
  grafana-plugin/src/components/Policy/Policy.consts.ts
  grafana-plugin/src/containers/EscalationChainSteps/EscalationChainSteps.tsx
  grafana-plugin/src/models/alertgroup/alertgroup.ts
  grafana-plugin/src/models/escalation_policy/escalation_policy.ts
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/incidents/parts/IncidentDropdown.tsx
  grafana-plugin/src/pages/incidents/parts/IncidentSilenceModal.tsx
  grafana-plugin/src/pages/incidents/parts/SilenceButtonCascader.tsx
  grafana-plugin/src/pages/incidents/parts/SilenceSelect.tsx
Labels: pr:no public docs, release:enhancement

#4407 Plugin.json: update with extensions info
  grafana-plugin/src/plugin.json
Labels: pr:no public docs, release:ignore

#4442 Fix escaping quotes in Insights queries
  grafana-plugin/src/dashboards/oncall_metrics_dashboard.json
  grafana-plugin/src/pages/insights/scenes/AlertGroupsByIntegration.tsx
  grafana-plugin/src/pages/insights/scenes/AlertGroupsByTeam.tsx
  grafana-plugin/src/pages/insights/scenes/MTTRAverageStat.tsx
  grafana-plugin/src/pages/insights/scenes/MTTRByIntegration.tsx
  grafana-plugin/src/pages/insights/scenes/MTTRByTeam.tsx
  grafana-plugin/src/pages/insights/scenes/MTTRChangedTimeseries.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroups.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroupsNotificationsTable.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroupsNotificationsTimeseries.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroupsTimeseries.tsx
  grafana-plugin/src/pages/insights/variables.ts
Labels: pr:no public docs, release:patch

#4393 change zvonok call verification
  docs/sources/set-up/open-source/index.md
  engine/apps/base/models/live_setting.py
  engine/apps/zvonok/phone_provider.py
  engine/apps/zvonok/tests/test_zvonok_provider.py
  engine/settings/base.py
Labels: release:patch

#4447 Fix display of schedule final in preview mode
  grafana-plugin/src/components/GTable/GTable.tsx
  grafana-plugin/src/pages/schedules/Schedules.tsx
Labels: pr:no public docs, release:patch

#4287 conditionally enable searching for alert groups via env var
  engine/apps/api/views/alert_group.py
  engine/settings/base.py
  grafana-plugin/src/models/alertgroup/alertgroup.ts
Labels: pr:no public docs, release:patch

#4456 Show correct swap request dates
  grafana-plugin/src/containers/Rotations/SchedulePersonal.tsx
  grafana-plugin/src/pages/schedule/Schedule.tsx
  grafana-plugin/src/styles/utils.styles.ts
Labels: pr:no public docs, release:patch

#4458 Reduce size of payload on `/escalate` Slack command
  engine/apps/slack/scenarios/paging.py
Labels: pr:no public docs, release:ignore

#4459 only validate existing settings
  engine/apps/base/models/live_setting.py
Labels: pr:no public docs, release:ignore

#4453 Support grafana escalate
  engine/apps/slack/slash_command.py
  engine/apps/slack/tests/test_interactive_api_endpoint.py
  engine/apps/slack/tests/test_slash_command.py
  engine/apps/slack/views.py
  engine/settings/base.py
Labels: pr:no public docs, release:ignore

#4466 Drone -> GitHub Actions migration
  .github/actions/build-sign-and-package-plugin/action.yml
  .github/actions/set-engine-version-in-settings/action.yml
  .github/workflows/build-engine-docker-image-and-publish-to-dockerhub.yml
  .github/workflows/linting-and-tests.yml
  .github/workflows/on-commits-to-dev.yml
  .github/workflows/on-pull-requests.yml
  .github/workflows/on-release-published.yml
Labels: pr:no public docs, release:ignore

#4433 add exotel call provider
  docs/sources/set-up/open-source/index.md
  engine/apps/base/models/live_setting.py
  engine/apps/exotel/__init__.py
  engine/apps/exotel/migrations/0001_initial.py
  engine/apps/exotel/migrations/__init__.py
  engine/apps/exotel/models/__init__.py
  engine/apps/exotel/models/phone_call.py
  engine/apps/exotel/phone_provider.py
  engine/apps/exotel/status_callback.py
  engine/apps/exotel/tests/__init__.py
  engine/apps/exotel/tests/test_exotel_provider.py
  engine/apps/exotel/urls.py
  engine/apps/exotel/views.py
  engine/engine/urls.py
  engine/settings/base.py
Labels: release:enhancement

#4463 Fix alert groups automatic refresh
  grafana-plugin/src/containers/RemoteFilters/RemoteFilters.tsx
  grafana-plugin/src/models/alertgroup/alertgroup.helpers.ts
  grafana-plugin/src/models/alertgroup/alertgroup.ts
  grafana-plugin/src/models/loader/action-keys.ts
  grafana-plugin/src/network/oncall-api/types-generator/custom-schemas.ts
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/incidents/parts/IncidentSilenceModal.tsx
Labels: pr:no public docs, release:patch

#4478 🪦 RIP Drone 🪦
  .drone.yml
  README.md
  dev/README.md
  tools/image-tag.sh
Labels: pr:no public docs, release:ignore

#4452 remove `CODE_OF_CONDUCT.md` and `LICENSING.md` files
  CODE_OF_CONDUCT.md
  LICENSING.md
Labels: release:ignore

#4465 First e2e tests for plugin initialization
  grafana-plugin/e2e-tests/globalSetup.ts
  grafana-plugin/e2e-tests/pluginInitialization/configuration.test.ts
  grafana-plugin/e2e-tests/pluginInitialization/initialization.test.ts
  grafana-plugin/e2e-tests/users/usersActions.test.ts
  grafana-plugin/e2e-tests/utils/constants.ts
  grafana-plugin/e2e-tests/utils/forms.ts
  grafana-plugin/e2e-tests/utils/users.ts
  grafana-plugin/src/components/ExtensionLinkMenu/ExtensionLinkMenu.tsx
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.tsx
  grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.tsx
  grafana-plugin/src/containers/ServiceNowConfigDrawer/ServiceNowConfigDrawer.tsx
  grafana-plugin/src/models/loader/action-keys.ts
  grafana-plugin/src/models/plugin/plugin.ts
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/state/rootBaseStore/RootBaseStore.ts
  grafana-plugin/src/types.ts
  grafana-plugin/src/utils/authorization/authorization.ts
  grafana-plugin/src/utils/consts.ts
  grafana-plugin/src/utils/faro.ts
  grafana-plugin/src/utils/hooks.tsx
  grafana-plugin/src/utils/string.ts
  grafana-plugin/src/utils/utils.ts
Labels: pr:no public docs, release:ignore

#4479 Remove Simulate Incident button
  engine/apps/integrations/mixins/browsable_instruction_mixin.py
  engine/apps/integrations/templates/integration_link.html
Labels: pr:no public docs, release:ignore

#4482 Update resolution note message shortcut instruction
  engine/apps/slack/scenarios/resolution_note.py
  engine/apps/slack/tests/test_scenario_steps/test_resolution_note.py
  engine/static/images/postmortem.gif
  engine/static/images/resolution_note.gif
Labels: pr:no public docs, release:enhancement

#4486 Handle SlackAPIRatelimitError in perform_notification
  engine/apps/slack/models/slack_message.py
Labels: pr:no public docs, release:patch

#4487 add missing deps, dont use mobx-react-lite
  grafana-plugin/package.json
  grafana-plugin/src/pages/integration/OutgoingTab/ConnectIntegrationModal.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/OtherIntegrations.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingWebhookDetailsDrawerTabs.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingWebhooksTable.tsx
  grafana-plugin/yarn.lock
Labels: pr:no public docs, release:ignore

#4488 Revert using backticks in insights queries
  grafana-plugin/src/dashboards/oncall_metrics_dashboard.json
  grafana-plugin/src/pages/insights/scenes/AlertGroupsByIntegration.tsx
  grafana-plugin/src/pages/insights/scenes/AlertGroupsByTeam.tsx
  grafana-plugin/src/pages/insights/scenes/MTTRAverageStat.tsx
  grafana-plugin/src/pages/insights/scenes/MTTRByIntegration.tsx
  grafana-plugin/src/pages/insights/scenes/MTTRByTeam.tsx
  grafana-plugin/src/pages/insights/scenes/MTTRChangedTimeseries.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroups.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroupsNotificationsTable.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroupsNotificationsTimeseries.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroupsTimeseries.tsx
  grafana-plugin/src/pages/insights/variables.ts
Labels: pr:no public docs, release:ignore

#4494 Fix alarming JS errors
  grafana-plugin/src/components/AlertTemplates/AlertTemplatesForm.config.ts
  grafana-plugin/src/containers/Alerts/Alerts.tsx
  grafana-plugin/src/containers/IntegrationContainers/IntegrationTemplatesList.config.ts
  grafana-plugin/src/containers/RotationForm/ScheduleOverrideForm.tsx
  grafana-plugin/src/containers/UserSettings/parts/tabs/PhoneVerification/PhoneVerification.tsx
  grafana-plugin/src/models/alertgroup/alertgroup.ts
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/utils/faro.ts
Labels: pr:no public docs, release:ignore

#4502 fix flaky tests + increase runner size when building docker image
  .github/workflows/build-engine-docker-image-and-publish-to-dockerhub.yml
  .github/workflows/linting-and-tests.yml
  .github/workflows/snyk-security-scan.yml
  engine/apps/alerts/tests/test_escalation_snapshot.py
  engine/apps/api/tests/test_user.py
  engine/tox.ini
Labels: pr:no public docs, release:ignore

#4376 [DOCS] SMS and call routing tutorial
  docs/sources/configure/live-call-routing/index.md
Labels: type/docs, release:ignore

#4516 update `sqlparse` to address CVE-2024-4340
  engine/requirements-dev.txt
  engine/requirements.txt
Labels: pr:no public docs, release:patch

#4510 Handle slack uninstall event from chatops-proxy
  engine/apps/chatops_proxy/events/handlers.py
  engine/apps/chatops_proxy/events/root_handler.py
  engine/apps/chatops_proxy/events/types.py
  engine/apps/chatops_proxy/tests/test_events.py
Labels: pr:no public docs, release:ignore

#4539 update api docs
  docs/sources/oncall-api-reference/_index.md
Labels: release:ignore

#4541 Fix "Cannot read ... of undefined" from Axios response
  grafana-plugin/src/utils/faro.ts
Labels: pr:no public docs, release:ignore

#4518 Support message shortcut broadcast
  engine/apps/slack/scenarios/resolution_note.py
  engine/apps/slack/tests/test_scenario_steps/test_resolution_note.py
Labels: pr:no public docs, release:ignore

#4481 Make rotation start and rotation end take timezone into consideration
  grafana-plugin/src/containers/Rotation/Rotation.tsx
  grafana-plugin/src/containers/RotationForm/RotationForm.helpers.test.ts
  grafana-plugin/src/containers/RotationForm/RotationForm.helpers.ts
  grafana-plugin/src/containers/RotationForm/RotationForm.tsx
  grafana-plugin/src/containers/RotationForm/ScheduleOverrideForm.tsx
  grafana-plugin/src/containers/RotationForm/ShiftSwapForm.tsx
  grafana-plugin/src/containers/RotationForm/parts/DateTimePicker.tsx
  grafana-plugin/src/containers/Rotations/Rotations.helpers.ts
  grafana-plugin/src/containers/Rotations/Rotations.tsx
  grafana-plugin/src/containers/Rotations/ScheduleFinal.tsx
  grafana-plugin/src/containers/Rotations/SchedulePersonal.tsx
  grafana-plugin/src/models/timezone/timezone.ts
  grafana-plugin/src/pages/schedule/Schedule.helpers.ts
  grafana-plugin/src/pages/schedule/Schedule.tsx
Labels: pr:no public docs, release:patch

#4544 Disable All option for non selectable variables
  grafana-plugin/src/pages/insights/variables.ts
Labels: pr:no public docs, release:ignore

#4546 fix right-hand navigation in API docs
  docs/sources/oncall-api-reference/alertgroups.md
  docs/sources/oncall-api-reference/alerts.md
  docs/sources/oncall-api-reference/escalation_chains.md
  docs/sources/oncall-api-reference/escalation_policies.md
  docs/sources/oncall-api-reference/integrations.md
  docs/sources/oncall-api-reference/on_call_shifts.md
  docs/sources/oncall-api-reference/outgoing_webhooks.md
  docs/sources/oncall-api-reference/personal_notification_rules.md
  docs/sources/oncall-api-reference/resolution_notes.md
  docs/sources/oncall-api-reference/routes.md
  docs/sources/oncall-api-reference/schedules.md
  docs/sources/oncall-api-reference/shift_swaps.md
  docs/sources/oncall-api-reference/slack_channels.md
  docs/sources/oncall-api-reference/user_groups.md
  docs/sources/oncall-api-reference/users.md
Labels: release:ignore

#4542 fix rbac check, add grafanaUrl to provisioning file, fix Tiltfile
  Tiltfile
  dev/grafana/provisioning/plugins/grafana-oncall-app-provisioning.yaml
  engine/apps/grafana_plugin/helpers/client.py
  engine/apps/grafana_plugin/tests/test_grafana_api_client.py
Labels: pr:no public docs, release:ignore

#4563 Only generate random OnCall secrets value when it is not provided
  helm/oncall/templates/secrets.yaml
Labels: pr:no public docs, release:ignore

#4564 Remove beta warning for mobile app
  docs/sources/set-up/open-source/index.md
Labels: pr:no public docs, release:ignore

#4566 initialize faro only on prod
  grafana-plugin/package.json
  grafana-plugin/src/utils/consts.ts
  grafana-plugin/src/utils/faro.ts
  grafana-plugin/webpack.config.ts
Labels: pr:no public docs, release:ignore

#4557 Add a simple phone number ban mechanism
  engine/apps/phone_notifications/exceptions.py
  engine/apps/phone_notifications/migrations/0002_bannedphonenumber.py
  engine/apps/phone_notifications/models/banned_phone_number.py
  engine/apps/phone_notifications/phone_backend.py
  engine/apps/phone_notifications/tests/test_banned_phone_number.py
  engine/apps/phone_notifications/tests/test_phone_backend_phone_verification.py
Labels: pr:no public docs, release:patch

#4559 Post stack slug to chatops proxy
  engine/apps/chatops_proxy/client.py
  engine/apps/chatops_proxy/tasks.py
  engine/apps/chatops_proxy/utils.py
  engine/apps/slack/views.py
  engine/apps/user_management/models/organization.py
Labels: pr:no public docs, release:ignore

#4556 Inject chatops-proxy metadata into direct paging user dropdown
  engine/apps/slack/scenarios/paging.py
Labels: pr:no public docs, release:ignore

#4553 Tweaks to overrides (added draggable bounds, take timezone into consideration)
  grafana-plugin/e2e-tests/alerts/onCallSchedule.test.ts
  grafana-plugin/e2e-tests/insights/insights.test.ts
  grafana-plugin/e2e-tests/schedules/addOverride.test.ts
  grafana-plugin/e2e-tests/schedules/addRotation.test.ts
  grafana-plugin/e2e-tests/schedules/quality.test.ts
  grafana-plugin/e2e-tests/schedules/scheduleDetails.test.ts
  grafana-plugin/e2e-tests/schedules/scheduleView.test.ts
  grafana-plugin/e2e-tests/schedules/schedulesList.test.ts
  grafana-plugin/e2e-tests/schedules/timezones.test.ts
  grafana-plugin/e2e-tests/utils/constants.ts
  grafana-plugin/e2e-tests/utils/grafanaProfile.ts
  grafana-plugin/e2e-tests/utils/schedule.ts
  grafana-plugin/src/containers/RotationForm/RotationForm.helpers.ts
  grafana-plugin/src/containers/RotationForm/RotationForm.tsx
  grafana-plugin/src/containers/RotationForm/ScheduleOverrideForm.tsx
  grafana-plugin/src/containers/Rotations/Rotations.helpers.ts
  grafana-plugin/src/containers/Rotations/Rotations.tsx
  grafana-plugin/src/containers/Rotations/ScheduleOverrides.tsx
  grafana-plugin/src/pages/schedule/Schedule.tsx
  grafana-plugin/src/utils/DOM.ts
  grafana-plugin/src/utils/hooks.tsx
Labels: pr:no public docs, release:patch

#4574 Add spacing between words in notifications.
  engine/apps/phone_notifications/phone_backend.py
Labels: pr:no public docs, release:ignore

#4565 Peridic chatops proxy sync
  engine/apps/chatops_proxy/register_oncall_tenant.py
  engine/apps/chatops_proxy/tasks.py
  engine/apps/chatops_proxy/utils.py
  engine/apps/user_management/models/organization.py
  engine/settings/base.py
  engine/settings/celery_task_routes.py
Labels: pr:no public docs, release:ignore

#4558 set ONCALL_API_URL value in provisioning file based on env var
  Tiltfile
  dev/grafana/provisioning/plugins/grafana-oncall-app-provisioning.yaml
  docker-compose-developer.yml
  grafana-plugin/src/utils/consts.ts
  grafana-plugin/webpack.config.ts
Labels: pr:no public docs, release:ignore

#4572 make links clickable in resolution notes
  grafana-plugin/package.json
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/containers/ServiceNowConfigDrawer/ServiceNowConfigDrawer.tsx
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/utils/string.ts
  grafana-plugin/yarn.lock
Labels: pr:no public docs, release:ignore

#4577 Rename notify whole Slack channel
  docs/sources/configure/escalation-chains-and-routes/index.md
  docs/sources/manage/notify/slack/index.md
  engine/apps/alerts/models/escalation_policy.py
Labels: release:ignore

#4582 Update Makefile dev bootstrap; fix test
  Makefile
  engine/apps/public_api/tests/test_shift_swap.py
Labels: pr:no public docs, release:ignore

#4448 add labels in grafana-incident alertgroup endpoint
  engine/apps/api_for_grafana_incident/serializers.py
  engine/apps/api_for_grafana_incident/tests/test_views.py
Labels: pr:no public docs, release:ignore

#4570 Fix PhoneNumberBanned producing status code 500
  engine/apps/api/views/user.py
Labels: pr:no public docs, release:patch

#4596 Add START_SYNC_ORG_WITH_CHATOPS_PROXY_ENABLED
  engine/settings/base.py
Labels: pr:no public docs, release:ignore

#4585 FARO npe fixes
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/containers/RotationForm/parts/DaysSelector.tsx
  grafana-plugin/src/utils/faro.ts
Labels: pr:no public docs, release:ignore

#4583 Updated filters look
  grafana-plugin/src/components/Text/Text.styles.ts
  grafana-plugin/src/components/Text/Text.tsx
  grafana-plugin/src/containers/RemoteFilters/RemoteFilters.module.css
  grafana-plugin/src/containers/RemoteFilters/RemoteFilters.tsx
Labels: pr:no public docs, release:patch

#4586 Changed polling to 10s for alert groups
  grafana-plugin/src/pages/incidents/Incidents.tsx
Labels: pr:no public docs, release:patch

#4567 Plugin initialization improvements
  engine/apps/user_management/sync.py
  grafana-plugin/e2e-tests/alerts/directPaging.test.ts
  grafana-plugin/e2e-tests/globalSetup.ts
  grafana-plugin/e2e-tests/integrations/integrationsTable.test.ts
  grafana-plugin/e2e-tests/pluginInitialization/configuration.test.ts
  grafana-plugin/e2e-tests/pluginInitialization/initialization.test.ts
  grafana-plugin/e2e-tests/utils/users.ts
  grafana-plugin/pkg/plugin/app.go
  grafana-plugin/pkg/plugin/install.go
  grafana-plugin/pkg/plugin/status.go
  grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.tsx
  grafana-plugin/src/containers/PluginInitializer/PluginInitializer.tsx
  grafana-plugin/src/models/plugin/plugin.ts
  grafana-plugin/src/network/grafana-api/http-client.ts
Labels: pr:no public docs, release:ignore

#4599 Minor plugin description update
  grafana-plugin/src/plugin.json
Labels: pr:no public docs, release:ignore
