Repository grafana/oncall, pull requests merged in 2024-05, with the labels that each got.

#4288 Display human readable time ranges in AG filters
  engine/apps/api/tests/test_alert_group.py
  engine/apps/api/views/alert_group.py
  engine/common/api_helpers/filters.py
  grafana-plugin/src/containers/RemoteFilters/RemoteFilters.helpers.ts
  grafana-plugin/src/containers/RemoteFilters/RemoteFilters.tsx
  grafana-plugin/src/models/alertgroup/alertgroup.ts
  grafana-plugin/src/models/filters/filters.helpers.ts
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/utils/datetime.test.ts
  grafana-plugin/src/utils/datetime.ts
Labels: pr:no public docs, release:enhancement

#4306 Set a timeout for mobile app incident proxy requests
  engine/apps/mobile_app/tests/test_mobile_app_gateway.py
  engine/apps/mobile_app/views.py
Labels: pr:no public docs, release:ignore

#4308 Make team selects searchable
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/containers/ScheduleForm/ScheduleForm.tsx
Labels: pr:no public docs, release:patch

#4296 improve frontend dev exp
  Tiltfile
  dev/README.md
  grafana-plugin/Dockerfile.dev
Labels: pr:no public docs, release:ignore

#4314 Add logging of arguments for celery tasks
  engine/engine/celery.py
  engine/settings/base.py
Labels: pr:no public docs, release:patch

#4316 Remove kwargs from celery logging
  engine/engine/celery.py
Labels: pr:no public docs, release:ignore

#4319 Fix escalation chain webhooks executing when disabled
  engine/apps/alerts/escalation_snapshot/snapshot_classes/escalation_policy_snapshot.py
  engine/apps/alerts/models/alert_group_log_record.py
  engine/apps/alerts/tests/test_escalation_policy_snapshot.py
Labels: pr:no public docs, release:patch

#4321 Update drone signature
  .drone.yml
Labels: pr:no public docs, release:ignore

#4322 Fix drone unit tests uv install
  .drone.yml
Labels: pr:no public docs, release:ignore

#4325 Minor query optimizations
  engine/apps/alerts/models/alert_group.py
  engine/apps/public_api/serializers/incidents.py
Labels: pr:no public docs, release:ignore

#4326 Handle empty values in convertFiltersToBackendFormat
  grafana-plugin/src/models/filters/filters.helpers.ts
Labels: pr:no public docs, release:ignore

#4317 Update deep link URL for Slack messages
  engine/apps/slack/models/slack_message.py
  engine/apps/slack/tests/test_slack_message.py
Labels: pr:no public docs, release:patch

#4328 Update out of office task to not retry on HttpError
  engine/apps/google/client.py
  engine/apps/google/tasks.py
  engine/apps/google/tests/test_sync_out_of_office_calendar_events_for_user.py
  engine/pyproject.toml
Labels: pr:no public docs, release:ignore

#4329 Avoid retrying to update Slack log message if cant_update_message
  engine/apps/slack/errors.py
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/slack/tests/test_scenario_steps/test_distribute_alerts.py
  engine/apps/slack/tests/test_slack_client.py
Labels: pr:no public docs, release:ignore

#4332 Fix Slack User Group search in Escalation Steps
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/containers/AlertRules/parts/connectors/MSTeamsConnector.tsx
  grafana-plugin/src/containers/AlertRules/parts/connectors/SlackConnector.tsx
  grafana-plugin/src/containers/AlertRules/parts/connectors/TelegramConnector.tsx
  grafana-plugin/src/containers/AttachIncidentForm/AttachIncidentForm.tsx
  grafana-plugin/src/containers/EscalationChainForm/EscalationChainForm.tsx
  grafana-plugin/src/containers/GSelect/GSelect.tsx
  grafana-plugin/src/containers/GrafanaTeamSelect/GrafanaTeamSelect.tsx
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/containers/MaintenanceForm/MaintenanceForm.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookFormFields.tsx
  grafana-plugin/src/containers/ScheduleForm/ScheduleForm.tsx
  grafana-plugin/src/containers/UserSettings/parts/tabs/GoogleCalendar/GoogleCalendar.tsx
  grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/SlackSettings/SlackSettings.tsx
Labels: pr:no public docs, release:patch

#4338 Improve query performance when fetching alert payload for templating
  engine/apps/api/serializers/alert_receive_channel.py
Labels: pr:no public docs, release:ignore

#4327 Fix misleading placeholder when creating a new Alerting Integration Contact Point
  grafana-plugin/src/components/IntegrationContactPoint/IntegrationContactPoint.tsx
Labels: pr:no public docs, release:patch

#4339 Avoid generating response time value metrics for empty integrations
  engine/apps/metrics_exporter/metrics_collectors.py
  engine/apps/metrics_exporter/tests/conftest.py
  engine/apps/metrics_exporter/tests/test_metrics_collectors.py
Labels: pr:no public docs, release:ignore

#4340 Add grafana-oncall-app.user-settings:read permission to notifications receiver role
  grafana-plugin/src/plugin.json
Labels: pr:no public docs, release:patch

#4347 pin drone docker image version
  .drone.yml
Labels: pr:no public docs, release:ignore

#4344 add frontend guidelines
  dev/.gitignore
  dev/frontend_guidelines.md
Labels: pr:no public docs, release:ignore

#4307 Remove schedule events duplicate requests and ignore window.resize
  grafana-plugin/src/containers/RotationForm/RotationForm.tsx
  grafana-plugin/src/containers/Rotations/ScheduleFinal.tsx
  grafana-plugin/src/containers/UserTimezoneSelect/UserTimezoneSelect.tsx
  grafana-plugin/src/pages/schedule/Schedule.tsx
  grafana-plugin/src/pages/schedules/Schedules.tsx
Labels: pr:no public docs, release:patch

#4351 Improve error logging
  grafana-plugin/src/network/network.ts
  grafana-plugin/src/network/oncall-api/http-client.test.ts
  grafana-plugin/src/network/oncall-api/http-client.ts
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/state/rootBaseStore/RootBaseStore.ts
  grafana-plugin/src/utils/faro.ts
  grafana-plugin/src/utils/hooks.tsx
  grafana-plugin/src/utils/string.ts
Labels: pr:no public docs, release:ignore

#4300 Add `service_name` label to insight metrics
  docs/sources/manage/insights-and-metrics/index.md
  engine/apps/metrics_exporter/helpers.py
  engine/apps/metrics_exporter/metrics_collectors.py
  engine/apps/metrics_exporter/tests/conftest.py
  engine/apps/metrics_exporter/tests/test_metrics_collectors.py
  engine/apps/metrics_exporter/tests/test_update_metrics_cache.py
Labels: release:patch

#4377 remove deprecated rbac workaround
  engine/apps/user_management/models/organization.py
  engine/apps/user_management/sync.py
  engine/apps/user_management/tests/test_sync.py
  engine/settings/base.py
Labels: pr:no public docs, release:ignore

#4367 Fix Slack user group warning false positives
  engine/apps/api/tests/test_schedules.py
  engine/apps/api/views/schedule.py
Labels: pr:no public docs, release:patch

#4334 Add details to escalation step description
  docs/sources/configure/escalation-chains-and-routes/index.md
Labels: release:ignore

#4133 Add service_name to Insights filters
  grafana-plugin/src/dashboards/oncall_metrics_dashboard.json
  grafana-plugin/src/pages/insights/scenes/AlertGroupsByIntegration.tsx
  grafana-plugin/src/pages/insights/scenes/AlertGroupsByTeam.tsx
  grafana-plugin/src/pages/insights/scenes/MTTRAverageStat.tsx
  grafana-plugin/src/pages/insights/scenes/MTTRByIntegration.tsx
  grafana-plugin/src/pages/insights/scenes/MTTRByTeam.tsx
  grafana-plugin/src/pages/insights/scenes/MTTRChangedTimeseries.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroups.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroupsNotificationsTable.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroupsNotificationsTimeseries.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroupsTimeseries.tsx
  grafana-plugin/src/pages/insights/variables.ts
Labels: pr:no public docs, release:patch

#4382 show datasource dropdown on cloud
  grafana-plugin/src/dashboards/oncall_metrics_dashboard.json
  grafana-plugin/src/pages/insights/variables.ts
Labels: pr:no public docs, release:ignore

#4384 fix silence_options schema
  engine/apps/api/views/alert_group.py
  grafana-plugin/src/network/oncall-api/autogenerated-api.types.d.ts
Labels: pr:no public docs, release:ignore

#4381 Fix order filtering when executing notify all/group steps from snapshot
  engine/apps/alerts/tasks/notify_all.py
  engine/apps/alerts/tasks/notify_group.py
  engine/apps/alerts/tests/test_notify_all.py
  engine/apps/alerts/tests/test_notify_group.py
Labels: pr:no public docs, release:patch

#4357 Fix missing filtering term type 1 when editing jinja route template
  grafana-plugin/src/pages/integration/Integration.tsx
Labels: pr:no public docs, release:patch

#4389 Drone -> GitHub Actions migration
  .github/actions/install-frontend-dependencies/action.yml
  .github/actions/setup-python/action.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/linting-and-tests.yml
Labels: pr:no public docs, release:ignore

#4386 hide datasource dropdown on cloud
  grafana-plugin/src/pages/insights/variables.ts
Labels: pr:no public docs, release:ignore

#4385 Read useBackendPlugin from jsonData
  Tiltfile
  dev/grafana/provisioning/plugins/grafana-oncall-app-provisioning.yaml
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/state/plugin/plugin.ts
  grafana-plugin/src/types.ts
  grafana-plugin/src/utils/consts.ts
Labels: pr:no public docs, release:ignore

#4375 Allow custom silence period for alert groups + display how much left is for a silenced AG
  grafana-plugin/src/components/RenderConditionally/RenderConditionally.tsx
  grafana-plugin/src/models/alertgroup/alertgroup.ts
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/incidents/parts/IncidentDropdown.tsx
  grafana-plugin/src/pages/incidents/parts/IncidentSilenceModal.tsx
  grafana-plugin/src/pages/incidents/parts/SilenceButtonCascader.tsx
  grafana-plugin/src/pages/incidents/parts/SilenceSelect.tsx
  grafana-plugin/src/styles/utils.styles.ts
Labels: pr:no public docs, release:enhancement

#4391 rename settings/ci-test.py to settings/ci_test.py
  .drone.yml
  .github/workflows/linting-and-tests.yml
  Makefile
  engine/apps/mobile_app/tests/test_alert_rendering.py
  engine/settings/ci_test.py
Labels: pr:no public docs, release:ignore

#4397 remove unnecessary CI step `bash` command
  .github/workflows/expensive-e2e-tests.yml
  .github/workflows/linting-and-tests.yml
  engine/apps/grafana_plugin/tests/test_app_config.py
Labels: pr:no public docs, release:ignore

#4395 Add endpoint to get a single user group
  engine/apps/api/tests/test_user_groups.py
  engine/apps/api/views/user_group.py
Labels: pr:no public docs, release:patch

#4394 Fixed UserGroup selectors not showing the set value
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/containers/ScheduleForm/ScheduleForm.tsx
  grafana-plugin/src/models/user_group/user_group.ts
Labels: pr:no public docs, release:patch

#4396 Setup team uniqueness at DB level
  engine/apps/user_management/migrations/0022_alter_team_unique_together.py
  engine/apps/user_management/models/team.py
  engine/apps/user_management/tests/test_team.py
Labels: pr:no public docs, release:ignore

#4405 Do not retry on SlackAPICantUpdateMessageError errors
  engine/apps/slack/alert_group_slack_service.py
  engine/apps/slack/scenarios/resolution_note.py
Labels: pr:no public docs, release:ignore

#4413 fix bad redirects
  engine/apps/webhooks/models/webhook.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
  engine/apps/webhooks/tests/test_webhook.py
Labels: pr:no public docs, release:ignore

#4416 Fix team uniqueness db migration
  engine/apps/user_management/migrations/0022_alter_team_unique_together.py
Labels: pr:no public docs, release:patch

#4318 Schedule two-weeks and monthly view
  grafana-plugin/.config/webpack/webpack.config.ts
  grafana-plugin/e2e-tests/schedules/scheduleView.test.ts
  grafana-plugin/src/assets/style/vars.css
  grafana-plugin/src/containers/Rotation/Rotation.module.css
  grafana-plugin/src/containers/Rotation/Rotation.tsx
  grafana-plugin/src/containers/Rotation/RotationTutorial.tsx
  grafana-plugin/src/containers/RotationForm/RotationForm.tsx
  grafana-plugin/src/containers/RotationForm/ScheduleOverrideForm.tsx
  grafana-plugin/src/containers/Rotations/Rotations.styles.ts
  grafana-plugin/src/containers/Rotations/Rotations.tsx
  grafana-plugin/src/containers/Rotations/ScheduleFinal.tsx
  grafana-plugin/src/containers/Rotations/ScheduleOverrides.tsx
  grafana-plugin/src/containers/Rotations/SchedulePersonal.tsx
  grafana-plugin/src/containers/ScheduleSlot/ScheduleSlot.helpers.ts
  grafana-plugin/src/containers/ScheduleSlot/ScheduleSlot.tsx
  grafana-plugin/src/containers/TimelineMarks/TimelineMarks.module.scss
  grafana-plugin/src/containers/TimelineMarks/TimelineMarks.tsx
  grafana-plugin/src/containers/UsersTimezones/UsersTimezones.tsx
  grafana-plugin/src/models/schedule/schedule.helpers.test.ts
  grafana-plugin/src/models/schedule/schedule.helpers.ts
  grafana-plugin/src/models/schedule/schedule.ts
  grafana-plugin/src/models/schedule/schedule.types.ts
  grafana-plugin/src/models/timezone/timezone.ts
  grafana-plugin/src/pages/schedule/Schedule.helpers.test.ts
  grafana-plugin/src/pages/schedule/Schedule.helpers.ts
  grafana-plugin/src/pages/schedule/Schedule.styles.ts
  grafana-plugin/src/pages/schedule/Schedule.tsx
  grafana-plugin/src/pages/schedules/Schedules.styles.ts
  grafana-plugin/src/pages/schedules/Schedules.tsx
  grafana-plugin/src/utils/DOM.ts
  grafana-plugin/src/utils/string.ts
  grafana-plugin/webpack.config.ts
Labels: pr:no public docs, involved:Frontend, release:enhancement

#4423 Fix update slack group to not raise if group is not found
  engine/apps/slack/models/slack_usergroup.py
  engine/apps/slack/tests/test_user_group.py
Labels: pr:no public docs, release:patch

#4425 Update escalation auditor to log total and failed escalations info
  engine/apps/alerts/tasks/check_escalation_finished.py
Labels: pr:no public docs, release:ignore

#4426 v1.5.4
  engine/apps/alerts/tasks/check_escalation_finished.py
  engine/apps/slack/models/slack_usergroup.py
  engine/apps/slack/tests/test_user_group.py
  grafana-plugin/.config/webpack/webpack.config.ts
  grafana-plugin/e2e-tests/schedules/scheduleView.test.ts
  grafana-plugin/src/assets/style/vars.css
  grafana-plugin/src/containers/Rotation/Rotation.module.css
  grafana-plugin/src/containers/Rotation/Rotation.tsx
  grafana-plugin/src/containers/Rotation/RotationTutorial.tsx
  grafana-plugin/src/containers/RotationForm/RotationForm.tsx
  grafana-plugin/src/containers/RotationForm/ScheduleOverrideForm.tsx
  grafana-plugin/src/containers/Rotations/Rotations.styles.ts
  grafana-plugin/src/containers/Rotations/Rotations.tsx
  grafana-plugin/src/containers/Rotations/ScheduleFinal.tsx
  grafana-plugin/src/containers/Rotations/ScheduleOverrides.tsx
  grafana-plugin/src/containers/Rotations/SchedulePersonal.tsx
  grafana-plugin/src/containers/ScheduleSlot/ScheduleSlot.helpers.ts
  grafana-plugin/src/containers/ScheduleSlot/ScheduleSlot.tsx
  grafana-plugin/src/containers/TimelineMarks/TimelineMarks.module.scss
  grafana-plugin/src/containers/TimelineMarks/TimelineMarks.tsx
  grafana-plugin/src/containers/UsersTimezones/UsersTimezones.tsx
  grafana-plugin/src/models/schedule/schedule.helpers.test.ts
  grafana-plugin/src/models/schedule/schedule.helpers.ts
  grafana-plugin/src/models/schedule/schedule.ts
  grafana-plugin/src/models/schedule/schedule.types.ts
  grafana-plugin/src/models/timezone/timezone.ts
  grafana-plugin/src/pages/schedule/Schedule.helpers.test.ts
  grafana-plugin/src/pages/schedule/Schedule.helpers.ts
  grafana-plugin/src/pages/schedule/Schedule.styles.ts
  grafana-plugin/src/pages/schedule/Schedule.tsx
  grafana-plugin/src/pages/schedules/Schedules.styles.ts
  grafana-plugin/src/pages/schedules/Schedules.tsx
  grafana-plugin/src/utils/DOM.ts
  grafana-plugin/src/utils/string.ts
  grafana-plugin/webpack.config.ts
Labels: pr:no public docs, release:ignore

#4429 Schedules minor fixes
  grafana-plugin/src/models/schedule/schedule.ts
  grafana-plugin/src/pages/schedule/Schedule.styles.ts
  grafana-plugin/src/pages/schedule/Schedule.tsx
Labels: pr:no public docs, release:ignore

#4422 Allow custom wait delays
  engine/apps/api/serializers/escalation_policy.py
  engine/apps/api/serializers/user_notification_policy.py
  engine/apps/api/tests/test_escalation_policy.py
  engine/apps/api/tests/test_user_notification_policy.py
  engine/apps/api/views/alert_group.py
  engine/apps/api/views/escalation_policy.py
  engine/common/api_helpers/custom_fields.py
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/components/Policy/NotificationPolicy.tsx
  grafana-plugin/src/components/Policy/Policy.consts.ts
  grafana-plugin/src/containers/EscalationChainSteps/EscalationChainSteps.tsx
  grafana-plugin/src/models/alertgroup/alertgroup.ts
  grafana-plugin/src/models/escalation_policy/escalation_policy.ts
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/incidents/parts/IncidentDropdown.tsx
  grafana-plugin/src/pages/incidents/parts/IncidentSilenceModal.tsx
  grafana-plugin/src/pages/incidents/parts/SilenceButtonCascader.tsx
  grafana-plugin/src/pages/incidents/parts/SilenceSelect.tsx
Labels: pr:no public docs, release:enhancement

#4431 Update escalation auditor logs to expose succeeding count
  engine/apps/alerts/tasks/check_escalation_finished.py
Labels: pr:no public docs, release:ignore
