Repository grafana/oncall, pull requests merged in 2024-08, with the labels that each got.

#4764 Enable notification bundling feature by default
  engine/settings/base.py
Labels: pr:no public docs, release:patch

#4757 [Docs] Notification bundle update
  docs/sources/manage/notify/phone-calls-sms/index.md
Labels: type/docs, release:ignore

#4772 Fix retrying email notification task
  engine/apps/email/models.py
  engine/apps/email/tasks.py
  engine/apps/email/tests/test_notify_user.py
Labels: pr:no public docs, release:patch

#4785 Fix e2e test
  grafana-plugin/e2e-tests/alerts/sms.test.ts
Labels: pr:no public docs, release:ignore

#4786 Fix e2e test
  grafana-plugin/e2e-tests/utils/phone.ts
Labels: pr:no public docs, release:ignore

#4787 Fix e2e test
  .github/workflows/expensive-e2e-tests.yml
Labels: pr:no public docs, release:ignore

#4776 adjust to unified slack
  engine/apps/api/views/features.py
  grafana-plugin/src/models/slack/slack.ts
  grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/SlackSettings/SlackSettings.module.css
  grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/SlackSettings/SlackSettings.tsx
  grafana-plugin/src/state/features.ts
Labels: pr:no public docs, release:ignore

#4795 Public API docs: add note on pagination
  docs/sources/oncall-api-reference/alertgroups.md
  docs/sources/oncall-api-reference/alerts.md
  docs/sources/oncall-api-reference/escalation_chains.md
  docs/sources/oncall-api-reference/escalation_policies.md
  docs/sources/oncall-api-reference/integrations.md
  docs/sources/oncall-api-reference/on_call_shifts.md
  docs/sources/oncall-api-reference/outgoing_webhooks.md
  docs/sources/oncall-api-reference/personal_notification_rules.md
  docs/sources/oncall-api-reference/resolution_notes.md
  docs/sources/oncall-api-reference/routes.md
  docs/sources/oncall-api-reference/schedules.md
  docs/sources/oncall-api-reference/shift_swaps.md
  docs/sources/oncall-api-reference/slack_channels.md
  docs/sources/oncall-api-reference/user_groups.md
  docs/sources/oncall-api-reference/users.md
Labels: release:ignore

#4792 add better logging for Google Calendar task
  engine/apps/google/client.py
  engine/apps/google/tasks.py
  engine/apps/google/tests/test_sync_out_of_office_calendar_events_for_user.py
  engine/apps/social_auth/pipeline/google.py
  engine/apps/user_management/models/user.py
  engine/apps/user_management/tests/test_user.py
  engine/pyproject.toml
Labels: pr:no public docs, release:ignore

#4793 Update Slack user group for a schedule - handle `paid_team_only` Slack API error
  docs/sources/manage/notify/slack/index.md
  engine/apps/slack/errors.py
  engine/apps/slack/models/slack_usergroup.py
  engine/apps/slack/tests/test_slack_client.py
  engine/apps/slack/tests/test_user_group.py
Labels: bug, release:patch

#4794 address occasional missing `nextCursor` data key from GCOM GET /instances
  engine/apps/grafana_plugin/helpers/client.py
  engine/apps/grafana_plugin/tests/test_gcom_api_client.py
Labels: pr:no public docs, release:ignore

#4796 `apps.webhooks.tasks.trigger_webhook.execute_webhook` task - don't retry on `requests.exceptions.SSLError`
  engine/apps/webhooks/tasks/trigger_webhook.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
Labels: pr:no public docs, release:patch

#4799 Fix missing `setuptools` dep
  .github/actions/setup-python/action.yml
  engine/Dockerfile
  engine/requirements-dev.txt
  engine/requirements.in
  engine/requirements.txt
Labels: pr:no public docs, release:ignore

#4781 Add settings var to choose application metrics to collect
  engine/apps/metrics_exporter/metrics_collectors.py
  engine/apps/metrics_exporter/tests/test_metrics_collectors.py
  engine/settings/base.py
Labels: pr:no public docs, release:ignore

#4810 chore: return 422 on slack step not found
  engine/apps/slack/views.py
Labels: pr:no public docs, release:ignore

#4805 Reduce a number of requests to db on `alert_receive_channel` internal api endpoint
  engine/apps/api/serializers/alert_receive_channel.py
Labels: pr:no public docs, release:ignore

#4765 Feature: Use ui extension hooks where available
  grafana-plugin/.eslintrc.js
  grafana-plugin/package.json
  grafana-plugin/src/components/ExtensionLinkMenu/ExtensionLinkDropdown.tsx
  grafana-plugin/src/containers/AddResponders/__snapshots__/AddResponders.test.tsx.snap
  grafana-plugin/src/containers/AddResponders/parts/AddRespondersPopup/__snapshots__/AddRespondersPopup.test.tsx.snap
  grafana-plugin/src/containers/AddResponders/parts/NotificationPoliciesSelect/__snapshots__/NotificationPoliciesSelect.test.tsx.snap
  grafana-plugin/src/containers/AddResponders/parts/TeamResponder/__snapshots__/TeamResponder.test.tsx.snap
  grafana-plugin/src/containers/AddResponders/parts/UserResponder/__snapshots__/UserResponder.test.tsx.snap
  grafana-plugin/src/containers/MobileAppConnection/__snapshots__/MobileAppConnection.test.tsx.snap
  grafana-plugin/src/containers/MobileAppConnection/parts/DisconnectButton/__snapshots__/DisconnectButton.test.tsx.snap
  grafana-plugin/src/containers/MobileAppConnection/parts/LinkLoginButton/__snapshots__/LinkLoginButton.test.tsx.snap
  grafana-plugin/src/containers/PluginConfigPage/__snapshots__/PluginConfigPage.test.tsx.snap
  grafana-plugin/src/containers/PluginConfigPage/parts/ConfigurationForm/__snapshots__/ConfigurationForm.test.tsx.snap
  grafana-plugin/src/containers/PluginConfigPage/parts/RemoveCurrentConfigurationButton/__snapshots__/RemoveCurrentConfigurationButton.test.tsx.snap
  grafana-plugin/yarn.lock
Labels: pr:no public docs, pr:dependencies, release:patch

#4779 Bump kind to match ops-devenv version
  dev/kind-config.yaml
Labels: pr:no public docs, release:ignore

#4808 docs: clarify LCR OSS options
  docs/sources/configure/live-call-routing/index.md
Labels: type/docs, release:ignore

#4813 Deleted organization fixes
  engine/apps/google/tasks.py
  engine/apps/google/tests/test_sync_out_of_office_calendar_events_for_user.py
  engine/apps/mobile_app/tasks/going_oncall_notification.py
  engine/apps/mobile_app/tests/tasks/test_going_oncall_notification.py
Labels: pr:no public docs, release:ignore

#4814 Better logging for `send_message_to_fcm_device`
  engine/apps/mobile_app/utils.py
Labels: pr:no public docs, release:ignore

#4681 Address deprecation warnings in tests
  .github/workflows/linting-and-tests.yml
  engine/apps/api/tests/conftest.py
  engine/apps/api/tests/test_alert_group.py
  engine/apps/api/views/alert_receive_channel.py
  engine/apps/api/views/shift_swap.py
  engine/apps/email/tests/test_inbound_email.py
  engine/apps/public_api/serializers/on_call_shifts.py
  engine/apps/schedules/tests/tasks/test_refresh_ical_files.py
  engine/apps/slack/utils.py
  engine/apps/telegram/tests/test_update_handlers.py
  engine/common/api_helpers/filters.py
  engine/common/tests/test_ordered_model.py
  engine/engine/middlewares.py
  engine/requirements.in
  engine/requirements.txt
  engine/settings/base.py
  engine/tox.ini
Labels: pr:no public docs, release:ignore

#4819 Polish unified slack ui
  grafana-plugin/src/assets/style/utils.css
  grafana-plugin/src/components/WithConfirm/WithConfirm.tsx
  grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/SlackSettings/SlackSettings.module.css
  grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/SlackSettings/SlackSettings.tsx
Labels: pr:no public docs, release:ignore

#4822 Fix collecting metrics
  engine/apps/metrics_exporter/metrics_collectors.py
Labels: pr:no public docs, release:ignore

#4818 Fix recaptcha
  grafana-plugin/src/network/network.ts
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/state/rootBaseStore/RootBaseStore.ts
Labels: pr:no public docs, release:ignore

#4802 address Google OAuth2 issues where user didn't grant us the `https://www.googleapis.com/auth/calendar.events.readonly` scope
  engine/apps/api/serializers/user.py
  engine/apps/api/tests/test_auth.py
  engine/apps/api/tests/test_user.py
  engine/apps/api/views/user.py
  engine/apps/google/client.py
  engine/apps/google/constants.py
  engine/apps/google/tasks.py
  engine/apps/google/tests/test_sync_out_of_office_calendar_events_for_user.py
  engine/apps/google/tests/test_utils.py
  engine/apps/google/utils.py
  engine/apps/social_auth/exceptions.py
  engine/apps/social_auth/pipeline/google.py
  engine/apps/user_management/models/user.py
  engine/apps/user_management/tests/test_user.py
  engine/conftest.py
  engine/settings/base.py
  grafana-plugin/src/containers/Alerts/Alerts.tsx
  grafana-plugin/src/containers/UserSettings/UserSettings.module.css
  grafana-plugin/src/containers/UserSettings/UserSettings.tsx
  grafana-plugin/src/models/user/user.ts
  grafana-plugin/src/network/oncall-api/autogenerated-api.types.d.ts
Labels: pr:no public docs, release:patch

#4830 Speed up internal api endpoints
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/models/alert_group_log_record.py
  engine/apps/alerts/models/resolution_note.py
  engine/apps/alerts/tasks/notify_ical_schedule_shift.py
  engine/apps/api/serializers/alert_group.py
  engine/apps/api/serializers/schedule_base.py
  engine/apps/api/serializers/schedule_polymorphic.py
  engine/apps/api/serializers/shift_swap.py
  engine/apps/api/serializers/user.py
  engine/apps/api/tests/test_alert_group.py
  engine/apps/api/tests/test_oncall_shift.py
  engine/apps/api/tests/test_schedules.py
  engine/apps/api/tests/test_shift_swaps.py
  engine/apps/api/tests/test_user.py
  engine/apps/api/views/schedule.py
  engine/apps/base/models/user_notification_policy.py
  engine/apps/base/models/user_notification_policy_log_record.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_on_call_schedule.py
  engine/apps/user_management/models/user.py
  engine/apps/user_management/tests/test_sync.py
Labels: pr:no public docs, release:ignore

#4815 add `POST /escalation` public API endpoint + add public API docs for teams/organization endpoints
  docs/sources/oncall-api-reference/escalation.md
  docs/sources/oncall-api-reference/organizations.md
  docs/sources/oncall-api-reference/teams.md
  engine/apps/api/serializers/direct_paging.py
  engine/apps/api/tests/test_direct_paging.py
  engine/apps/api/urls.py
  engine/apps/api/views/direct_paging.py
  engine/apps/public_api/serializers/__init__.py
  engine/apps/public_api/serializers/escalation.py
  engine/apps/public_api/tests/test_escalation.py
  engine/apps/public_api/urls.py
  engine/apps/public_api/views/__init__.py
  engine/apps/public_api/views/escalation.py
Labels: release:enhancement

#4833 update public API docs subpage ordering
  docs/sources/oncall-api-reference/_index.md
  docs/sources/oncall-api-reference/alertgroups.md
  docs/sources/oncall-api-reference/alerts.md
  docs/sources/oncall-api-reference/escalation.md
  docs/sources/oncall-api-reference/escalation_chains.md
  docs/sources/oncall-api-reference/escalation_policies.md
  docs/sources/oncall-api-reference/integrations.md
  docs/sources/oncall-api-reference/on_call_shifts.md
  docs/sources/oncall-api-reference/organizations.md
  docs/sources/oncall-api-reference/outgoing_webhooks.md
  docs/sources/oncall-api-reference/personal_notification_rules.md
  docs/sources/oncall-api-reference/resolution_notes.md
  docs/sources/oncall-api-reference/routes.md
  docs/sources/oncall-api-reference/schedules.md
  docs/sources/oncall-api-reference/shift_swaps.md
  docs/sources/oncall-api-reference/slack_channels.md
  docs/sources/oncall-api-reference/teams.md
  docs/sources/oncall-api-reference/user_groups.md
  docs/sources/oncall-api-reference/users.md
Labels: release:ignore

#4832 Update alert groups public API filters support
  docs/sources/oncall-api-reference/alertgroups.md
  engine/apps/public_api/serializers/__init__.py
  engine/apps/public_api/serializers/alert_groups.py
  engine/apps/public_api/tests/test_alert_groups.py
  engine/apps/public_api/tests/test_escalation.py
  engine/apps/public_api/urls.py
  engine/apps/public_api/views/__init__.py
  engine/apps/public_api/views/alert_groups.py
  engine/apps/public_api/views/escalation.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
  engine/apps/webhooks/utils.py
  engine/common/api_helpers/filters.py
Labels: release:patch

#4838 Update msteams app refs to be for Grafana IRM
  docs/sources/manage/notify/ms-teams/index.md
  grafana-plugin/src/containers/MSTeams/MSTeamsInstructions.tsx
Labels: release:ignore

#4841 remove engine field
  grafana-plugin/package.json
Labels: pr:no public docs, release:ignore

#4817 Fix pagination behavior when page # exceeds search results
  engine/apps/public_api/tests/test_alert_groups.py
  engine/common/api_helpers/paginators.py
  grafana-plugin/src/pages/integrations/Integrations.tsx
Labels: pr:no public docs, release:patch

#4851 fix `apps.telegram.tasks.send_log_and_actions_message` retrying tasks
  .nvmrc
  engine/apps/telegram/client.py
  engine/apps/telegram/decorators.py
  engine/apps/telegram/models/connectors/channel.py
  engine/apps/telegram/models/connectors/personal.py
  engine/apps/telegram/tasks.py
  engine/apps/telegram/tests/test_personal_connector.py
  engine/apps/telegram/tests/test_tasks.py
  grafana-plugin/.nvmrc
Labels: pr:no public docs, release:patch

#4842 Add missing labels permissions, fix `tilt ci` from ops-devenv, fix expensive e2e tests
  .github/workflows/e2e-tests.yml
  .github/workflows/expensive-e2e-tests.yml
  .github/workflows/linting-and-tests.yml
  Tiltfile
  grafana-plugin/e2e-tests/alerts/directPaging.test.ts
  grafana-plugin/e2e-tests/globalSetup.ts
  grafana-plugin/e2e-tests/insights/insights.test.ts
  grafana-plugin/e2e-tests/labels/createNewLabelKeysAndValues.test.ts
  grafana-plugin/e2e-tests/pluginInitialization/initialization.test.ts
  grafana-plugin/e2e-tests/schedules/scheduleView.test.ts
  grafana-plugin/e2e-tests/users/usersActions.test.ts
  grafana-plugin/e2e-tests/utils/constants.ts
  grafana-plugin/e2e-tests/utils/userSettings.ts
  grafana-plugin/package.json
  grafana-plugin/src/plugin.json
Labels: pr:no public docs, release:ignore

#4686 Move slack log report from message thread to button
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/signals.py
  engine/apps/slack/representatives/alert_group_representative.py
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/slack/scenarios/slack_renderer.py
  engine/apps/slack/tasks.py
  engine/apps/slack/tests/test_scenario_steps/test_distribute_alerts.py
  engine/settings/celery_task_routes.py
Labels: pr:no public docs, release:enhancement

#4858 remove leftofter/deprecated slack log report tasks
  engine/apps/alerts/migrations/0056_remove_alertgroup_slack_log_message_state.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/move_to_migrations_folder_soon_0057_remove_alertgroup_slack_log_message_db.py
  engine/apps/slack/representatives/alert_group_representative.py
  engine/apps/slack/tasks.py
  engine/settings/celery_task_routes.py
Labels: pr:no public docs, release:ignore

#4849 Changed swap shift to take timezone into consideration
  grafana-plugin/src/containers/RotationForm/ShiftSwapForm.tsx
  grafana-plugin/src/pages/schedule/Schedule.tsx
Labels: pr:no public docs, release:patch

#4835 chore: more adjustments to IRM monorepo
  .github/workflows/e2e-tests.yml
  Tiltfile
  grafana-plugin/e2e-tests/utils/navigation.ts
  grafana-plugin/package.json
  grafana-plugin/playwright.config.ts
  grafana-plugin/src/utils/authorization/authorization.ts
  grafana-plugin/src/utils/consts.ts
  grafana-plugin/yarn.lock
Labels: pr:no public docs, release:ignore

#4862 second `AlertGroup.slack_log_message` migration
  engine/apps/alerts/migrations/0057_remove_alertgroup_slack_log_message_db.py
Labels: pr:no public docs, release:ignore

#4864 Add stack_id to Tenant dataclass
  engine/apps/chatops_proxy/client.py
Labels: pr:no public docs, release:ignore

#4868 Fix SSR push notifications for deleted orgs
  engine/apps/mobile_app/tests/tasks/test_new_shift_swap_request.py
  engine/apps/schedules/models/shift_swap_request.py
Labels: pr:no public docs, release:patch

#4867 ci: fix expensive e2e tests
  .github/workflows/e2e-tests.yml
  .github/workflows/expensive-e2e-tests.yml
  Tiltfile
Labels: pr:no public docs, release:ignore

#4871 address outstanding CVEs + remove `plop` from `grafana-plugin/`
  engine/requirements-dev.txt
  engine/requirements.in
  engine/requirements.txt
  grafana-plugin/package.json
  grafana-plugin/plopfile.js
  grafana-plugin/tools/plop/generators/createComponentFiles.js
  grafana-plugin/tools/plop/generators/createContainerFiles.js
  grafana-plugin/tools/plop/generators/createModelFiles.js
  grafana-plugin/tools/plop/helpers/configNeeded.js
  grafana-plugin/tools/plop/prompts/componentPrompts.js
  grafana-plugin/tools/plop/prompts/containerPrompts.js
  grafana-plugin/tools/plop/prompts/modelPrompts.js
  grafana-plugin/tools/plop/templates/Component/ClassComponent.tsx.hbs
  grafana-plugin/tools/plop/templates/Component/Component.module.css.hbs
  grafana-plugin/tools/plop/templates/Component/FunctionalComponent.tsx.hbs
  grafana-plugin/tools/plop/templates/Container/ClassComponent.tsx.hbs
  grafana-plugin/tools/plop/templates/Container/Component.module.css.hbs
  grafana-plugin/tools/plop/templates/Container/FunctionalComponent.tsx.hbs
  grafana-plugin/tools/plop/templates/Model/BaseModel.ts.hbs
  grafana-plugin/tools/plop/templates/Model/BaseModel.types.ts.hbs
  grafana-plugin/yarn.lock
  tools/migrators/requirements.in
  tools/migrators/requirements.txt
Labels: pr:no public docs, release:patch

#4875 fix synk security scan on CI
  .github/workflows/on-pull-requests.yml
  .github/workflows/on-release-published.yml
  .github/workflows/snyk-security-scan.yml
  engine/requirements.in
  engine/requirements.txt
  grafana-plugin/package.json
  grafana-plugin/yarn.lock
Labels: pr:no public docs, release:ignore

#4879 upgrade Docker base image from `python:3.12.3-alpine3.18` to `python:3.12.3-alpine3.20`
  .github/workflows/snyk-security-scan.yml
  engine/Dockerfile
Labels: pr:no public docs, release:patch

#4863 Make root command configurable
  engine/apps/slack/scenarios/paging.py
  engine/apps/slack/slash_command.py
  engine/apps/slack/tests/test_interactive_api_endpoint.py
  engine/apps/slack/tests/test_slash_command.py
  engine/settings/base.py
Labels: pr:no public docs, release:ignore

#4884 chore: use mobx-react
  grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.tsx
Labels: pr:no public docs, release:ignore

#4886 v1.9.9
  engine/apps/slack/scenarios/paging.py
  engine/apps/slack/slash_command.py
  engine/apps/slack/tests/test_interactive_api_endpoint.py
  engine/apps/slack/tests/test_slash_command.py
  engine/settings/base.py
  grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.tsx
Labels: pr:no public docs, release:ignore

#4854 add `start_rotation_from_user_index` field to `/oncall_shifts` internal API response
  engine/apps/api/serializers/on_call_shifts.py
  engine/apps/api/tests/test_oncall_shift.py
  grafana-plugin/src/containers/RotationForm/RotationForm.tsx
  grafana-plugin/src/models/schedule/schedule.types.ts
Labels: pr:no public docs, release:patch

#4883 migration scripts: add missing arg in recursive call
  tools/migrators/lib/network.py
Labels: pr:no public docs, release:patch

#4891 Fix getting metrics list from env
  engine/settings/base.py
Labels: pr:no public docs, release:ignore

#4844 docs: unified slack
  docs/sources/configure/integrations/references/slack/index.md
  docs/sources/manage/notify/slack/index.md
  docs/sources/set-up/get-started/index.md
  engine/apps/slack/scenarios/paging.py
  grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/SlackSettings/SlackSettings.tsx
Labels: type/docs, release:ignore

#4896 fix: show api url in main settings
  grafana-plugin/src/containers/ApiTokenSettings/ApiTokenForm.tsx
  grafana-plugin/src/models/plugin/plugin.ts
  grafana-plugin/src/network/oncall-api/api.types.d.ts
  grafana-plugin/src/pages/settings/tabs/MainSettings/MainSettings.module.css
  grafana-plugin/src/pages/settings/tabs/MainSettings/MainSettings.tsx
  grafana-plugin/src/state/rootBaseStore/RootBaseStore.ts
  grafana-plugin/src/types.ts
Labels: pr:no public docs, release:ignore

#4901 Update sync task to consider never synced orgs
  engine/apps/grafana_plugin/tasks/sync.py
  engine/apps/grafana_plugin/tests/test_sync.py
Labels: pr:no public docs, release:ignore

#4904 Make sure organization token is valid before sync
  engine/apps/user_management/sync.py
  engine/apps/user_management/tests/test_sync.py
Labels: pr:no public docs, release:patch

#4907 Fix flaky test depending on DB ordering
  engine/apps/grafana_plugin/tests/test_sync.py
Labels: pr:no public docs, release:ignore

#4905 Add logging for invalid api_tokens during sync
  engine/apps/grafana_plugin/tasks/sync_v2.py
  engine/apps/grafana_plugin/tests/test_sync_v2.py
Labels: pr:no public docs, release:ignore

#4910 optionally prefix oncall api path with grafana sub url
  grafana-plugin/src/utils/consts.ts
Labels: pr:no public docs, release:ignore

#4912 Fix api_token not being updated
  engine/apps/grafana_plugin/helpers/gcom.py
  engine/apps/grafana_plugin/tests/test_gcom.py
Labels: pr:no public docs, release:ignore

#4918 Add more validation when updating api_token
  engine/apps/grafana_plugin/helpers/gcom.py
  engine/apps/grafana_plugin/tests/test_gcom.py
Labels: pr:no public docs, release:ignore

#4919 Move validate_grafana_token_format to common location, use in sync_v2
  engine/apps/grafana_plugin/helpers/client.py
  engine/apps/grafana_plugin/helpers/gcom.py
  engine/apps/grafana_plugin/tasks/sync_v2.py
  engine/apps/grafana_plugin/tests/test_sync_v2.py
Labels: pr:no public docs, release:ignore

#4920 v1.9.13
  engine/apps/grafana_plugin/helpers/client.py
  engine/apps/grafana_plugin/helpers/gcom.py
  engine/apps/grafana_plugin/tasks/sync_v2.py
  engine/apps/grafana_plugin/tests/test_gcom.py
  engine/apps/grafana_plugin/tests/test_sync.py
  engine/apps/grafana_plugin/tests/test_sync_v2.py
  grafana-plugin/go.mod
  grafana-plugin/src/utils/consts.ts
Labels: pr:no public docs

#4915 chore: more adjustments to irm monorepo
  grafana-plugin/.gitignore
  grafana-plugin/e2e-tests/users/usersActions.test.ts
  grafana-plugin/e2e-tests/utils/integrations.ts
  grafana-plugin/pkg/plugin/permissions.go
  grafana-plugin/pkg/plugin/settings.go
  grafana-plugin/src/network/grafana-api/http-client.ts
  grafana-plugin/src/utils/consts.ts
  grafana-plugin/src/utils/utils.ts
Labels: pr:no public docs, release:ignore

#4916 Handle TimeoutError on sending message to Slack
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/slack/tests/test_scenario_steps/test_distribute_alerts.py
Labels: pr:no public docs, release:ignore

#4911 update oncall tilt setup
  Tiltfile
Labels: pr:no public docs, release:ignore

#4917 update `CODEOWNERS` to account for a few extra golang files under `grafana-plugin`
  .github/CODEOWNERS
Labels: pr:no public docs, release:ignore

#4926 Update org creation to use DB uniqueness constraint
  engine/apps/grafana_plugin/helpers/gcom.py
  engine/apps/grafana_plugin/tests/test_gcom.py
Labels: pr:no public docs, release:ignore

#4928 v1.9.15
  .github/CODEOWNERS
  Tiltfile
  engine/apps/grafana_plugin/helpers/gcom.py
  engine/apps/grafana_plugin/tests/test_gcom.py
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/slack/tests/test_scenario_steps/test_distribute_alerts.py
  grafana-plugin/.bra.toml
  grafana-plugin/package.json
Labels: pr:no public docs

#4930 Fix plugin sync issues
  engine/apps/grafana_plugin/tasks/sync_v2.py
  engine/apps/grafana_plugin/views/sync_v2.py
Labels: pr:no public docs, release:ignore

#4931 Fix incorrect IDs being used to lookup user permissions during sync
  grafana-plugin/pkg/plugin/settings.go
  grafana-plugin/pkg/plugin/users.go
Labels: pr:no public docs, release:ignore

#4932 v1.9.16
  engine/apps/grafana_plugin/tasks/sync_v2.py
  engine/apps/grafana_plugin/views/sync_v2.py
  grafana-plugin/pkg/plugin/settings.go
  grafana-plugin/pkg/plugin/users.go
Labels: pr:no public docs

#4935 changes need for Tilt development in `grafana/irm`
  grafana-plugin/.bra.toml
  grafana-plugin/package.json
Labels: pr:no public docs, release:ignore

#4945 types improvements
  .github/workflows/linting-and-tests.yml
  grafana-plugin/e2e-tests/integrations/integrationsTable.test.ts
  grafana-plugin/package.json
  grafana-plugin/src/components/ExtensionLinkMenu/ExtensionLinkMenu.tsx
  grafana-plugin/src/components/Modal/Modal.tsx
  grafana-plugin/src/components/PageErrorHandlingWrapper/PageErrorHandlingWrapper.tsx
  grafana-plugin/src/components/ScheduleBorderedAvatar/ScheduleBorderedAvatar.tsx
  grafana-plugin/src/components/Text/Text.tsx
  grafana-plugin/src/components/TextEllipsisTooltip/TextEllipsisTooltip.tsx
  grafana-plugin/src/components/WithContextMenu/WithContextMenu.tsx
  grafana-plugin/src/containers/DefaultPageLayout/DefaultPageLayout.tsx
  grafana-plugin/src/containers/IntegrationContainers/IntegrationHeartbeatForm/IntegrationHeartbeatForm.tsx
  grafana-plugin/src/containers/PluginInitializer/PluginInitializer.tsx
  grafana-plugin/yarn.lock
Labels: pr:no public docs, release:ignore

#4865 Make jinja template limits configurable by env var
  engine/settings/base.py
Labels: pr:no public docs, release:patch

#4937 Handle a deleted organization triggering auth
  engine/apps/grafana_plugin/helpers/gcom.py
  engine/apps/grafana_plugin/tests/test_gcom.py
Labels: pr:no public docs, release:ignore

#4939 Sync process and backend plugin tweaks
  engine/apps/grafana_plugin/tasks/sync_v2.py
  engine/apps/grafana_plugin/tests/test_sync_v2.py
  engine/settings/celery_task_routes.py
  grafana-plugin/pkg/plugin/permissions.go
  grafana-plugin/pkg/plugin/settings.go
  grafana-plugin/pkg/plugin/status.go
  grafana-plugin/pkg/plugin/sync.go
  grafana-plugin/pkg/plugin/teams.go
  grafana-plugin/pkg/plugin/users.go
Labels: pr:no public docs, release:ignore

#4947 Check for incident enabled before making mobile app request
  engine/apps/mobile_app/tests/test_mobile_app_gateway.py
  engine/apps/mobile_app/views.py
Labels: pr:no public docs, release:ignore

#4952 fix: fix alert group card layout
  grafana-plugin/src/components/CardButton/CardButton.tsx
Labels: pr:no public docs, release:ignore

#4953 Fixed Schedules modals dragging/initial positioning
  grafana-plugin/src/containers/RotationForm/RotationForm.helpers.ts
  grafana-plugin/src/containers/RotationForm/RotationForm.tsx
  grafana-plugin/src/containers/RotationForm/ShiftSwapForm.tsx
  grafana-plugin/src/containers/Rotations/Rotations.helpers.ts
Labels: pr:no public docs, release:patch

#4950 Improve schedule filters before generating user calendar export
  engine/apps/public_api/views/users.py
Labels: pr:no public docs, release:patch

#4942 e2e to run against 11
  .github/workflows/expensive-e2e-tests.yml
  .github/workflows/linting-and-tests.yml
  grafana-plugin/e2e-tests/labels/createNewLabelKeysAndValues.test.ts
Labels: pr:no public docs, release:ignore

#4951 Compress sync data
  engine/apps/grafana_plugin/serializers/sync_data.py
  engine/apps/grafana_plugin/tests/test_sync_v2.py
  engine/apps/grafana_plugin/views/sync_v2.py
  grafana-plugin/pkg/plugin/debug.go
  grafana-plugin/pkg/plugin/permissions.go
  grafana-plugin/pkg/plugin/resources.go
  grafana-plugin/pkg/plugin/settings.go
  grafana-plugin/pkg/plugin/sync.go
  grafana-plugin/pkg/plugin/teams.go
  grafana-plugin/pkg/plugin/users.go
Labels: pr:no public docs, release:ignore

#4958 v1.9.18
  .github/workflows/expensive-e2e-tests.yml
  .github/workflows/linting-and-tests.yml
  engine/apps/grafana_plugin/serializers/sync_data.py
  engine/apps/grafana_plugin/tests/test_sync_v2.py
  engine/apps/grafana_plugin/views/sync_v2.py
  engine/apps/public_api/views/users.py
  grafana-plugin/e2e-tests/labels/createNewLabelKeysAndValues.test.ts
  grafana-plugin/pkg/plugin/debug.go
  grafana-plugin/pkg/plugin/permissions.go
  grafana-plugin/pkg/plugin/resources.go
  grafana-plugin/pkg/plugin/settings.go
  grafana-plugin/pkg/plugin/sync.go
  grafana-plugin/pkg/plugin/teams.go
  grafana-plugin/pkg/plugin/users.go
  grafana-plugin/src/components/CardButton/CardButton.tsx
  grafana-plugin/src/containers/RotationForm/RotationForm.helpers.ts
  grafana-plugin/src/containers/RotationForm/RotationForm.tsx
  grafana-plugin/src/containers/RotationForm/ShiftSwapForm.tsx
  grafana-plugin/src/containers/Rotations/Rotations.helpers.ts
Labels: pr:no public docs, release:ignore

#4957 Fix direct paging ack
  engine/apps/alerts/tasks/notify_user.py
  engine/apps/alerts/tests/test_notify_user.py
Labels: pr:no public docs, release:patch

#4963 Plugin sync logging improvements
  grafana-plugin/pkg/plugin/sync.go
Labels: pr:no public docs, release:ignore

#4965 v1.9.20
  grafana-plugin/package.json
  grafana-plugin/pkg/plugin/sync.go
  grafana-plugin/playwright.config.ts
Labels: pr:no public docs, release:ignore
