Repository grafana/oncall, pull requests merged in 2024-11, with the labels that each got.

#5219 docs: add supported SMS/voice countries to docs
  docs/sources/manage/notify/phone-calls-sms/index.md
Labels: release:ignore

#5191 feat: convert `organization.general_log_channel_id` to `organization.default_slack_channel`
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/models/channel_filter.py
  engine/apps/alerts/models/resolution_note.py
  engine/apps/alerts/tests/test_alert_receiver_channel.py
  engine/apps/api/serializers/organization.py
  engine/apps/api/tests/test_set_org_default_slack_channel.py
  engine/apps/api/urls.py
  engine/apps/api/views/organization.py
  engine/apps/integrations/tasks.py
  engine/apps/slack/models/slack_team_identity.py
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/slack/tasks.py
  engine/apps/slack/tests/test_reset_slack.py
  engine/apps/slack/tests/test_scenario_steps/test_distribute_alerts.py
  engine/apps/user_management/migrations/0025_organization_default_slack_channel.py
  engine/apps/user_management/migrations/0026_auto_20241017_1919.py
  engine/apps/user_management/models/organization.py
  engine/common/insight_log/chatops_insight_logs.py
  engine/common/insight_log/insight_logs_enabled_check.py
Labels: pr:no public docs, release:patch

#5221 SocialAuthAuthCanceledExceptionMiddleware should only process social …
  engine/apps/social_auth/middlewares.py
Labels: pr:no public docs, release:ignore

#5224 chore: convert two slack channel ID char fields to foreign keys
  engine/apps/alerts/escalation_snapshot/snapshot_classes/escalation_policy_snapshot.py
  engine/apps/alerts/incident_log_builder/incident_log_builder.py
  engine/apps/alerts/migrations/0062_rename_slack_channel_id_channelfilter__slack_channel_id_and_more.py
  engine/apps/alerts/migrations/0063_migrate_channelfilter_slack_channel_id.py
  engine/apps/alerts/migrations/0064_migrate_resolutionnoteslackmessage_slack_channel_id.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/models/channel_filter.py
  engine/apps/alerts/models/invitation.py
  engine/apps/alerts/models/resolution_note.py
  engine/apps/alerts/tasks/declare_incident.py
  engine/apps/alerts/tasks/notify_group.py
  engine/apps/alerts/tests/test_alert_group.py
  engine/apps/alerts/tests/test_incident_log_builder.py
  engine/apps/alerts/tests/test_notify_all.py
  engine/apps/alerts/tests/test_notify_group.py
  engine/apps/api/serializers/channel_filter.py
  engine/apps/api/tests/test_channel_filter.py
  engine/apps/api/tests/test_organization.py
  engine/apps/api/views/channel_filter.py
  engine/apps/public_api/serializers/routes.py
  engine/apps/public_api/tests/test_routes.py
  engine/apps/schedules/ical_utils.py
  engine/apps/slack/models/slack_channel.py
  engine/apps/slack/models/slack_message.py
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/slack/scenarios/resolution_note.py
  engine/apps/slack/scenarios/slack_channel.py
  engine/apps/slack/scenarios/slack_channel_integration.py
  engine/apps/slack/scenarios/slack_renderer.py
  engine/apps/slack/tasks.py
  engine/apps/slack/tests/factories.py
  engine/apps/slack/tests/test_reset_slack.py
  engine/apps/slack/tests/test_scenario_steps/test_resolution_note.py
  engine/apps/slack/tests/test_scenario_steps/test_slack_channel_integration.py
  engine/apps/user_management/models/user.py
  engine/common/api_helpers/custom_fields.py
  engine/common/tests/test_custom_fields.py
Labels: pr:no public docs, release:ignore

#5199 feat: convert `schedule.channel` (char field) to `schedule.slack_channel` (foreign key)
  engine/apps/alerts/tasks/notify_ical_schedule_shift.py
  engine/apps/alerts/tests/test_notify_ical_schedule_shift.py
  engine/apps/api/serializers/organization.py
  engine/apps/api/serializers/schedule_base.py
  engine/apps/api/views/schedule.py
  engine/apps/google/tests/test_sync_out_of_office_calendar_events_for_user.py
  engine/apps/public_api/serializers/schedules_base.py
  engine/apps/public_api/serializers/schedules_calendar.py
  engine/apps/public_api/serializers/schedules_ical.py
  engine/apps/public_api/serializers/schedules_web.py
  engine/apps/public_api/tests/test_schedules.py
  engine/apps/schedules/migrations/0018_oncallschedule_slack_channel.py
  engine/apps/schedules/migrations/0019_auto_20241021_1735.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/models/shift_swap_request.py
  engine/apps/schedules/tasks/notify_about_empty_shifts_in_schedule.py
  engine/apps/schedules/tasks/notify_about_gaps_in_schedule.py
  engine/apps/schedules/tasks/refresh_ical_files.py
  engine/apps/schedules/tests/tasks/shift_swaps/test_notify_when_taken.py
  engine/apps/schedules/tests/tasks/shift_swaps/test_slack_followups.py
  engine/apps/schedules/tests/tasks/shift_swaps/test_slack_messages.py
  engine/apps/schedules/tests/test_notify_about_empty_shifts_in_schedule.py
  engine/apps/schedules/tests/test_notify_about_gaps_in_schedule.py
  engine/apps/slack/models/slack_team_identity.py
  engine/common/api_helpers/custom_fields.py
  engine/common/tests/test_custom_fields.py
Labels: pr:no public docs, release:ignore

#5227 chore: add more slack related tests
  engine/apps/slack/scenarios/slack_channel.py
  engine/apps/slack/tasks.py
  engine/apps/slack/tests/scenario_steps/__init__.py
  engine/apps/slack/tests/scenario_steps/test_alert_group_actions.py
  engine/apps/slack/tests/scenario_steps/test_distribute_alerts.py
  engine/apps/slack/tests/scenario_steps/test_manage_responders.py
  engine/apps/slack/tests/scenario_steps/test_paging.py
  engine/apps/slack/tests/scenario_steps/test_resolution_note.py
  engine/apps/slack/tests/scenario_steps/test_shift_swap_requests.py
  engine/apps/slack/tests/scenario_steps/test_slack_channel.py
  engine/apps/slack/tests/scenario_steps/test_slack_channel_integration.py
  engine/apps/slack/tests/scenario_steps/test_slack_usergroup_steps.py
  engine/apps/slack/tests/test_reset_slack.py
Labels: pr:no public docs, release:ignore

#5228 chore: fix some minor issues with recent `slack_channel` changes
  engine/apps/api/serializers/channel_filter.py
  engine/apps/api/serializers/organization.py
  engine/apps/api/serializers/schedule_base.py
  engine/apps/api/serializers/schedule_calendar.py
  engine/apps/api/serializers/schedule_ical.py
  engine/apps/api/serializers/schedule_polymorphic.py
  engine/apps/api/serializers/schedule_web.py
  engine/apps/api/serializers/slack_channel.py
  engine/apps/api/tests/test_channel_filter.py
  engine/apps/api/tests/test_schedules.py
  engine/apps/api/tests/test_set_org_default_slack_channel.py
  engine/apps/api/views/channel_filter.py
Labels: pr:no public docs, release:ignore

#5226 PD migrator: populate important OnCall notification rules
  tools/migrators/README.md
  tools/migrators/lib/pagerduty/resources/notification_rules.py
  tools/migrators/lib/tests/pagerduty/test_migrate_notification_rules.py
Labels: release:ignore

#5230 feat: add `grafana_irm_enabled` to `GET /organization` endpoint response
  engine/apps/api/serializers/organization.py
  engine/apps/api/tests/test_organization.py
Labels: pr:no public docs, release:ignore

#4988 Always emit insight logs to simplify debugging
  engine/common/insight_log/insight_logs_enabled_check.py
Labels: pr:no public docs, pr:stale, release:ignore

#5233 fix: improve performance of recent `SlackChannel` related migrations
  engine/apps/alerts/migrations/0063_migrate_channelfilter_slack_channel_id.py
  engine/apps/alerts/migrations/0064_migrate_resolutionnoteslackmessage_slack_channel_id.py
  engine/apps/schedules/migrations/0019_auto_20241021_1735.py
  engine/apps/user_management/migrations/0026_auto_20241017_1919.py
Labels: pr:no public docs, release:ignore

#5236 Upgrade django-anymail
  engine/requirements-dev.txt
  engine/requirements.in
  engine/requirements.txt
Labels: pr:no public docs, release:ignore

#5246 Limit slack block text length when rendering alert group timeline
  engine/apps/slack/scenarios/alertgroup_timeline.py
Labels: pr:no public docs, release:patch

#5245 fix: disable accessControlOnCall for Grafana 11.3
  .github/workflows/linting-and-tests.yml
  Tiltfile
  dev/helm-local.yml
  helm/oncall/values.yaml
Labels: pr:no public docs, release:patch

#5255 fix: disable accessControlonCall for Grafana 11.3 in docker compose
  docker-compose-developer.yml
  docker-compose-mysql-rabbitmq.yml
  docker-compose.yml
Labels: pr:no public docs, release:patch

#5258 remove add_stack_slug_to_message_title utility from push notification titles
  engine/apps/mobile_app/demo_push.py
  engine/apps/mobile_app/tasks/going_oncall_notification.py
  engine/apps/mobile_app/tasks/new_alert_group.py
  engine/apps/mobile_app/tasks/new_shift_swap_request.py
  engine/apps/mobile_app/tests/tasks/test_going_oncall_notification.py
  engine/apps/mobile_app/tests/tasks/test_new_shift_swap_request.py
  engine/apps/mobile_app/tests/test_demo_push.py
Labels: pr:no public docs, release:patch

#5263 Inbound email improvements (continued)
  engine/apps/email/inbound.py
  engine/apps/email/tests/test_inbound_email.py
Labels: pr:no public docs, release:ignore

#5264 fix: update `next_shifts_per_user` to only list users with upcoming shifts
  engine/apps/api/tests/test_schedules.py
  engine/apps/api/views/schedule.py
Labels: pr:no public docs, release:ignore

#5254 Enable service account token auth for public API
  engine/apps/alerts/migrations/0065_alertreceivechannel_service_account.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/api/permissions.py
  engine/apps/auth_token/auth.py
  engine/apps/auth_token/grafana/grafana_auth_token.py
  engine/apps/auth_token/migrations/0007_serviceaccounttoken.py
  engine/apps/auth_token/models/__init__.py
  engine/apps/auth_token/models/service_account_token.py
  engine/apps/auth_token/tests/helpers.py
  engine/apps/auth_token/tests/test_grafana_auth.py
  engine/apps/grafana_plugin/helpers/client.py
  engine/apps/public_api/serializers/integrations.py
  engine/apps/public_api/tests/test_alert_groups.py
  engine/apps/public_api/tests/test_integrations.py
  engine/apps/public_api/tests/test_rbac_permissions.py
  engine/apps/public_api/tests/test_resolution_notes.py
  engine/apps/public_api/views/alert_groups.py
  engine/apps/public_api/views/alerts.py
  engine/apps/public_api/views/escalation_chains.py
  engine/apps/public_api/views/escalation_policies.py
  engine/apps/public_api/views/integrations.py
  engine/apps/public_api/views/on_call_shifts.py
  engine/apps/public_api/views/organizations.py
  engine/apps/public_api/views/routes.py
  engine/apps/public_api/views/schedules.py
  engine/apps/public_api/views/shift_swap.py
  engine/apps/public_api/views/slack_channels.py
  engine/apps/public_api/views/teams.py
  engine/apps/public_api/views/user_groups.py
  engine/apps/public_api/views/users.py
  engine/apps/public_api/views/webhooks.py
  engine/apps/user_management/migrations/0027_serviceaccount.py
  engine/apps/user_management/models/__init__.py
  engine/apps/user_management/models/service_account.py
  engine/apps/user_management/tests/factories.py
  engine/conftest.py
  engine/engine/middlewares.py
Labels: pr:no public docs, release:patch

#5240 chore: remove deprecated `AlertGroupPostMortem` model + recently refactored/deprecated slack channel related columns
  engine/apps/alerts/migrations/0001_squashed_initial.py
  engine/apps/alerts/migrations/0066_remove_channelfilter__slack_channel_id_and_more.py
  engine/apps/alerts/models/channel_filter.py
  engine/apps/alerts/models/resolution_note.py
  engine/apps/schedules/migrations/0020_remove_oncallschedule_channel.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/user_management/migrations/0028_remove_organization_general_log_channel_id.py
  engine/apps/user_management/models/organization.py
Labels: pr:no public docs, release:ignore

#5265 feat: Auto retry escalation on failed audit
  engine/apps/alerts/tasks/check_escalation_finished.py
  engine/apps/alerts/tests/test_check_escalation_finished_task.py
  engine/settings/base.py
Labels: pr:no public docs, release:patch

#5269 Fix first heading level
  docs/sources/configure/jinja2-templating/_index.md
Labels: release:ignore

#5270 chore: remove deprecated `slack_channel` and `heartbeat` integration types
  dev/helm-local.yml
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/heartbeat/migrations/0003_remove_integrationheartbeat_actual_check_up_task_id_and_more.py
  engine/apps/heartbeat/models.py
  engine/apps/heartbeat/tasks.py
  engine/apps/heartbeat/tests/factories.py
  engine/apps/integrations/tasks.py
  engine/apps/public_api/tests/test_integrations.py
  engine/apps/slack/alert_group_slack_service.py
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/config_integrations/heartbeat.py
  engine/config_integrations/slack_channel.py
  engine/settings/base.py
  engine/settings/celery_task_routes.py
Labels: pr:no public docs, release:ignore

#5063 security: Update docker redis image to v7.0.15
  .github/workflows/linting-and-tests.yml
  docker-compose-developer.yml
  docker-compose-mysql-rabbitmq.yml
  docker-compose.yml
Labels: release:ignore

#5260 fix: remove notification failure policy log record when prevent posting is set
  engine/apps/alerts/incident_log_builder/incident_log_builder.py
  engine/apps/alerts/tasks/notify_user.py
  engine/apps/alerts/tests/test_notify_user.py
Labels: pr:no public docs, release:patch

#5266 Fix issue with DST starting/ending causing overlaps/gaps
  engine/apps/schedules/ical_events/adapter/amixr_recurring_ical_events_adapter.py
  engine/apps/schedules/tests/test_on_call_schedule.py
Labels: pr:no public docs, release:patch

#5277 chore: patch recent migration files that drop db columns
  .github/workflows/linting-and-tests.yml
  engine/apps/alerts/migrations/0066_remove_channelfilter__slack_channel_id_and_more.py
  engine/apps/alerts/migrations/0067_remove_channelfilter__slack_channel_id_state.py
  engine/apps/alerts/migrations/0068_remove_resolutionnoteslackmessage__slack_channel_id_state.py
  engine/apps/schedules/migrations/0020_remove_oncallschedule_channel_state.py
  engine/apps/user_management/migrations/0028_remove_organization_general_log_channel_id_state.py
Labels: pr:no public docs, release:ignore

#5280 chore: finish drop columns migrations
  engine/apps/alerts/migrations/0069_remove_channelfilter__slack_channel_id_db.py
  engine/apps/alerts/migrations/0070_remove_resolutionnoteslackmessage__slack_channel_id_db.py
  engine/apps/schedules/migrations/0021_remove_oncallschedule_channel_db.py
  engine/apps/user_management/migrations/0029_remove_organization_general_log_channel_id_db.py
Labels: pr:no public docs, release:ignore

#5286 fix: check for service account user on public API resolution note
  engine/apps/public_api/serializers/resolution_notes.py
  engine/apps/public_api/tests/test_resolution_notes.py
Labels: pr:no public docs, release:ignore

#5271 Inbound email better logging
  engine/apps/email/inbound.py
  engine/engine/middlewares.py
Labels: pr:no public docs, release:ignore

#5261 Remove AM status from title
  engine/config_integrations/alertmanager.py
  engine/config_integrations/grafana_alerting.py
Labels: pr:no public docs, release:patch

#5282 Listen for alert group actions during whole notification call
  engine/apps/twilioapp/gather.py
  engine/apps/twilioapp/phone_provider.py
  engine/apps/twilioapp/tests/test_phone_calls.py
  engine/apps/twilioapp/tests/test_twilio_provider.py
Labels: pr:no public docs, release:patch

#5294 Inbound email improvements (continued)
  engine/apps/email/tests/test_inbound_email.py
  engine/apps/email/validate_amazon_sns_message.py
Labels: pr:no public docs, release:ignore

#5297 fix: patch data migration scripts for non-MySQL databases
  engine/apps/alerts/migrations/0063_migrate_channelfilter_slack_channel_id.py
  engine/apps/alerts/migrations/0064_migrate_resolutionnoteslackmessage_slack_channel_id.py
  engine/apps/schedules/migrations/0019_auto_20241021_1735.py
  engine/apps/user_management/migrations/0026_auto_20241017_1919.py
Labels: pr:no public docs, release:patch

#5303 feat: add timestamp_to_datetime jinja template filter
  docs/sources/configure/jinja2-templating/advanced-templates/index.md
  engine/common/jinja_templater/filters.py
  engine/common/jinja_templater/jinja_template_env.py
  engine/common/tests/test_apply_jinja_template.py
Labels: release:patch

#5262 Merge alert group static labels to integration labels
  docs/sources/configure/integrations/labels/index.md
  engine/apps/alerts/migrations/0071_migrate_labels.py
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/labels/0007_remove_alertreceivechannelassociatedlabel_inheritable_db.py
  engine/apps/labels/alert_group_labels.py
  engine/apps/labels/migrations/0006_remove_alertreceivechannelassociatedlabel_inheritable_state.py
  engine/apps/labels/models.py
Labels: release:patch

#5308 fix: address django migration failing on SQLite
  .github/workflows/linting-and-tests.yml
  engine/apps/alerts/migrations/0070_remove_resolutionnoteslackmessage__slack_channel_id_db.py
Labels: pr:no public docs, release:patch

#5305 feat: add service account checks in plugin auth
  engine/apps/auth_token/auth.py
  engine/apps/auth_token/grafana/grafana_auth_token.py
  engine/apps/auth_token/tests/helpers.py
  engine/apps/auth_token/tests/test_grafana_auth.py
  engine/apps/auth_token/tests/test_plugin_auth.py
  engine/apps/grafana_plugin/helpers/client.py
  engine/apps/public_api/tests/test_alert_groups.py
  engine/apps/public_api/tests/test_integrations.py
  engine/apps/public_api/tests/test_resolution_notes.py
Labels: pr:no public docs, release:patch

#5311 fix: mobile app template preview use dynamic value
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/mobile_app/alert_rendering.py
Labels: pr:no public docs, release:patch

#5307 chore: random slack code cleanup
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/tasks/compare_escalations.py
  engine/apps/alerts/tasks/escalate_alert_group.py
  engine/apps/alerts/tasks/notify_user.py
  engine/apps/alerts/tasks/unsilence.py
  engine/apps/alerts/tests/test_alert_group.py
  engine/apps/alerts/tests/test_maintenance.py
  engine/apps/alerts/tests/test_notify_user.py
  engine/apps/alerts/tests/test_silence.py
  engine/apps/api/tests/conftest.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/slack/alert_group_slack_service.py
  engine/apps/slack/models/slack_message.py
  engine/apps/slack/models/slack_user_identity.py
  engine/apps/slack/representatives/alert_group_representative.py
  engine/apps/slack/scenarios/alertgroup_appearance.py
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/slack/scenarios/notification_delivery.py
  engine/apps/slack/scenarios/resolution_note.py
  engine/apps/slack/scenarios/shift_swap_requests.py
  engine/apps/slack/tasks.py
  engine/apps/slack/tests/scenario_steps/test_distribute_alerts.py
  engine/apps/slack/tests/scenario_steps/test_resolution_note.py
  engine/apps/slack/tests/scenario_steps/test_slack_channel_integration.py
  engine/conftest.py
  engine/requirements.in
  engine/requirements.txt
Labels: pr:no public docs, release:patch
