Repository grafana/oncall, pull requests merged in 2024-03, with the labels that each got.

#3985 Enable / disable SNOW webhook
  grafana-plugin/src/models/alert_receive_channel_webhooks/alert_receive_channel_webhooks.ts
  grafana-plugin/src/network/oncall-api/types-generator/custom-schemas.ts
  grafana-plugin/src/pages/integration/OutgoingTab/ConnectIntegrationModal.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingTab.hooks.ts
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingTab.styles.ts
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingTab.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingWebhookDetailsDrawerTabs.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingWebhooksTable.tsx
Labels: pr:no changelog, pr:no public docs

#3982 Add trace_id to log lines
  engine/engine/celery.py
  engine/engine/middlewares.py
  engine/engine/wsgi.py
  engine/manage.py
  engine/requirements-dev.txt
  engine/requirements.in
  engine/requirements.txt
  engine/settings/base.py
Labels: pr:no changelog, pr:no public docs

#3988 fe-o11-team/upgrade-faro-and-adjust-config
  grafana-plugin/package.json
  grafana-plugin/src/utils/faro.ts
  grafana-plugin/yarn.lock
Labels: pr:no changelog, pr:no public docs, pr:dependencies, javascript

#3996 Remove add-to-project job
  .github/workflows/on-issue-creation.yml
Labels: pr:no changelog, pr:no public docs

#3997 Use uwsgi instrumentation and log request headers
  engine/engine/middlewares.py
  engine/engine/wsgi.py
  engine/requirements.in
  engine/requirements.txt
  engine/settings/base.py
Labels: pr:no changelog, pr:no public docs

#3990 Support nullable shift.by_day
  grafana-plugin/src/containers/RotationForm/RotationForm.tsx
  grafana-plugin/src/models/schedule/schedule.types.ts
  grafana-plugin/src/pages/schedule/Schedule.helpers.ts
Labels: pr:no changelog, pr:no public docs

#3998 update changelog
  CHANGELOG.md
Labels: pr:no public docs

#3979 Refactored Integration Form to use react-hook-form + ServiceNow changes
  CHANGELOG.md
  grafana-plugin/package.json
  grafana-plugin/src/components/HowTheIntegrationWorks/HowTheIntegrationWorks.tsx
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.helpers.ts
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.module.scss
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.styles.ts
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/containers/IntegrationForm/IntegrationFormContainer.module.scss
  grafana-plugin/src/containers/IntegrationForm/IntegrationFormContainer.tsx
  grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.tsx
  grafana-plugin/src/pages/integration/Integration.helper.ts
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/pages/integrations/Integrations.tsx
  grafana-plugin/src/utils/consts.ts
  grafana-plugin/yarn.lock
Labels: pr:no public docs

#3986 Check if base element exists when dragging the rotation form
  CHANGELOG.md
  grafana-plugin/src/containers/RotationForm/RotationForm.tsx
Labels: pr:no public docs

#3991 Use autogenerated types for alert groups
  grafana-plugin/package.json
  grafana-plugin/src/components/ExtensionLinkMenu/ExtensionLinkDropdown.tsx
  grafana-plugin/src/components/ManualAlertGroup/ManualAlertGroup.tsx
  grafana-plugin/src/containers/AddResponders/AddResponders.tsx
  grafana-plugin/src/containers/AddResponders/parts/AddRespondersPopup/AddRespondersPopup.tsx
  grafana-plugin/src/containers/AttachIncidentForm/AttachIncidentForm.tsx
  grafana-plugin/src/containers/ChannelFilterForm/ChannelFilterForm.module.css
  grafana-plugin/src/containers/ChannelFilterForm/ChannelFilterForm.tsx
  grafana-plugin/src/containers/ColumnsSelectorWrapper/ColumnsModal.tsx
  grafana-plugin/src/containers/ColumnsSelectorWrapper/ColumnsSelectorWrapper.tsx
  grafana-plugin/src/containers/IncidentMatcher/IncidentMatcher.module.css
  grafana-plugin/src/containers/IncidentMatcher/IncidentMatcher.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
  grafana-plugin/src/containers/Labels/LabelsFilter.tsx
  grafana-plugin/src/containers/TemplatePreview/TemplatePreview.tsx
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/models/alertgroup/alertgroup.helpers.ts
  grafana-plugin/src/models/alertgroup/alertgroup.ts
  grafana-plugin/src/models/alertgroup/alertgroup.types.ts
  grafana-plugin/src/models/direct_paging/direct_paging.ts
  grafana-plugin/src/models/resolution_note/resolution_note.ts
  grafana-plugin/src/models/resolution_note/resolution_note.types.ts
  grafana-plugin/src/network/oncall-api/autogenerated-api.types.d.ts
  grafana-plugin/src/network/oncall-api/types-generator/custom-schemas.ts
  grafana-plugin/src/network/oncall-api/types-generator/generate-types.ts
  grafana-plugin/src/pages/incident/Incident.helpers.tsx
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/incidents/parts/IncidentDropdown.tsx
Labels: pr:no changelog, pr:no public docs

#4001 Update CHANGELOG.md
  CHANGELOG.md
Labels: pr:no public docs

#3976 Add scheduled task to start cleanup tasks
  CHANGELOG.md
  engine/apps/grafana_plugin/tasks/sync.py
  engine/apps/grafana_plugin/tests/test_gcom_api_client.py
  engine/apps/user_management/sync.py
  engine/apps/user_management/tests/test_sync.py
  engine/settings/base.py
  engine/settings/celery_task_routes.py
Labels: pr:no public docs

#4007 Fix slack declare incident label
  engine/apps/alerts/incident_appearance/renderers/slack_renderer.py
Labels: pr:no changelog, pr:no public docs

#4008 Instrument requests lib
  engine/engine/wsgi.py
  engine/manage.py
  engine/requirements.in
  engine/requirements.txt
Labels: pr:no changelog, pr:no public docs

#4009 Fix notification settings dropdowns
  CHANGELOG.md
  grafana-plugin/src/containers/GSelect/GSelect.tsx
  grafana-plugin/src/containers/ScheduleForm/ScheduleForm.tsx
Labels: pr:no public docs

#4012 Update readme
  README.md
Labels: pr:no changelog, pr:no public docs, release:ignore

#4011 Allow setting integration_filter to null in webhooks internal API
  CHANGELOG.md
  engine/apps/api/serializers/webhook.py
  engine/apps/api/tests/test_webhooks.py
Labels: pr:no public docs

#3999 Configure knip and remove dead code
  grafana-plugin/knip.json
  grafana-plugin/package.json
  grafana-plugin/src/__mocks__/@grafana/runtime.ts
  grafana-plugin/src/components/AlertTemplates/AlertTemplatesForm.helper.tsx
  grafana-plugin/src/components/LabelTag/LabelTag.tsx
  grafana-plugin/src/components/ScheduleWarning/ScheduleWarning.tsx
  grafana-plugin/src/components/SchedulesFilters/SchedulesFilters.tsx
  grafana-plugin/src/components/SchedulesFilters/SchedulesFilters.types.ts
  grafana-plugin/src/components/SearchInput/SearchInput.module.scss
  grafana-plugin/src/components/SearchInput/SearchInput.tsx
  grafana-plugin/src/containers/AlertReceiveChannelCard/AlertReceiveChannelCard.module.scss
  grafana-plugin/src/containers/AlertReceiveChannelCard/AlertReceiveChannelCard.tsx
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.config.tsx
  grafana-plugin/src/containers/RotationForm/parts/WeekdayTimePicker.tsx
  grafana-plugin/src/containers/SlackInstructions/SlackInstructions.module.css
  grafana-plugin/src/containers/SlackInstructions/SlackInstructions.tsx
  grafana-plugin/src/containers/TemplatesAlertGroupsList/WebhooksDefaultAlertGroup.ts
  grafana-plugin/src/containers/UserSummary/UserSummary.tsx
  grafana-plugin/src/pages/routes.tsx
  grafana-plugin/yarn.lock
Labels: pr:no changelog, pr:no public docs

#4020 update PR template + change assigned label on issue creation
  .github/pull_request_template.md
  .github/workflows/on-issue-creation.yml
Labels: pr:no changelog, pr:no public docs

#4004 Automate release note generation
  .github/CODEOWNERS
  .github/pull_request_template.md
  .github/release.yml
  .github/workflows/verify-changelog-updated.yml
  .github/workflows/verify-release-label-added.yml
  CHANGELOG.md
Labels: pr:no public docs

#3992 Add `silenced_at` field to alert group public API
  docs/sources/oncall-api-reference/alertgroups.md
  engine/apps/public_api/serializers/incidents.py
  engine/apps/public_api/tests/test_alert_groups.py
Labels: release:patch

#3747 OnCall Docs - Add description of Slack timeouts [support request]
  docs/sources/manage/notify/slack/index.md
Labels: type/docs, release:ignore

#4026 allow `@grafana/grafana-oncall` GitHub team users to approve changes to `/docs`
  .github/CODEOWNERS
Labels: release:ignore

#4021 remove `GOVERNANCE.md` and `MAINTAINERS.md`
  .github/pull_request_template.md
  GOVERNANCE.md
  MAINTAINERS.md
Labels: release:ignore

#4030 Backend support for "connected" integrations
  engine/apps/alerts/migrations/0046_alertreceivechannelconnection.py
  engine/apps/alerts/models/__init__.py
  engine/apps/alerts/models/alert_receive_channel_connection.py
  engine/apps/alerts/tests/factories.py
  engine/apps/api/serializers/alert_receive_channel_connection.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/views/alert_receive_channel.py
  engine/conftest.py
Labels: pr:no public docs, release:ignore

#4032 Add `id_ne` filter for integrations (internal API)
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/views/alert_receive_channel.py
Labels: pr:no public docs, release:ignore

#4034 Move fcm_relay task from webhook to critical queue
  engine/settings/celery_task_routes.py
Labels: pr:no public docs, release:patch

#4027 Add support for integration additional settings via custom serializer
  engine/apps/alerts/integration_options_mixin.py
  engine/apps/alerts/migrations/0047_alertreceivechannel_additional_settings.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/tests/test_alert_receive_channel.py
Labels: pr:no public docs, release:patch

#4035 v1.3.111
  .github/CODEOWNERS
  .github/pull_request_template.md
  GOVERNANCE.md
  MAINTAINERS.md
  engine/apps/alerts/integration_options_mixin.py
  engine/apps/alerts/migrations/0046_alertreceivechannelconnection.py
  engine/apps/alerts/migrations/0047_alertreceivechannel_additional_settings.py
  engine/apps/alerts/models/__init__.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/models/alert_receive_channel_connection.py
  engine/apps/alerts/tests/factories.py
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/serializers/alert_receive_channel_connection.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/views/alert_receive_channel.py
  engine/conftest.py
  engine/settings/celery_task_routes.py
  grafana-plugin/e2e-tests/alerts/onCallSchedule.test.ts
  grafana-plugin/e2e-tests/insights/insights.test.ts
  grafana-plugin/e2e-tests/schedules/addOverride.test.ts
  grafana-plugin/e2e-tests/schedules/quality.test.ts
  grafana-plugin/e2e-tests/schedules/scheduleDetails.test.ts
  grafana-plugin/e2e-tests/schedules/schedulesList.test.ts
  grafana-plugin/e2e-tests/schedules/timezones.test.ts
  grafana-plugin/e2e-tests/utils/schedule.ts
  grafana-plugin/src/containers/UsersTimezones/ScheduleUserDetails/ScheduleUserDetails.tsx
  grafana-plugin/src/models/loader/action-keys.ts
  grafana-plugin/src/models/user/user.ts
Labels: pr:no public docs

#4038 Fix passing additional headers to custom fetch
  grafana-plugin/src/network/oncall-api/http-client.test.ts
  grafana-plugin/src/network/oncall-api/http-client.ts
Labels: pr:no public docs, release:patch

#4022 fe-o11y-team/chore(deps): upgrade faro to v1.4.2
  grafana-plugin/package.json
  grafana-plugin/yarn.lock
Labels: pr:no public docs, pr:dependencies, javascript, release:ignore

#4042 Add additional settings serializer details for OpenAPI schema generation
  engine/apps/api/serializers/alert_receive_channel.py
Labels: pr:no public docs, release:ignore

#4043 v1.3.112
  engine/apps/api/serializers/alert_receive_channel.py
  grafana-plugin/package.json
  grafana-plugin/src/network/oncall-api/http-client.test.ts
  grafana-plugin/src/network/oncall-api/http-client.ts
  grafana-plugin/yarn.lock
Labels: pr:no public docs

#4041 Update CHANGELOG.md
  CHANGELOG.md
Labels: release:ignore

#4039 Connect dependent alert receive channels to source channel
  grafana-plugin/src/components/Button/Button.tsx
  grafana-plugin/src/models/alert_receive_channel_connected_channels/alert_receive_channel_connected_channels.ts
  grafana-plugin/src/models/alert_receive_channel_webhooks/alert_receive_channel_webhooks.ts
  grafana-plugin/src/models/loader/action-keys.ts
  grafana-plugin/src/network/oncall-api/autogenerated-api.types.d.ts
  grafana-plugin/src/pages/integration/OutgoingTab/ConnectIntegrationModal.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/ConnectedIntegrationsTable.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/NewOutgoingWebhookDrawerContent.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/OtherIntegrations.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingTab.styles.ts
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingTab.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingWebhooksTable.tsx
  grafana-plugin/src/state/rootBaseStore/RootBaseStore.ts
Labels: pr:no public docs, release:ignore

#4045 Fix frontend unit tests
  .github/workflows/linting-and-tests.yml
  grafana-plugin/.gitignore
  grafana-plugin/jest.config.js
  grafana-plugin/jest.setup.ts
  grafana-plugin/package.json
  grafana-plugin/src/components/Collapse/Collapse.test.tsx
  grafana-plugin/src/containers/AddResponders/parts/AddRespondersPopup/AddRespondersPopup.test.tsx
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.test.tsx
  grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.test.tsx
  grafana-plugin/src/containers/PluginConfigPage/__snapshots__/PluginConfigPage.test.tsx.snap
  grafana-plugin/src/models/user/user.test.ts
  grafana-plugin/src/network/oncall-api/http-client.test.ts
  grafana-plugin/src/state/rootBaseStore/RootBaseStore.test.ts
  grafana-plugin/src/utils/faro.test.tsx
  grafana-plugin/yarn.lock
Labels: pr:no public docs, release:ignore

#4040 Show new indicator for which slack channel is default
  grafana-plugin/src/containers/AlertRules/parts/connectors/SlackConnector.tsx
  grafana-plugin/src/containers/GSelect/GSelect.tsx
Labels: pr:no public docs, release:patch

#4051 Fix ical link revoke
  grafana-plugin/e2e-tests/users/userProfile.test.ts
  grafana-plugin/e2e-tests/utils/navigation.ts
  grafana-plugin/src/containers/UserSettings/parts/connectors/ICalConnector.tsx
  grafana-plugin/src/models/user/user.helpers.tsx
Labels: pr:no public docs, release:patch

#4048 Delete connection on channel delete
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/api/tests/test_alert_receive_channel.py
Labels: pr:no public docs, release:ignore

#4047 Pass additional_settings from the integration form to backend
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.helpers.ts
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/network/oncall-api/autogenerated-api.types.d.ts
Labels: pr:no public docs, release:ignore

#4052 Create default webhooks on integration creation
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/views/alert_receive_channel.py
Labels: pr:no public docs, release:ignore

#4057 Fix user profile test
  grafana-plugin/e2e-tests/users/userProfile.test.ts
Labels: pr:no public docs, release:ignore

#4046 ServiceNow configuration
  grafana-plugin/src/components/CheatSheet/CheatSheet.module.scss
  grafana-plugin/src/components/IntegrationCollapsibleTreeView/IntegrationCollapsibleTreeView.module.scss
  grafana-plugin/src/components/IntegrationHowToConnect/IntegrationHowToConnect.tsx
  grafana-plugin/src/components/IntegrationInputField/IntegrationInputField.tsx
  grafana-plugin/src/components/Integrations/IntegrationBlock.module.scss
  grafana-plugin/src/components/Integrations/IntegrationBlockItem.module.scss
  grafana-plugin/src/components/Integrations/IntegrationTemplateBlock.module.scss
  grafana-plugin/src/components/ScheduleQuality/ScheduleQuality.module.scss
  grafana-plugin/src/components/ScheduleQualityDetails/ScheduleQualityDetails.module.scss
  grafana-plugin/src/components/ScheduleQualityDetails/ScheduleQualityProgressBar.module.scss
  grafana-plugin/src/components/TooltipBadge/TooltipBadge.module.scss
  grafana-plugin/src/containers/AddResponders/AddResponders.module.scss
  grafana-plugin/src/containers/AddResponders/parts/AddRespondersPopup/AddRespondersPopup.module.scss
  grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.module.scss
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.styles.ts
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.module.scss
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.module.scss
  grafana-plugin/src/containers/ServiceNowConfigDrawer/ServiceNowConfigDrawer.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.types.ts
  grafana-plugin/src/models/loader/action-keys.ts
  grafana-plugin/src/pages/incident/Incident.module.scss
  grafana-plugin/src/pages/incidents/Incidents.module.scss
  grafana-plugin/src/pages/incidents/parts/IncidentDropdown.module.scss
  grafana-plugin/src/pages/integration/Integration.module.scss
  grafana-plugin/src/pages/integration/Integration.tsx
Labels: pr:no public docs, release:ignore

#4060 Allow description to be optional
  grafana-plugin/src/components/IntegrationHowToConnect/IntegrationHowToConnect.tsx
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
Labels: pr:no public docs, release:ignore

#4055 chore: fix some comments
  docs/sources/configure/outgoing-webhooks/index.md
  engine/apps/social_auth/backends.py
  engine/common/custom_celery_tasks/dedicated_queue_retry_task.py
  engine/common/utils.py
Labels: release:ignore

#4053 Update universal integrations to reject requests without payload
  engine/apps/integrations/tests/test_views.py
  engine/apps/integrations/views.py
Labels: pr:no public docs, release:ignore

#4059 update types
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/containers/ServiceNowConfigDrawer/ServiceNowConfigDrawer.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/network/oncall-api/autogenerated-api.types.d.ts
Labels: pr:no public docs, release:ignore

#4068 Fix web alert templater with many links
  engine/apps/alerts/incident_appearance/templaters/web_templater.py
  engine/apps/alerts/tests/test_alert_group_renderer.py
Labels: pr:no public docs, release:patch

#4050 Add test_connection endpoint for alert receive channel backsync setup
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/views/alert_receive_channel.py
  engine/common/exceptions/__init__.py
  engine/common/exceptions/exceptions.py
Labels: pr:no public docs, release:patch

#4069 remove duplicate `plugin.json` routes
  grafana-plugin/src/plugin.json
Labels: pr:no public docs, release:ignore

#4056 Integration backsync token
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/views/alert_receive_channel.py
  engine/apps/auth_token/auth.py
  engine/apps/auth_token/migrations/0005_integrationauthtoken.py
  engine/apps/auth_token/models/__init__.py
  engine/apps/auth_token/models/integration_backsync_auth_token.py
  engine/apps/auth_token/tests/test_integration_backsync_auth_token.py
  engine/conftest.py
Labels: pr:no public docs, release:ignore

#4061 Add integration status_options endpoint listing backsync possible statuses
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/views/alert_receive_channel.py
  engine/common/exceptions/__init__.py
  engine/common/exceptions/exceptions.py
Labels: pr:no public docs, release:patch

#4077 Update alert receive channel OpenAPI schemas
  engine/apps/api/views/alert_receive_channel.py
Labels: pr:no public docs, release:ignore

#4084 Disable integration backsync conditionally
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.helpers.ts
  grafana-plugin/src/models/alert_receive_channel_connected_channels/alert_receive_channel_connected_channels.ts
  grafana-plugin/src/network/oncall-api/autogenerated-api.types.d.ts
  grafana-plugin/src/pages/integration/Integration.hooks.ts
  grafana-plugin/src/pages/integration/OutgoingTab/ConnectIntegrationModal.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/ConnectedIntegrationsTable.tsx
Labels: pr:no public docs, release:ignore

#4076 SNOW external ID
  .pre-commit-config.yaml
  engine/apps/alerts/migrations/0048_alertgroupexternalid.py
  engine/apps/alerts/models/__init__.py
  engine/apps/alerts/models/alert_receive_channel_connection.py
  engine/apps/alerts/signals.py
  engine/apps/alerts/tests/test_alert_group.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/views/alert_receive_channel.py
  engine/apps/webhooks/models/webhook.py
  engine/apps/webhooks/tasks/trigger_webhook.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
  engine/apps/webhooks/utils.py
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingWebhookFormFields.tsx
Labels: pr:no public docs, release:ignore

#4082 Integtation backsync endpoint
  engine/apps/integrations/tests/test_integration_backsync.py
  engine/apps/integrations/throttlers/__init__.py
  engine/apps/integrations/throttlers/integration_backsync_throttler.py
  engine/apps/integrations/urls.py
  engine/apps/integrations/views.py
Labels: pr:no public docs, release:ignore

#4090 Tweak connected integration filter
  engine/apps/webhooks/models/webhook.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
  engine/apps/webhooks/utils.py
Labels: pr:no public docs, release:ignore

#4091 Enable test_connection for existing integrations reusing data
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/views/alert_receive_channel.py
Labels: pr:no public docs, release:ignore

#3842 Use Tilt CI to run e2e tests on Github workflows
  .github/helm-values.yml
  .github/kind.yml
  .github/workflows/e2e-tests.yml
  Tiltfile
  dev/helm-local.yml
  grafana-plugin/e2e-tests/insights/insights.test.ts
  grafana-plugin/e2e-tests/utils/navigation.ts
  grafana-plugin/package.json
  grafana-plugin/playwright.config.ts
Labels: pr:no public docs, release:patch

#4100 Add permalinks field to the alert groups list view in internal api
  engine/apps/api/serializers/alert_group.py
Labels: pr:no public docs, release:patch

#4103 Fix schedule gaps when DST happens between rotation start and end date
  grafana-plugin/e2e-tests/schedules/scheduleDetails.test.ts
  grafana-plugin/e2e-tests/schedules/timezones.test.ts
  grafana-plugin/src/containers/Rotation/Rotation.tsx
  grafana-plugin/src/containers/RotationForm/RotationForm.helpers.ts
  grafana-plugin/src/containers/RotationForm/RotationForm.tsx
  grafana-plugin/src/containers/RotationForm/parts/DateTimePicker.tsx
  grafana-plugin/src/containers/ScheduleSlot/ScheduleSlot.module.css
  grafana-plugin/src/containers/ScheduleSlot/ScheduleSlot.tsx
  grafana-plugin/src/containers/UserTimezoneSelect/UserTimezoneSelect.tsx
  grafana-plugin/src/containers/UsersTimezones/ScheduleUserDetails/ScheduleUserDetails.tsx
  grafana-plugin/src/containers/UsersTimezones/UsersTimezones.helpers.ts
  grafana-plugin/src/models/timezone/timezone.ts
Labels: pr:no public docs, release:patch

#4109 fix status_options schema
  engine/apps/api/views/alert_receive_channel.py
Labels: pr:no public docs, release:ignore

#4080 Fix alert group table default filter being ignored, add 1 week window as default time range
  grafana-plugin/e2e-tests/utils/alertGroup.ts
  grafana-plugin/src/containers/RemoteFilters/RemoteFilters.helpers.ts
  grafana-plugin/src/containers/RemoteFilters/RemoteFilters.tsx
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/utils/utils.ts
Labels: pr:no public docs, release:patch

#4106 Fix unlink Slack and Telegram API calls
  grafana-plugin/src/containers/UserSettings/parts/connectors/Connectors.tsx
  grafana-plugin/src/containers/UserSettings/parts/connectors/MobileAppConnector.tsx
  grafana-plugin/src/containers/UserSettings/parts/connectors/PhoneConnector.tsx
  grafana-plugin/src/containers/UserSettings/parts/connectors/SlackConnector.tsx
  grafana-plugin/src/containers/UserSettings/parts/connectors/TelegramConnector.tsx
  grafana-plugin/src/models/user/user.ts
Labels: pr:no public docs, release:patch

#4078 Show servicenow indicator for AGs + complete your servicenow config
  grafana-plugin/src/components/IntegrationInputField/IntegrationInputField.module.scss
  grafana-plugin/src/components/IntegrationInputField/IntegrationInputField.tsx
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.styles.ts
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/containers/ServiceNowConfigDrawer/CompleteServiceNowConfigModal.tsx
  grafana-plugin/src/containers/ServiceNowConfigDrawer/ServiceNow.styles.tsx
  grafana-plugin/src/containers/ServiceNowConfigDrawer/ServiceNowAuthSection.tsx
  grafana-plugin/src/containers/ServiceNowConfigDrawer/ServiceNowConfig.helpers.ts
  grafana-plugin/src/containers/ServiceNowConfigDrawer/ServiceNowConfigDrawer.tsx
  grafana-plugin/src/containers/ServiceNowConfigDrawer/ServiceNowStatusSection.tsx
  grafana-plugin/src/containers/ServiceNowConfigDrawer/ServiceNowTokenSection.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.helpers.ts
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/models/loader/action-keys.ts
  grafana-plugin/src/network/oncall-api/autogenerated-api.types.d.ts
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/utils/consts.ts
  grafana-plugin/src/utils/decorators.ts
Labels: pr:no public docs, release:ignore

#4113 Fix working hours over the schedule events rendering
  grafana-plugin/src/components/WorkingHours/WorkingHours.tsx
Labels: pr:no public docs, release:patch

#4108 Fix ratelimit bug
  engine/apps/integrations/mixins/ratelimit_mixin.py
  engine/apps/integrations/tests/test_ratelimit.py
Labels: pr:no public docs, release:patch

#4105 run expensive e2e tests
  .github/workflows/daily-e2e-tests.yml
  .github/workflows/e2e-tests.yml
  grafana-plugin/e2e-tests/alerts/sms.test.ts
  grafana-plugin/package.json
  grafana-plugin/playwright.config.ts
Labels: pr:no public docs, release:ignore

#4089 Update alert group state by backsync
  engine/apps/alerts/constants.py
  engine/apps/alerts/migrations/0049_alter_alertgrouplogrecord_action_source.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/models/alert_group_log_record.py
  engine/apps/alerts/tests/test_acknowledge_reminder.py
  engine/apps/alerts/tests/test_alert_group.py
  engine/apps/api/tests/test_alert_group.py
  engine/apps/api/views/alert_group.py
  engine/apps/metrics_exporter/tests/test_update_metrics_cache.py
  engine/apps/public_api/views/incidents.py
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/telegram/tests/test_keyboard_renderer.py
  engine/apps/telegram/tests/test_message_renderer.py
  engine/apps/telegram/updates/update_handlers/button_press.py
  engine/apps/twilioapp/gather.py
  engine/apps/zvonok/status_callback.py
Labels: pr:no public docs, release:ignore

#4124 v1.3.114
  .github/workflows/daily-e2e-tests.yml
  .github/workflows/e2e-tests.yml
  engine/apps/alerts/constants.py
  engine/apps/alerts/migrations/0049_alter_alertgrouplogrecord_action_source.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/models/alert_group_log_record.py
  engine/apps/alerts/tests/test_acknowledge_reminder.py
  engine/apps/alerts/tests/test_alert_group.py
  engine/apps/api/tests/test_alert_group.py
  engine/apps/api/views/alert_group.py
  engine/apps/metrics_exporter/tests/test_update_metrics_cache.py
  engine/apps/public_api/views/incidents.py
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/telegram/tests/test_keyboard_renderer.py
  engine/apps/telegram/tests/test_message_renderer.py
  engine/apps/telegram/updates/update_handlers/button_press.py
  engine/apps/twilioapp/gather.py
  engine/apps/zvonok/status_callback.py
  grafana-plugin/e2e-tests/alerts/sms.test.ts
  grafana-plugin/package.json
  grafana-plugin/playwright.config.ts
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/network/oncall-api/autogenerated-api.types.d.ts
Labels: pr:no public docs

#4115 Match dev helm chart version from main
  helm/oncall/Chart.yaml
Labels: pr:no public docs, release:ignore

#4121 Allow custom values for Self Hosted Clusters (Slugs, Titles, Region)
  engine/settings/base.py
Labels: pr:no public docs, release:ignore

#4129 add `grafana_incident_enabled` to `GET /organization` internal API response
  engine/apps/api/serializers/organization.py
  engine/apps/api/tests/test_organization.py
Labels: pr:no public docs, release:patch

#4130 Fix chatops search
  grafana-plugin/src/containers/AlertRules/parts/connectors/SlackConnector.tsx
Labels: pr:no public docs, release:patch

#2544 cleanup `CustomButton` backend code + add `ngrok`/`express` outgoing webhook e2e test
  dev/helm-local.yml
  docs/sources/oncall-api-reference/escalation_policies.md
  engine/apps/alerts/escalation_snapshot/escalation_snapshot_mixin.py
  engine/apps/alerts/escalation_snapshot/serializers/escalation_policy_snapshot.py
  engine/apps/alerts/escalation_snapshot/snapshot_classes/escalation_policy_snapshot.py
  engine/apps/alerts/incident_log_builder/incident_log_builder.py
  engine/apps/alerts/migrations/0050_alter_alertgrouplogrecord_type.py
  engine/apps/alerts/models/alert_group_log_record.py
  engine/apps/alerts/models/custom_button.py
  engine/apps/alerts/models/escalation_policy.py
  engine/apps/alerts/tasks/__init__.py
  engine/apps/alerts/tasks/custom_button_result.py
  engine/apps/alerts/tests/test_custom_button.py
  engine/apps/alerts/tests/test_escalation_policy_snapshot.py
  engine/apps/alerts/tests/test_escalation_snapshot.py
  engine/apps/alerts/tests/test_utils.py
  engine/apps/alerts/utils.py
  engine/apps/api/serializers/alert_group_escalation_snapshot.py
  engine/apps/api/serializers/custom_button.py
  engine/apps/api/serializers/escalation_policy.py
  engine/apps/api/tests/test_alert_group_escalation_snapshot.py
  engine/apps/api/tests/test_custom_button.py
  engine/apps/api/tests/test_escalation_policy.py
  engine/apps/api/tests/test_schedules.py
  engine/apps/api/tests/test_team.py
  engine/apps/api/urls.py
  engine/apps/api/views/custom_button.py
  engine/apps/api/views/escalation_policy.py
  engine/apps/public_api/serializers/escalation_policies.py
  engine/apps/public_api/tests/test_escalation_policies.py
  engine/apps/public_api/views/action.py
  engine/apps/slack/representatives/alert_group_representative.py
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/webhooks/migrations/0008_auto_20230712_1613.py
  engine/apps/webhooks/tasks/trigger_webhook.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
  engine/apps/webhooks/utils.py
  engine/common/api_helpers/utils.py
  engine/common/tests/test_urlvalidator_without_tld.py
  engine/settings/celery_task_routes.py
  grafana-plugin/e2e-tests/escalationChains/escalationPolicy.test.ts
  grafana-plugin/e2e-tests/outgoingWebhooks/advancedWebhook.test.ts
  grafana-plugin/e2e-tests/outgoingWebhooks/createSimpleWebhook.test.ts
  grafana-plugin/e2e-tests/outgoingWebhooks/simpleWebhook.test.ts
  grafana-plugin/e2e-tests/utils/escalationChain.ts
  grafana-plugin/package.json
  grafana-plugin/yarn.lock
Labels: release:ignore

#4132 Fix validation of integration name when team is not present in request data
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/public_api/serializers/integrations.py
  engine/apps/public_api/tests/test_integrations.py
Labels: pr:no public docs, release:patch

#4136 Snow polishing
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingTab.tsx
  grafana-plugin/src/pages/integration/OutgoingTab/OutgoingWebhookFormFields.tsx
  grafana-plugin/src/state/types.ts
  grafana-plugin/src/utils/hoc.tsx
Labels: pr:no public docs, release:ignore
