Repository grafana/oncall, pull requests merged in 2024-10, with the labels that each got.

#5098 Back merge irm
  .markdownlintignore
  grafana-plugin/CHANGELOG.md
  grafana-plugin/e2e-tests/utils/integrations.ts
  grafana-plugin/e2e-tests/utils/schedule.ts
  grafana-plugin/go.mod
  grafana-plugin/go.sum
  grafana-plugin/package.json
  grafana-plugin/pnpm-lock.yaml
  grafana-plugin/src/components/ExtensionLinkMenu/ExtensionLinkMenu.tsx
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.tsx
  grafana-plugin/src/helpers/consts.ts
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/module.ts
  grafana-plugin/src/pages/incident/Incident.styles.ts
  grafana-plugin/src/pages/outgoing_webhooks/OutgoingWebhooks.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/version.ts
Labels: pr:no public docs, release:ignore

#5101 Update schedule related users to use cached final representation
  engine/apps/alerts/tests/test_paging.py
  engine/apps/api/tests/test_schedules.py
  engine/apps/mobile_app/tests/tasks/test_new_shift_swap_request.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tests/test_on_call_schedule.py
  engine/apps/slack/tests/test_scenario_steps/test_manage_responders.py
  engine/apps/slack/tests/test_scenario_steps/test_paging.py
Labels: pr:no public docs, release:patch

#5111 chore: back merge irm
  grafana-plugin/CHANGELOG.md
  grafana-plugin/package.json
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/containers/EscalationChainSteps/EscalationChainSteps.tsx
  grafana-plugin/src/containers/RotationForm/RotationForm.tsx
  grafana-plugin/src/containers/RotationForm/ScheduleOverrideForm.tsx
  grafana-plugin/src/containers/RotationForm/parts/DeletionModal.tsx
  grafana-plugin/src/models/alertgroup/alertgroup.types.ts
  grafana-plugin/src/models/escalation_policy/escalation_policy.ts
  grafana-plugin/src/models/escalation_policy/escalation_policy.types.ts
  grafana-plugin/src/models/loader/action-keys.ts
  grafana-plugin/src/models/schedule/schedule.ts
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/version.ts
Labels: pr:no public docs, release:ignore

#5047 Add declare incident step and model
  engine/apps/alerts/escalation_snapshot/serializers/escalation_policy_snapshot.py
  engine/apps/alerts/escalation_snapshot/snapshot_classes/escalation_policy_snapshot.py
  engine/apps/alerts/migrations/0059_escalationpolicy_severity_and_more.py
  engine/apps/alerts/models/__init__.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/models/alert_group_log_record.py
  engine/apps/alerts/models/declared_incident.py
  engine/apps/alerts/models/escalation_policy.py
  engine/apps/alerts/tasks/__init__.py
  engine/apps/alerts/tasks/declare_incident.py
  engine/apps/alerts/tests/factories.py
  engine/apps/alerts/tests/test_declare_incident.py
  engine/apps/alerts/tests/test_escalation_policy_snapshot.py
  engine/apps/alerts/tests/test_escalation_snapshot.py
  engine/apps/alerts/utils.py
  engine/apps/api/serializers/escalation_policy.py
  engine/apps/api/tests/test_alert_group.py
  engine/apps/api/tests/test_escalation_policy.py
  engine/apps/api/views/alert_group.py
  engine/apps/api/views/escalation_policy.py
  engine/apps/public_api/serializers/escalation_policies.py
  engine/apps/public_api/tests/test_escalation_policies.py
  engine/common/incident_api/client.py
  engine/common/incident_api/tests/test_client.py
  engine/conftest.py
  engine/settings/base.py
  engine/settings/celery_task_routes.py
Labels: pr:no public docs, release:enhancement

#5108 fix: sanitize email HTML templates
  engine/apps/alerts/paging.py
  engine/apps/alerts/tests/test_paging.py
  engine/common/utils.py
Labels: pr:no public docs, release:patch

#5059 Add latest alert to public api alert groups endpoint
  docs/sources/oncall-api-reference/alertgroups.md
  engine/apps/api/serializers/alert_group.py
  engine/apps/api/views/alert_group.py
  engine/apps/public_api/serializers/alert_groups.py
  engine/apps/public_api/tests/test_alert_groups.py
  engine/apps/public_api/tests/test_escalation.py
  engine/apps/public_api/views/alert_groups.py
  engine/common/api_helpers/mixins.py
  engine/settings/base.py
Labels: release:ignore

#5099 fix: update internal labels endpoints to work with RBAC
  engine/apps/alerts/models/alert_group.py
  engine/apps/api/permissions.py
  engine/apps/api/tests/test_labels.py
  engine/apps/api/tests/test_permissions.py
  engine/apps/api/views/labels.py
  engine/apps/grafana_plugin/helpers/client.py
  engine/apps/labels/client.py
  engine/common/constants/plugin_ids.py
  engine/common/incident_api/client.py
  engine/conftest.py
Labels: pr:no public docs, release:patch

#5109 Make threshold for logging slow requests configurable
  engine/settings/base.py
Labels: pr:no public docs, release:ignore

#5112 Include link information for objects referenced in alert group timeline
  engine/apps/alerts/models/alert_group_log_record.py
  engine/apps/alerts/tests/test_alert_group_log_record.py
Labels: pr:no public docs, release:patch

#5119 Clean up reverted migration
  engine/apps/alerts/escalation_snapshot/serializers/escalation_policy_snapshot.py
  engine/apps/alerts/escalation_snapshot/snapshot_classes/escalation_policy_snapshot.py
  engine/apps/alerts/migrations/0059_escalationpolicy_severity_and_more.py
  engine/apps/alerts/models/escalation_policy.py
  engine/apps/alerts/tests/test_escalation_snapshot.py
  engine/apps/api/tests/test_escalation_policy.py
  engine/apps/api/views/escalation_policy.py
  engine/common/incident_api/client.py
  engine/common/incident_api/tests/test_client.py
Labels: pr:no public docs, release:ignore

#5120 v1.10.1
  engine/apps/alerts/escalation_snapshot/snapshot_classes/escalation_policy_snapshot.py
  engine/apps/alerts/migrations/0059_escalationpolicy_severity_and_more.py
  engine/apps/alerts/models/__init__.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/models/alert_group_log_record.py
  engine/apps/alerts/models/declared_incident.py
  engine/apps/alerts/models/escalation_policy.py
  engine/apps/alerts/tasks/__init__.py
  engine/apps/alerts/tasks/declare_incident.py
  engine/apps/alerts/tests/factories.py
  engine/apps/alerts/tests/test_alert_group_log_record.py
  engine/apps/alerts/tests/test_declare_incident.py
  engine/apps/alerts/tests/test_escalation_policy_snapshot.py
  engine/apps/alerts/utils.py
  engine/apps/api/serializers/escalation_policy.py
  engine/apps/api/tests/test_alert_group.py
  engine/apps/api/tests/test_escalation_policy.py
  engine/apps/api/views/alert_group.py
  engine/apps/api/views/escalation_policy.py
  engine/apps/public_api/serializers/escalation_policies.py
  engine/apps/public_api/tests/test_escalation_policies.py
  engine/conftest.py
  engine/settings/base.py
  engine/settings/celery_task_routes.py
Labels: pr:no public docs, release:ignore

#5121 Truncate slack block text so it is not rejected by slack API
  engine/apps/slack/models/slack_message.py
Labels: pr:no public docs, release:patch

#5123 Include link information for objects referenced in alert group timeline
  engine/apps/alerts/models/alert_group_log_record.py
  engine/apps/alerts/tests/test_alert_group_log_record.py
Labels: pr:no public docs, release:ignore

#5064 Fix for user appearing in shift rotation when they should not be
  engine/apps/schedules/models/custom_on_call_shift.py
  engine/apps/schedules/tests/custom_shift_test_cases.py
  engine/apps/schedules/tests/test_custom_on_call_shift.py
Labels: pr:no public docs, release:patch

#5126 fix: don't update Slack messages if resolution note text not changed
  engine/apps/public_api/tests/test_resolution_notes.py
  engine/apps/public_api/views/resolution_notes.py
Labels: pr:no public docs, release:patch

#5130 Reworked declare incident escalation step
  engine/apps/alerts/escalation_snapshot/snapshot_classes/escalation_policy_snapshot.py
  engine/apps/alerts/migrations/0060_relatedincident.py
  engine/apps/alerts/models/__init__.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/models/alert_group_log_record.py
  engine/apps/alerts/models/escalation_policy.py
  engine/apps/alerts/models/related_incident.py
  engine/apps/alerts/tasks/__init__.py
  engine/apps/alerts/tasks/declare_incident.py
  engine/apps/alerts/tests/factories.py
  engine/apps/alerts/tests/test_escalation_policy_snapshot.py
  engine/apps/alerts/tests/test_related_incident.py
  engine/apps/alerts/utils.py
  engine/apps/api/serializers/escalation_policy.py
  engine/apps/api/tests/test_alert_group.py
  engine/apps/api/tests/test_escalation_policy.py
  engine/apps/api/views/alert_group.py
  engine/apps/api/views/escalation_policy.py
  engine/apps/public_api/serializers/escalation_policies.py
  engine/apps/public_api/tests/test_escalation_policies.py
  engine/conftest.py
  engine/settings/base.py
  engine/settings/celery_task_routes.py
Labels: pr:no public docs, release:patch

#5132 fix jinja_template values to int
  engine/settings/base.py
Labels: pr:no public docs, release:patch

#5133 Fix error encoding on install_v2 endpoint
  engine/apps/grafana_plugin/tests/test_install_v2.py
  engine/apps/grafana_plugin/views/install_v2.py
Labels: pr:no public docs, release:patch

#5135 Remove "Add to docs project" workflow
  .github/workflows/add-to-docs-project.yml
  helm/oncall/Chart.yaml
Labels: release:ignore

#5127 Split up organizations across metrics exporters
  engine/apps/metrics_exporter/helpers.py
  engine/settings/base.py
Labels: pr:no public docs, release:ignore

#5137 update URLs constructed by the backend to support IRM plugin
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/api/serializers/user.py
  engine/apps/api/tests/test_auth.py
  engine/apps/api/views/auth.py
  engine/apps/chatops_proxy/register_oncall_tenant.py
  engine/apps/chatops_proxy/utils.py
  engine/apps/grafana_plugin/tests/test_ui_url_builder.py
  engine/apps/grafana_plugin/ui_url_builder.py
  engine/apps/oss_installation/cloud_heartbeat.py
  engine/apps/oss_installation/serializers/cloud_user.py
  engine/apps/oss_installation/utils.py
  engine/apps/oss_installation/views/cloud_connection.py
  engine/apps/oss_installation/views/cloud_heartbeat.py
  engine/apps/oss_installation/views/cloud_users.py
  engine/apps/public_api/tests/test_escalation.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/models/shift_swap_request.py
  engine/apps/slack/scenarios/paging.py
  engine/apps/slack/scenarios/schedules.py
  engine/apps/slack/scenarios/shift_swap_requests.py
  engine/apps/slack/tests/test_interactive_api_endpoint.py
  engine/apps/slack/tests/test_scenario_steps/test_shift_swap_requests.py
  engine/apps/slack/views.py
  engine/apps/social_auth/middlewares.py
  engine/apps/social_auth/pipeline/google.py
  engine/apps/social_auth/pipeline/slack.py
  engine/apps/user_management/migrations/0023_organization_is_grafana_irm_enabled.py
  engine/apps/user_management/models/organization.py
  engine/common/constants/slack_auth.py
Labels: pr:no public docs, release:ignore

#5143 LOG_REQUEST_HEADERS
  engine/settings/base.py
Labels: pr:no public docs, release:ignore

#5144 fix: no longer set `AlertGroup.resolved_by_alert`
  engine/apps/alerts/models/alert.py
  engine/apps/alerts/models/alert_group.py
  engine/apps/user_management/tests/test_organization.py
Labels: pr:no public docs, release:patch

#5145 Skip user notification if alert group is already resolved
  engine/apps/alerts/tasks/notify_user.py
  engine/apps/alerts/tests/test_notify_user.py
Labels: pr:no public docs, release:patch

#5142 feat: add `timedeltaparse` function to the jinja template
  docs/sources/configure/jinja2-templating/advanced-templates/index.md
  engine/common/jinja_templater/filters.py
  engine/common/jinja_templater/jinja_template_env.py
  engine/common/tests/test_apply_jinja_template.py
  grafana-plugin/src/components/CheatSheet/CheatSheet.config.ts
Labels: release:enhancement

#5148 remove `deprecate_field` usage
  engine/apps/alerts/models/alert.py
  engine/apps/alerts/models/alert_group.py
Labels: pr:no public docs, release:ignore

#5156 Remove resolved_by_alert field from state and remove constraint
  engine/apps/alerts/migrations/0061_alter_alertgroup_resolved_by_alert.py
  engine/apps/alerts/models/alert_group.py
Labels: pr:no public docs, release:ignore

#5150 Allow valid URLs for web image_url template
  engine/apps/alerts/incident_appearance/templaters/web_templater.py
  engine/apps/alerts/tests/test_alert_group_renderer.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api_for_grafana_incident/tests/test_views.py
  engine/common/utils.py
Labels: pr:no public docs, release:ignore

#5093 Doc for `Declare Incident` step
  docs/sources/configure/escalation-chains-and-routes/index.md
  docs/sources/oncall-api-reference/escalation_policies.md
Labels: release:ignore

#5160 Fix retrying tasks
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/tasks/notify_user.py
Labels: pr:no public docs, release:ignore

#5149 feat: update RBAC permissioning to support `grafana-irm-app`
  engine/apps/api/permissions.py
  engine/apps/api/tests/test_permissions.py
  engine/apps/api/tests/test_user.py
  engine/apps/api/views/user.py
  engine/apps/auth_token/auth.py
  engine/apps/grafana_plugin/helpers/client.py
  engine/apps/oss_installation/views/cloud_users.py
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/tests/test_ical_utils.py
  engine/apps/slack/models/slack_team_identity.py
  engine/apps/slack/models/slack_usergroup.py
  engine/apps/user_management/models/user.py
  engine/apps/user_management/tests/test_user.py
Labels: pr:no public docs, release:patch

#5163 fix: fix tests failing because of `faker`
  engine/common/utils.py
Labels: pr:no public docs, release:ignore

#5168 Move send_alert_group_signal to critical
  engine/settings/celery_task_routes.py
Labels: pr:no public docs, release:ignore

#5171 feat: persist `is_grafana_irm_enabled` from backend plugin sync data
  engine/apps/grafana_plugin/helpers/client.py
  engine/apps/grafana_plugin/serializers/sync_data.py
  engine/apps/grafana_plugin/sync_data.py
  engine/apps/grafana_plugin/tasks/sync_v2.py
  engine/apps/grafana_plugin/tests/test_sync_v2.py
  engine/apps/user_management/models/organization.py
  engine/apps/user_management/sync.py
  engine/apps/user_management/tests/test_organization.py
  engine/apps/user_management/tests/test_sync.py
Labels: pr:no public docs, release:ignore

#5172 Minor optimizations for public API endpoints
  engine/apps/public_api/serializers/escalation_chains.py
  engine/apps/public_api/serializers/escalation_policies.py
  engine/apps/public_api/serializers/integrations.py
  engine/apps/public_api/serializers/on_call_shifts.py
  engine/apps/public_api/serializers/routes.py
  engine/apps/public_api/serializers/schedules_base.py
  engine/apps/public_api/serializers/schedules_web.py
  engine/apps/public_api/serializers/webhooks.py
  engine/apps/public_api/views/escalation_chains.py
  engine/apps/public_api/views/integrations.py
  engine/apps/public_api/views/routes.py
  engine/apps/public_api/views/schedules.py
  engine/apps/public_api/views/webhooks.py
  engine/apps/schedules/ical_utils.py
Labels: pr:no public docs, release:ignore

#5141 Remove the deprecated "Format Alert" button from the Slack renderer
  engine/apps/alerts/incident_appearance/renderers/slack_renderer.py
  engine/apps/slack/tests/test_slack_renderer.py
  engine/apps/slack/views.py
Labels: pr:no public docs, release:ignore

#5177 Remove slack user chat:write scope
  docs/sources/manage/notify/slack/index.md
  docs/sources/set-up/open-source/index.md
  engine/apps/social_auth/backends.py
Labels: pr:no public docs, release:ignore

#5178 Reschedule rate limited telegram task instead of retry
  engine/apps/alerts/tasks/notify_user.py
  engine/apps/alerts/tests/test_notify_user.py
  engine/apps/base/models/user_notification_policy_log_record.py
Labels: pr:no public docs, release:ignore

#5182 Undo schedules using ical cached final data
  engine/apps/api/serializers/schedule_base.py
  engine/apps/public_api/serializers/schedules_base.py
Labels: pr:no public docs, release:ignore

#5184 Handle incident client general request errors
  engine/common/incident_api/client.py
  engine/common/incident_api/tests/test_client.py
Labels: pr:no public docs, release:ignore

#5192 Remove deprecated identify slack scope
  engine/apps/social_auth/backends.py
Labels: pr:no public docs, release:ignore

#5196 Update shift change notification to consider microsecond timestamps
  engine/apps/alerts/tasks/notify_ical_schedule_shift.py
  engine/apps/alerts/tests/test_notify_ical_schedule_shift.py
Labels: pr:no public docs, release:ignore

#5201 Allow more escalation step wait times over public api
  docs/sources/oncall-api-reference/escalation_policies.md
  engine/apps/public_api/serializers/escalation_policies.py
Labels: release:patch

#5189 Add org setting to configure direct paging preferred policy
  engine/apps/api/serializers/organization.py
  engine/apps/api/tests/test_organization.py
  engine/apps/slack/scenarios/paging.py
  engine/apps/slack/tests/test_scenario_steps/test_paging.py
  engine/apps/user_management/migrations/0024_organization_direct_paging_prefer_important_policy.py
  engine/apps/user_management/models/organization.py
Labels: pr:no public docs, release:ignore

#5207 Disable e2e tests for grafana latest
  .github/workflows/linting-and-tests.yml
Labels: pr:no public docs, release:ignore
