Repository grafana/oncall, pull requests merged in 2024-12, with the labels that each got.

#5312 fix: service accounts creating webhooks through API
  engine/apps/public_api/serializers/webhooks.py
  engine/apps/public_api/tests/test_webhooks.py
  engine/apps/user_management/models/service_account.py
Labels: pr:no public docs, release:ignore

#5314 fix: patch slack ID reference issue
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/models/channel_filter.py
  engine/apps/alerts/tests/test_alert_group.py
  engine/apps/alerts/tests/test_channel_filter.py
  engine/apps/alerts/tests/test_notify_all.py
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/slack/tasks.py
  engine/apps/slack/tests/scenario_steps/test_distribute_alerts.py
  engine/apps/slack/tests/test_installation.py
Labels: pr:no public docs, release:patch

#5315 chore: add `pytest-socket` library + disable network calls in tests
  engine/apps/api/tests/test_schedule_export.py
  engine/apps/api/tests/test_schedules.py
  engine/apps/api/tests/test_user_schedule_export.py
  engine/apps/auth_token/tests/test_plugin_auth.py
  engine/apps/grafana_plugin/tests/test_sync_v2.py
  engine/requirements-dev.in
  engine/requirements-dev.txt
  engine/tox.ini
Labels: pr:no public docs, release:ignore

#5331 chore: upgrade django to 4.2.17
  engine/requirements-dev.txt
  engine/requirements.in
  engine/requirements.txt
Labels: pr:no public docs, release:ignore

#5326 fix: allow service account requests to access organization teams
  engine/apps/public_api/tests/test_escalation_chain.py
  engine/apps/user_management/models/service_account.py
Labels: pr:no public docs, release:ignore

#5335 Inbound email additional logging
  engine/apps/email/inbound.py
  engine/tox.ini
Labels: pr:no public docs, release:ignore

#5325 chore: remove references to `SlackMessage._channel_id`
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/tests/test_alert_group.py
  engine/apps/alerts/tests/test_alert_receiver_channel.py
  engine/apps/slack/0009_remove_slackmessage_active_update_task_id_db.py
  engine/apps/slack/alert_group_slack_service.py
  engine/apps/slack/migrations/0008_remove_slackmessage_active_update_task_id_state.py
  engine/apps/slack/models/slack_message.py
  engine/apps/slack/models/slack_user_identity.py
  engine/apps/slack/scenarios/alertgroup_appearance.py
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/slack/scenarios/notification_delivery.py
  engine/apps/slack/scenarios/resolution_note.py
  engine/apps/slack/scenarios/shift_swap_requests.py
  engine/apps/slack/scenarios/slack_channel_integration.py
  engine/apps/slack/scenarios/step_mixins.py
  engine/apps/slack/tasks.py
  engine/apps/slack/tests/scenario_steps/test_slack_channel.py
  engine/apps/slack/tests/tasks/test_update_alert_group_slack_message.py
  engine/apps/slack/views.py
  engine/conftest.py
  engine/engine/management/commands/alertmanager_v2_migrate.py
  engine/engine/management/commands/batch_migrate_slack_message_channel.py
Labels: pr:no public docs, release:ignore

#5330 chore: drop usage of `SlackMessage.organization` + drop orphaned `SlackMessage`s
  engine/apps/alerts/tests/test_alert_group.py
  engine/apps/alerts/tests/test_notify_user.py
  engine/apps/public_api/tests/test_alert_groups.py
  engine/apps/schedules/tests/tasks/shift_swaps/test_slack_followups.py
  engine/apps/schedules/tests/tasks/shift_swaps/test_slack_messages.py
  engine/apps/slack/alert_group_slack_service.py
  engine/apps/slack/migrations/0007_migrate_slackmessage_channel_id.py
  engine/apps/slack/migrations/0009_drop_orphaned_messages_and_fill_in_missing_team_identity_values.py
  engine/apps/slack/models/slack_message.py
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/slack/scenarios/resolution_note.py
  engine/apps/slack/scenarios/shift_swap_requests.py
  engine/apps/slack/scenarios/slack_channel_integration.py
  engine/apps/slack/scenarios/step_mixins.py
  engine/apps/slack/tasks.py
  engine/apps/slack/tests/scenario_steps/test_alert_group_actions.py
  engine/apps/slack/tests/scenario_steps/test_manage_responders.py
  engine/apps/slack/tests/scenario_steps/test_resolution_note.py
  engine/apps/slack/tests/scenario_steps/test_shift_swap_requests.py
  engine/apps/slack/tests/scenario_steps/test_slack_channel.py
  engine/apps/slack/tests/scenario_steps/test_slack_channel_integration.py
  engine/apps/slack/tests/tasks/test_update_alert_group_slack_message.py
  engine/apps/slack/tests/test_slack_message.py
  engine/apps/slack/views.py
  engine/apps/user_management/tests/test_organization.py
  engine/conftest.py
  engine/settings/celery_task_routes.py
Labels: pr:no public docs, release:ignore

#5340 chore: remove `SlackMessage._channel_id` and `SlackMessage.organization` fields
  engine/apps/slack/0013_remove_slackmessage__channel_id_db.py
  engine/apps/slack/0014_remove_slackmessage_organization_db.py
  engine/apps/slack/migrations/0010_remove_slackmessage_active_update_task_id_db.py
  engine/apps/slack/migrations/0011_remove_slackmessage__channel_id_state.py
  engine/apps/slack/migrations/0012_remove_slackmessage_organization_state.py
  engine/apps/slack/models/slack_message.py
Labels: pr:no public docs, release:ignore

#5342 chore: fix migration linter issue
  engine/apps/slack/0013_remove_slackmessage__channel_id_db.py
  engine/apps/slack/0014_remove_slackmessage_organization_db.py
  engine/apps/slack/migrations/0010_remove_slackmessage_active_update_task_id_db.py
Labels: pr:no public docs, release:ignore

#5349 chore: update public API docs authentication and perms
  docs/sources/oncall-api-reference/_index.md
  docs/sources/oncall-api-reference/alertgroups.md
  docs/sources/oncall-api-reference/alerts.md
  docs/sources/oncall-api-reference/escalation.md
  docs/sources/oncall-api-reference/escalation_chains.md
  docs/sources/oncall-api-reference/escalation_policies.md
  docs/sources/oncall-api-reference/integrations.md
  docs/sources/oncall-api-reference/on_call_shifts.md
  docs/sources/oncall-api-reference/organizations.md
  docs/sources/oncall-api-reference/outgoing_webhooks.md
  docs/sources/oncall-api-reference/personal_notification_rules.md
  docs/sources/oncall-api-reference/resolution_notes.md
  docs/sources/oncall-api-reference/routes.md
  docs/sources/oncall-api-reference/schedules.md
  docs/sources/oncall-api-reference/shift_swaps.md
  docs/sources/oncall-api-reference/slack_channels.md
  docs/sources/oncall-api-reference/teams.md
  docs/sources/oncall-api-reference/user_groups.md
  docs/sources/oncall-api-reference/users.md
Labels: release:ignore

#5354 chore: update service account token auth organization setup check
  engine/apps/auth_token/auth.py
  engine/apps/auth_token/tests/test_grafana_auth.py
Labels: pr:no public docs, release:ignore

#5355 fix: remove service account role check on sync requests
  engine/apps/auth_token/auth.py
  engine/apps/auth_token/tests/test_plugin_auth.py
Labels: pr:no public docs, release:ignore

#5361 docs: clarify MS Teams connect steps and limitations
  docs/sources/manage/notify/ms-teams/index.md
Labels: type/docs, release:ignore

#5365 fix: validate grafana URL value during organization auth check
  engine/apps/auth_token/auth.py
  engine/apps/auth_token/tests/test_grafana_auth.py
Labels: pr:no public docs, release:ignore

#5257 Explain setting the GRAFANA_CLOUD_ONCALL_API_URL
  docs/sources/set-up/open-source/index.md
Labels: pr:stale

#5369 Fix merge from main conflict
  docs/sources/set-up/open-source/index.md
Labels: pr:no public docs, release:ignore

#5363 Fix dynamic label template validation
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/labels/alert_group_labels.py
  engine/apps/labels/tests/test_alert_group.py
  engine/apps/labels/tests/test_labels.py
  engine/apps/labels/tests/test_labels_cache.py
  engine/conftest.py
Labels: pr:no public docs, release:patch

#5348 Inbound email: download from S3 + convert HTML to plaintext
  engine/apps/email/inbound.py
  engine/apps/email/tests/test_inbound_email.py
  engine/settings/base.py
Labels: pr:no public docs, release:ignore

#5378 chore: add pagerduty migrator test + fix linting
  tools/migrators/lib/pagerduty/migrate.py
  tools/migrators/lib/tests/pagerduty/test_migrate.py
Labels: pr:no public docs, release:ignore

#5374 fix: return a throttled response if org is being synced for the first time during auth
  engine/apps/auth_token/auth.py
  engine/apps/auth_token/tests/test_grafana_auth.py
Labels: pr:no public docs, release:ignore
