Repository grafana/oncall, pull requests merged in 2024-01, with the labels that each got.

#3606 Add msteams feature flag
  engine/apps/api/tests/test_features.py
  engine/apps/api/views/features.py
Labels: pr:no changelog, pr:no public docs

#3587 Handle telegram message to reply to not found on send log task
  CHANGELOG.md
  engine/apps/telegram/tasks.py
  engine/apps/telegram/tests/test_tasks.py
Labels: pr:no public docs

#3604 Add ability to create an Outgoing Webhook with the PATCH HTTP method via the UI
  CHANGELOG.md
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.config.tsx
Labels: pr:no public docs

#3561 Bump MobX version to 6.12 and simplify stores
  CHANGELOG.md
  grafana-plugin/babel.config.json
  grafana-plugin/package.json
  grafana-plugin/src/components/Policy/EscalationPolicy.tsx
  grafana-plugin/src/components/Policy/NotificationPolicy.tsx
  grafana-plugin/src/containers/AlertRules/parts/index.tsx
  grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
  grafana-plugin/src/containers/IntegrationContainers/IntegrationTemplatesList.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
  grafana-plugin/src/containers/PersonalNotificationSettings/PersonalNotificationSettings.tsx
  grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/models/alert_receive_channel_filters/alert_receive_channel_filters.ts
  grafana-plugin/src/models/alert_templates/alert_templates.ts
  grafana-plugin/src/models/alertgroup/alertgroup.ts
  grafana-plugin/src/models/alertgroup/alertgroup.types.ts
  grafana-plugin/src/models/api_key.ts
  grafana-plugin/src/models/api_token/api_token.ts
  grafana-plugin/src/models/channel/channel.ts
  grafana-plugin/src/models/channel_filter.ts
  grafana-plugin/src/models/cloud/cloud.ts
  grafana-plugin/src/models/direct_paging/direct_paging.ts
  grafana-plugin/src/models/escalation_chain/escalation_chain.ts
  grafana-plugin/src/models/escalation_policy.ts
  grafana-plugin/src/models/escalation_policy/escalation_policy.ts
  grafana-plugin/src/models/escalation_policy/escalation_policy.types.ts
  grafana-plugin/src/models/filters/filters.ts
  grafana-plugin/src/models/global_setting/global_setting.ts
  grafana-plugin/src/models/grafana_team/grafana_team.ts
  grafana-plugin/src/models/heartbeat/heartbeat.ts
  grafana-plugin/src/models/label/label.ts
  grafana-plugin/src/models/loader/loader.ts
  grafana-plugin/src/models/notification_policy/notification_policy.ts
  grafana-plugin/src/models/notify_by.ts
  grafana-plugin/src/models/organization/organization.ts
  grafana-plugin/src/models/outgoing_webhook/outgoing_webhook.ts
  grafana-plugin/src/models/resolution_note/resolution_note.ts
  grafana-plugin/src/models/schedule.ts
  grafana-plugin/src/models/schedule/schedule.ts
  grafana-plugin/src/models/slack/slack.ts
  grafana-plugin/src/models/slack_channel/slack_channel.ts
  grafana-plugin/src/models/telegram_channel/telegram_channel.ts
  grafana-plugin/src/models/user/user.ts
  grafana-plugin/src/models/user_group/user_group.ts
  grafana-plugin/src/models/wait_delay.ts
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/pages/settings/tabs/LiveSettings/LiveSettingsPage.tsx
  grafana-plugin/src/services/mixpanel.ts
  grafana-plugin/src/state/rootBaseStore/index.ts
  grafana-plugin/tsconfig.json
  grafana-plugin/yarn.lock
Labels: pr:no public docs

#3609 revert forked redis lib change (#3600)
  engine/requirements.txt
Labels: pr:no changelog, pr:no public docs

#3612 Setup one-at-a-time lock for sync_organization tasks
  CHANGELOG.md
  engine/apps/user_management/sync.py
  engine/apps/user_management/tests/test_sync.py
  engine/common/utils.py
Labels: pr:no public docs

#3583 Brojd/implement insights
  .github/helm-values.yml
  CHANGELOG.md
  dev/helm-local.yml
  grafana-plugin/e2e-tests/insights/insights.test.ts
  grafana-plugin/e2e-tests/utils/alertGroup.ts
  grafana-plugin/e2e-tests/utils/navigation.ts
  grafana-plugin/package.json
  grafana-plugin/src/containers/Alerts/Alerts.tsx
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.test.tsx
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.tsx
  grafana-plugin/src/navbar/Header/Header.tsx
  grafana-plugin/src/pages/index.tsx
  grafana-plugin/src/pages/insights/Insights.helpers.ts
  grafana-plugin/src/pages/insights/Insights.tsx
  grafana-plugin/src/pages/insights/Insights.types.ts
  grafana-plugin/src/pages/insights/scenes/AlertGroupsByIntegration.tsx
  grafana-plugin/src/pages/insights/scenes/AlertGroupsByTeam.tsx
  grafana-plugin/src/pages/insights/scenes/MTTR.tsx
  grafana-plugin/src/pages/insights/scenes/MTTRByIntegration.tsx
  grafana-plugin/src/pages/insights/scenes/MTTRByTeam.tsx
  grafana-plugin/src/pages/insights/scenes/MTTRChangedForPeriodStat.tsx
  grafana-plugin/src/pages/insights/scenes/MTTRChangedForPeriodTimeseries.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroupsDuringTimePeriod.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroupsForSelectedPeriod.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroupsNotificationsDuringTimePeriod.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroupsNotificationsForPeriodTable.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroupsNotificationsInTotal.tsx
  grafana-plugin/src/pages/insights/scenes/TotalAlertGroups.tsx
  grafana-plugin/src/pages/insights/scenes/TotalAlertGroupsByState.tsx
  grafana-plugin/src/pages/insights/variables.ts
  grafana-plugin/src/pages/routes.tsx
  grafana-plugin/src/pages/settings/tabs/ChatOps/ChatOps.tsx
  grafana-plugin/src/plugin.json
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/state/rootBaseStore/index.ts
  grafana-plugin/yarn.lock
  helm/oncall/Chart.yaml
  helm/oncall/charts/prometheus-25.8.2.tgz
  helm/oncall/values.yaml
Labels: pr:no public docs

#3623 Brojd/improve insights
  grafana-plugin/src/pages/insights/Insights.helpers.ts
  grafana-plugin/src/pages/insights/Insights.tsx
  grafana-plugin/src/state/plugin/index.ts
  grafana-plugin/src/state/rootBaseStore/index.ts
  grafana-plugin/src/types.ts
Labels: pr:no changelog, pr:no public docs

#3594 move ms teams related models, containers, components etc to oncall
  grafana-plugin/.dockerignore
  grafana-plugin/.gitignore
  grafana-plugin/src/components/AlertTemplates/AlertTemplatesForm.config.ts
  grafana-plugin/src/components/AlertTemplates/AlertTemplatesForm.module.css
  grafana-plugin/src/components/AlertTemplates/AlertTemplatesForm.tsx
  grafana-plugin/src/components/AlertTemplates/CommonAlertTemplatesForm.config.ts
  grafana-plugin/src/containers/AlertRules/parts/connectors/MSTeamsConnector.tsx
  grafana-plugin/src/containers/AlertRules/parts/index.tsx
  grafana-plugin/src/containers/AlertTemplatesFormContainer/AlertTemplatesFormContainer.tsx
  grafana-plugin/src/containers/DefaultPageLayout/helper.ts
  grafana-plugin/src/containers/IntegrationContainers/IntegrationTemplatesList.config.ts
  grafana-plugin/src/containers/IntegrationContainers/IntegrationTemplatesList.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
  grafana-plugin/src/containers/MSTeams/MSTeamsInstructions.module.css
  grafana-plugin/src/containers/MSTeams/MSTeamsInstructions.tsx
  grafana-plugin/src/containers/MSTeamsIntegrationButton/MSTeamsIntegrationButton.module.css
  grafana-plugin/src/containers/MSTeamsIntegrationButton/MSTeamsIntegrationButton.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/WebhookPresetIcons.config.tsx
  grafana-plugin/src/containers/UserSettings/UserSettings.tsx
  grafana-plugin/src/containers/UserSettings/UserSettings.types.ts
  grafana-plugin/src/containers/UserSettings/parts/connectors/MSTeamsConnector.tsx
  grafana-plugin/src/containers/UserSettings/parts/connectors/index.tsx
  grafana-plugin/src/containers/UserSettings/parts/index.tsx
  grafana-plugin/src/containers/UserSettings/parts/tabs/MSTeamsInfo/MSTeamsInfo.module.css
  grafana-plugin/src/containers/UserSettings/parts/tabs/MSTeamsInfo/MSTeamsInfo.tsx
  grafana-plugin/src/icons/MSTeamsLogo.tsx
  grafana-plugin/src/icons/MachineLearningLogo.tsx
  grafana-plugin/src/models/msteams_channel/msteams_channel.ts
  grafana-plugin/src/models/msteams_channel/msteams_channel.types.ts
  grafana-plugin/src/pages/integration/Integration.config.ts
  grafana-plugin/src/pages/integration/Integration.helper.ts
  grafana-plugin/src/pages/integration/Integration.tsx
  grafana-plugin/src/pages/settings/tabs/ChatOps/ChatOps.tsx
  grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/MSTeamsSettings/MSTeamsSettings.module.css
  grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/MSTeamsSettings/MSTeamsSettings.tsx
  grafana-plugin/src/state/features.ts
  grafana-plugin/src/state/rootBaseStore/index.ts
  grafana-plugin/tsconfig.json
  grafana-plugin/webpack.config.js
Labels: pr:no changelog, pr:no public docs

#3619 Let mobile use paging endpoint
  CHANGELOG.md
  engine/apps/api/views/paging.py
Labels: pr:no public docs

#3625 Brojd/polish insights
  grafana-plugin/src/pages/insights/Insights.module.scss
  grafana-plugin/src/pages/insights/Insights.tsx
  grafana-plugin/src/plugin.json
Labels: pr:no changelog, pr:no public docs

#3618 Brojd/fix timezone issues
  CHANGELOG.md
  grafana-plugin/e2e-tests/schedules/timezones.test.ts
  grafana-plugin/jest.setup.ts
  grafana-plugin/src/components/ScheduleQuality/ScheduleQuality.tsx
  grafana-plugin/src/containers/Rotation/Rotation.tsx
  grafana-plugin/src/containers/Rotation/RotationTutorial.tsx
  grafana-plugin/src/containers/RotationForm/RotationForm.tsx
  grafana-plugin/src/containers/RotationForm/ScheduleOverrideForm.tsx
  grafana-plugin/src/containers/RotationForm/ShiftSwapForm.tsx
  grafana-plugin/src/containers/RotationForm/parts/DateTimePicker.tsx
  grafana-plugin/src/containers/Rotations/Rotations.tsx
  grafana-plugin/src/containers/Rotations/ScheduleFinal.tsx
  grafana-plugin/src/containers/Rotations/ScheduleOverrides.tsx
  grafana-plugin/src/containers/Rotations/SchedulePersonal.tsx
  grafana-plugin/src/containers/ScheduleSlot/ScheduleSlot.tsx
  grafana-plugin/src/containers/TimelineMarks/TimelineMarks.module.scss
  grafana-plugin/src/containers/TimelineMarks/TimelineMarks.tsx
  grafana-plugin/src/containers/UserTimezoneSelect/UserTimezoneSelect.module.css
  grafana-plugin/src/containers/UserTimezoneSelect/UserTimezoneSelect.tsx
  grafana-plugin/src/containers/UsersTimezones/ScheduleUserDetails/ScheduleUserDetails.module.css
  grafana-plugin/src/containers/UsersTimezones/ScheduleUserDetails/ScheduleUserDetails.tsx
  grafana-plugin/src/containers/UsersTimezones/ScheduleUserDetails/img/line.svg
  grafana-plugin/src/containers/UsersTimezones/UsersTimezones.helpers.ts
  grafana-plugin/src/containers/UsersTimezones/UsersTimezones.tsx
  grafana-plugin/src/models/loader/action-keys.ts
  grafana-plugin/src/models/schedule/schedule.ts
  grafana-plugin/src/models/timezone/timezone.helpers.ts
  grafana-plugin/src/models/timezone/timezone.ts
  grafana-plugin/src/models/user/user.ts
  grafana-plugin/src/pages/incident/Incident.tsx
  grafana-plugin/src/pages/schedule/Schedule.helpers.ts
  grafana-plugin/src/pages/schedule/Schedule.tsx
  grafana-plugin/src/pages/schedules/Schedules.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/plugin/dayjs.ts
  grafana-plugin/src/state/rootBaseStore/index.ts
  grafana-plugin/tsconfig.json
Labels: pr:no public docs

#3628 Create log record for telegram formatting error in notification
  CHANGELOG.md
  engine/apps/base/models/user_notification_policy_log_record.py
  engine/apps/telegram/models/connectors/personal.py
  engine/apps/telegram/tests/test_personal_connector.py
Labels: pr:no public docs

#3632 manually retry for `requests.exceptions.Timeout` exceptions when sending outgoing webhooks
  CHANGELOG.md
  engine/apps/webhooks/tasks/trigger_webhook.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
Labels: pr:no public docs

#3637 do not retry `firebase.messaging.UnregisteredError` exceptions for FCM relay tasks
  CHANGELOG.md
  engine/apps/mobile_app/tests/test_utils.py
  engine/apps/mobile_app/utils.py
Labels: pr:no public docs

#3622 Address Telegram HTTP 500s when receiving message from Telegram in discussion group
  CHANGELOG.md
  engine/apps/telegram/tests/test_webhook.py
  engine/apps/telegram/updates/update_manager.py
  engine/apps/telegram/urls.py
  engine/conftest.py
Labels: pr:no public docs

#3640 Fix `module 'apps.schedules.tasks.notify_about_empty_shifts_in_schedule' has no attribute 'apply_async'` `AttributeError`
  CHANGELOG.md
  engine/apps/schedules/tasks/__init__.py
  engine/apps/schedules/tasks/drop_cached_ical.py
  engine/apps/schedules/tasks/notify_about_empty_shifts_in_schedule.py
  engine/apps/schedules/tasks/notify_about_gaps_in_schedule.py
  engine/apps/schedules/tasks/refresh_ical_files.py
  engine/apps/schedules/tests/tasks/test_drop_cached_ical.py
  engine/apps/schedules/tests/tasks/test_refresh_ical_files.py
  engine/apps/schedules/tests/test_notify_about_empty_shifts_in_schedule.py
  engine/apps/schedules/tests/test_notify_about_gaps_in_schedule.py
  engine/settings/celery_task_routes.py
Labels: pr:no public docs

#3296 Move mobile app QR code to Grafana user profile page
  CHANGELOG.md
  grafana-plugin/e2e-tests/globalSetup.ts
  grafana-plugin/package.json
  grafana-plugin/src/components/ExtensionLinkMenu/ExtensionLinkDropdown.tsx
  grafana-plugin/src/components/ExtensionLinkMenu/ExtensionLinkMenu.tsx
  grafana-plugin/src/containers/DefaultPageLayout/DefaultPageLayout.tsx
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.module.scss
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.test.tsx
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.tsx
  grafana-plugin/src/containers/MobileAppConnection/MobileAppConnectionTab.tsx
  grafana-plugin/src/containers/MobileAppConnection/__snapshots__/MobileAppConnection.test.tsx.snap
  grafana-plugin/src/containers/UserSettings/parts/connectors/Connectors.module.css
  grafana-plugin/src/containers/UserSettings/parts/connectors/Connectors.tsx
  grafana-plugin/src/containers/UserSettings/parts/index.tsx
  grafana-plugin/src/containers/UserSettings/parts/tabs/UserInfoTab/UserInfoTab.tsx
  grafana-plugin/src/module.ts
  grafana-plugin/src/navbar/LegacyNavTabsBar.tsx
  grafana-plugin/src/pages/schedule/Schedule.helpers.ts
  grafana-plugin/src/plugin.json
  grafana-plugin/src/plugin/GrafanaPluginRootPage.helpers.test.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.helpers.tsx
  grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
  grafana-plugin/src/state/index.ts
  grafana-plugin/src/utils/authorization/index.ts
  grafana-plugin/src/utils/consts.ts
  grafana-plugin/src/utils/index.ts
  grafana-plugin/yarn.lock
Labels: pr:no changelog, pr:no public docs

#3644 Add stack slug to /organization endpoint response
  CHANGELOG.md
  engine/apps/api/serializers/organization.py
  engine/apps/api/tests/test_organization.py
Labels: pr:no public docs

#3647 add missing @action.bound
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
  grafana-plugin/src/models/alert_receive_channel_filters/alert_receive_channel_filters.ts
  grafana-plugin/src/models/alertgroup/alertgroup.ts
  grafana-plugin/src/models/api_token/api_token.ts
  grafana-plugin/src/models/base_store.ts
  grafana-plugin/src/models/cloud/cloud.ts
  grafana-plugin/src/models/direct_paging/direct_paging.ts
  grafana-plugin/src/models/escalation_chain/escalation_chain.ts
  grafana-plugin/src/models/escalation_policy/escalation_policy.ts
  grafana-plugin/src/models/filters/filters.ts
  grafana-plugin/src/models/global_setting/global_setting.ts
  grafana-plugin/src/models/grafana_team/grafana_team.ts
  grafana-plugin/src/models/heartbeat/heartbeat.ts
  grafana-plugin/src/models/label/label.ts
  grafana-plugin/src/models/loader/loader.ts
  grafana-plugin/src/models/msteams_channel/msteams_channel.ts
  grafana-plugin/src/models/organization/organization.ts
  grafana-plugin/src/models/outgoing_webhook/outgoing_webhook.ts
  grafana-plugin/src/models/resolution_note/resolution_note.ts
  grafana-plugin/src/models/schedule/schedule.ts
  grafana-plugin/src/models/slack/slack.ts
  grafana-plugin/src/models/slack_channel/slack_channel.ts
  grafana-plugin/src/models/telegram_channel/telegram_channel.ts
  grafana-plugin/src/models/user/user.test.ts
  grafana-plugin/src/models/user/user.ts
  grafana-plugin/src/models/user_group/user_group.ts
  grafana-plugin/src/pages/insights/Insights.tsx
  grafana-plugin/src/state/rootBaseStore/index.ts
  grafana-plugin/src/state/rootBaseStore/rootBaseStore.test.ts
Labels: pr:no changelog, pr:no public docs

#3615 Add endpoint for alert group escalation snapshot
  CHANGELOG.md
  engine/apps/api/serializers/alert_group_escalation_snapshot.py
  engine/apps/api/serializers/custom_button.py
  engine/apps/api/serializers/webhook.py
  engine/apps/api/tests/test_alert_group.py
  engine/apps/api/tests/test_alert_group_escalation_snapshot.py
  engine/apps/api/views/alert_group.py
Labels: pr:no public docs

#3638 Add task logging personal notifications triggered/completed counts
  engine/apps/alerts/tasks/check_escalation_finished.py
  engine/apps/alerts/tests/test_check_escalation_finished_task.py
  engine/settings/base.py
  engine/settings/celery_task_routes.py
Labels: pr:no changelog, pr:no public docs

#3670 Fix unicode character encoding in JSON for webhooks
  CHANGELOG.md
  engine/apps/webhooks/tests/test_webhook.py
  engine/apps/webhooks/utils.py
Labels: pr:no public docs

#3654 Brojd/get stack from backend on insights
  grafana-plugin/src/models/organization/organization.types.ts
  grafana-plugin/src/pages/insights/Insights.tsx
Labels: pr:no changelog, pr:no public docs

#3669 Restore ms teams connector
  grafana-plugin/src/containers/UserSettings/parts/connectors/Connectors.tsx
  grafana-plugin/src/containers/UserSettings/parts/connectors/MSTeamsConnector.tsx
  grafana-plugin/src/containers/UserSettings/parts/connectors/index.tsx
Labels: pr:no changelog, pr:no public docs

#3664 Add missing notification log records
  engine/apps/mobile_app/tests/tasks/test_new_alert_group.py
  engine/apps/mobile_app/utils.py
  engine/apps/telegram/models/connectors/personal.py
  engine/apps/telegram/tests/test_personal_connector.py
Labels: pr:no changelog, pr:no public docs

#3671 Fix oncall_now for a schedule in orgs with multiple entries
  CHANGELOG.md
  engine/apps/api/tests/test_schedules.py
  engine/apps/api/views/schedule.py
Labels: pr:no public docs

#3629 Improve OpenAPI schema coverage
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/models/maintainable_object.py
  engine/apps/api/serializers/alert.py
  engine/apps/api/serializers/alert_group.py
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/serializers/integration_heartbeat.py
  engine/apps/api/serializers/slack_user_identity.py
  engine/apps/api/serializers/user.py
  engine/apps/api/tests/test_features.py
  engine/apps/api/views/alert_group.py
  engine/apps/api/views/alert_receive_channel.py
  engine/apps/api/views/features.py
  engine/apps/api/views/labels.py
  engine/apps/api/views/user.py
  engine/apps/auth_token/auth.py
  engine/apps/heartbeat/models.py
  engine/apps/mobile_app/auth.py
  engine/apps/oss_installation/constants.py
  engine/apps/oss_installation/utils.py
  engine/apps/oss_installation/views/cloud_users.py
  engine/apps/slack/models/slack_user_identity.py
  engine/apps/user_management/models/user.py
  engine/common/api_helpers/custom_fields.py
  engine/common/api_helpers/filters.py
  engine/common/api_helpers/mixins.py
  engine/common/api_helpers/paginators.py
  engine/engine/schema.py
  engine/settings/base.py
  engine/settings/prod_without_db.py
Labels: pr:no changelog, pr:no public docs

#3665 fix webhook form
  Tiltfile
  grafana-plugin/src/components/GForm/GForm.tsx
  grafana-plugin/src/models/label/label.ts
Labels: pr:no changelog, pr:no public docs

#3659 Fix several UI related bugs
  CHANGELOG.md
  grafana-plugin/src/components/TimeRange/TimeRange.tsx
  grafana-plugin/src/containers/UserSettings/UserSettings.tsx
Labels: pr:no public docs

#3678 unskip escalation policy test
  grafana-plugin/e2e-tests/escalationChains/escalationPolicy.test.ts
Labels: pr:no changelog, pr:no public docs

#3677 add `LogExceptionOnFailureTask` celery task class
  engine/apps/alerts/tasks/check_escalation_finished.py
  engine/common/custom_celery_tasks/dedicated_queue_retry_task.py
  engine/common/custom_celery_tasks/log_exception_on_failure_task.py
  engine/common/custom_celery_tasks/tests/__init__.py
  engine/common/custom_celery_tasks/tests/test_log_exception_on_failure_task.py
  engine/common/tests/test_task_queue_assignment.py
Labels: pr:no changelog, pr:no public docs

#3682 enable live reload
  grafana-plugin/package.json
  grafana-plugin/webpack.config.js
  grafana-plugin/yarn.lock
Labels: pr:no changelog, pr:no public docs

#3683 add e2e test for schedules
  grafana-plugin/e2e-tests/schedules/schedulesList.test.ts
  grafana-plugin/e2e-tests/utils/navigation.ts
  grafana-plugin/src/pages/insights/Insights.tsx
  grafana-plugin/src/pages/schedules/Schedules.tsx
Labels: pr:no changelog, pr:no public docs

#3684 servicenow logo
  grafana-plugin/src/components/IntegrationLogo/IntegrationLogo.config.ts
Labels: pr:no changelog, pr:no public docs

#3687 Fix occasional `AttributeError` in `apps.grafana_plugin.tasks.sync.sync_organization_async` task
  CHANGELOG.md
  engine/apps/grafana_plugin/helpers/client.py
  engine/apps/user_management/sync.py
  engine/apps/user_management/tests/test_sync.py
Labels: pr:no public docs

#3686 Fix updating a shift swap with no Slack message
  CHANGELOG.md
  engine/apps/slack/scenarios/shift_swap_requests.py
  engine/apps/slack/tests/test_scenario_steps/test_shift_swap_requests.py
Labels: pr:no public docs

#3695 add more logging on celery task retry
  engine/common/custom_celery_tasks/dedicated_queue_retry_task.py
  engine/common/custom_celery_tasks/tests/test_dedicated_queue_retry_task.py
  engine/common/tests/test_task_queue_assignment.py
Labels: pr:no changelog, pr:no public docs

#3691 Proper fix for GForm not resetting the hidden fields to undefined
  CHANGELOG.md
  grafana-plugin/src/components/GForm/GForm.tsx
  grafana-plugin/src/components/GForm/GForm.types.ts
  grafana-plugin/src/components/TextEllipsisTooltip/TextEllipsisTooltip.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.config.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.module.css
  grafana-plugin/src/pages/outgoing_webhooks/OutgoingWebhooks.tsx
Labels: pr:no public docs

#3702 Fix posting Slack message when route is deleted
  CHANGELOG.md
  engine/apps/slack/scenarios/distribute_alerts.py
  engine/apps/slack/tests/test_scenario_steps/test_distribute_alerts.py
Labels: pr:no public docs

#3701 Fix post message to slack channel
  engine/apps/slack/tests/test_utils.py
  engine/apps/slack/utils.py
Labels: pr:no changelog, pr:no public docs

#3643 Adds new templates cheatsheats
  engine/apps/api/tests/test_alert_receive_channel_template.py
  engine/common/api_helpers/mixins.py
  grafana-plugin/src/components/AlertTemplates/CommonAlertTemplatesForm.config.ts
  grafana-plugin/src/components/CheatSheet/CheatSheet.config.ts
  grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.tsx
  grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.tsx
  grafana-plugin/src/containers/TemplatePreview/TemplatePreview.module.css
  grafana-plugin/src/containers/TemplatePreview/TemplatePreview.tsx
  grafana-plugin/src/containers/WebhooksTemplateEditor/WebhooksTemplateEditor.tsx
  grafana-plugin/src/pages/integration/Integration.config.ts
  grafana-plugin/src/pages/integration/IntegrationCommon.config.ts
Labels: pr:no changelog, pr:no public docs

#3703 Update and refactor users API team filter
  engine/apps/api/tests/test_user.py
  engine/apps/api/views/user.py
  engine/common/api_helpers/filters.py
Labels: pr:no changelog, pr:no public docs

#3704 update mobile app gateway jwt to include user email
  engine/apps/mobile_app/tests/test_mobile_app_gateway.py
  engine/apps/mobile_app/views.py
Labels: pr:no changelog, pr:no public docs

#3699 Update schedule on-call cache on scheduled refresh tasks
  CHANGELOG.md
  engine/apps/schedules/constants.py
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/tasks/refresh_ical_files.py
  engine/apps/schedules/tests/tasks/test_refresh_ical_files.py
Labels: pr:no public docs

#3698 Update alert group personal notifications checker to check sent SMS
  engine/apps/alerts/tasks/check_escalation_finished.py
  engine/apps/alerts/tests/test_check_escalation_finished_task.py
Labels: pr:no changelog, pr:no public docs

#3707 modify mobile app proxy gateway headers + request body
  engine/apps/mobile_app/tests/test_mobile_app_gateway.py
  engine/apps/mobile_app/views.py
Labels: pr:no changelog, pr:no public docs

#3668 AG columns polishing
  CHANGELOG.md
  grafana-plugin/package.json
  grafana-plugin/src/containers/ColumnsSelector/ColumnsSelector.styles.ts
  grafana-plugin/src/containers/ColumnsSelector/ColumnsSelector.tsx
  grafana-plugin/src/containers/ColumnsSelectorWrapper/ColumnsModal.tsx
  grafana-plugin/src/containers/ColumnsSelectorWrapper/ColumnsSelectorWrapper.tsx
  grafana-plugin/src/models/alertgroup/alertgroup.ts
  grafana-plugin/src/utils/decorators.ts
  grafana-plugin/yarn.lock
Labels: pr:no public docs

#3708 fix infinitely retrying `apps.alerts.tasks.notify_user.perform_notification` task
  CHANGELOG.md
  engine/apps/alerts/tasks/notify_user.py
  engine/apps/alerts/tests/test_notify_user.py
  engine/common/custom_celery_tasks/dedicated_queue_retry_task.py
Labels: pr:no public docs

#3713 Speed up send email notification task
  engine/apps/user_management/subscription_strategy/free_public_beta_subscription_strategy.py
Labels: pr:no changelog, pr:no public docs

#3715 [DOCS] fix column ordering in RBAC roles tables
  docs/sources/user-and-team-management/_index.md
  docs/sources/user-and-team-management/convert_plugin_json_rbac_roles_into_markdown_table.py
Labels: pr:no changelog

#3720 fix queries in insights scenes
  grafana-plugin/src/pages/insights/scenes/AlertGroupsByIntegration.tsx
  grafana-plugin/src/pages/insights/scenes/AlertGroupsByTeam.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroupsDuringTimePeriod.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroupsForSelectedPeriod.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroupsNotificationsDuringTimePeriod.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroupsNotificationsForPeriodTable.tsx
  grafana-plugin/src/pages/insights/scenes/NewAlertGroupsNotificationsInTotal.tsx
  grafana-plugin/src/pages/insights/scenes/TotalAlertGroups.tsx
  grafana-plugin/src/pages/insights/scenes/TotalAlertGroupsByState.tsx
Labels: pr:no changelog, pr:no public docs

#3712 Improved alert group table columns layout calculation
  CHANGELOG.md
  grafana-plugin/src/pages/incidents/Incidents.tsx
  grafana-plugin/src/utils/types.ts
Labels: pr:no public docs

#3709 Brojd/add e2e test for webhooks creation
  grafana-plugin/e2e-tests/outgoingWebhooks/createAdvancedWebhook.test.ts
  grafana-plugin/e2e-tests/outgoingWebhooks/createSimpleWebhook.test.ts
  grafana-plugin/e2e-tests/utils/navigation.ts
  grafana-plugin/e2e-tests/utils/outgoingWebhooks.ts
  grafana-plugin/src/pages/outgoing_webhooks/OutgoingWebhooks.tsx
Labels: pr:no changelog, pr:no public docs

#3717 OnCall Docs: Fix 'escalations' typo on Get Started page
  docs/sources/get-started/_index.md
Labels: type/docs

#3721 Chatops api v3
  engine/apps/slack/urls.py
  engine/apps/slack/views.py
  engine/apps/social_auth/pipeline.py
  engine/apps/telegram/client.py
  engine/apps/telegram/urls.py
  engine/apps/user_management/models/organization.py
  engine/common/oncall_gateway/__init__.py
  engine/common/oncall_gateway/client.py
  engine/common/oncall_gateway/legacy_client.py
  engine/common/oncall_gateway/tasks.py
  engine/common/oncall_gateway/utils.py
  engine/settings/base.py
  engine/settings/celery_task_routes.py
Labels: pr:no changelog, pr:no public docs

#3723 Slack and telegram routes to test chatops-proxy v3
  engine/apps/slack/urls.py
  engine/apps/telegram/client.py
  engine/apps/telegram/urls.py
  engine/engine/urls.py
Labels: pr:no changelog, pr:no public docs

#3724 Update v3 telegram routes namespace
  engine/engine/urls.py
Labels: pr:no changelog, pr:no public docs

#3722 Alertmanager V2 migration prep
  engine/apps/alerts/migrations/0044_alertreceivechannel_alertmanager_v2_backup_templates_and_more.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/tests/test_alert_receiver_channel.py
  engine/apps/api/serializers/alert_receive_channel.py
  engine/engine/management/commands/alertmanager_v2_migrate.py
  grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.types.ts
  grafana-plugin/src/pages/integration/Integration.tsx
Labels: pr:no changelog, pr:no public docs

#3727 Show extra fields for servicenow
  grafana-plugin/src/components/GForm/GForm.module.scss
  grafana-plugin/src/components/GForm/GForm.tsx
  grafana-plugin/src/components/GForm/GForm.types.ts
  grafana-plugin/src/containers/IntegrationForm/IntegrationForm.config.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.tsx
Labels: pr:no changelog, pr:no public docs

#3732 Minor Fix to Format of REFRESH-INTERVAL in ical_utils.py
  engine/apps/schedules/ical_utils.py
Labels: pr:no changelog, pr:no public docs

#3741 Handle a possible outdated cached integration error
  engine/apps/integrations/mixins/alert_channel_defining_mixin.py
  engine/apps/integrations/tests/test_views.py
Labels: pr:no changelog, pr:no public docs

#3730 Add more logging to plugin sync and install
  CHANGELOG.md
  engine/apps/auth_token/auth.py
  engine/apps/grafana_plugin/views/install.py
  engine/apps/grafana_plugin/views/status.py
  engine/apps/user_management/sync.py
Labels: pr:no public docs

#3744 Retry `perform_notification` with Telegram ratelimit countdown on `RetryAfter` error
  CHANGELOG.md
  engine/apps/alerts/tasks/notify_user.py
  engine/apps/alerts/tests/test_notify_user.py
Labels: pr:no public docs

#3751 Fix `routes` and `schedules` public api endpoints
  CHANGELOG.md
  engine/apps/public_api/serializers/routes.py
  engine/apps/public_api/serializers/schedules_base.py
  engine/apps/public_api/tests/test_integrations.py
  engine/apps/public_api/tests/test_routes.py
  engine/apps/public_api/tests/test_schedules.py
Labels: pr:no public docs

#3748 mobile app proxy - request auth token from cloud auth api
  engine/apps/mobile_app/tests/test_mobile_app_gateway.py
  engine/apps/mobile_app/views.py
  engine/common/cloud_auth_api/__init__.py
  engine/common/cloud_auth_api/client.py
  engine/common/cloud_auth_api/tests/__init__.py
  engine/common/cloud_auth_api/tests/test_client.py
  engine/common/oncall_gateway/client.py
  engine/requirements.txt
  engine/settings/base.py
Labels: pr:no changelog, pr:no public docs

#3753 Fix dynamic labels & multi-label extraction labels
  CHANGELOG.md
  grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.tsx
  grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.tsx
Labels: pr:no public docs

#3764 Show warning when edit AM-based resolve templates
  CHANGELOG.md
  grafana-plugin/src/components/Integrations/IntegrationTemplateBlock.tsx
  grafana-plugin/src/components/WithConfirm/WithConfirm.tsx
  grafana-plugin/src/containers/IntegrationContainers/IntegrationTemplatesList.tsx
Labels: pr:no public docs

#3773 Fix calculating number of oncall users per team
  CHANGELOG.md
  engine/apps/api/serializers/team.py
  engine/apps/api/tests/test_team.py
Labels: pr:no public docs

#3765 Add is_currently_oncall information to internal user details API
  CHANGELOG.md
  engine/apps/api/serializers/user.py
  engine/apps/api/tests/test_user.py
  engine/apps/api/views/user.py
Labels: pr:no public docs

#3769 Enable labels feature only if labels plugin is enabled
  engine/apps/grafana_plugin/helpers/client.py
  engine/apps/labels/tests/test_labels.py
  engine/apps/labels/utils.py
  engine/apps/user_management/migrations/0020_organization_is_grafana_labels_enabled.py
  engine/apps/user_management/models/organization.py
  engine/apps/user_management/sync.py
  engine/apps/user_management/tests/test_sync.py
  engine/conftest.py
Labels: pr:no changelog, pr:no public docs

#3759 Refactor create_alert task
  CHANGELOG.md
  engine/apps/alerts/models/alert.py
  engine/apps/alerts/tasks/distribute_alert.py
  engine/apps/alerts/tests/test_alert.py
  engine/apps/integrations/tasks.py
Labels: pr:no public docs

#3784 Merge hotfix 1.3.94
  engine/common/oncall_gateway/utils.py
  helm/oncall/Chart.yaml
Labels: pr:no changelog, pr:no public docs

#3776 Improve GSelect modelName typing
  grafana-plugin/src/containers/GSelect/GSelect.tsx
  grafana-plugin/src/state/rootBaseStore/index.ts
  grafana-plugin/src/utils/types.ts
Labels: pr:no changelog, pr:no public docs

#3778 Support alert routing based on labels
  CHANGELOG.md
  engine/apps/alerts/models/alert.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/models/channel_filter.py
  engine/apps/alerts/tests/test_alert.py
  engine/apps/alerts/tests/test_channel_filter.py
  engine/apps/alerts/tests/test_default_templates.py
  engine/apps/api/views/alert_group.py
  engine/apps/api/views/alert_receive_channel.py
  engine/apps/api/views/alert_receive_channel_template.py
  engine/apps/api/views/channel_filter.py
  engine/apps/api/views/custom_button.py
  engine/apps/api/views/escalation_chain.py
  engine/apps/api/views/escalation_policy.py
  engine/apps/api/views/integration_heartbeat.py
  engine/apps/api/views/live_setting.py
  engine/apps/api/views/on_call_shifts.py
  engine/apps/api/views/resolution_note.py
  engine/apps/api/views/schedule.py
  engine/apps/api/views/slack_channel.py
  engine/apps/api/views/team.py
  engine/apps/api/views/telegram_channels.py
  engine/apps/api/views/user.py
  engine/apps/api/views/webhooks.py
  engine/apps/integrations/tasks.py
  engine/apps/labels/alert_group_labels.py
  engine/apps/labels/types.py
  engine/common/jinja_templater/__init__.py
  engine/common/jinja_templater/apply_jinja_template.py
  engine/common/tests/test_apply_jinja_template.py
Labels: pr:no public docs

#3789 Add headers for ChatopsProxyAPIClient
  engine/common/oncall_gateway/client.py
Labels: pr:no changelog, pr:no public docs

#3793 Fix list user serializer logic
  CHANGELOG.md
  engine/apps/api/serializers/user.py
  engine/apps/api/tests/test_user.py
  engine/apps/api/views/user.py
Labels: pr:no public docs

#3775 Fix interval validation when creating shift via public API
  CHANGELOG.md
  engine/apps/public_api/serializers/on_call_shifts.py
  engine/apps/public_api/tests/test_on_call_shifts.py
Labels: pr:no public docs

#3794 Fix telegram connection check
  CHANGELOG.md
  engine/apps/api/tests/test_user.py
  engine/apps/api/views/user.py
  engine/apps/user_management/models/user.py
  engine/apps/user_management/tests/test_user.py
Labels: pr:no public docs

#3785 Refactor gaps and empty shift checks
  CHANGELOG.md
  engine/apps/api/serializers/schedule_base.py
  engine/apps/api/serializers/schedule_calendar.py
  engine/apps/api/serializers/schedule_ical.py
  engine/apps/api/serializers/schedule_web.py
  engine/apps/api/views/schedule.py
  engine/apps/schedules/models/custom_on_call_shift.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tasks/__init__.py
  engine/apps/schedules/tasks/check_gaps_and_empty_shifts.py
  engine/apps/schedules/tasks/notify_about_empty_shifts_in_schedule.py
  engine/apps/schedules/tasks/notify_about_gaps_in_schedule.py
  engine/apps/schedules/tasks/refresh_ical_files.py
  engine/apps/schedules/tests/test_check_gaps_and_empty_shifts.py
  engine/apps/schedules/tests/test_notify_about_empty_shifts_in_schedule.py
  engine/apps/schedules/tests/test_notify_about_gaps_in_schedule.py
  engine/settings/base.py
  engine/settings/celery_task_routes.py
Labels: pr:no public docs

#3779 Add transaction block and callbacks when triggering tasks
  engine/apps/alerts/models/alert_group_log_record.py
  engine/apps/alerts/paging.py
  engine/apps/alerts/tasks/acknowledge_reminder.py
  engine/apps/alerts/tests/test_acknowledge_reminder.py
  engine/apps/alerts/tests/test_paging.py
Labels: pr:no changelog, pr:no public docs

#3803 fix slack API rate limit errors in `send_message_to_thread_if_bot_not_in_channel` task
  CHANGELOG.md
  engine/apps/slack/tasks.py
  engine/apps/slack/tests/tasks/__init__.py
  engine/apps/slack/tests/tasks/test_send_message_to_thread_if_bot_not_in_channel.py
Labels: pr:no public docs

#3802 Fix Incident plugin status sync
  CHANGELOG.md
  engine/apps/user_management/sync.py
  engine/apps/user_management/tests/test_sync.py
Labels: pr:no public docs

#3731 Add transaction on_commit before signals for alert group actions
  CHANGELOG.md
  engine/apps/alerts/models/alert_group.py
  engine/apps/alerts/models/alert_group_log_record.py
  engine/apps/alerts/tasks/__init__.py
  engine/apps/alerts/tasks/acknowledge_reminder.py
  engine/apps/alerts/tasks/delete_alert_group.py
  engine/apps/alerts/tasks/send_alert_group_signal.py
  engine/apps/alerts/tests/test_alert_group.py
  engine/apps/metrics_exporter/tests/test_update_metrics_cache.py
  engine/apps/slack/representatives/alert_group_representative.py
  engine/apps/telegram/alert_group_representative.py
  engine/apps/telegram/tasks.py
  engine/apps/webhooks/listeners.py
  engine/settings/celery_task_routes.py
Labels: pr:no public docs
