Repository grafana/oncall, pull requests merged in 2025-03, with the labels that each got.

#5484 chore(deps): bump django-related deps
  engine/requirements-dev.txt
  engine/requirements.in
  engine/requirements.txt
Labels: pr:no public docs, release:ignore

#5487 fix: update e2e test
  grafana-plugin/e2e-tests/users/personalWebhook.test.ts
Labels: pr:no public docs, release:ignore

#5493 Update: Grafana OnCall OSS
  README.md
Labels: pr:no public docs, release:ignore

#5497 chore(deps): Bump grafana-plugin-sdk-go from v0.250.0 to v0.271.0
  grafana-plugin/go.mod
  grafana-plugin/go.sum
Labels: pr:no public docs, release:patch

#5485 Service to service model migration
  helm/oncall/Chart.yaml
  tools/migrators/README.md
  tools/migrators/lib/base_config.py
  tools/migrators/lib/common/resources/services.py
  tools/migrators/lib/grafana/service_migrate.py
  tools/migrators/lib/grafana/service_model_client.py
  tools/migrators/lib/grafana/transform.py
  tools/migrators/lib/oncall/api_client.py
  tools/migrators/lib/pagerduty/config.py
  tools/migrators/lib/pagerduty/migrate.py
  tools/migrators/lib/pagerduty/report.py
  tools/migrators/lib/pagerduty/resources/business_service.py
  tools/migrators/lib/pagerduty/resources/services.py
  tools/migrators/lib/tests/grafana/__init__.py
  tools/migrators/lib/tests/grafana/test_transform.py
  tools/migrators/lib/tests/pagerduty/test_migrate.py
  tools/migrators/lib/tests/pagerduty/test_service_filter.py
  tools/migrators/lib/tests/pagerduty/test_services.py
  tools/migrators/requirements.in
  tools/migrators/requirements.txt
Labels: release:enhancement

#5471 feat: enhance PagerDuty migrator filtering + and improve user migration operations
  tools/migrators/README.md
  tools/migrators/add_users_to_grafana.py
  tools/migrators/lib/pagerduty/config.py
  tools/migrators/lib/pagerduty/migrate.py
  tools/migrators/lib/tests/pagerduty/test_migrate.py
  tools/migrators/lib/tests/test_add_users_to_grafana.py
Labels: release:patch
