Repository grafana/oncall, pull requests merged in 2025-02, with the labels that each got.

#5433 chore: do not run e2e against grafana latest
  .github/workflows/linting-and-tests.yml
Labels: pr:no public docs, release:ignore

#5443 chore: remove reference to recaptcha site
  engine/settings/base.py
Labels: pr:no public docs, release:ignore

#5447 Use a different GH secret to sign plugin
  .github/workflows/on-release-published.yml
Labels: pr:no public docs, release:ignore

#5451 fix: disable recaptcha when site key is not set
  grafana-plugin/src/containers/UserSettings/parts/tabs/PhoneVerification/PhoneVerification.tsx
Labels: pr:no public docs, release:patch

#5426 feat: add personal webhook notification backend
  docs/sources/configure/integrations/outgoing-webhooks/index.md
  docs/sources/manage/notify/webhook/index.md
  docs/sources/oncall-api-reference/outgoing_webhooks.md
  docs/sources/oncall-api-reference/personal_notification_rules.md
  engine/apps/api/tests/test_webhooks.py
  engine/apps/api/views/features.py
  engine/apps/api/views/webhooks.py
  engine/apps/webhooks/backend.py
  engine/apps/webhooks/migrations/0018_alter_webhook_trigger_type_and_more.py
  engine/apps/webhooks/models/__init__.py
  engine/apps/webhooks/models/webhook.py
  engine/apps/webhooks/tasks/__init__.py
  engine/apps/webhooks/tasks/notify_user.py
  engine/apps/webhooks/tasks/trigger_webhook.py
  engine/apps/webhooks/tests/factories.py
  engine/apps/webhooks/tests/test_backend.py
  engine/apps/webhooks/tests/test_notify_user.py
  engine/apps/webhooks/tests/test_trigger_webhook.py
  engine/apps/webhooks/tests/test_webhook.py
  engine/conftest.py
  engine/settings/base.py
  engine/settings/celery_task_routes.py
  grafana-plugin/src/containers/UserSettings/UserSettings.tsx
  grafana-plugin/src/containers/UserSettings/UserSettings.types.ts
  grafana-plugin/src/containers/UserSettings/parts/UserSettingsParts.tsx
  grafana-plugin/src/containers/UserSettings/parts/connectors/Connectors.tsx
  grafana-plugin/src/containers/UserSettings/parts/connectors/PersonalWebhookConnector.tsx
  grafana-plugin/src/containers/UserSettings/parts/tabs/PersonalWebhookInfo/PersonalWebhookInfo.tsx
  grafana-plugin/src/models/outgoing_webhook/outgoing_webhook.types.ts
  grafana-plugin/src/models/user/user.ts
  grafana-plugin/src/state/features.ts
Labels: release:enhancement
