Repository grafana/oncall, pull requests merged in 2025-06, with the labels that each got.

#5545 chore: update deps
  .github/workflows/linting-and-tests.yml
  engine/requirements-dev.txt
  engine/requirements.in
  engine/requirements.txt
Labels: pr:no public docs, release:ignore

#5547 chore: update deps
  engine/requirements-dev.txt
  engine/requirements.in
  engine/requirements.txt
Labels: pr:no public docs, release:ignore

#5548 v1.16.2
  .github/workflows/linting-and-tests.yml
  .github/workflows/on-helm-release-pr-merged.yml
  .github/workflows/on-release-published.yml
  engine/requirements-dev.txt
  engine/requirements.in
  engine/requirements.txt
Labels: pr:no public docs

#5534 chore: fix spelling in CommonAlertTemplatesForm.config.ts
  grafana-plugin/src/components/AlertTemplates/CommonAlertTemplatesForm.config.ts
Labels: pr:stale
