Repository grafana/oncall, pull requests merged in 2025-01, with the labels that each got.

#5322 fix: update missing users / empty shifts check
  engine/apps/schedules/ical_utils.py
  engine/apps/schedules/models/custom_on_call_shift.py
  engine/apps/schedules/tasks/__init__.py
  engine/apps/schedules/tasks/notify_about_empty_shifts_in_schedule.py
  engine/apps/schedules/tasks/notify_about_gaps_in_schedule.py
  engine/apps/schedules/tests/test_notify_about_empty_shifts_in_schedule.py
  engine/apps/schedules/tests/test_notify_about_gaps_in_schedule.py
  engine/apps/schedules/tests/test_on_call_schedule.py
  engine/settings/celery_task_routes.py
Labels: pr:no public docs, release:patch

#5382 feat: create direct paging integrations with two default routes (+ migrate existing ones)
  docs/sources/configure/integrations/references/manual/index.md
  engine/apps/alerts/migrations/0072_upsert_direct_paging_integration_routes.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/tests/test_alert_receiver_channel.py
  engine/apps/user_management/tests/test_sync.py
Labels: release:enhancement

#5379 feat: allow setting direct paging importance for teams
  docs/sources/configure/integrations/references/manual/index.md
  docs/sources/oncall-api-reference/escalation.md
  engine/apps/alerts/migrations/0072_upsert_direct_paging_integration_routes.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/paging.py
  engine/apps/alerts/tests/test_alert_receiver_channel.py
  engine/apps/alerts/tests/test_paging.py
  engine/apps/api/serializers/direct_paging.py
  engine/apps/api/tests/test_direct_paging.py
  engine/apps/api/views/direct_paging.py
  engine/apps/public_api/tests/test_escalation.py
  engine/apps/public_api/views/escalation.py
  engine/apps/slack/scenarios/paging.py
  engine/apps/slack/tests/scenario_steps/test_paging.py
  engine/apps/user_management/tests/test_sync.py
Labels: release:enhancement

#5397 fix: update direct paging integration non-default route data
  engine/apps/alerts/migrations/0073_update_direct_paging_integration_non_default_routes.py
Labels: pr:no public docs, release:ignore

#5399 Update publishing workflows to use GitHub App authentication
  .github/workflows/publish-technical-documentation-next.yml
  .github/workflows/publish-technical-documentation-release.yml
Labels: pr:no public docs, release:ignore

#5401 fix: patch direct paging routes migration
  engine/apps/alerts/migrations/0073_update_direct_paging_integration_non_default_routes.py
Labels: pr:no public docs, release:ignore

#5404 Use tags only workflow behavior
  .github/workflows/publish-technical-documentation-release.yml
Labels: pr:no public docs, release:ignore

#5373 Add default `service_name` label for Alerting integrations
  engine/apps/alerts/constants.py
  engine/apps/alerts/models/alert.py
  engine/apps/alerts/models/alert_receive_channel.py
  engine/apps/alerts/tests/test_alert.py
  engine/apps/api/serializers/alert_receive_channel.py
  engine/apps/api/tests/test_alert_receive_channel.py
  engine/apps/api/tests/test_labels.py
  engine/apps/api/urls.py
  engine/apps/api/views/alert_receive_channel.py
  engine/apps/api/views/labels.py
  engine/apps/labels/alert_group_labels.py
  engine/apps/labels/client.py
  engine/apps/labels/migrations/0007_remove_alertreceivechannelassociatedlabel_inheritable_db.py
  engine/apps/labels/models.py
  engine/apps/labels/tasks.py
  engine/apps/labels/tests/test_add_service_label.py
  engine/apps/labels/tests/test_labels_cache.py
  engine/apps/public_api/serializers/integrations.py
  engine/settings/celery_task_routes.py
Labels: pr:no public docs, release:ignore

#5413 Fix typo
  engine/apps/alerts/constants.py
Labels: pr:no public docs, release:ignore

#5414 Fix getting label by name
  engine/apps/labels/models.py
  engine/apps/labels/tests/test_labels_cache.py
Labels: pr:no public docs, release:ignore

#5412 chore: update schedule checks notification period and improve wording
  engine/apps/api/serializers/schedule_base.py
  engine/apps/api/serializers/schedule_calendar.py
  engine/apps/api/serializers/schedule_ical.py
  engine/apps/api/serializers/schedule_web.py
  engine/apps/api/views/schedule.py
  engine/apps/schedules/constants.py
  engine/apps/schedules/models/on_call_schedule.py
  engine/apps/schedules/tasks/check_gaps_and_empty_shifts.py
  engine/apps/schedules/tasks/notify_about_empty_shifts_in_schedule.py
  engine/apps/schedules/tasks/notify_about_gaps_in_schedule.py
  engine/apps/schedules/tests/test_check_gaps_and_empty_shifts.py
  engine/apps/schedules/tests/test_notify_about_gaps_in_schedule.py
Labels: pr:no public docs, release:ignore

#5415 feat: add filter affected services internal endpoint
  engine/apps/api/tests/test_alert_group.py
  engine/apps/api/views/alert_group.py
  engine/apps/grafana_plugin/tests/test_ui_url_builder.py
  engine/apps/grafana_plugin/ui_url_builder.py
  engine/common/constants/plugin_ids.py
Labels: pr:no public docs, release:ignore

#5420 Add service dependencies feature flag
  engine/apps/api/tests/test_alert_group.py
  engine/apps/api/views/alert_group.py
  engine/apps/api/views/features.py
  engine/settings/base.py
Labels: pr:no public docs, release:ignore

#5418 Add important version of round-robin escalation step
  docs/sources/oncall-api-reference/escalation_policies.md
  engine/apps/alerts/escalation_snapshot/snapshot_classes/escalation_policy_snapshot.py
  engine/apps/alerts/incident_log_builder/incident_log_builder.py
  engine/apps/alerts/migrations/0074_alter_escalationpolicy_step.py
  engine/apps/alerts/models/escalation_policy.py
  engine/apps/alerts/tests/test_escalation_policy_snapshot.py
  engine/apps/api/tests/test_escalation_policy.py
  engine/apps/public_api/serializers/escalation_policies.py
  engine/apps/webhooks/utils.py
Labels: release:patch

#5421 chore: capitalize Slack name references
  engine/apps/alerts/incident_log_builder/incident_log_builder.py
  engine/apps/alerts/tasks/notify_user.py
  engine/apps/api/views/schedule.py
  engine/apps/slack/scenarios/resolution_note.py
  engine/apps/slack/scenarios/schedules.py
  engine/apps/slack/views.py
Labels: pr:no public docs, release:ignore
